fix(dedicated): update india order link for ldp
ovh/manager pull request #10009
Opened 2023-09-20 07:36 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-12187
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-09-20 07:37 UTC, darsene submitted a review, later dismissed

2023-09-20 07:38 UTC, qpavy submitted a review, later dismissed

2023-09-20 08:00 UTC, anooparveti approved these changes

2023-09-20 08:01 UTC, anooparveti requested changes
Failing check: https://github.com/ovh/manager/actions/runs/6245450904/job/16954111517?pr=10009

2023-09-20 08:38 UTC, anooparveti approved these changes

2023-09-20 08:39 UTC, darsene approved these changes

2023-09-26 16:20 UTC, acavalloni approved these changes

2023-09-26 16:26 UTC, merged

2023-09-26 16:42 UTC, BrunoMarquesOVH reviewed
I'll leave an empty comment because github seems to be bugging on my side