feat(dedicated): hide carbon calculator cta when no data
ovh/manager pull request #10039
Opened 2023-09-27 09:01 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-12356
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ (n/a)
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (n/a)

## Description

Hide the download carbon footprint when no data are available

## Related

2023-09-27 09:03 UTC, anooparveti approved these changes

2023-09-27 10:02 UTC, darsene requested changes

2023-09-27 10:02 UTC, darsene commented on packages/manager/modules/carbon-calculator/src/dashboard/routing.js
> +          .catch(() => false),
Should be moved into `CarbonFootprintService` to gather API calls. 

```suggestion
      hasInvoice: /* @ngInject */ (CarbonFootprintService) =>
       CarbonFootprintService.hasInvoice(),
```

2023-09-27 12:18 UTC, anooparveti approved these changes

2023-09-29 08:49 UTC, darsene approved these changes

2023-10-03 10:23 UTC, merged