feat(signup): adding gender and birthday on details step
ovh/manager pull request #10041
Opened 2023-09-27 20:06 UTC by BrunoMarquesOVH

ref: MANAGER-11285

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11285
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

Adding gender and birthday on details step in sign-up (only for CZ country)

## Related

2023-09-29 08:41 UTC, JacquesLarique submitted a review, later dismissed

2023-09-29 08:50 UTC, sachinrameshn requested changes

2023-09-29 08:50 UTC, sachinrameshn commented on packages/manager/modules/sign-up/src/form/details/details.html
> +        data-ng-if="$ctrl.signUpFormCtrl.rules.sex && $ctrl.signUpFormCtrl.model.country === 'CZ'"
Can you please move country to constant file ?

2023-09-29 08:50 UTC, sachinrameshn commented on packages/manager/modules/sign-up/src/form/details/details.html
> +        data-ng-if="$ctrl.signUpFormCtrl.rules.birthDay && $ctrl.signUpFormCtrl.model.country === 'CZ'"
here to move it to constant

2023-10-03 08:37 UTC, JacquesLarique submitted a review, later dismissed

2023-10-03 08:59 UTC, sachinrameshn approved these changes

2023-10-20 06:45 UTC, qpavy approved these changes

2023-10-20 06:59 UTC, sachinrameshn approved these changes

2023-10-20 07:41 UTC, merged