feat(octavia): add listeners to lb creation
ovh/manager pull request #10050
Opened 2023-09-29 13:53 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/octavia-batch-1`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10670
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2023-10-04 05:46 UTC, ghyenne commented on packages/manager/modules/octavia-load-balancer/src/create/translations/Messages_fr_FR.json
> +  "octavia_load_balancer_create_instance_banner_text": "Vous pouvez ajouter jusqu'à 5 listeners avec 5 instances au maximum dans cet assistant. Pour plus d'options ou pour éditer des fonctionnalités
Maybe the values could be dynamic ?

2023-10-04 08:38 UTC, JacquesLarique requested changes

2023-10-04 08:38 UTC, JacquesLarique commented on packages/manager/modules/octavia-load-balancer/src/create/service.js
>        // TODO: Add listeners when ticket 10670 is done
This comment can be removed, since it is done

2023-10-20 11:43 UTC, ghyenne approved these changes

2023-10-23 08:43 UTC, JacquesLarique approved these changes

2023-10-24 06:20 UTC, merged