feat(pci): add activate discovery mode modal
ovh/manager pull request #10092
Opened 2023-10-09 11:01 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-93
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [X] Only FR translations have been updated
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

2023-10-10 08:54 UTC, BrunoMarquesOVH approved these changes

2023-10-10 09:00 UTC, sachinrameshn approved these changes

2023-10-10 14:20 UTC, brofik approved these changes

2023-10-11 06:26 UTC, anooparveti approved these changes

2023-10-20 05:43 UTC, anooparveti approved these changes

2023-10-20 05:43 UTC, anooparveti requested changes
Could you please resolve conflicts?

2023-11-30 14:33 UTC, merged