feat(dedicated.gamefirewall): apply feedback
ovh/manager pull request #10105
Opened 2023-10-11 07:07 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-499
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

- update labels for pop-up in activate/de-activate policy
- add check on game firewall ports
- add default port for game firewall rule

## Related

2023-10-11 08:53 UTC, darsene requested changes

2023-10-11 08:53 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
>        self.rule.ports.to === undefined
```suggestion
      !self.rule.ports.from ||
      !self.rule.ports.to
```
`!` manages also `undefined` value

2023-10-11 09:08 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
> +import get from 'lodash/get';
```suggestion
```

2023-10-11 09:08 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
> +    );
```suggestion
    const defaultPort = IP_MITIGATION_RULE_PROTOCOL_PORT[self.rule.protocol];
```

2023-10-13 08:54 UTC, anooparveti approved these changes

2023-10-13 08:59 UTC, ghyenne approved these changes

2023-10-16 13:05 UTC, merged