feat(projects.project): add discovery label
ovh/manager pull request #10126
Opened 2023-10-13 13:02 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/TAPC-97` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-269 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-10-16 08:44 UTC, anooparveti requested changes
Can you please update the ui-kit in all the apps & modules?
Also, include `package-lock.json` changes.

2023-10-16 08:45 UTC, sachinrameshn approved these changes

2023-10-17 12:00 UTC, anooparveti approved these changes

2023-10-17 13:04 UTC, y4nnL approved these changes

2023-10-17 14:08 UTC, merged