Feat/manager 12208
ovh/manager pull request #10120
Opened 2023-10-12 14:41 UTC by antonymarion

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/dkim-b2`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Feat #MANAGER-12208
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Enable to configure DKIM with domain outside ovh

## Related

2023-10-12 15:12 UTC, ghyenne requested changes

2023-10-12 15:12 UTC, ghyenne commented on packages/manager/modules/exchange/src/domain/dkim-autoconfig/domain-dkim-autoconfig.controller.js
> +    this.getSelectorNameForNoOvhCloud();
```suggestion
    return this.getSelectorNameForNoOvhCloud();
```

2023-10-12 16:12 UTC, antonymarion commented on packages/manager/modules/exchange/src/domain/dkim-autoconfig/domain-dkim-autoconfig.html
> +            data-wizard-on-cancel="leaveDkimConfigurator"
Yes, basically, leaveDkimConfigurator reset all vars for modals stepper; and once configuration is done then chip will be red until user updates with given values from last modal (step 3 of configurator)

2023-10-13 08:02 UTC, darsene requested changes

2023-10-13 08:02 UTC, darsene commented on packages/manager/modules/exchange/src/domain/dkim-autoconfig/domain-dkim-autoconfig.controller.js
> +      .then((res) => res)
```suggestion
      
```
Seems useless

2023-10-13 12:06 UTC, antonymarion reviewed
done

2023-10-25 12:29 UTC, closed without merging