refactor(dedicated.server): move secondary dns module
ovh/manager pull request #10137
Opened 2023-10-17 15:25 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `refactor/MANAGER-12284` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-12286 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
Refactor secondary dns section, move secondary dns module

## Related

2023-10-18 08:59 UTC, darsene approved these changes

2023-10-20 06:14 UTC, anooparveti requested changes

2023-10-20 06:14 UTC, anooparveti commented on packages/manager/modules/bm-server-components/src/secondary-dns/add/secondary-dns-add.controller.js
**nitpick:** Remove `$stateParams` and add it as an input to the component.

2023-10-20 06:14 UTC, anooparveti commented on packages/manager/modules/bm-server-components/src/secondary-dns/delete/secondary-dns-delete.controller.js
**nitpick:** Remove `$stateParams` and add it as an input to the component.

2023-10-20 06:14 UTC, anooparveti commented on packages/manager/modules/bm-server-components/src/secondary-dns/secondary-dns.controller.js
**nitpick:** Remove `$stateParams` and add it as an input to the component.

2023-10-20 07:16 UTC, ghyenne commented on packages/manager/modules/bm-server-components/src/secondary-dns/add/secondary-dns-add.controller.js
I removed it. I reuse this.server.name.

2023-10-20 07:16 UTC, ghyenne commented on packages/manager/modules/bm-server-components/src/secondary-dns/secondary-dns.controller.js
I removed it. I reuse this.server.name.

2023-10-20 07:17 UTC, ghyenne commented on packages/manager/modules/bm-server-components/src/secondary-dns/delete/secondary-dns-delete.controller.js
I removed it. I reuse this.server.name and $transition$.params for this.domain

2023-10-20 08:11 UTC, anooparveti approved these changes

2023-10-20 08:48 UTC, darsene approved these changes

2023-10-27 09:59 UTC, merged