Feat/container axios
ovh/manager pull request #10146
Opened 2023-10-19 13:08 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | DTCORE-1591
| License          | BSD 3-Clause

## Description

Replace ovh-reket with axios in container & shell

2023-10-19 13:19 UTC, kqesar submitted a review, later dismissed

2023-11-10 08:19 UTC, kqesar approved these changes

2023-11-13 15:04 UTC, cbourgois submitted a review, later dismissed

2023-11-16 16:10 UTC, kqesar submitted a review, later dismissed

2023-11-22 07:47 UTC, anooparveti requested changes
@frenautvh can you please resolve the conflicts?

2023-11-22 09:10 UTC, kqesar submitted a review, later dismissed

2023-12-12 10:48 UTC, anooparveti submitted a review, later dismissed

2023-12-13 09:23 UTC, aboungnaseng-ovhcloud approved these changes

2023-12-27 13:43 UTC, anooparveti submitted a review, later dismissed

2024-01-12 09:13 UTC, anooparveti approved these changes

2024-01-15 09:43 UTC, aboungnaseng-ovhcloud approved these changes

2024-01-18 08:14 UTC, chipp972 approved these changes

2024-04-29 09:30 UTC, closed without merging