test(container): enable lint for container and fix lint error
ovh/manager pull request #10147
Opened 2023-10-19 13:12 UTC by kqesar

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | DTCORE-1593
| License          | BSD 3-Clause

## Description

Enable eslint and fix lint errors for the container

2023-10-19 13:16 UTC, frenautvh submitted a review, later dismissed

2023-10-27 09:02 UTC, anooparveti commented on packages/manager/apps/container/src/container/legacy/server-sidebar/SidebarVirtual.tsx
> +    } if (item?.depth === 0) {
```suggestion
    } 
    if (item?.depth === 0) {
```

2023-11-10 08:28 UTC, frenautvh approved these changes

2023-11-14 07:38 UTC, anooparveti approved these changes

2023-11-14 07:39 UTC, anooparveti requested changes
@kqesar can you change the commit type to `fix`?

2023-11-14 09:59 UTC, kqesar commented
@anooparveti the commit type have been updated

2023-11-15 10:23 UTC, anooparveti approved these changes

2023-11-29 17:05 UTC, merged