feat(hub): adding global availability iam invite banner
ovh/manager pull request #10190
Opened 2023-10-27 07:32 UTC by BrunoMarquesOVH

ref: MANAGER-12468

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12468
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

Adding global availability iam invite banner

## Related

2023-10-27 08:55 UTC, darsene submitted a review, later dismissed

2023-10-30 09:30 UTC, anooparveti requested changes
Since we will be removing beta message on hub. Can you also clean up the code for beta message?

2023-11-03 10:00 UTC, anooparveti approved these changes

2023-11-10 09:46 UTC, darsene approved these changes

2023-11-10 09:48 UTC, qpavy approved these changes

2023-11-10 10:05 UTC, merged