feat(web): Manage DKIM key in the manager - Exchange and E-mail pro
ovh/manager pull request #10218
Opened 2023-11-02 11:18 UTC by darsene

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12167
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~Breaking change is mentioned in relevant commits~

## Description

Manage DKIM key in the manager - Exchange and E-mail pro

## Related

2023-11-02 11:43 UTC, qpavy submitted a review, later dismissed

2023-11-02 12:42 UTC, antonymarion requested changes

2023-11-02 12:42 UTC, antonymarion commented on packages/manager/modules/emailpro/src/domain/dkim-autoconfig/dkim-auto-configurator.js
> +        this.$routerParams.organization,
Line 24 should be removed since signature for EmailPro is (productId, name, selectorName)

2023-11-06 10:34 UTC, antonymarion approved these changes

2023-11-15 11:25 UTC, anooparveti requested changes

2023-11-15 11:25 UTC, anooparveti commented on packages/manager/modules/emailpro/src/dashboard/emailproServices.module.js
> +  .service('messaging', messaging)
```suggestion
  .service('Messaging', messaging)
```

2023-11-15 11:26 UTC, anooparveti commented on packages/manager/modules/emailpro/src/dashboard/translations/Messages_fr_FR.json
> +  "emailpro_tab_domain_diagnostic_dkim_name": "Name",
```suggestion
  "emailpro_tab_domain_diagnostic_dkim_name": "Nom",
```

2023-11-15 11:30 UTC, anooparveti commented on packages/manager/modules/emailpro/src/domain/dkim-autoconfig/emailpro-domain-dkim-autoconfig.controller.js
> +    messaging,
```suggestion
    Messaging,
```

2023-11-23 16:27 UTC, darsene commented on packages/manager/modules/emailpro/src/dashboard/emailproServices.module.js
> +  .service('messaging', messaging)
service has been removed (unused)

2023-11-27 08:49 UTC, anooparveti commented on packages/manager/modules/emailpro/src/domain/dkim-autoconfig/dkim-auto-configurator.js
> +  }
**nitpick:** You are only using these functions once. I dont see the need to create 3 additional wrappers for them.
Also, please avoid shortcuts and use fullnames, `msg` -> `message`, `args` -> `arguments` and so on.

2023-11-27 09:44 UTC, anooparveti requested changes

2023-11-27 09:44 UTC, anooparveti commented on packages/manager/modules/emailpro/src/domain/dkim-autoconfig/emailpro-domain-dkim-autoconfig.controller.js
> +  }
**nitpick:** The function names ending with `For` does not convey the complete meaning of what it is supposed to do. Please use a meaningful names.

2023-12-21 08:46 UTC, antonymarion approved these changes

2023-12-21 08:46 UTC, qpavy approved these changes

2024-01-02 15:46 UTC, merged