feat: add docker command into ai deploy order funnel
ovh/manager pull request #10222
Opened 2023-11-02 14:36 UTC by abullet33

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #datatr-374 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

customer can add a docker command into ai deploy order funnel for custom app that will be executed on launch 
## Related

2023-11-03 09:33 UTC, JacquesLarique commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/add.controller.js
> +      : [];
```suggestion
    this.appModel.command = this.splitIntoArray(this.commandLine);
```
The test you're making is also done in the splitIntoArray method, so no need to do it again here

2023-11-03 10:08 UTC, BrunoMarquesOVH requested changes

2023-11-03 10:59 UTC, anooparveti requested changes

2023-11-03 10:59 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/add.controller.js
> +  }
**nitpick:** Please use the full-form and avoid shortNames like `cmd`, `elt`

2023-11-03 10:59 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/components/app-image/app-image.controller.js
> +        return elt;
**nitpick:** Use full-forms and avoid shortNames like `elt`

2023-11-03 10:59 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/components/app-image/app-image.html
> +                data-ng-if="$ctrl.customDockerCmd && $ctrl.splitStringCommandIntoArray().length > 0"
```suggestion
                data-ng-if="$ctrl.customDockerCommand && $ctrl.splitStringCommandIntoArray().length > 0"
```

2023-11-03 10:59 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/components/app-image/app-image.html
> +                            </li>
```suggestion
                            <li
                                ng-repeat="command in $ctrl.splitStringCommandIntoArray()"
                                class="api-list-item"
                            >
                                {{ command }}
                            </li>
```

2023-11-03 17:01 UTC, anooparveti approved these changes

2023-11-06 09:40 UTC, sachinrameshn approved these changes

2023-11-28 14:58 UTC, jperchoc approved these changes

2023-11-29 17:09 UTC, ghyenne approved these changes

2023-11-29 17:10 UTC, merged