feat(web.domain): datagrid - display renewal mode
ovh/manager pull request #10262
Opened 2023-11-08 10:25 UTC by dectotam

ref: MANAGER-11776

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/domain-optim
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-11776
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2023-11-08 10:34 UTC, qpavy approved these changes

2023-11-08 11:12 UTC, anooparveti commented on packages/manager/apps/web/client/app/domain/list/template.html
> +            data-translate=" {{ 'domains_renewal_mode_' + $value }}"
```suggestion
            class="{{:: 'oui-badge ' + $ctrl.DOMAINS_BADGES_RENEWAL_MODE[$value] }}"
            data-translate=" {{:: 'domains_renewal_mode_' + $value }}"
```

2023-11-08 11:14 UTC, anooparveti requested changes

2023-11-08 13:59 UTC, dectotam commented on packages/manager/apps/web/client/app/domain/list/template.html
> +        data-searchable
ok, for now searchable has been removed

2023-11-09 07:44 UTC, anooparveti approved these changes

2023-11-13 08:39 UTC, merged