feat(hub): cleanup angularjs catalog code
ovh/manager pull request #10261
Opened 2023-11-08 09:50 UTC by benjaminlepine

ref: MANAGER-12587

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/EPIC-MANAGER-12587
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12587
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-11-08 11:17 UTC, anooparveti requested changes
Can you also remove `packages/manager/modules/hub/src/components/catalog-items`?

2023-11-08 13:33 UTC, darsene approved these changes

2023-11-08 13:33 UTC, karim-ovh commented
I think we should not remove the other language files. We should only delete the fr_FR files.

2023-11-14 07:36 UTC, anooparveti approved these changes

2023-11-14 14:47 UTC, anooparveti requested changes

2023-11-14 14:47 UTC, anooparveti commented on packages/manager/apps/hub/src/app.module.js
> +    )
```suggestion
    .run(
      /* @ngInject */ ($urlRouterProvider) => {
        $urlRouterProvider.rule(($injector, $location) => {
          const path = $location.path();
          if (path === '/hub/catalog') {
            return '/catalog';
          }
          return undefined;
        });
      },
    )
```

2023-11-22 18:21 UTC, anooparveti commented
Rebasing with `release/catalog-uapp`

2023-11-23 06:51 UTC, anooparveti approved these changes

2023-11-23 07:52 UTC, ghyenne approved these changes

2023-12-01 11:46 UTC, anooparveti commented
Rebasing with `release/catalog-uapp`

2023-12-01 11:47 UTC, merged