fix(dedicated): update links to docs
ovh/manager pull request #10272
Opened 2023-11-09 15:32 UTC by benjaminlepine

ref: MANAGER-11786

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-11-09 16:08 UTC, antonymarion submitted a review, later dismissed

2023-11-09 17:17 UTC, anooparveti requested changes
The goal of this task is to add new links for Australian sub. Currently, `IE` links are configured as default and the links for `AU` doesn't exist. So AU users are navigated to IE links. You can add an entry for `AU` and its corresponding link to currently navigate AU users.

2023-11-10 15:59 UTC, antonymarion approved these changes

2023-11-13 14:18 UTC, dectotam submitted a review, later dismissed

2023-11-15 11:22 UTC, anooparveti submitted a review, later dismissed

2024-06-20 08:14 UTC, qpavy commented
Still in testing

2024-09-11 09:54 UTC, sachinrameshn approved these changes

2024-09-11 09:54 UTC, SimonChaumet approved these changes

2024-09-12 15:16 UTC, merged