feat(dedicated.vrack): add trackCLick for move add del
ovh/manager pull request #10297
Opened 2023-11-14 11:56 UTC by antonymarion

ref: MANAGER-12513

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-11-15 08:33 UTC, qpavy commented on packages/manager/modules/vrack/src/dashboard/translations/Messages_fr_FR.json
> +  "vrack_introduction_change_owner": "Vous avez aussi la possibilité de",
Better keep initial translation because here you cut the sentence and it can be hard to translate on other languages

2023-11-15 08:40 UTC, ghyenne requested changes

2023-11-15 08:40 UTC, ghyenne commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +  }
```suggestion
  trackClick(hit, action = true) {
    this.atInternet.trackClick({
      name: `${VRACK_DASHBOARD_TRACKING_PREFIX}${action ? '::' + VRACK_ACTIONS_SUFFIX : '' }::${hit}`,
      type: 'action',
    });
  }
```

2023-11-15 08:40 UTC, ghyenne commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    );
```suggestion
    this.trackClick('add');
```

2023-11-15 08:40 UTC, ghyenne commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    this.trackClick(`${VRACK_DASHBOARD_TRACKING_PREFIX}::change-owner`);
```suggestion
    this.trackClick('change-owner', false);
```

2023-11-15 08:40 UTC, ghyenne commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    );
```suggestion
    this.trackClick('move');
```

2023-11-15 08:51 UTC, darsene commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +      `${VRACK_DASHBOARD_TRACKING_PREFIX}::${VRACK_ACTIONS_SUFFIX}::remove`,
```suggestion
     'remove',
```

2023-11-15 09:33 UTC, qpavy submitted a review, later dismissed

2023-11-15 10:45 UTC, darsene commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    this.trackClick(`remove`);
```suggestion
    this.trackClick('remove');
```

2023-11-15 10:45 UTC, darsene approved these changes

2023-11-15 10:47 UTC, darsene submitted a review, later dismissed

2023-11-15 11:18 UTC, anooparveti approved these changes

2023-11-16 09:37 UTC, darsene submitted a review, later dismissed

2023-11-16 09:38 UTC, qpavy submitted a review, later dismissed

2023-11-16 11:33 UTC, anooparveti approved these changes

2023-11-16 13:42 UTC, darsene approved these changes

2023-11-16 13:45 UTC, ghyenne approved these changes

2023-11-17 09:58 UTC, merged