feat(web): allow both clic and escape for modals
ovh/manager pull request #10336
Opened 2023-11-17 11:44 UTC by antonymarion

ref: MANAGER-12646

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-11-17 12:09 UTC, darsene commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/view/view.controller.js
> +        this.$state.go('^');
usually, it's the `goBack` function, so you can use it instead of recreating a new routing call

2023-11-17 12:09 UTC, darsene commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/view/view.controller.js
> +  }
can be removed as you use the `goBack` function

2023-11-17 12:51 UTC, ghyenne requested changes

2023-11-17 12:51 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/restore/restore.controller.js
> +      });
```suggestion
      .catch(({ data: { message } }) => 
        this.Alerter.error(
          this.$translate.instant('dashboard_history_error', { message }),
          ALERT_DNS_RESTORE_ID,
        ));
```

2023-11-17 12:51 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/restore/restore.controller.js
> +  constructor(DNSZoneService, Alerter, $translate) {
```suggestion
export default class RestoreDnsZoneController {
/* @ngInject */
  constructor($translate, Alerter, DNSZoneService) {
```

2023-11-17 12:51 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/view/view.html
> +    ></div>
```suggestion
    data-on-dismiss="$ctrl.goBack()"
    data-loading="$ctrl.loadingDnsZoneData"
>
    <div
        style="white-space: pre-wrap;"
        class="modal-scroll-auto"
        data-ng-bind-html="$ctrl.dnsZoneData"
    ></div>
```

2023-11-17 12:51 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/restore/restore.html
> +</oui-modal>
```suggestion
<oui-modal
    data-heading="{{:: 'dashboard_history_restore_modal_title' | translate }}"
    data-primary-action="$ctrl.confirmRestoreDnsAtDate()"
    data-primary-label="{{ :: 'dashboard_history_restore_modal_primary_label' | translate }}"
    data-secondary-action="$ctrl.goBack()"
    data-secondary-label="{{ :: 'dashboard_history_restore_modal_secondary_label' | translate }}"
    data-on-dismiss="$ctrl.goBack()"
>
    <p
        data-translate="dashboard_history_restore_modal_content"
        data-translate-values="{ date: $ctrl.chosenDate }"
    ></p>
 
    <oui-message type="warning">
      <p data-translate="dashboard_history_restore_modal_warning_message"></p>
    </oui-message>
    
    <oui-message type="info">
      <p data-translate="dashboard_history_restore_modal_info_message"></p>
    </oui-message>
    
    <div data-ovh-alert="dnsZoneAlert"></div>
</oui-modal>
```

2023-11-17 12:51 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/view/view.html
> +    ></div>
What is the data type in $ctrl.dnsZoneData ? Is it text ?
What is the goal to add style and class ?

2023-11-17 13:23 UTC, darsene commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/dashboard.controller.js
> +    this.$state.go('app.zone.details.zone-history.view', { url });
should be defined in the resolve of routing file as well

2023-11-17 13:23 UTC, darsene commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/restore/restore.controller.js
> +  constructor($translate, Alerter, DNSZoneService) {
`/* @ngInject */`

2023-11-17 13:45 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/view/view.html
> +    ></div>
```suggestion
    <pre
        data-ng-bind="$ctrl.dnsZoneData"
    ></pre>
```
I think a `<pre>` is more adapted for your case.

2023-11-17 13:56 UTC, darsene approved these changes

2023-11-17 13:57 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/dashboard/restore/restore.html
> +    secondary-label="{{ :: 'dashboard_history_restore_modal_secondary_label' | translate }}"
```suggestion
    data-primary-action="$ctrl.confirmRestoreDnsAtDate()"
    data-primary-label="{{ :: 'dashboard_history_restore_modal_primary_label' | translate }}"
    data-secondary-action="$ctrl.goBack()"
    data-secondary-label="{{ :: 'dashboard_history_restore_modal_secondary_label' | translate }}"
```

2023-11-20 08:21 UTC, ghyenne commented on packages/manager/apps/web/client/app/dns-zone/history/history.routing.js
> +      },
```suggestion
      getDnsZoneData: /* @ngInject */ (DNSZoneService) => (url) => DNSZoneService.getDnsFile(url),
```

2023-11-20 08:41 UTC, ghyenne approved these changes

2023-11-20 08:45 UTC, merged