fix(dedicated.game-firewall): reload game firewall page
ovh/manager pull request #10362
Opened 2023-11-21 14:59 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-12672
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Resolve error on reload game firewall page

## Related

2023-11-22 09:22 UTC, anooparveti requested changes

2023-11-22 09:22 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
> +  $stateParams,
**nitpick:** Can you please send the stateParam as an input and avoid injecting `$stateParams` service into the controller.

2023-11-22 09:23 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
> +        .get(`/ip?ip=${window.encodeURIComponent($stateParams.ip)}`)
**niptick** : set `id` params in the `resolve` part of the routing instead of injecting it directly in the controller

2023-11-22 09:23 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controller.js
> +  $stateParams,
```suggestion
```

2023-11-24 09:28 UTC, qpavy approved these changes

2023-11-24 09:34 UTC, ghyenne approved these changes

2023-11-24 09:35 UTC, merged

2023-11-24 09:36 UTC, JacquesLarique approved these changes