feat(web.domain): datagrid - display status technical
ovh/manager pull request #10360
Opened 2023-11-21 14:26 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/domain-optim
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-11841
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

datagrid - display status technical

## Related

2023-11-21 14:34 UTC, qpavy requested changes

2023-11-21 14:34 UTC, qpavy commented on packages/manager/apps/web/client/app/domain/list/list-domain-layout.controller.js
> +      ),
```suggestion
      values: this.domainLockStatusEnum.map(
        (status) => ({
          status: this.$translate.instant(
            `domains_transfer_lock_status_${status}`,
          ),
        })
      ),
```

2023-11-21 14:34 UTC, qpavy commented on packages/manager/apps/web/client/app/domain/list/list-domain-layout.controller.js
> +      ),
```suggestion
      values: this.domainDnssecStateEnum.map(
        ( status) => ({
          status: this.$translate.instant(`domains_dnssec_state_${status}`),
        })
      ),
```

2023-11-22 07:50 UTC, anooparveti approved these changes

2023-11-22 08:07 UTC, sachinrameshn approved these changes

2023-11-22 08:29 UTC, merged

2023-11-22 08:30 UTC, qpavy approved these changes