feat(web.hosting): db order: retrieve ram sizes from new api
ovh/manager pull request #10387
Opened 2023-11-24 10:29 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? |no
| Tickets          | Feat MANAGER-12619
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Use new API to retrieve ram sizes for web cloud database order

## Related

2023-11-24 10:39 UTC, antonymarion commented on packages/manager/apps/web/client/app/private-database/order/clouddb/private-database-order-clouddb.service.js
> +          label: this.$filter('bytes')(ram, undefined, false, 'MB'),
can we remove the usage of $filter?

2023-11-24 10:48 UTC, JacquesLarique requested changes

2023-11-24 10:48 UTC, JacquesLarique commented on packages/manager/apps/web/client/app/private-database/order/clouddb/private-database-order-clouddb.service.js
> +      .filter((value) => value !== null)
Can you merge these two loop into one reduce.
And if you feel adventurous include also the sort (but it's more complicated)

2023-11-24 14:29 UTC, antonymarion approved these changes

2023-11-24 15:16 UTC, JacquesLarique approved these changes

2023-11-27 11:23 UTC, anooparveti approved these changes

2023-12-01 13:49 UTC, merged