PCI vouchers standalone application
ovh/manager pull request #10445
Opened 2023-12-01 13:45 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | DTCORE-1661
| License          | BSD 3-Clause

## Description

- Extract PCI vouchers section into an angular "pci-vouchers" module
- Create "pci-vouchers-app" standalone application
- Use "pci-vouchers" angular module in both "public-cloud" and "pci-vouchers-app" applications

2023-12-06 08:13 UTC, cbourgois approved these changes

2023-12-06 08:45 UTC, kqesar approved these changes

2023-12-12 10:44 UTC, cbourgois approved these changes

2023-12-12 11:05 UTC, anooparveti reviewed
**question:** @frenautvh during our last weekly, we spoke about not having to create a new module in the "modules" folder. Can we follow the same strategy here as well and move the files to "app" folder itself?

2023-12-13 09:29 UTC, chipp972 submitted a review, later dismissed

2023-12-13 09:29 UTC, chipp972 commented on packages/manager/apps/pci-vouchers/src/index.js
> +      .catch(() => {})
It will work without the region config ?
Is there a fallback config ?

2023-12-13 15:33 UTC, frenautvh commented
> **question:** @frenautvh during our last weekly, we spoke about not having to create a new module in the "modules" folder. Can we follow the same strategy here as well and move the files to "app" folder itself?

@anooparveti we won't create a module app for new react applications, for micro app migration in angular js we need a module because we need to be able to share code between micro app and monolith app during the feature-flipping phase

2023-12-27 09:54 UTC, kqesar submitted a review, later dismissed

2023-12-29 10:42 UTC, anooparveti requested changes

2023-12-29 10:42 UTC, anooparveti commented on packages/manager/apps/pci-vouchers/src/pci-vouchers.module.js
Redirection to error page needs to be set-up in case we have an error during the state transition.

2024-01-12 09:18 UTC, anooparveti approved these changes

2024-01-18 08:15 UTC, chipp972 approved these changes

2024-01-23 07:59 UTC, merged