Add general information and attach data tab in ai training and rework clean up code
ovh/manager pull request #10485
Opened 2023-12-06 15:34 UTC by abullet33

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #datatr-416 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description
Rework on dashboard (add general information and attach data tab)
Rework on ai training and ai jobs
Rework on onboarding page
better management of mutualized component

## Related

2023-12-08 11:25 UTC, BrunoMarquesOVH requested changes

2023-12-11 12:59 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/jobs/dashboard/attach-data/attach-data.controller.js
> +    console.log(this.job);
hello, resolve :)

2023-12-12 09:50 UTC, dectotam approved these changes

2023-12-12 15:06 UTC, jperchoc commented on packages/manager/modules/pci/src/projects/project/training/training.service.js
> +  // validé
I’m not sure that we want to keep this comment here

2023-12-13 09:26 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/jobs/components/resubmit/resubmit.controller.js
> +        this.isLoading = false;
Yep  thx :)

2023-12-13 09:38 UTC, BrunoMarquesOVH approved these changes

2023-12-13 10:33 UTC, jperchoc approved these changes

2023-12-13 10:36 UTC, dectotam approved these changes

2024-01-28 00:00 UTC, closed without merging