Dev/vcasse/ena 68
ovh/manager pull request #10496
Opened 2023-12-07 16:25 UTC by VincentCasse

| Question         | Answer
| ---------------- | ---
| Branch?          |  `develop` 
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | ENA-68 -->
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

ENA68 allow users to have both local users and federated users in the same time.
+ a lot of quicks fix
* Clean all error messages
* Display missing right when error is 403
* Fix display with users > federation > groups (was mixed before)
* Remove customer code that was confusing and push compatible nichandle

## Related

2023-12-08 09:50 UTC, darsene commented on packages/manager/apps/dedicated/client/app/account/user/users/update/user-users-update.controller.js
> +        if (err.data.message === 'User not granted for this request') {
same

2023-12-08 17:03 UTC, VincentCasse commented on packages/manager/apps/dedicated/client/app/account/user/users/add/user-users-add.controller.js
> +        if (err.data.message === 'User not granted for this request') {
Agree, it could be better if message changes. I will apply this patch foreach line with the error message

2023-12-08 17:07 UTC, VincentCasse commented on packages/manager/apps/dedicated/client/app/account/user/users/translations/Messages_fr_FR.json
> +  "user_users_sso_update_modal_group_local_users_to_enable": "Conserver les utilisateurs OVHcloud activés",
I just "duplicate" the way this page is done but if you agree for aggregation, I'm following you, it's better

2023-12-08 17:15 UTC, VincentCasse commented
@darsene thanks a lot for the review. I have just sent a new commit to apply your requests

2023-12-12 09:45 UTC, darsene submitted a review, later dismissed

2023-12-12 09:45 UTC, darsene commented
> @darsene thanks a lot for the review. I have just sent a new commit to apply your requests

Hello @VincentCasse , all is good for me

2023-12-12 09:58 UTC, sachinrameshn approved these changes

2023-12-20 16:41 UTC, Alkorin requested changes
Do not remove CustomerCode as it was done for CA and US to avoid personal data leak

2024-01-02 14:51 UTC, VincentCasse commented
> Do not remove CustomerCode as it was done for CA and US to avoid personal data leak

After discussion with product managers, revert on customerCode was sent in my last commit

2024-01-19 08:33 UTC, merged