feat(dedicated.cluster) : general information tab
ovh/manager pull request #10511
Opened 2023-12-11 08:14 UTC by karim-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-12272`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-12272
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [] Breaking change is mentioned in relevant commits

## Description

Add the cluster level and general information tab

## Related

2023-12-11 12:30 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/cluster.routing.js
> +const STATUS_DONE = 'DONE';
```suggestion
```
Maybe we can move in contants file

2023-12-11 12:32 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/edit-display-name/template.html
> +</edit-service-name>
```suggestion
<edit-service-name
    data-service-id="{{ $ctrl.serviceInfos.serviceId }}"
    data-name="{{ $ctrl.displayName }}"
    data-on-success="$ctrl.handleSuccess(message, name)"
    data-on-cancel="$ctrl.goBack()"
    data-on-error="$ctrl.handleError(error)"
>
</edit-service-name>
```

2023-12-11 12:34 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.constants.js
> +};
```suggestion
export const TRAVAUX_LINK = {
  US: 'https://status.us.ovhcloud.com/',
  DEFAULT: 'https://www.status-ovhcloud.com/',
};
export default {
  TRAVAUX_LINK
}

```

2023-12-11 12:35 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.controller.js
> +  constructor(coreConfig) {
```suggestion
export default class DedicatedClusterDashboard {
/* @ngInject */
  constructor(coreConfig) {
```

2023-12-11 12:37 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster/cluster.controller.js
> +export default class ClusterCtrl {}
```suggestion
```
I think no need this file.

2023-12-11 12:39 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster/cluster.html
> +    ></h2>
```suggestion
    <h2
        class="oui-header__description"
        data-ng-bind="'Cluster description - To retrieved from an API - Hard coded for now'"
    ></h2>
```
Maybe remove it for now and added it only when the information is available

2023-12-11 12:40 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster/cluster.service.js
> +  constructor($http) {
```suggestion
export default class Cluster {
/* @ngInject */
  constructor($http) {
```

2023-12-11 12:42 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/general-information/general-information.html
> +                on-click="$ctrl.goToEditName($ctrl.displayName)"
```suggestion
                data-on-click="$ctrl.goToEditName($ctrl.displayName)"
```

2023-12-11 12:43 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.html
> +            ></server-support>
```suggestion
            <server-support
                data-service-name="{{$ctrl.displayName}}"
                data-travaux-url="{{$ctrl.TRAVAUX_LINK}}"
                data-tracking-prefix="$ctrl.trackingPrefix"
            ></server-support>
```

2023-12-11 12:44 UTC, ghyenne commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.html
> +            </billing-subscription-tile>
```suggestion
            <billing-subscription-tile
                data-on-error="$ctrl.onBillingInformationError(error)"
                data-service-infos="$ctrl.serviceInfos"
                data-user="$ctrl.user"
                data-tracking-prefix="$ctrl.trackingPrefix"
            >
            </billing-subscription-tile>
```

2023-12-20 11:28 UTC, darsene requested changes

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/cluster.constant.js
> +export const STATUS_DONE = 'DONE';
no other values for status ?
```suggestion
export const STATUS = { DONE: 'DONE' };
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/cluster.constant.js
> +  STATUS_DONE,
```suggestion
  STATUS,
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/cluster.routing.js
> +import { STATUS_DONE } from './cluster.constant';
```suggestion
import { STATUS } from './cluster.constant';
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/cluster.routing.js
> +        const reload = (message && type === STATUS_DONE) || stateReload;
```suggestion
      ) => (message = false, type = STATUS.DONE, stateReload = false) => {
        const reload = (message && type === STATUS.DONE) || stateReload;
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/edit-display-name/routing.js
> +            error.message || error.data?.message,
sounds more logic to check `error.data` before. And what about if no message ?
```suggestion
            error.data?.message || error.message || error,
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/cluster/translations/Messages_fr_FR.json
> +  "cluster_informations_general": "Informations générales"
put key in english format
```suggestion
  "cluster_general_information": "Informations générales"
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/README.md
should be removed

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.constants.js
> +export const TRAVAUX_LINK = {
do not use french variable
```suggestion
export const WORK_IN_PROGRESS_LINK = {
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.constants.js
> +  TRAVAUX_LINK,
```suggestion
  WORK_IN_PROGRESS_LINK,
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/cluster-dashboard/dashboard.controller.js
> +  }
```suggestion
import { WORK_IN_PROGRESS_LINK } from './dashboard.constants';

export default class DedicatedClusterDashboard {
  /* @ngInject */
  constructor(coreConfig) {
    this.WORK_IN_PROGRESS_LINK =
      WORK_IN_PROGRESS_LINK[coreConfig.getRegion()] || WORK_IN_PROGRESS_LINK.DEFAULT;
  }
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/cluster/cluster.html
> +            ><span data-translate="cluster_informations_general"></span
```suggestion
            ><span data-translate="cluster_general_information"></span
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/cluster/cluster.service.js
> +      .then(({ data }) => data.billing.plan.invoiceName);
To prevent null access
```suggestion
      .then(({ data: {billing : {plan : {invoiceName} } } } ) => invoiceName);
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/general-information/general-information.html
> +    data-heading="{{ 'dedicated_cluster_dashboard_informations_general' | translate }}"
```suggestion
    data-heading="{{ 'dedicated_cluster_dashboard_general_information | translate }}"
```

2023-12-20 11:28 UTC, darsene commented on packages/manager/modules/bm-cluster-components/src/general-information/translations/Messages_fr_FR.json
> +  "dedicated_cluster_dashboard_informations_general": "Informations générales",
```suggestion
  "dedicated_cluster_dashboard_general_information": "Informations générales",
```

2024-01-09 15:22 UTC, darsene approved these changes

2024-01-10 09:22 UTC, ghyenne approved these changes

2024-01-10 09:32 UTC, merged