Feat/default private network cidr
ovh/manager pull request #10574
Opened 2023-12-20 09:17 UTC by blemoineovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-01-02 09:30 UTC, anooparveti requested changes
Can you rebase your branch with `master`. The PR has an unwanted commit from your other ticket?
Also, the scope of the commit should indicate `pci` and not `vrack`.

2024-01-10 05:48 UTC, anooparveti approved these changes

2024-01-10 09:33 UTC, sachinrameshn submitted a review, later dismissed

2024-01-16 11:28 UTC, darsene approved these changes

2024-01-16 11:45 UTC, merged