fix(dedicated): update us documentation links in datastores
ovh/manager pull request #10604
Opened 2023-12-29 09:56 UTC by BrunoMarquesOVH

ref: MANAGER-12482

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-12-29 10:32 UTC, anooparveti requested changes

2023-12-29 10:32 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.controller.js
**nitpick:** The previous implementation is a faulty one to use "Manager Language" Can you refactor it to use subsidiary instead?

2024-01-02 11:38 UTC, BrunoMarquesOVH commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/datacenter/datastore/dedicatedCloud-datacenter-datastore.controller.js
Done!

2024-01-03 09:28 UTC, anooparveti approved these changes

2024-01-03 09:38 UTC, dectotam approved these changes

2024-01-25 16:56 UTC, merged