feat(signup): add searchable country list and update labels
ovh/manager pull request #10625
Opened 2024-01-04 07:57 UTC by BrunoMarquesOVH

ref: MANAGER-12502

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-12502
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

Add searchable country list and update labels

## Related

2024-01-05 09:09 UTC, JacquesLarique requested changes

2024-01-05 09:09 UTC, JacquesLarique commented on packages/manager/modules/sign-up/src/form/details/details.controller.js
> -  onCountryChange() {
As disscussed, we should not need to handle any rebinding on the controller side,
I'm currently checking with Anoop to have an update on the oui-select component to have the binding on the country code working (PR: https://github.com/ovh/ovh-ui-kit/pull/836/).

2024-01-12 13:18 UTC, anooparveti requested changes
Can you please update `ui-kit` on all the apps and not just `sign-up` app.

2024-01-18 13:48 UTC, JacquesLarique submitted a review, later dismissed

2024-01-24 09:26 UTC, anooparveti approved these changes

2024-02-06 08:53 UTC, dectotam submitted a review, later dismissed

2024-02-06 10:03 UTC, anooparveti approved these changes

2024-03-28 09:11 UTC, sachinrameshn approved these changes

2024-03-29 12:34 UTC, merged