feat(dedicated): eol rbx1 banner
ovh/manager pull request #10626
Opened 2024-01-04 08:56 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12907
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-01-04 08:58 UTC, antonymarion submitted a review, later dismissed

2024-01-04 09:12 UTC, antonymarion approved these changes

2024-01-04 09:14 UTC, anooparveti requested changes

2024-01-04 09:14 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/app.module.js
> +import ovhManagerHub from '@ovh-ux/manager-hub';
**nitpick(blocking):** We cannot import Hub into dedicated. Please find a more suitable place to define the component.

2024-01-04 09:17 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/servers/servers.html
> +        data-show="$ctrl.displayRbx1EolBanner.rbx1Eol"
```suggestion
        data-ng-if="$ctrl.displayRbx1EolBanner.rbx1Eol"
```

2024-01-04 09:17 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +            data-show="$ctrl.displayRbx1EolBanner.rbx1Eol"
```suggestion
            data-ng-if="$ctrl.displayRbx1EolBanner.rbx1Eol"
```

2024-01-05 07:00 UTC, anooparveti requested changes

2024-01-05 07:00 UTC, anooparveti commented on packages/manager/apps/dedicated/package.json
> +    "@ovh-ux/manager-hub": "^3.7.14",
**nitpick:** You dont need this anymore

2024-01-05 07:00 UTC, anooparveti commented on packages/manager/modules/cloud-universe-components/src/rbx-eol-banner/translations/Messages_fr_FR.json
> +  "rbx1_eol_banner": "ATTENTION: Pour permettre la modernisation du bâtiment, les serveurs situés au Datacenter Roubaix RBX1 doivent être migrés avant le 31 décembre 2024. Merci de vous référer au ma
**nitpick:** Link can be separated into a different key and define the anchor tag in template.

2024-01-05 12:03 UTC, anooparveti approved these changes

2024-01-05 12:37 UTC, ghyenne approved these changes

2024-01-15 09:03 UTC, ghyenne submitted a review, later dismissed

2024-01-15 09:04 UTC, dectotam approved these changes

2024-01-15 09:04 UTC, JacquesLarique submitted a review, later dismissed

2024-02-22 13:52 UTC, antonymarion approved these changes

2024-02-22 13:53 UTC, JacquesLarique approved these changes

2024-02-22 13:53 UTC, ghyenne approved these changes

2024-02-22 13:53 UTC, anooparveti approved these changes

2024-02-22 15:13 UTC, merged