feat(dedicated-cloud): add commercial name in general information tab
ovh/manager pull request #10642
Opened 2024-01-05 10:01 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-12966
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

add commercial name in general information tab

## Related

2024-01-05 10:03 UTC, anooparveti requested changes
Scope of the commit can be `dedicated`

2024-01-05 10:03 UTC, ghyenne approved these changes

2024-01-05 10:19 UTC, qpavy approved these changes

2024-01-05 13:06 UTC, anooparveti submitted a review, later dismissed

2024-01-25 06:28 UTC, anooparveti approved these changes

2024-01-25 07:39 UTC, qpavy approved these changes

2024-01-25 07:51 UTC, ghyenne approved these changes

2024-01-25 16:58 UTC, merged