fix(dedicated):fix typo in contact management page
ovh/manager pull request #10646
Opened 2024-01-05 15:25 UTC by benjaminlepine

ref: MANAGER-12852

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-02-02 14:24 UTC, anooparveti approved these changes

2024-02-06 06:53 UTC, anooparveti requested changes
Can you remove the changes from `Messsages_fr_CA.json`

2024-02-07 09:22 UTC, anooparveti submitted a review, later dismissed

2024-02-07 09:24 UTC, darsene approved these changes

2024-02-12 09:25 UTC, darsene submitted a review, later dismissed

2024-02-12 09:33 UTC, anooparveti approved these changes

2024-02-29 17:41 UTC, anooparveti approved these changes

2024-03-07 15:05 UTC, merged