fix(catalog): improve text design on catalog
ovh/manager pull request #10671
Opened 2024-01-10 14:13 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-12956
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I changed design issue in ods text for catalog

## Related

2024-01-10 14:22 UTC, chipp972 approved these changes

2024-01-23 13:37 UTC, vovh commented on packages/manager/apps/catalog/src/components/Filters/FilterItem.tsx
> +  ODS_THEME_COLOR_HUE,
I think you forgot to remove this unused import, would you mind to clean it up pretty please ? 
[Sonarcloud](https://sonarcloud.io/project/issues?resolved=false&pullRequest=10671&id=ovh_manager&open=AYz9O84usTMlDTLTl5Cw)

2024-02-05 14:19 UTC, chipp972 submitted a review, later dismissed

2024-02-05 14:48 UTC, anooparveti requested changes
Remove `manager` submodule.

2024-02-06 06:20 UTC, anooparveti approved these changes

2024-02-09 11:34 UTC, merged