feat(webcloud): change links for SSL certificate support
ovh/manager pull request #10673
Opened 2024-01-10 16:29 UTC by blemoineovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-01-12 09:31 UTC, darsene approved these changes

2024-01-12 09:32 UTC, ghyenne approved these changes

2024-01-12 13:10 UTC, anooparveti requested changes
Can you change the scope of the commit to `feat(webcloud):..` -> `feat(web):...`

2024-01-17 08:55 UTC, blemoineovh commented
> Can you change the scope of the commit to `feat(webcloud):..` -> `feat(web):...`

changed commit message

2024-01-17 13:18 UTC, anooparveti approved these changes

2024-03-04 00:00 UTC, closed without merging