feat(rancher): add dashboard page and pooling on rancher
ovh/manager pull request #10714
Opened 2024-01-17 10:00 UTC by lionel95200x

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-12775-rancher-epic` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-12785
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

- Add dashboard page for Rancher Project
- Setup Pooling of rancher to display message statut

## Related

2024-01-18 08:57 UTC, anooparveti requested changes
Complete the PR checklist and description

2024-01-18 09:11 UTC, ghyenne commented on packages/manager/apps/pci-rancher/src/components/TileBlock/TileBlock.tsx
> +};
I think that the typing of children is missing

2024-01-18 09:11 UTC, ghyenne commented on packages/manager/apps/pci-rancher/src/components/layout-helpers/Dashboard/Dashboard.tsx
> +      <div className="py-4 ">
```suggestion
      <div className="py-4">
```

2024-01-18 15:47 UTC, anooparveti requested changes

2024-01-18 15:47 UTC, anooparveti commented on packages/manager/apps/container/src/container/legacy/server-sidebar/universe/public-cloud/pci-menu.ts
> +  'rancher',
```suggestion
  'pci-rancher',
```

2024-01-18 15:47 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts
> +        'rancher',
```suggestion
        'pci-rancher',
```

2024-01-19 08:21 UTC, aboungnaseng-ovhcloud commented on packages/manager/apps/pci-rancher/src/pages/dashboard/Tabs1.tsx
> -    <div className="grid xs:grid-cols-1 sm:grid-cols-2 md:grid-cols-3 py-6"></div>
Do you use this Tabs1 ? you have Dashboard.tsx no ?

2024-01-19 08:23 UTC, aboungnaseng-ovhcloud commented on packages/manager/apps/pci-rancher/src/components/layout-helpers/Dashboard/RancherDetail.tsx
> +              {rancher.currentState.plan}
no need to use OsdsText ?

2024-01-19 08:24 UTC, aboungnaseng-ovhcloud commented on packages/manager/apps/pci-rancher/src/components/layout-helpers/Dashboard/RancherDetail.tsx
> +                    {t('last_update_date', {
no need to use OsdsText ?

2024-01-22 07:11 UTC, anooparveti requested changes
Please complete the PR description with appropriate info.
* No corresponding ticket number is mentioned
* Target branch name is wrong

2024-01-22 09:23 UTC, aboungnaseng-ovhcloud commented
- Missing keys in rancherTaskMessage (we have console warning)
- In the delete modal you can click on delete button while the button is disabled
- Wrong police under  under Rancher version
-  Wrong police under  under "Number of CPUs" too
- "Ip authorized" in the tab is clickable
- In the "Ip authorized" tab, the chip "coming soon" is also missing
- The font is not good in the description of “general informations”

2024-01-22 14:27 UTC, merged