feat(dedicated): add region column
ovh/manager pull request #10715
Opened 2024-01-17 11:07 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/multi-az` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-11844 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-01-17 11:39 UTC, darsene approved these changes

2024-01-17 11:40 UTC, ghyenne approved these changes

2024-01-17 12:19 UTC, anooparveti approved these changes

2024-02-29 07:19 UTC, anooparveti requested changes

2024-02-29 07:19 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/dedicated-server.routing.js
> +            .$promise.then(({ data }) => data.length !== 0),
**nitpick:** Avoid making an API call just to decide if user has clusters. If it cannot be avoided, atleast re-use this response to display the Clusters listing page.

2024-02-29 08:50 UTC, anooparveti approved these changes

2024-02-29 13:11 UTC, ghyenne approved these changes

2024-02-29 13:16 UTC, merged