feat(iam): enabling both local and federated accounts (#10496)
ovh/manager pull request #10728
Opened 2024-01-19 08:35 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          |  `master` 
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | ENA-68 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

ENA68 allow users to have both local users and federated users in the same time.
+ a lot of quicks fix
* Clean all error messages
* Display missing right when error is 403
* Fix display with users > federation > groups (was mixed before)
* Remove customer code that was confusing and push compatible nichandle

## Related

:flags: Translation

- [x]  CMT-6630

Same PR as https://github.com/ovh/manager/pull/10496

2024-01-19 08:51 UTC, darsene approved these changes

2024-01-19 09:09 UTC, sachinrameshn approved these changes

2024-01-29 14:56 UTC, anooparveti requested changes
And in all other files

2024-01-29 14:56 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/account/user/users/add/user-users-add.controller.js
> +            err.data.message
```suggestion
            err?.data?.message
```

2024-01-29 14:56 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/account/user/users/delete/user-users-delete.controller.js
> +            err.data.message
```suggestion
            err?.data?.message
```

2024-01-29 14:56 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/account/user/users/disable/user-users-disable.controller.js
> +            err.data.message
```suggestion
            err?.data?.message
```

2024-02-22 14:45 UTC, merged