feat(core.tracking):Add new ODS component on tracking
ovh/manager pull request #10773
Opened 2024-01-25 14:59 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-12621
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-13140
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

I added new ODS components on tracking.

## Related

2024-01-31 08:56 UTC, ghyenne submitted a review, later dismissed

2024-01-31 09:01 UTC, anooparveti requested changes
Scope of the commit is `core` and not `react.tracking`

2024-01-31 09:31 UTC, chipp972 submitted a review, later dismissed

2024-02-01 06:19 UTC, anooparveti submitted a review, later dismissed

2024-02-01 09:14 UTC, chipp972 approved these changes

2024-02-01 13:12 UTC, ghyenne approved these changes

2024-02-02 09:40 UTC, merged