fix(dedicated.nutanix): display the list of nutanix racks
ovh/manager pull request #10780
Opened 2024-01-26 08:26 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-12983
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

display the list of nutanix racks in cluster general information tile

## Related

2024-01-26 08:43 UTC, ghyenne approved these changes

2024-01-26 12:20 UTC, antonymarion submitted a review, later dismissed

2024-02-02 13:44 UTC, anooparveti requested changes

2024-02-02 13:44 UTC, anooparveti commented on packages/manager/modules/nutanix/src/dashboard/module.js
> +  .service('NutanixNode', service)
Not good to move the `NodeService` to cluster level.

2024-03-01 10:13 UTC, anooparveti requested changes
As discussed move the getNodes function to NutanixService.

2024-03-01 10:49 UTC, anooparveti approved these changes

2024-03-04 10:05 UTC, antonymarion approved these changes

2024-03-07 15:07 UTC, merged