feat(octavia): added l7 rules listing page
ovh/manager pull request #10796
Opened 2024-01-29 14:23 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          |  `feat/octavia-policies-and-rules`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | vno
| Tickets          | MANAGER-12801
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (n/a)

## Description

Added the L7 Rules policies page

## Related

2024-01-29 14:38 UTC, anooparveti requested changes

2024-01-29 14:38 UTC, anooparveti commented on packages/manager/modules/octavia-load-balancer/src/load-balancers/load-balancer/listeners/listener/l7/rules/list/routing.js
> +        rename: `${TRACKING_NAME}::${LISTENERS_TACKING_SUFFIX}::${POLICIES_TACKING_SUFFIX}::${TRACKING_SUFFIX}`,
```suggestion
        rename: `${TRACKING_NAME}::${LISTENERS_TRACKING_SUFFIX}::${POLICIES_TACKING_SUFFIX}::${TRACKING_SUFFIX}`,
```

2024-01-29 16:30 UTC, JacquesLarique commented on packages/manager/modules/octavia-load-balancer/src/load-balancers/load-balancer/listeners/listener/l7/rules/list/routing.js
> +        breadcrumb: () => 'L7 Rules',
In fact I think we don't need one, as in the description of the page we have `L7 rule` not translated:
`Une L7 rule est un test logique et unique qui renvoie les statuts "True" ou "False". Toutes les règles doivent retourner "True" pour que la L7 Policy déclenche son action.`

2024-01-30 07:16 UTC, qpavy approved these changes

2024-01-30 09:31 UTC, anooparveti approved these changes

2024-01-30 15:43 UTC, merged