feat(web): remove spf banneer
ovh/manager pull request #10822
Opened 2024-01-31 15:31 UTC by antonymarion

ref: MANAGER-13035

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Feat#MANAGER-13035
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
~~- [ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-01-31 16:10 UTC, darsene approved these changes

2024-01-31 16:40 UTC, anooparveti requested changes
Component name is still `spf-banner`. Rename accordingly.

2024-02-01 11:54 UTC, anooparveti approved these changes

2024-02-01 16:50 UTC, darsene approved these changes

2024-02-01 17:10 UTC, merged