fix(pci.project.activate): can not use same voucher twice
ovh/manager pull request #10836
Opened 2024-02-02 13:55 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/pci-discovery`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-572
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] Only FR translations have been updated
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

2024-02-02 13:58 UTC, ghyenne approved these changes

2024-02-02 13:59 UTC, anooparveti requested changes

2024-02-02 13:59 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/activate/activate.routing.js
> +            })
There's already a catch block in Line 63, add the `if` there and throw the error.

2024-02-02 13:59 UTC, JacquesLarique approved these changes

2024-02-06 09:29 UTC, dectotam approved these changes

2024-02-06 09:33 UTC, merged