feat(dedicated.nutanix): make nutanix package clickable link
ovh/manager pull request #10838
Opened 2024-02-02 15:25 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-12973
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Make "Type of pack" a link clickable in the cluster general information page

## Related

2024-02-02 15:30 UTC, darsene requested changes

2024-02-02 15:30 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/general-info/controller.js
> +    this.coreConfig = coreConfig;
```suggestion
    this.NUTANIX_LINK = GUIDE_PACKAGES_URL[this.coreConfig.getUser().ovhSubsidiary] ||
      GUIDE_PACKAGES_URL.DEFAULT;
```
to be compliant with the other links

2024-02-02 15:30 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/general-info/controller.js
> +  }
```suggestion
```

2024-02-02 15:30 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/general-info/template.html
> +                        data-ng-href="{{:: $ctrl.getNutanixGuideUrl() }}"
```suggestion
                        data-ng-href="{{:: $ctrl.NUTANIX_LINK }}"
```

2024-02-02 15:38 UTC, darsene approved these changes

2024-02-05 12:45 UTC, antonymarion submitted a review, later dismissed

2024-02-05 12:46 UTC, JacquesLarique submitted a review, later dismissed

2024-02-05 12:58 UTC, anooparveti requested changes

2024-02-05 12:58 UTC, anooparveti commented on packages/manager/modules/nutanix/src/dashboard/general-info/constants.js
> +  DEFAULT: 'https://www.ovhcloud.com/en/hosted-private-cloud/nutanix/packaged',
**nitpick:** This is not a valid link. Maybe you can use `https://www.ovhcloud.com/en-gb/hosted-private-cloud/nutanix/packaged`

2024-02-05 13:55 UTC, antonymarion submitted a review, later dismissed

2024-02-05 14:00 UTC, anooparveti approved these changes

2024-02-29 16:23 UTC, merged