fix(ip.firewall): display select component completely
ovh/manager pull request #10912
Opened 2024-02-14 12:50 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #UXCT-523
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Display select component completely

## Related

2024-02-15 06:00 UTC, anooparveti submitted a review, later dismissed

2024-02-15 06:00 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                            class="position-initial"
**question:** Where are the classes `position-initial` & `overflow-visible` defined? They are not fro bootstrap utilities as well.

2024-02-16 09:45 UTC, JacquesLarique submitted a review, later dismissed

2024-02-16 11:31 UTC, qpavy approved these changes

2024-02-21 06:05 UTC, anooparveti requested changes

2024-02-21 06:05 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/app.less
> +  }
**nitpick:** Can you please use the scoped css classes. It is not recommended to define a CSS class required for a ips in the CSS file dedicated for the app.

2024-02-21 09:36 UTC, anooparveti requested changes

2024-02-21 09:36 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/firewall.styles.scss
> +}
**nitpick:** Define the scoped CSS class. Also, add `ip-list-firewall` in HTML template.
```suggestion
.ip-list-firewall{
   .overflow-visible {
     overflow: visible !important;
   }
}
```

2024-02-29 17:44 UTC, anooparveti approved these changes

2024-03-14 13:04 UTC, ghyenne approved these changes

2024-03-14 13:06 UTC, merged