feat(manager-components): add ods version 17.1.0
ovh/manager pull request #10956
Opened 2024-02-18 18:13 UTC by stif59100

ref:MANAGER-13705

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-12703
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I updated the ods version onmanager components library

## Related

2024-02-19 07:56 UTC, frenautvh approved these changes

2024-02-19 08:16 UTC, frenautvh requested changes
i think yarn.lock might be missing

2024-02-19 08:25 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2024-02-19 08:48 UTC, frenautvh submitted a review, later dismissed

2024-02-19 09:08 UTC, cbourgois approved these changes

2024-02-19 09:08 UTC, chipp972 approved these changes

2024-02-19 09:10 UTC, ghyenne approved these changes

2024-02-19 13:36 UTC, kqesar approved these changes

2024-02-20 10:30 UTC, ghyenne submitted a review, later dismissed

2024-02-20 10:35 UTC, chipp972 approved these changes

2024-02-20 10:55 UTC, aboungnaseng-ovhcloud approved these changes

2024-02-20 11:07 UTC, ghyenne submitted a review, later dismissed

2024-02-20 12:08 UTC, aboungnaseng-ovhcloud approved these changes

2024-02-20 12:11 UTC, aboungnaseng-ovhcloud approved these changes

2024-02-21 04:39 UTC, anooparveti approved these changes

2024-02-22 14:49 UTC, merged