fix(side-bare): fix route matcher for web domain operation
ovh/manager pull request #10967
Opened 2024-02-19 16:02 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-13579 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I fixed the routeMatcher for web domain operation

## Related

2024-02-19 16:03 UTC, frenautvh approved these changes

2024-02-19 16:08 UTC, darsene approved these changes

2024-02-19 16:12 UTC, antonymarion approved these changes

2024-02-21 04:57 UTC, anooparveti requested changes
Scope of the commit should be `container`

2024-02-22 15:03 UTC, merged