fix(catalog): avoid router redirection on catalog init
ovh/manager pull request #10966
Opened 2024-02-19 15:46 UTC by vovh

REF: MANAGER-13102

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-02-20 09:37 UTC, JacquesLarique submitted a review, later dismissed

2024-02-20 09:39 UTC, darsene commented on packages/manager/apps/catalog/src/pages/index.tsx
> +      else if (!routerInitiated && customSearchParams.size !== 0) {
`routerInitiated` is `false` here so no to check it again.
Can you add `{}` to ease the readability as well ?
```suggestion
      else if (customSearchParams.size !== 0) {
```

2024-02-21 09:08 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2024-02-21 09:11 UTC, cbourgois approved these changes

2024-02-21 09:16 UTC, acavalloni submitted a review, later dismissed

2024-02-21 09:27 UTC, anooparveti requested changes
PR title cannot start with Block letters.
`fix(catalog): Apply the filters when the user lands on the manager` -> `fix(catalog): apply filters when the user lands on the manager`.
Also, `REF` -> `ref` is the right format in the commit.

2024-02-21 09:27 UTC, chipp972 submitted a review, later dismissed

2024-02-21 09:57 UTC, vovh commented
> PR title cannot start with Block letters. `fix(catalog): Apply the filters when the user lands on the manager` -> `fix(catalog): apply filters when the user lands on the manager`. Also, `REF` -> `ref` is the right format in the commit.

Applied suggested changes and squashed commits aswell.

2024-02-21 09:59 UTC, anooparveti submitted a review, later dismissed

2024-02-28 08:50 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2024-02-28 08:53 UTC, chipp972 submitted a review, later dismissed

2024-03-21 09:48 UTC, aboungnaseng-ovhcloud approved these changes

2024-03-21 10:00 UTC, chipp972 approved these changes

2024-03-21 16:26 UTC, darsene approved these changes

2024-03-22 08:31 UTC, merged