fix(web.domain): correct the display of domain contact info
ovh/manager pull request #10968
Opened 2024-02-19 16:04 UTC by vmesnyovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-13724
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

This PR addresses the incorrect display of domain contact information, where contact details were shown as JSON objects instead of plain IDs. 
Changes ensure compatibility with both data structures (object with id and direct string formats) across Administrator, Technical, and Billing contact sections.

## Related

2024-02-20 09:44 UTC, sachinrameshn commented on packages/manager/apps/web/client/app/domain/general-informations/GENERAL_INFORMATIONS.html
> +                                ng-if="::$ctrl.domainInfos.contactAdmin.id"
```suggestion
                                data-ng-if="::$ctrl.domainInfos.contactAdmin.id"
```

2024-02-20 09:44 UTC, sachinrameshn commented on packages/manager/apps/web/client/app/domain/general-informations/GENERAL_INFORMATIONS.html
> +                                ng-if="!$ctrl.domainInfos.contactAdmin.id"
```suggestion
                                data-ng-if="!$ctrl.domainInfos.contactAdmin.id"
```

2024-02-20 09:44 UTC, sachinrameshn commented on packages/manager/apps/web/client/app/domain/general-informations/GENERAL_INFORMATIONS.html
> +                                ng-if="::$ctrl.domainInfos.contactTech.id"
```suggestion
                                data-ng-if="::$ctrl.domainInfos.contactTech.id"
```

2024-02-21 04:56 UTC, anooparveti requested changes
**question:** @vmesnyovh do we have approval for the change?

2024-02-21 08:44 UTC, vmesnyovh commented
> **question:** @vmesnyovh do we have approval for the change?

Hello @anooparveti the change was requested by Antoine Calloch.
The problem is that this affects some of the prod users, and more and more people are affected as the deployment progresses.

2024-02-21 09:19 UTC, anooparveti approved these changes

2024-02-21 09:23 UTC, sachinrameshn approved these changes

2024-02-22 15:04 UTC, merged