feat(instances.instance): use coherent formating for the instance price
ovh/manager pull request #10987
Opened 2024-02-21 09:38 UTC by brofik

ref: TAPC-481

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-481 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-02-21 10:47 UTC, y4nnL requested changes

2024-02-21 10:47 UTC, y4nnL commented on packages/manager/modules/pci/src/projects/project/instances/instance/instance.controller.js
> +    return priceFormater.format(this.instancePrice?.price.value);
```suggestion
import { Pricing } from '@ovh-ux/manager-models';

return new Pricing(
  {
    price: {
      value: this.instancePrice?.price.value,
      currencyCode: this.coreConfig.getUser().currency.code,
    },
  },
  this.coreConfig.getUserLocale(),
).price.text;
```

2024-02-23 09:42 UTC, brofik commented on packages/manager/modules/pci/src/projects/project/instances/instance/instance.controller.js
> +    return priceFormater.format(this.instancePrice?.price.value);
Done

2024-02-26 09:42 UTC, dectotam submitted a review, later dismissed

2024-02-26 11:59 UTC, anooparveti approved these changes

2024-03-07 11:16 UTC, anooparveti approved these changes

2024-04-23 00:00 UTC, closed without merging