feat(signup): added helper text for address field
ovh/manager pull request #10998
Opened 2024-02-22 08:16 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-13601
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (n/a)

## Description

Added a text helper for indian customer to insist on the fact they need to set the same address than the one on their documents.

## Related

2024-02-22 08:27 UTC, anooparveti requested changes

2024-02-22 08:27 UTC, anooparveti commented on packages/manager/modules/sign-up/src/form/details/details.scss
> +    margin-bottom: 10px;
**nitpick:** Use utilities from bootstrap (margin, display, font-size, font-weight) & ui-kit (color).

2024-02-22 08:28 UTC, darsene commented on packages/manager/apps/sign-up/src/form/component.js
> +    subsidiary: '<',
Why just not add `subsidiary` with the value `this.subsidiary || this.user.subsidiary`? You don't really need whole `user`

2024-02-22 08:28 UTC, darsene commented on packages/manager/apps/sign-up/src/routing.js
> +    subsidiary: /* @ngInject */ ($location) => $location.search().ovhSubsidiary,
```suggestion
    subsidiary: /* @ngInject */ ($location, coreConfig) => $location.search().ovhSubsidiary || coreConfig.getUser().ovhSubsidiary,
```

2024-02-22 08:28 UTC, darsene commented on packages/manager/apps/sign-up/src/routing.js
> +    user: /* @ngInject */ (coreConfig) => coreConfig.getUser(),
```suggestion
```

2024-02-22 08:28 UTC, darsene commented on packages/manager/apps/sign-up/src/form/form.controller.js
>        SUBSIDIARIES_LABEL_SUFFIX.DEFAULT;
```suggestion
     this.subsidiaryLabelSuffix =
      SUBSIDIARIES_LABEL_SUFFIX[this.subsidiary] ||
      SUBSIDIARIES_LABEL_SUFFIX.DEFAULT;
```

2024-02-22 08:32 UTC, darsene commented on packages/manager/apps/sign-up/src/details/routing.js
> +      (subsidiary || user.ovhSubsidiary) === INDIAN_SUBSIDIARY,
```suggestion
    isIndianSubsidiary: /* @ngInject */ (subsidiary) =>
      subsidiary === INDIAN_SUBSIDIARY,
```

2024-02-23 08:40 UTC, darsene approved these changes

2024-02-26 11:57 UTC, anooparveti approved these changes

2024-03-14 11:33 UTC, merged