feat(project.instances): add instances tooltips for some openstack status
ovh/manager pull request #11037
Opened 2024-02-28 08:34 UTC by brofik

ref: TAPC-476

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-476 
| License          | BSD 3-Clause

- [ x Try to keep pull requests small so they can be easily reviewed.
- [ x Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-01 09:48 UTC, dectotam requested changes

2024-03-01 09:48 UTC, dectotam commented on packages/manager/modules/pci/src/projects/project/instances/instances.controller.js
> +      'SUSPENDED',
Constants should be move in a constant file

2024-03-05 08:39 UTC, dectotam approved these changes

2024-03-05 09:24 UTC, y4nnL approved these changes

2024-03-26 09:42 UTC, dectotam approved these changes

2024-03-27 08:49 UTC, y4nnL commented on packages/manager/modules/pci/src/projects/project/instances/instances.constants.js
> +  RESUMING: 'RESUMING',
Please sort by alphanum 💅

2024-03-27 08:50 UTC, y4nnL approved these changes

2024-04-04 11:22 UTC, merged

2024-04-04 11:33 UTC, sachinrameshn commented
Same PR: https://github.com/ovh/manager/pull/11376