fix: logs data dlatform archive url payload
ovh/manager pull request #11047
Opened 2024-02-28 14:22 UTC by pfrayer

| Question         | Answer
| ---------------- | ---
| Branch?          |`develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

In Logs Data Platform, when downloading an archive, this API is called:

https://eu.api.ovh.com/console/#/dbaas/logs/%7BserviceName%7D/output/graylog/stream/%7BstreamId%7D/archive/%7BarchiveId%7D/url~POST

In the current code, a payload is given while no payload is expected. This PR removes the payload

2024-02-29 07:53 UTC, pfrayer commented
> @pfrayer there is a typo in the commit title `dlatform` -> `platform`. Can you please correct it?

Nice catch, fixed

2024-03-01 09:43 UTC, sachinrameshn reviewed
Can you add ticket reference either in description of PR or in commit message ?

2024-03-01 10:02 UTC, anooparveti requested changes
@pfrayer please be informed that all the commits on Manager must be signed-off. You can do it by using `git commit -s`. Can you please add ticket reference in your commit and sign it off?

2024-03-01 10:16 UTC, pfrayer commented
@anooparveti done

About signature, don't having the "Signed-off by:" doesn't mean the commit isn't signed:
```
› git log --show-signature                                                                   
commit cf00fde906628423c78340e1e26f105a4541a52f (HEAD -> dev/pierre.fayer/fix_ldp_archive_payload, origin/dev/pierre.fayer/fix_ldp_archive_payload)
gpg: Signature made Fri 01 Mar 2024 10:44:00 AM CET
gpg:                using EDDSA key E9C202EE8524306B1859990FCF3873C85DD3C6E7
gpg: Good signature from "Pierre Frayer <pfrayer@gmail.com>" [ultimate]
Author: Pierre Frayer <pfrayer@gmail.com>
Date:   Wed Feb 28 15:18:27 2024 +0100

    fix: logs data platform archive url payload
```
Nevertheless I added it

2024-03-06 09:39 UTC, sachinrameshn approved these changes

2024-03-12 09:49 UTC, anooparveti approved these changes

2024-04-25 13:09 UTC, merged