feat(tracking): add tracking flag users as partner
ovh/manager pull request #11095
Opened 2024-03-05 09:00 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-12998
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-03-05 11:23 UTC, anooparveti requested changes

2024-03-05 11:23 UTC, anooparveti commented on packages/components/ovh-shell/src/plugin/tracking/tracking.ts
> +      userIsPartener: user?.isPartener,
```suggestion
      userIsPartener: user?.isPartner,
```

2024-03-05 11:23 UTC, anooparveti commented on packages/manager/modules/config/src/environment/user.ts
> +  isPartener?: boolean;
```suggestion
  isPartner?: boolean;
```

2024-03-05 16:55 UTC, anooparveti approved these changes

2024-03-06 09:37 UTC, sachinrameshn approved these changes

2024-08-10 00:00 UTC, closed without merging