feat(container): add ods modal from sso auth
ovh/manager pull request #11105
Opened 2024-03-05 16:29 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/MANAGER-12303
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes/no
| Tickets          |MANAGER-13858
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I replaced sso auth modal by ods modal

## Related

2024-03-06 06:45 UTC, anooparveti commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +                </OsdsTile>
**nitpick:** The JSX is not formatted properly. Can you please format it?

2024-03-13 08:58 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +  const DisconnectedButton = ({ label }: { label: string }) => (
```suggestion
  const LogoutButton = ({ label }: { label: string }) => (
```

2024-03-13 08:59 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +const ModalContent = ({ label }: { label: string }) => (
Take children instead

2024-03-18 09:57 UTC, ghyenne approved these changes

2024-03-18 09:57 UTC, ghyenne commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +                  <div className="mb-2 ">
```suggestion
                  <div className="mb-2">
```

2024-03-19 07:04 UTC, frenautvh requested changes

2024-03-19 07:04 UTC, frenautvh commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +
```suggestion
```

2024-03-22 14:39 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +   useEffect(() => {
```suggestion
    useEffect(() => {
```

2024-03-22 14:40 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +                mode === connectedToOther) && (
```suggestion
              {([disconnectedToConnected, connectedToOther].includes(mode)) && (
```

2024-03-22 14:41 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +            mode === connectedToOther) && (
```suggestion
          {([connectedToDisconnected, disconnectedToConnected, connectedToOther].includes(mode)) && (
```

2024-03-22 14:41 UTC, chipp972 commented on packages/manager/apps/container/src/sso-auth-modal/SSOAuthModal.tsx
> +              onClick={() => authPlugin.logout()}
```suggestion
              onClick={authPlugin.logout}
```

2024-04-02 08:36 UTC, JacquesLarique submitted a review, later dismissed

2024-04-05 07:30 UTC, JacquesLarique submitted a review, later dismissed

2024-04-05 07:45 UTC, chipp972 commented
You have to rebase on master for the tests to pass

2024-04-10 07:45 UTC, JacquesLarique approved these changes

2024-04-11 15:17 UTC, merged