feat(dedicated): add tracking on byoip slice and aggregate and delete…
ovh/manager pull request #11101
Opened 2024-03-05 15:21 UTC by benjaminlepine

… additional ip

ref: MANAGER-12733

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-06 09:51 UTC, qpavy approved these changes

2024-03-07 11:12 UTC, anooparveti requested changes

2024-03-07 11:12 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/block/ip-ip-block.constant.js
> +export const DELETE_TRACKING_PREFIX = 'dedicated::ip::delete-additional-ip';
Can you add it in the default export as well? And also can you place the default export at the end of the file?

2024-03-15 07:20 UTC, ghyenne approved these changes

2024-03-15 10:26 UTC, merged