feat(iam): list identities in policy page
ovh/manager pull request #11113
Opened 2024-03-06 15:41 UTC by rjamet-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-12815`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-12815
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Add identities section in policy page, split into sections sorted by identities type.

2024-03-08 11:08 UTC, darsene requested changes

2024-03-08 11:08 UTC, darsene commented on packages/manager/modules/iam/src/components/identities/serviceAccountIdentities/serviceAccountIdentities.template.html
> +            title="'iam_identities_service_accounts_name' | translate"
```suggestion
            data-title="'iam_identities_service_accounts_name' | translate"
```

2024-03-08 11:08 UTC, darsene commented on packages/manager/modules/iam/src/components/identities/userIdentities/userIdentities.template.html
> +        <oui-datagrid-column title="'iam_identities_users_user' | translate">
```suggestion
        <oui-datagrid-column data-title="'iam_identities_users_user' | translate">
```

2024-03-08 11:08 UTC, darsene commented on packages/manager/modules/iam/src/components/identities/userIdentities/userIdentities.template.html
> +            property="status"
```suggestion
            data-title="'iam_identities_users_status' | translate"
            data-property="status"
```

2024-03-12 10:13 UTC, dectotam approved these changes

2024-03-12 15:13 UTC, merged