feat(projects.project): disable display of the mediation banner in a discovery project
ovh/manager pull request #11144
Opened 2024-03-11 08:16 UTC by brofik

ref: TAPC-519

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-519 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-13 09:35 UTC, sachinrameshn approved these changes

2024-03-14 08:27 UTC, PowerCoach requested changes
Please amend the commit message to include the pci universe in the subject

2024-03-14 08:28 UTC, y4nnL requested changes
Please amend the commit message to include the pci universe in the subject

2024-03-14 08:49 UTC, y4nnL approved these changes

2024-03-14 13:16 UTC, anooparveti approved these changes

2024-03-22 08:27 UTC, merged