feat(project.sidebar): change position of the Managed Registery Service entry in the sidebar menu
ovh/manager pull request #11143
Opened 2024-03-11 08:02 UTC by brofik

ref: TAPC-567

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-567 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-12 09:29 UTC, darsene submitted a review, later dismissed

2024-03-14 08:30 UTC, y4nnL requested changes
Please amend the commit message to include the container app in the subject instead of "project"

2024-03-14 08:48 UTC, y4nnL submitted a review, later dismissed

2024-03-14 13:31 UTC, anooparveti approved these changes

2024-03-22 08:41 UTC, darsene approved these changes

2024-03-22 08:41 UTC, anooparveti approved these changes

2024-03-22 08:51 UTC, merged