fix(public-cloud): use add private network link if no private network
ovh/manager pull request #11151
Opened 2024-03-11 15:44 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-13911
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- ~~[ ] Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

On instance creation page if the user choose a local zone region, and has no private network, a link is displaying which redirect to private network creation

## Related

2024-03-11 15:48 UTC, darsene commented on packages/manager/modules/pci/src/projects/project/instances/add/add.routing.js
> +        !privateNetworks.lenght
```suggestion
        !privateNetworks.length
```

2024-03-11 15:52 UTC, darsene approved these changes

2024-03-11 15:53 UTC, ghyenne approved these changes

2024-03-11 15:55 UTC, anooparveti requested changes
fix typo in the commit title. `ling` -> `link`

2024-03-11 16:08 UTC, darsene submitted a review, later dismissed

2024-03-11 16:13 UTC, ghyenne submitted a review, later dismissed

2024-03-12 05:38 UTC, anooparveti approved these changes

2024-03-12 12:05 UTC, anooparveti approved these changes

2024-03-12 12:07 UTC, ghyenne approved these changes

2024-03-14 15:17 UTC, merged