fix(generator): delete generouted
ovh/manager pull request #11173
Opened 2024-03-13 14:45 UTC by aboungnaseng-ovhcloud

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix MANAGER-12814
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Delete generouted

## Related

2024-03-20 16:06 UTC, aboungnaseng-ovhcloud commented on packages/manager-components/src/components/typography/links/links.component.tsx
> +        onClick={() => navigate(href)}
Nice feedback, I change this

2024-03-20 16:07 UTC, aboungnaseng-ovhcloud commented on packages/manager/core/shell-client/src/hooks/useGuideUtils.tsx
> +  tmp.forEach((value) => {
👍

2024-03-26 09:17 UTC, aboungnaseng-ovhcloud commented on packages/manager/core/generator/app/conditional-templates/dashboard/Tab2.tsx
> +import React from 'react';
Remove the Tab2 exemple ?

2024-03-26 09:18 UTC, aboungnaseng-ovhcloud commented on packages/manager/core/generator/app/conditional-templates/dashboard/_layout.tsx.hbs
> +    label: 'Retour à la liste',
yes we can translate it

2024-04-09 13:02 UTC, chipp972 commented on packages/manager/core/shell-client/src/hooks/useBreadcrumb.tsx
> +  label: string | undefined;
```suggestion
  label?: string;
```

2024-04-10 09:27 UTC, aboungnaseng-ovhcloud commented on packages/manager/core/shell-client/src/hooks/useBreadcrumb.tsx
> +  label: string | undefined;
👍

2024-04-10 09:29 UTC, chipp972 approved these changes

2024-04-11 12:54 UTC, vovh requested changes

2024-04-11 12:54 UTC, vovh commented on packages/manager/apps/container/src/core/dev/index.ts
> +      let devConfig = {
devConfig is not reassigned, shouldn't we keep const ?

2024-04-11 14:01 UTC, JacquesLarique approved these changes

2024-04-11 14:29 UTC, vovh approved these changes

2024-04-11 14:38 UTC, merged