feat(zimbra.dashboard): add usefull links
ovh/manager pull request #11224
Opened 2024-03-19 09:59 UTC by stif59100

ref:MANAGER-13738

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-13738
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added usefull links guide for zimbra dashboard.

## Related

2024-03-21 09:41 UTC, vovh approved these changes

2024-03-21 09:42 UTC, vovh requested changes
Tests are failing, could you fix them ?

2024-03-21 09:44 UTC, vovh submitted a review, later dismissed

2024-03-27 08:40 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/GeneralInformation.tsx
> +              />
Maybe we can do a map for avoid a lot html code.
For example (have to be adapted):

```suggestion
Object.values(GUIDES_LIST).map((guide, index) => 
           <div key={index}>
              <OsdsDivider separator />
              <Links
                type={LinkType.external}
                target={OdsHTMLAnchorElementTarget._blank}
                href={guide.webmail}
                label={t(guide.translationKey)
                className="block"
              />
           </div>
```

2024-03-29 10:37 UTC, ghyenne submitted a review, later dismissed

2024-05-14 08:09 UTC, aboungnaseng-ovhcloud approved these changes

2024-05-15 07:54 UTC, merged