Feat/manager 13152
ovh/manager pull request #11234
Opened 2024-03-19 15:10 UTC by benjaminlepine

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/pnr-v2
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-13152
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-22 10:39 UTC, JacquesLarique requested changes

2024-03-22 15:52 UTC, JacquesLarique requested changes

2024-03-22 15:52 UTC, JacquesLarique commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/index.tsx
> -          <ul id="menu">
Please keep the id "menu" on the ul, as it is used by the guided tour

2024-03-22 15:52 UTC, JacquesLarique commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/root.ts
> -    {
Not sure where it went but I think this is still needed (maybe in its own file)
For example `sidebar-link-billing` will be used by the guided tour

2024-04-12 14:45 UTC, benjaminlepine commented on packages/manager/apps/container/src/container/common/urls-constants.ts
> +    marketplace: 'https://marketplace.ovhcloud.com/',
i removed it

2024-04-12 14:45 UTC, benjaminlepine commented on packages/manager/apps/container/src/container/common/urls-constants.ts
> +    marketplace: 'https://marketplace.ovhcloud.com/',
removed

2024-04-15 15:04 UTC, benjaminlepine commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/SidebarLink.tsx
>  const StaticLink: React.FC<ComponentProps<StaticLinkProps>> = ({
Done

2024-04-15 16:54 UTC, benjaminlepine commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/SubTree.tsx
I think it's a great idea, but it's quite complex to implement. 
We will need to keep it for a separate ticket.

2024-04-17 10:13 UTC, JacquesLarique requested changes
The menu is not working as expected: once the mouse leave the sub menu, the sub menu stay display.
Also we need to validate what we do with the user account menu, from the code it seems no longer displayed but we still need links like the identity documents one.

2024-05-07 08:55 UTC, MaximeBajeux commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/utils.ts
> +  const regex = /Mobi|Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i;
We could use an external lib to be more accurate, but there isn't an optimal way to do that I think

2024-05-12 16:28 UTC, MaximeBajeux commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/Assistance.tsx
> +    }
Yes, it's handle globally at the navigation tree level, but we're outside of the tree here.

2024-05-14 08:42 UTC, darsene commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/Assistance.tsx
> +    }
In that case, you can group your features in one call.
```
const results: Record<string, boolean> = await reketInstance.get(
        `/feature/livechat,carbon-calculator/availability`,
        {
          requestType: 'aapi',
        },
      );
```

2024-05-15 07:45 UTC, oalkabouss commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/utils.ts
> +  const regex = /Mobi|Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i;
So, well, never mind.

2024-05-15 08:25 UTC, darsene approved these changes

2024-05-15 15:26 UTC, oalkabouss approved these changes

2024-05-16 07:00 UTC, merged