feat(signup): modification of the field related to language
ovh/manager pull request #11277
Opened 2024-03-25 07:54 UTC by MaximeBajeux

Modification on the account creation form of the field relates to customer language

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-12955
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits (n/a)

## Description

Preselect the language on reload and change the label

## Related

2024-03-25 09:05 UTC, JacquesLarique requested changes

2024-03-25 09:05 UTC, JacquesLarique commented on packages/manager/modules/sign-up/src/form/details/details.controller.js
> -    } else {
Can you use a boolean parameter to keep the behavior of emptying the language field when the user select a different country

2024-03-26 09:19 UTC, JacquesLarique requested changes

2024-03-26 09:19 UTC, JacquesLarique commented on packages/manager/modules/sign-up/src/form/details/details.controller.js
> +      if (get(this.signUpFormCtrl, 'rules.language.in.length', 0) === 1) {
Can you keep this if block ouside of the `if (isOnChange)` as it allow us to preselect the language (if unique) on the arrival on the page

2024-03-27 09:05 UTC, JacquesLarique approved these changes

2024-03-27 09:26 UTC, qpavy submitted a review, later dismissed

2024-04-11 11:43 UTC, JacquesLarique approved these changes

2024-04-11 12:06 UTC, antonymarion approved these changes

2024-04-11 14:58 UTC, merged