feat(pci.projects.dashboard): disable discovery project creation in IN when undergoing kyc validation
ovh/manager pull request #11297
Opened 2024-03-27 07:10 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-625 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-03-27 07:36 UTC, sachinrameshn requested changes

2024-03-27 07:36 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.controller.js
> +  isIndianAccountUnderVerification() {
To be more generic: 
```suggestion
  isKycValidationUnderVerification() {
```

2024-03-27 07:36 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.html
> +        >
```suggestion
            data-ng-if="$ctrl. isKycValidationUnderVerification()"
        >
```

2024-03-27 07:36 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.html
> +                data-disabled="$ctrl.isIndianAccountUnderVerification()"
```suggestion
                data-disabled="$ctrl. isKycValidationUnderVerification()"
```

2024-03-27 07:36 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/onboarding/translations/Messages_fr_FR.json
> +  "pci_projects_onboarding_banner_account_under_verification_description": "Vous souhaitez créer un projet Public Cloud : la réglementation en vigueur nécessite une vérification de votre identité. Le
```suggestion
  "pci_projects_onboarding_banner_kyc_validation_under_verification_description": "Vous souhaitez créer un projet Public Cloud : la réglementation en vigueur nécessite une vérification de votre identité. Le traitement de vos documents est actuellement en cours d'analyse par notre équipe. Pour plus d'information, vous pouvez consulter ",
```

2024-03-27 07:36 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/onboarding/translations/Messages_fr_FR.json
> +  "pci_projects_onboarding_banner_account_under_verification_link": "Mes demandes d'assistance"
```suggestion
  "pci_projects_onboarding_banner_kyc_validation_under_verification_link": "Mes demandes d'assistance"
```

2024-03-27 07:55 UTC, brofik commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.controller.js
> +  isIndianAccountUnderVerification() {
Done.

2024-03-27 07:55 UTC, brofik commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.html
> +        >
Done.

2024-03-27 07:56 UTC, brofik commented on packages/manager/modules/pci/src/projects/onboarding/onboarding.html
> +                data-disabled="$ctrl.isIndianAccountUnderVerification()"
Done.

2024-03-27 07:56 UTC, brofik commented on packages/manager/modules/pci/src/projects/onboarding/translations/Messages_fr_FR.json
> +  "pci_projects_onboarding_banner_account_under_verification_description": "Vous souhaitez créer un projet Public Cloud : la réglementation en vigueur nécessite une vérification de votre identité. Le
Done.

2024-03-27 07:56 UTC, brofik commented on packages/manager/modules/pci/src/projects/onboarding/translations/Messages_fr_FR.json
> +  "pci_projects_onboarding_banner_account_under_verification_link": "Mes demandes d'assistance"
Done.

2024-03-27 07:58 UTC, sachinrameshn submitted a review, later dismissed

2024-04-19 12:27 UTC, y4nnL approved these changes

2024-05-17 07:48 UTC, qpavy approved these changes

2024-05-17 07:48 UTC, darsene approved these changes

2024-05-17 07:50 UTC, anooparveti approved these changes

2024-05-17 08:56 UTC, merged