feat(containers.add): add storageClass selection for object import
ovh/manager pull request #11368
Opened 2024-04-04 07:30 UTC by brofik

ref: TAPC-695

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/s3-endpoint-merge`  
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-695 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-04-05 08:38 UTC, dectotam requested changes

2024-04-05 08:38 UTC, dectotam commented on packages/manager/modules/pci/src/projects/project/storages/containers/container/object/add/add.controller.js
> +    ];
```suggestion
    this.priceLink = STORAGE_PRICES_LINK[
      this.coreConfig.getUser().ovhSubsidiary
    ] || STORAGE_PRICES_LINK.DEFAULT;
```

2024-04-05 08:38 UTC, dectotam commented on packages/manager/modules/pci/src/projects/project/storages/containers/container/object/add/add.controller.js
> +    this.STORAGE_PRICES_LINK = STORAGE_PRICES_LINK;
It seems that this is not used in the template, therefore you can directly use STORAGE_PRICES_LINK in the controller 
```suggestion
```

2024-04-05 13:47 UTC, dectotam approved these changes

2024-04-10 09:12 UTC, y4nnL approved these changes

2024-04-11 05:47 UTC, merged