feat(dedicated): delete ipv6 from vrack
ovh/manager pull request #11462
Opened 2024-04-16 06:13 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/additional-ipv6-feature`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #MANAGER-13709
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-04-16 12:09 UTC, qpavy requested changes

2024-04-16 12:09 UTC, qpavy commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    this.showModal = () => {
Can you check if it is possible to use moveDialog component that already exist on vrack ? If it is not possible, try to not use jquery but use a component for the modal and use n-gi to display it or not like it is done here : https://github.com/ovh/manager/blob/master/packages/manager/apps/dedicated/client/app/account/identity-documents/upload-identity-documents-confirm/template.html

2024-04-16 12:09 UTC, qpavy commented on packages/manager/modules/vrack/src/dashboard/vrack.module.js
> +      $templateCache.put('vrack/partials/delete.html', deletePartials);
If not possible to use actual moveDialog, create a new component instead of using partials

2024-04-16 12:09 UTC, qpavy commented on packages/manager/modules/vrack/src/partials/delete.html
> +<form name="deleteIpv6FromVrack" novalidate>
Why do you need a form ? there is no fields on the modal

2024-04-22 09:16 UTC, qpavy commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    this.CucVrackService = CucVrackService;
it seems like this is not used, if it is the case, can you remove it ?

2024-04-24 08:32 UTC, qpavy approved these changes

2024-04-24 09:46 UTC, sachinrameshn approved these changes

2024-04-26 16:03 UTC, merged