feat(dedicated): delete subnet from vrack ipv6
ovh/manager pull request #11538
Opened 2024-04-24 07:56 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/additional-ipv6-feature`
| Bug fix?         |no
| New feature?     | yes
| Breaking change? |no
| Tickets          | Fix #MANAGER-14042
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-04-26 10:07 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-services/ip/add/controller.js
> +      this.onConfirm()(this.subnet, this.address);
you confuse `&` and `=` bindings. That's why you have a weird call functions here.
As you're using `&` bindings, you should set `data-on-confirm=myFunction(this.subnet, this.address)` directly in the modal html declaration

2024-04-26 10:11 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-services/ip/delete/index.js
> +    ],
`$scope` injection is useless here.
Moreover, it's weird to have the close function defined here but not the open one.
As you're using an `onConfirm` function, sounds more logic to have also `onCancel` function

2024-04-29 13:06 UTC, qpavy requested changes

2024-04-29 13:06 UTC, qpavy commented on packages/manager/modules/vrack/src/vrack-services/ip/ip.controller.js
> +      this.openAddModal()((subnet, address) => {
Same as https://github.com/ovh/manager/pull/11538/files#r1580801446

2024-04-29 13:06 UTC, qpavy commented on packages/manager/modules/vrack/src/vrack-services/ip/ip.controller.js
> +      this.openDeleteModal()(() => {
Same as https://github.com/ovh/manager/pull/11538/files#r1580801446

2024-05-03 07:36 UTC, mhelhali-soufien commented on packages/manager/modules/vrack/src/vrack-services/ip/ip.less
> +      padding: 0.625rem 0.9375rem;
It should be like as ipv4

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/dashboard/vrack.controller.js
> +    };
try to keep on way for declaring function

```suggestion
     static isIPv6(service) {
      return !!service.id.match(/::/);
    };
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/dashboard/vrack.service.js
> +      `/vrack/${serviceName}/ipv6/${window.encodeURIComponent(ipv6)}`,
```suggestion
      `/vrack/${serviceName}/ipv6/${encodeURIComponent(ipv6)}`,
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-associated-services/ipv6/ipv6.controller.js
> +  refrechData() {
```suggestion
  refreshData() {
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-associated-services/ipv6/ipv6.controller.js
> +        this.refrechData();
```suggestion
        this.refreshData();
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-associated-services/ipv6/ipv6.service.js
> +    );
```suggestion
    return this.$http.delete(
      `/vrack/${encodeURIComponent(
        serviceName,
      )}/ipv6/${encodeURIComponent(
        ipBlock,
      )}/routedSubrange/${encodeURIComponent(routedSubrange)}`,
    );
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-associated-services/ipv6/ipv6.controller.js
> +                (err.data && err.data.message) || err.message || '',
```suggestion
                error.data?.message || err.message || '',
```

2024-05-03 08:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack-associated-services/ipv6/ipv6.controller.js
> +                (err.data && err.data.message) || err.message || '',
```suggestion
               error.data?.message || err.message || '',
```

2024-05-03 10:53 UTC, darsene approved these changes

2024-05-03 11:31 UTC, qpavy approved these changes

2024-05-03 11:32 UTC, merged