feat(dedicated): add feedback option
ovh/manager pull request #11547
Opened 2024-04-24 12:20 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-04-24 13:03 UTC, antonymarion approved these changes

2024-04-24 13:07 UTC, JacquesLarique approved these changes

2024-04-25 06:44 UTC, qpavy approved these changes

2024-05-07 15:17 UTC, darsene requested changes

2024-05-07 15:17 UTC, darsene commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ip-ip-agoraOrder.constant.js
> +};
```suggestion
export const SURVEY_LANGUAGES = {
 ALLOWED : ['fr'],
 DEFAULT: 'en',
};
```

2024-05-07 15:17 UTC, darsene commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ip-ip-agoraOrder.controller.js
> +    this.surveyUrl = `${this.BASE_URL_SURVEY}${languageToUse}&nic=${user.nichandle}`;
I find the logic quite complicated.
Regarding the previous comment for the constant property, you can ease it in that way : 
```suggestion
    const userLanguage = this.coreConfig.getUserLanguage();
    const languageToUse = this.SURVEY_LANGUAGES.ALLOWED.includes(userLanguage) ? userLanguage : this.SURVEY_LANGUAGES.DEFAULT;
      
    // Get user
    const user = this.coreConfig.getUser();

    // Build url for survey link
    this.surveyUrl = `${this.BASE_URL_SURVEY}${languageToUse}&nic=${user.nichandle}`;
```
Maybe you can move it in a dedicated function as well

2024-05-07 15:17 UTC, darsene commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ip-ip-agoraOrder.html
> +                data-ng-href="{{ $ctrl.surveyUrl }}"
```suggestion
                data-ng-href="{{ :: $ctrl.surveyUrl }}"
```

2024-05-07 15:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack.constant.js
Those constants are already defined. Maybe you can group them in one dedicated module

2024-05-07 15:17 UTC, darsene commented on packages/manager/modules/vrack/src/vrack.routing.js
> +        return `${BASE_URL_SURVEY}${languageToUse}&nic=${user.nichandle}`;
This code is already defined, try to put it in a service exposed by your module and use it in the other locations

2024-05-07 15:17 UTC, darsene commented on packages/manager/modules/ng-layout-helpers/src/list/template.html
> +    </div>
You should consider to create a component and reuse it instead of duplicating the code

2024-05-22 08:28 UTC, qpavy approved these changes

2024-05-22 08:32 UTC, darsene approved these changes

2024-05-22 08:41 UTC, merged