feat(pci.project): update project creation documentation links
ovh/manager pull request #11577
Opened 2024-04-29 08:16 UTC by selm3n

ref: TAPC-616

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`  
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-616 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

## Related

2024-05-03 08:21 UTC, darsene submitted a review, later dismissed

2024-05-06 08:34 UTC, brofik commented on packages/manager/modules/pci/src/projects/creating/constants.js
> +  LT: undefined,
for LT, the displayed documentation should be the default one. You can remove this line.

2024-05-06 08:34 UTC, brofik commented on packages/manager/modules/pci/src/projects/creating/constants.js
> +  CZ: undefined,
same as https://github.com/ovh/manager/pull/11577/commits/7d3b96c487d0353ffdff6704c58ebc92ae8834fd#r1590700922

2024-05-10 08:12 UTC, brofik approved these changes

2024-05-21 07:53 UTC, y4nnL requested changes
Please amend the commit message so we have one ref / signed off note

2024-05-31 16:11 UTC, JacquesLarique approved these changes

2024-06-05 15:04 UTC, brofik approved these changes

2024-06-05 15:05 UTC, brofik approved these changes

2024-06-06 10:16 UTC, darsene approved these changes

2024-06-20 11:42 UTC, merged