feat(2fa): add redirection rule to pages
ovh/manager pull request #11588
Opened 2024-04-29 16:49 UTC by oalkabouss

ref: MANAGER-14035

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/acquisition-storage-2fa`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14035
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-04-30 07:01 UTC, anooparveti requested changes

2024-04-30 07:01 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/interfaces/index.ts
Can you please change the folder to `types` instead of `interfaces`?
Refer Manager pages for the folder structure.

2024-04-30 07:19 UTC, oalkabouss commented on packages/manager/apps/account-disable-2fa/src/interfaces/index.ts
i used interfaces because types is ignore in the gitignore file

2024-04-30 13:40 UTC, JacquesLarique reviewed
Can you add some tests for this please.
_You may take example on packages/manager/apps/pci-rancher/src/e2e/Error.e2e.ts._

2024-05-02 09:40 UTC, JacquesLarique approved these changes

2024-05-02 15:43 UTC, chipp972 commented on packages/manager/apps/account-disable-2fa/src/data/hooks/useStatus.tsx
> +export const fetch2faStatus = () =>
useFetch...

2024-05-03 14:18 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/components/Loading/Loading.tsx
Can we avoid this Loading component? It does not look like a UX approved behavior to me.

2024-05-10 14:35 UTC, JacquesLarique commented on packages/manager/apps/account-disable-2fa/src/constants/route-path-constants.ts
To be compliant with the folder structure definition, this file should be called home.constants.ts and be placed at the same level as the Home page component

2024-05-14 10:18 UTC, anooparveti requested changes

2024-05-14 10:18 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/pages/home.constants.ts.ts
Remove redundant `.ts` in the file name.

2024-05-14 10:18 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/pages/home.constants.ts.ts
Also, the routes constants must be added in the `routes` folder.

2024-05-17 08:21 UTC, anooparveti approved these changes

2024-05-17 14:40 UTC, merged