feat(pci.ai): add AI Endpoints into pci menu
ovh/manager pull request #11587
Opened 2024-04-29 15:23 UTC by abullet33

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix datatr-651 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Add a new entry into PCI menu for AI Endpoints new product
## Related

2024-04-30 08:18 UTC, JacquesLarique submitted a review, later dismissed

2024-04-30 12:24 UTC, jperchoc approved these changes

2024-04-30 15:27 UTC, JacquesLarique approved these changes

2024-05-02 11:52 UTC, anooparveti submitted a review, later dismissed

2024-05-07 08:24 UTC, anooparveti approved these changes

2024-05-07 08:26 UTC, JacquesLarique approved these changes

2024-05-07 08:38 UTC, anooparveti requested changes
There's a Jest test failure. Can you take a look on that?

2024-05-07 08:56 UTC, abullet33 commented
Hey @anooparveti,
It 's related to rancher unit test, nothing linked to files I changed, so it should be done by Rancher team

2024-05-07 11:14 UTC, anooparveti approved these changes

2024-05-10 09:03 UTC, merged