feat(rancher): use component from manager component
ovh/manager pull request #11668
Opened 2024-05-07 12:47 UTC by lionel95200x

ref: MANAGER-14286

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-14286
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Use component from manager components

## Related

2024-05-08 10:48 UTC, anooparveti requested changes

2024-05-08 10:48 UTC, anooparveti commented on packages/manager/apps/pci-rancher/tailwind.config.js
> +    '../../../manager-components/src/**/*.{js,jsx,ts,tsx}',
**nitpick:** As `manager-components` package is independent, we cannot force the consumers of the package to include it in their `tailwind.config`.
```suggestion
```

2024-05-14 08:02 UTC, chipp972 commented on packages/manager/apps/pci-rancher/src/pages/dashboard/_layout.tsx
> +      )}
Why do you have to put Dashboard twice ?

2024-05-24 08:09 UTC, chipp972 submitted a review, later dismissed

2024-06-06 12:21 UTC, selm3n submitted a review, later dismissed

2024-06-07 09:56 UTC, frenautvh commented on packages/manager/apps/pci-rancher/src/components/layout-helpers/Dashboard/RancherDetail.tsx
> +              <CommonTitle typoSize={ODS_TEXT_SIZE._400}>
why do we have to specify a size for commontitle component ? isn't it supposed to be the same size everywhere ?

2024-06-07 09:56 UTC, frenautvh submitted a review, later dismissed

2024-06-07 10:03 UTC, chipp972 submitted a review, later dismissed

2024-06-11 09:43 UTC, frenautvh approved these changes

2024-06-11 13:55 UTC, anooparveti approved these changes

2024-06-17 11:40 UTC, merged