feat(pci.rancher): define version of a rancher
ovh/manager pull request #11666
Opened 2024-05-07 09:47 UTC by selm3n

| Question         | Answer
| ---------------- | ---
| Branch?          |  `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-833 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

## Related

2024-05-08 07:47 UTC, anooparveti requested changes
Change the scope of the commit from `pci.rancher` to `pci-rancher`

2024-05-08 07:53 UTC, anooparveti commented on packages/manager/apps/pci-rancher/src/components/layout-helpers/CreateRancher/CreateRancher.tsx
> +      );
**nitpick:**  Looks like only first match is used. So `Array.prototype.find` is the right function to use.
```suggestion
      const availableVersions = versions.find(
        ({ status }) => status === 'AVAILABLE',
      );
```

2024-05-15 08:25 UTC, anooparveti approved these changes

2024-05-20 14:01 UTC, anooparveti approved these changes

2024-06-06 09:53 UTC, merged

2024-06-10 15:07 UTC, AdilCHAGRAOUI commented
release/components-w24