fix(i18n): LDP - change English traduction for paused streams
ovh/manager pull request #11719
Opened 2024-05-15 12:15 UTC by jehuty0shift

| Question         | Answer
| ---------------- | ---
| Branch?          |  `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-14329
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

This change allows users to have a better understanding of the status of a logs stream in Logs Data Platform by changing the translation of a paused stream from "On break" to "Paused".

## Related

None

2024-05-16 08:28 UTC, anooparveti requested changes
Hello @jehuty0shift,
As mentioned in https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations we can only update the French sentences. May I request you to create an issue or contact me on Webex (if you're an internal)

2024-05-20 08:31 UTC, anooparveti requested changes

2024-05-20 08:31 UTC, anooparveti commented on packages/manager/modules/dbaas-logs/src/logs/translations/Messages_en_GB.json
Hello @jehuty0shift, as a developer we cannot update the locale files directly except `Messages_fr_FR.json` as mentioned in https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations. Can you please create a ticket on CMT to fix it??

2024-05-31 15:27 UTC, jehuty0shift commented
closing because of: https://github.com/ovh/manager/pull/11859

2024-05-31 15:27 UTC, closed without merging