fix(dedicated): add missing translations for multi-AZ cluster servers
ovh/manager pull request #11722
Opened 2024-05-15 16:20 UTC by JayBeeDe

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
~Only FR translations have been updated~ see description below
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
~Breaking change is mentioned in relevant commits~

## Description

Move some existing translations (translation keys & their values doesn't change) to a new location to fix missing translations for 3AZ servers.

## Related

ref: MANAGER-14336

2024-05-16 06:13 UTC, ghyenne submitted a review, later dismissed

2024-05-16 06:45 UTC, anooparveti requested changes
Please request you to modify only `Messages_fr_FR.json` files for both removal and addition.

2024-05-16 08:13 UTC, anooparveti commented
> Please request you to modify only `Messages_fr_FR.json` files for both removal and addition.

Since the keys and the content did not change, approved even with modifications on other lang files.

2024-05-16 08:13 UTC, anooparveti submitted a review, later dismissed

2024-06-26 15:32 UTC, sachinrameshn approved these changes

2024-06-26 15:34 UTC, chipp972 approved these changes

2024-06-27 12:43 UTC, merged