feat(dedicated.nutanix): remove public bandwidth from cluster node
ovh/manager pull request #11720
Opened 2024-05-15 15:39 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/nutanix-package-v2
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Feat MANAGER-13777
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ]~~ Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

since the component is used in several places, set conditionnal display of bandwidth based on stateprefix to avoid regression in baremetal sections

## Related

2024-05-15 15:49 UTC, darsene requested changes

2024-05-15 15:49 UTC, darsene commented on packages/manager/modules/bm-server-components/src/network-tile/template.html
> +            data-display-public-bandwidth="$ctrl.displayPublicBandwidth"
```suggestion
            data-display-public-bandwidth="!$ctrl.hidePublicBandwidth"
```

2024-05-15 15:49 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/component.js
> +    statePrefix: '<',
```suggestion
    hidePublicBandwidth: '<',
```

2024-05-15 15:49 UTC, darsene commented on packages/manager/modules/bm-server-components/src/network-tile/controller.js
> +      this.statePrefix !== 'nutanix.dashboard.nodes.node.general-info';
You should rather define a property `hidePublicBandwitdth`  instead of checking the state name
```suggestion
```

2024-05-15 15:49 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/routing.js
> +        'nutanix.dashboard.nodes.node.general-info',
no need to add `/* @ngInject */` here as you're defining a constant
```suggestion
      hidePublicBandwidth: () => true,
```

2024-05-15 15:49 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/template.html
> +                data-state-prefix="$ctrl.statePrefix"
```suggestion
                data-hide-public-bandwidth="$ctrl.hidePublicBandwidth"
```

2024-05-16 06:34 UTC, anooparveti approved these changes

2024-05-16 07:14 UTC, darsene approved these changes

2024-05-17 08:42 UTC, merged