Feat(*): update log-to-customer module and octavia-load-balancer module's instance
ovh/manager pull request #11749
Opened 2024-05-20 15:40 UTC by rjamet-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-14287`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | Fix #MANAGER-14325
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

update live tail module:
- add a prop to specify log keys to display
- add a log prefix

and use it with octavia-load-balancer

## Related

2024-05-22 12:23 UTC, anooparveti requested changes

2024-05-22 12:23 UTC, anooparveti commented on packages/manager/modules/log-to-customer/src/constants.js
**nitpick:** Be careful, this will break the logs for Kubernetes. The removed constants must be added for the Kubernetes product and passed to the generic components.

2024-05-22 12:25 UTC, darsene commented on packages/manager/modules/log-to-customer/src/constants.js
@anooparveti, as discussed with @rjamet-ovh  kubernetes refactoring will be done in a second PR to ease the review

2024-05-22 12:27 UTC, darsene commented on packages/components/ng-log-live-tail/src/controller.js
> +    const [locale] = ovhLocale?.split('_');
Can you take a look to the sonarcloud alert `Unsafe usage of optional chaining. If it short-circuits with 'undefined' the evaluation will throw TypeError.`

2024-05-23 15:33 UTC, darsene approved these changes

2024-05-24 07:33 UTC, merged