feat(pci.file-storage): listing page
ovh/manager pull request #11752
Opened 2024-05-21 07:14 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/pci_file-storage_tapc-1`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-225
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [X] Only FR translations have been updated
- [X] Branch is up-to-date with target branch
- [ ] ❌ Lint has passed locally ❌ 
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

2024-07-16 11:49 UTC, anooparveti requested changes

2024-07-16 11:49 UTC, anooparveti commented on packages/manager/apps/pci-file-storage/src/pages/listing/listing.scss
Required stylings will be applied on the Manager-components datagrid. Can you remove it?

2024-07-16 11:49 UTC, anooparveti commented on packages/manager-components/src/components/navigation/menus/action/action.component.tsx
Isolate this change from this PR. Changes on manager-components must target develop/master and must be tracked with the Github issue on the project board.

2024-07-25 16:43 UTC, y4nnL commented on packages/manager/apps/pci-file-storage/src/pages/listing/listing.scss
According to the mock ups these stylings are needed and are not yet provided by the Datagrid comp
We'll removed them as soon as we can

2024-07-25 16:54 UTC, y4nnL commented on packages/manager/apps/pci-file-storage/src/components/Breadcrumb/Breadcrumb.tsx
> +    const breadcrumbPci = usePciBreadcrumb({
This came from the generator 🤷‍♂️
```javascript
// packages/manager/core/generator/app/templates/src/components/Breadcrumb/Breadcrumb.tsx.hbs
  {{#if isPCI}}
  const { projectId } = useParams();
  const { project } = useProject({ projectId });

  if (project) {
    const breadcrumbPci = usePciBreadcrumb({
      projectId,
      appName: '{{appName}}',
    });
    return <OsdsBreadcrumb items={breadcrumbPci} />;
  }
  {{else}}
```

2024-07-26 10:02 UTC, fredericvilcot commented on packages/manager/apps/pci-file-storage/src/pages/listing/index.tsx
> +          cell: (props: any) => cellContents[element](props) ?? <div>-</div>,
It could be safer to use `unknown` here instead of `any`

2024-07-26 10:08 UTC, Tsiorifamonjena approved these changes

2024-08-27 08:27 UTC, anooparveti approved these changes

2025-05-18 00:00 UTC, closed without merging