feat(2fa): add disable 2fa form
ovh/manager pull request #11766
Opened 2024-05-22 06:57 UTC by oalkabouss

ref: MANAGER-14182

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/acquisition-storage-2fa`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14182
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-05-23 07:40 UTC, anooparveti requested changes

2024-05-23 07:43 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/pages/create/form/FormDocumentFields/FormDocumentFieldItem.tsx
> +      maxFiles={10}
**nitpick:** add it in a constant file.

2024-05-23 07:43 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/pages/create/form/FormDocumentFields/FormDocumentFieldItem.tsx
> +      maxSize={10 * 1024 * 1024}
**nitpick:** add it in a constant file.

2024-05-23 09:38 UTC, JacquesLarique requested changes

2024-05-23 09:38 UTC, JacquesLarique commented on packages/manager/apps/account-disable-2fa/src/pages/create/form/FormDocumentFields/FormDocumentFieldList.tsx
> +};
```suggestion
type LegalFrom = 'individual' | 'association' | 'corporation' | 'other' | 'administration';
type Sub = 'FR' | 'DE' | 'ES' | 'PL' | 'IE' | 'IT' | 'NL' | 'PT' | 'GB' | 'CZ' | 'FI' | 'LT' | 'LTE' | 'CA' | 'QC' | 'WS' | 'TN' | 'MA' | 'SN' | 'AU' | 'ASIA' | 'SG' | 'IN' | 'WE';

type Props = {
  legalForm: LegalFrom | 'default';
  subsidiary: Sub | 'DEFAULT';
  control: Control<FieldValues>;
};

type FieldDefinition = {
  field: string;
  multiple: boolean;
  tooltipCount: number;
};

type FieldsListDefinition = {
  fields: FieldDefinition [];
};

type DocumentsFieldRules = Record<LegalFrom | 'default', Record<Sub | 'DEFAULT', FieldsListDefinition >>;
```

@anooparveti do you agree with the usage of this kind of type definition for `LegalForm` and `Sub` ?
If we I think this proposition would be clearer

2024-05-23 09:38 UTC, JacquesLarique commented on packages/manager/apps/account-disable-2fa/src/public/translations/account-disable-2fa-documents/Messages_fr_FR.json
I feel like we should regroup the same field and rename them since we have the json file defining which tooltips are associated with which field.

For example, `field-2.1` and `field-2.2` have the same wording and can be merged without issue.

Moreorver, we would have "named field" which would be easier to understand which file is asked (because for now reading that you display `field-2.2` for "FR individual" force you to go check the translation file to know that it is the "identity card" we are asking for)

2024-05-23 13:31 UTC, oalkabouss commented on packages/manager/apps/account-disable-2fa/src/components/FileInput/FileInputContainer.tsx
> +// export type FileInputErrorEventHandler = (hasError: boolean) => void | undefined;
Nop, i forget to delete it.

2024-05-24 09:09 UTC, JacquesLarique approved these changes

2024-06-10 07:24 UTC, anooparveti requested changes

2024-06-10 07:24 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/pages/create/form/FormDocumentFields/formDocumentFieldValidationConstants.ts
**nitpick:** Can you rename the file to `formDocumentFieldValidation.constants.ts`?

2024-06-10 07:25 UTC, anooparveti requested changes

2024-06-10 07:25 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/public/translations/account-disable-2fa-documents/Messages_fr_FR.json
**nitpick:** Can you replace `-` with `_` in the translation keys?

2024-06-10 07:26 UTC, anooparveti commented on packages/manager/apps/account-disable-2fa/src/public/translations/account-disable-2fa/Messages_fr_FR.json
Same as https://github.com/ovh/manager/pull/11766#discussion_r1632707966

2024-06-12 07:31 UTC, anooparveti approved these changes

2024-06-12 08:06 UTC, merged