fix(dedicated): pnr sidebar missing translation
ovh/manager pull request #11771
Opened 2024-05-22 13:26 UTC by dectotam

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix MANAGER-14364
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-05-22 13:27 UTC, ghyenne submitted a review, later dismissed

2024-05-22 13:28 UTC, anooparveti requested changes

2024-05-22 13:28 UTC, anooparveti commented on packages/manager/apps/container/src/public/translations/sidebar/Messages_fr_FR.json
> +  "sidebar_databases": "Databases",
```suggestion
  "sidebar_databases": "Bases de données",
```

2024-05-22 13:28 UTC, oalkabouss approved these changes

2024-05-22 13:30 UTC, anooparveti approved these changes

2024-05-22 13:31 UTC, ghyenne approved these changes

2024-05-30 07:51 UTC, darsene approved these changes

2024-05-31 13:20 UTC, merged