fix(xdsl.templates): display error reason on template creation
ovh/manager pull request #11774
Opened 2024-05-22 15:18 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #UXCT-592
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~Only FR translations have been updated~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Display reason of the error on template creation

## Related

2024-05-24 08:25 UTC, antonymarion approved these changes

2024-05-24 10:17 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.controller.js
> +        }
```suggestion
        if (err.data?.message.includes(this.TEMPLATE_CONSTANT.errors.modemWifi)) {
          this.message.reason = err.data?.message;
        }
```

2024-05-24 10:17 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.html
> +            {{$ctrl.message.detail}}
```suggestion
<span data-ng-bind="$ctrl.message.detail"></span>
```

2024-05-24 10:17 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.html
> +            </div>
```suggestion
            <p data-ng-bind="$ctrl.message.detail" ></p>
            <p data-ng-if="$ctrl.message.reason" data-ng-bind="$ctrl.message.reason">
            </p>
```

2024-05-31 08:38 UTC, antonymarion submitted a review, later dismissed

2024-05-31 13:01 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.html
> +            {{$ctrl.message.detail}}
You have done for error message but the modification isn't done for success message. you have to use data-ng-bind

2024-05-31 13:04 UTC, ghyenne requested changes
You have done for error message but the modification isn't done for success message. you have to use data-ng-bind

2024-06-04 08:28 UTC, ghyenne submitted a review, later dismissed

2024-06-13 14:26 UTC, mhelhali-soufien approved these changes

2024-06-13 14:28 UTC, antonymarion approved these changes

2024-06-13 14:45 UTC, merged