fix(hosting): do not allow phpcgi for stable64"
ovh/manager pull request #11886
Opened 2024-06-04 09:23 UTC by lucas-chaigne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | WEB-18476
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description
in hosting general panel, when changing global php version, we want to have dynamic drop down list for engine name : if operating system is stable64, phpcgi can't be selected 

## Related

2024-06-19 11:27 UTC, anooparveti requested changes
Can you please include ticket reference in the commit message?

Commit must folow the below strcuture.
```
type(scope): title

  [Optional Description]
  ref: Ticket-Number

Signed-off-by: Author Full Name <author email-id>
```

2024-06-21 08:54 UTC, ghyenne commented on packages/manager/apps/web/client/app/hosting/ovhconfig/hosting-ovhconfig.controller.js
> +      }
```suggestion
      const allEngineNames = this.apiStruct.models[
        'hosting.web.ovhConfig.EngineNameEnum'
      ].enum;

      if (this.model.container !== 'stable64') {
        this.engineNames = allEngineNames;
      } else {
        this.engineNames = allEngineNames.filter((e) => e !== 'phpcgi');
      }
```

2024-06-24 08:38 UTC, ghyenne approved these changes

2024-07-11 13:00 UTC, anooparveti approved these changes

2024-07-11 13:02 UTC, acavalloni approved these changes

2024-07-11 13:41 UTC, merged