feat(rancher): update version page for rancher
ovh/manager pull request #11884
Opened 2024-06-04 09:19 UTC by lionel95200x

| Question         | Answer
| ---------------- | ---
| Branch?          |  `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-834
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

- New page to update rancher version
- Check if a new version available to display update banner in rancher detail page
- 

## Related

Rename PR cause CDS not build over 50 characters https://github.com/ovh/manager/pull/11737

2024-06-13 12:42 UTC, brofik submitted a review, later dismissed

2024-06-14 08:02 UTC, chipp972 approved these changes

2024-06-14 08:14 UTC, selm3n approved these changes

2024-06-17 08:16 UTC, selm3n approved these changes

2024-06-17 08:16 UTC, aboungnaseng-ovhcloud approved these changes

2024-06-17 09:11 UTC, selm3n submitted a review, later dismissed

2024-06-17 12:47 UTC, selm3n approved these changes

2024-06-17 12:49 UTC, chipp972 approved these changes

2024-06-17 12:56 UTC, aboungnaseng-ovhcloud approved these changes

2024-06-17 13:25 UTC, anooparveti requested changes

2024-06-17 13:25 UTC, anooparveti commented on packages/manager/apps/pci-rancher/src/routes.tsx
> +      },
**nitpick:** According to the folder structure, "Update Software" looks like a child of Dashboard. Can you make it consistent with the folder structure?

2024-06-17 14:14 UTC, anooparveti approved these changes
Refactoring for folder structure will be handled with TAPC-1128.

2024-06-17 14:15 UTC, merged