feat(telecom): add line configuration modal
ovh/manager pull request #11898
Opened 2024-06-05 07:47 UTC by antonymarion

ref: MANAGER-14099

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Feat#MANAGER-14099
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-06-06 08:50 UTC, ghyenne requested changes

2024-06-06 08:50 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/addDevice/add-device.routing.js
> +          $transition$.params().isConfiguration,
```suggestion
        deviceId: /* @ngInject */ ($transition$) =>
          $transition$.params().deviceId,
```
Maybe you can use the deviceId as params ? If you have it's a configuration if not it's new add device

2024-06-06 08:50 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                            data-on-click="$ctrl.openAddDeviceModal(true)"
```suggestion
                            data-on-click="$ctrl.openAddDeviceModal(deviceId)"
```

2024-06-06 08:50 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.routing.js
> +        openAddDeviceModal: /* @ngInject */ ($state) => (isConfiguration) =>
```suggestion
        openAddDeviceModal: /* @ngInject */ ($state) => (deviceId) =>
```

2024-06-06 08:50 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.routing.js
> +            { isConfiguration },
```suggestion
            { deviceId },
```

2024-06-06 16:40 UTC, ghyenne approved these changes

2024-06-07 08:30 UTC, sachinrameshn commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/translations/Messages_fr_FR.json
> +  "telephony_line_softphone_configurate": "Configurer mon appareil",
```suggestion
  "telephony_line_softphone_configure": "Configurer mon appareil",
```

2024-06-07 08:30 UTC, sachinrameshn commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/addDevice/add-device.html
> +    data-heading="{{ $ctrl.deviceId ? 'telephony_line_softphone_configurate':'telephony_line_softphone_add_my_device' | translate }}"
```suggestion
    data-heading="{{ $ctrl.deviceId ? 'telephony_line_softphone_configure':'telephony_line_softphone_add_my_device' | translate }}"
```

2024-06-07 08:31 UTC, antonymarion commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/translations/Messages_fr_FR.json
> +  "telephony_line_softphone_configurate": "Configurer mon appareil",
Sorry, Excuse my english

2024-06-07 08:40 UTC, sachinrameshn approved these changes

2024-06-07 08:52 UTC, merged