Feat/manager-14233 2FA implementation of upload documents api calls
ovh/manager pull request #11895
Opened 2024-06-05 06:42 UTC by oalkabouss

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-14182`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14233
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
2FA implementation of upload documents api calls
## Related

2024-06-12 08:02 UTC, MaximeBajeux commented on packages/manager/apps/procedures/src/data/hooks/useDocments.tsx
I think that miss a "u" in the filename.

2024-06-12 08:06 UTC, MaximeBajeux approved these changes

2024-06-12 13:00 UTC, JacquesLarique commented on packages/manager/apps/procedures/src/pages/create/form/Modal/ConfirmModal.tsx
> +      dismissible
Don't we risk to close the confirmation modal while the documents are being uploaded ?
_If so we should handle it properly, as right now I think the user will have access to the form to upload other documents when in reality his/her procedure is being "finalized"_

2024-06-14 07:05 UTC, JacquesLarique requested changes

2024-06-14 08:23 UTC, JacquesLarique approved these changes

2024-06-14 08:32 UTC, merged