feat(zimbra): add page to add domain
ovh/manager pull request #11906
Opened 2024-06-05 12:40 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/zimbra
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14004
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added page for add domain

## Related

2024-06-06 09:10 UTC, antonymarion commented on packages/manager/apps/zimbra/src/routes/routes.tsx
> +        element: <div>toto</div>,
Toto is normal ?

2024-06-06 09:12 UTC, antonymarion commented on packages/manager/apps/zimbra/src/hooks/useDomains.ts
> +import { useOrganization } from './useOrganization'; // Assurez-vous de remplacer le chemin correct si nécessaire
in english maybe ?

2024-06-06 10:18 UTC, ghyenne requested changes

2024-06-06 10:18 UTC, ghyenne commented on packages/manager/apps/zimbra/src/routes/routes.tsx
> +      },
```suggestion
```

2024-06-06 10:18 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/Domains.tsx
> +    navigate(urlWithParams);
Maybe we can use useHref
```suggestion
const hrefAddDomain = useHref(`./add-domain${organization?.id ? organizationId=organization.id : '' }`);
```

2024-06-06 10:18 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/Domains.tsx
> +  const shouldHideContent = useOverridePage();
```suggestion
  const isOverriddedPage = useOverridePage();
```

2024-06-06 10:18 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/Domains.tsx
> +      {!shouldHideContent && (
```suggestion
      {!isOverriddedPage && (
```

2024-06-06 10:18 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/Domains.tsx
> +              onClick={handleAddDomain}
```suggestion
              href={hrefAddDomain}
```

2024-06-06 16:03 UTC, ghyenne requested changes

2024-06-07 06:16 UTC, ghyenne requested changes

2024-06-07 06:16 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +          )}
```suggestion
          {isLoading && (
            <div slot="helper">
              <OsdsSpinner
                color={ODS_THEME_COLOR_INTENT.primary}
                size={ODS_SPINNER_SIZE.sm}
                inline
              />
            </div>
          )}
```

2024-06-07 07:26 UTC, ghyenne approved these changes

2024-06-07 07:40 UTC, antonymarion approved these changes

2024-06-07 07:47 UTC, merged