fix(hosting.multisite): separate logs display
ovh/manager pull request #11928
Opened 2024-06-06 12:58 UTC by lucas-chaigne

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | WEB-18803
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description
in hosting general page, multisite tab : if user modifies a domain with separated logs already activated, display is not correct (Object Object)

## Related

2024-06-19 11:19 UTC, anooparveti requested changes
Can you please include ticket reference in the commit message?

Commit must folow the below strcuture.
```
type(scope): title

  [Optional Description]
  ref: Ticket-Number

Signed-off-by: Author Full Name <author email-id>
```

2024-06-21 08:40 UTC, ghyenne approved these changes

2024-07-11 12:59 UTC, anooparveti approved these changes

2024-07-11 13:01 UTC, acavalloni approved these changes

2024-07-11 13:23 UTC, merged