feat(hpc-vmware-cloud-director): init hpc VCD react µapp
ovh/manager pull request #11926
Opened 2024-06-06 10:46 UTC by darsene

ref: MANAGER-14419

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/hpc-vcd-beta`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14419
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

New µapp for HPC VMware Cloud Director offer

## Related

2024-06-11 08:33 UTC, rjamet-ovh approved these changes

2024-06-12 08:10 UTC, vovh approved these changes

2024-06-12 13:41 UTC, darsene commented
> I think we should fix the tests that are not passing, if i remember well you just have to rename the files to avoid having them running with the wrong test suit

@vovh it's done. script `test:e2e:ci` has been renamed to `test:e2e:cii` temporally

2024-06-12 18:01 UTC, anooparveti commented on packages/manager/apps/hpc-vmware-managed-vcd/mocks/example/project-uuids.json
**question:** Do we need this file?

2024-06-12 18:01 UTC, anooparveti commented on packages/manager/apps/hpc-vmware-managed-vcd/mocks/example/project-uuids.ts
**question:** Do we need this file?

2024-06-12 18:01 UTC, anooparveti commented on packages/manager/apps/hpc-vmware-managed-vcd/mocks/index.ts
**question:** Do we need this file?

2024-06-12 18:02 UTC, anooparveti commented on packages/manager/apps/hpc-vmware-managed-vcd/package.json
> +  "description": "New managed VMware cloud director offers",
```suggestion
  "description": "New managed VMware Cloud Director offers",
```

2024-06-12 18:10 UTC, anooparveti requested changes

2024-06-12 18:10 UTC, anooparveti commented on packages/manager/apps/hpc-vmware-managed-vcd/src/data/hooks/pci/useProject.tsx
Looks like an error on generator. Can you remove this file?

2024-06-13 08:37 UTC, darsene commented on packages/manager/apps/hpc-vmware-managed-vcd/mocks/example/project-uuids.json
not anymore as the API will change. I removed all the corresponding files

2024-06-13 08:37 UTC, darsene commented on packages/manager/apps/hpc-vmware-managed-vcd/package.json
> +  "description": "New managed VMware cloud director offers",
Fixed

2024-06-13 08:37 UTC, darsene commented on packages/manager/apps/hpc-vmware-managed-vcd/src/data/hooks/pci/useProject.tsx
File removed

2024-06-13 11:02 UTC, anooparveti approved these changes

2024-06-13 11:45 UTC, merged