feat(manager-components): correcting css for zimbra no qa needed
ovh/manager pull request #11937
Opened 2024-06-07 08:41 UTC by stif59100

ref:MANAGER-14454

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? |no
| Tickets          | MANAGER-14454
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I put a small correcting for dashboard component using content
## Related

2024-06-07 08:43 UTC, antonymarion commented on packages/manager/apps/zimbra/public/translations/dashboard/Messages_fr_FR.json
> +  "zimbra_dashboard_error_service": "No services info",
is it ok for french?

2024-06-07 08:44 UTC, antonymarion commented on packages/manager/apps/zimbra/src/api/GET/apiv2/services.ts
> +    const response = await apiClient.v2.get<Organization[]>(
const { data } =

2024-06-07 08:44 UTC, antonymarion approved these changes

2024-06-07 08:45 UTC, ghyenne approved these changes

2024-06-07 12:12 UTC, chipp972 approved these changes

2024-06-11 06:16 UTC, anooparveti requested changes
Can you synchronise with @aboungnaseng-ovhcloud to see if it is inline with the latest guidelines provided by the design team.

2024-06-18 09:27 UTC, closed without merging