feat(telecom): add softphone configuration
ovh/manager pull request #11958
Opened 2024-06-11 05:18 UTC by antonymarion

ref: MANAGER-13662

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Feat#MANAGER-13662
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
~~- [ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-06-11 13:46 UTC, ghyenne requested changes

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.controller.js
> +      name: 'telephony_line_softphone_configuration_name',
```suggestion
      title: 'telephony_line_softphone_configuration_name',
      url: GUIDE_URL,
      external: true,
```
The translate of button "guide" can be put directly in html. External require a boolean

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                    ><span data-ng-bind="::$ctrl.guide.name | translate"></span>
```suggestion
                    ><span data-translate="{{ $ctrl.guide.name }}"></span>
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                    term="{{:: 'telephony_line_softphone_status' | translate}}"
```suggestion
                   data-term="{{:: 'telephony_line_softphone_status' | translate}}"
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.routing.js
> +          ),
You have to do a iceberg call not one for id and second for expend.

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +            <oui-guide-menu data-text="{{ ::$ctrl.guide.title | translate }}">
```suggestion
            <oui-guide-menu data-text="{{ 'telephony_line_softphone_guide_title' | translate }}">
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                                data-translate="::$ctrl.getDeviceStatusById(deviceId)"
```suggestion
                                data-translate="{{ 'my_key_for_status_' + $ctrl.deviceId.status }}"
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                                     }"
```suggestion
                                data-ng-class="{
                                     'oui-badge_error': $ctrl.deviceId.status === $ctrl.MY_CONST_FOR_STATUS.unregistered,
                                     'oui-badge_success': $ctrl.deviceId.status === $ctrl.MY_CONST_FOR_STATUS.registered,
                                     }"
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                                class="rounded p-1 text-white"
```suggestion
                                class="oui-badge"
```

2024-06-11 13:46 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +                        </div>
Maybe you can use oui-field ui-kit component

2024-06-12 09:03 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.service.js
> +
```suggestion
```

2024-06-12 09:11 UTC, antonymarion commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.controller.js
> +  }
I believe I must keep this one

2024-06-12 09:11 UTC, antonymarion commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.controller.js
> +  }
I believe I must keep this one

2024-06-12 09:21 UTC, antonymarion commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.controller.js
> +    ];
![image](https://github.com/ovh/manager/assets/8767496/ccd9d410-f35f-481d-bf06-881f22103c3c)
![image](https://github.com/ovh/manager/assets/8767496/ccd9d410-f35f-481d-bf06-881f22103c3c)

I am keeping model.name for readability (ease comprehension of property modified on the model)

2024-06-14 06:10 UTC, ghyenne approved these changes

2024-06-14 06:50 UTC, merged