feat(telecom): add ont shipping address on move and migrate steps
ovh/manager pull request #11974
Opened 2024-06-12 08:52 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-585
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Add ONT shipping address selection on move and migrate offers.

## Related

2024-06-12 17:52 UTC, anooparveti commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +    this.loading.init = true;
**nitpick:** 2 statements can be combined
```suggestion
    this.loading = {
      init: true,
    };
```

2024-06-12 17:55 UTC, anooparveti commented on packages/manager/apps/telecom/src/app/telecom/pack/move/ont-shipping/move-ont-shipping.controller.js
> +    this.loading.init = true;
```suggestion
    this.loading = {
      init: true,
    };
    this.ontShipping = {
      address: null,
    };
```

2024-06-13 09:35 UTC, ghyenne requested changes

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +      })
For avoid to use deprecated library, you can create a function in service file that call directly the api call
```js
this.$http.get(`/pack/xdsl/${packName}/shippingAddresses`).then(({data}) => data);
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +        );
You can use the native javascript function for avoid to use lodash library
```suggestion
        this.ovhContactOptions.customList = ontShippingAddresses.map((ontShippingAddress) =>
            new this.OvhContact({
              address: {
                line1: ontShippingAddress.address,
                city: ontShippingAddress.cityName,
                country: ontShippingAddress.countryCode,
                zip: ontShippingAddress.zipCode,
              },
              firstName: ontShippingAddress.firstName,
              lastName: ontShippingAddress.lastName,
              id: ontShippingAddress.shippingId,
            }),
        );
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +        );
```suggestion
        this.process.ontShipping.address = this.ovhContactOptions.customList.at(0);
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +        )} ${get(error, 'data.message', '')}`;
Same no need get lodash
```suggestion
        )} ${error?.data?.message}`;
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +    }
You have to move the constant in constant files.
And if this.process.selectedOffer.needNewModem for example you change twice time yours this.process.currentStep and second this.process.currentStep = 'shipping', maye there is an other best way

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.html
> +                </div>
```suggestion
                <div data-ng-if="!$ctrl.loading.init">
                    <!-- CONTACT CHOICE -->
                    <div class="contact-choice">
                        <h3
                            data-translate="telecom_pack_migration_ont_shipping_contact"
                            class="mb-3 mt-5"
                        ></h3>

                        <ovh-contact
                            data-ng-model="$ctrl.process.ontShipping.address"
                            data-ovh-contact-choice-options="$ctrl.ovhContactOptions"
                        >
                            <div class="text-center">
                                <oui-spinner></oui-spinner>
                            </div>
                        </ovh-contact>
                    </div>
                    <!-- CONTACT CHOICE -->

                <div class="mt-5">
                    <a
                        class="btn btn-default"
                        data-translate="telecom_pack_migration_confirm_cancel_button"
                        data-ui-sref="telecom.packs.pack"
                    >
                    </a>
                    <button
                        type="button"
                        class="btn btn-primary"
                        data-ng-disabled="!$ctrl.process.ontShipping.address"
                        data-translate="telecom_pack_migration_ont_shipping_confirm"
                        data-ng-click="$ctrl.nextStep()"
                    ></button>
                </div>
             </div>
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/pack-migration.html
> +        data-ng-if="!$ctrl.loading.init && $ctrl.process.currentStep === 'ontShipping'"
```suggestion
        data-ng-if="$ctrl.process.currentStep === $ctrl.MY_SUPER_VARIABLE.ontShipping"
```

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/pack-migration.html
> +        data-ng-if="!$ctrl.loading.init && $ctrl.process.currentStep === 'ontShipping'"
```suggestion
    <!-- ONT SHIPPING STEP -->
    <div data-ng-if="!$ctrl.loading.init">
    <div
        data-ng-if="$ctrl.process.currentStep === 'ontShipping'"
```
You can use only one div for each step for avoid to duplicate the code data-ng-if="!$ctrl.loading.init" for each step

2024-06-13 09:35 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/service-delete/pack-migration-service-delete.html
> +            data-ng-click="$ctrl.process.currentStep = $ctrl.process.selectedOffer.customOntAddress ? 'ontShipping' : $ctrl.process.selectedOffer.needNewModem ? 'shipping' : $ctrl.process.selectedOff
And in addition, move also the constant in constant file

2024-06-13 09:49 UTC, Steffy29 commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/index.js
> +  .component('packMigrationOntShipping', component);
No, other component names are 'pack-migration-...', if I put 'telecom-pack-migration-ont-shipping', I need to change all component names.

2024-06-14 08:47 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +            }),
```suggestion
          ({address, cityName, countryCode, zipCode, firstName, lastName, shippingId}) =>
            new this.OvhContact({
              address: {
                line1: address,
                city: cityName,
                country: countryCode,
                zip: zipCode,
              },
              firstName: firstName,
              lastName: lastName,
              id: shippingId,
            }),
```

2024-06-14 08:50 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/translations/Messages_fr_FR.json
> +  "telecom_pack_migration_ont_shipping_addresses_error": "Une erreur est survenue lors du chargement de vos contacts."
```suggestion
  "telecom_pack_migration_ont_shipping_addresses_error": "Une erreur est survenue lors du chargement de vos contacts. {{ error }}"
```

2024-06-14 09:06 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +        return this.$q.reject(error);
```suggestion
```
I don't think is needed you can also remove the import of $q

2024-06-18 08:28 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +    $q,
```suggestion
```

2024-06-18 08:28 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +    this.$q = $q;
```suggestion
```
not used

2024-06-18 08:28 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.controller.js
> +        this.TucToast.error(mgError);
```suggestion
        this.TucToast.error(this.$translate.instant(
          'telecom_pack_migration_ont_shipping_addresses_error',
          { error: error.data?.message },
        ));
```

2024-06-19 09:02 UTC, ghyenne submitted a review, later dismissed

2024-06-19 09:06 UTC, anooparveti requested changes

2024-06-19 09:06 UTC, anooparveti commented on packages/manager/apps/telecom/src/app/telecom/pack/migration/ont-shipping/pack-migration-ont-shipping.service.js
> +  /* @nbgInject */
```suggestion
  /* @ngInject */
```

2024-06-20 08:29 UTC, ghyenne approved these changes

2024-06-20 08:32 UTC, anooparveti approved these changes

2024-06-27 11:22 UTC, qpavy approved these changes

2024-06-27 11:30 UTC, acavalloni approved these changes

2024-06-27 12:49 UTC, merged