feat(zimbra): add configuration domaine page
ovh/manager pull request #11982
Opened 2024-06-12 14:52 UTC by stif59100

ref:MANAGER-13883

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/zimbra
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-13883
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added domains page add 

## Related

2024-06-13 08:34 UTC, ghyenne commented on packages/manager/apps/zimbra/public/translations/domains/addDomain/Messages_fr_FR.json
> +  "zimbra_domains_add_domain_select": "Selectionner un nom de domaine",
```suggestion
  "zimbra_domains_add_domain_select": "Sélectionner un nom de domaine",
```

2024-06-13 08:34 UTC, ghyenne commented on packages/manager/apps/zimbra/public/translations/domains/addDomain/Messages_fr_FR.json
> +  "zimbra_domains_add_domain_input_title": "Saisir un nom de domaine non géré par notre compte OVH",
```suggestion
  "zimbra_domains_add_domain_input_title": "Saisir un nom de domaine non géré par notre compte OVHcloud",
```

2024-06-13 08:34 UTC, ghyenne commented on packages/manager/apps/zimbra/public/translations/domains/addDomain/Messages_fr_FR.json
> +  "zimbra_domains_add_domain_organization_select": "Selectionner une organisation",
```suggestion
  "zimbra_domains_add_domain_organization_select": "Sélectionner une organisation",
```

2024-06-13 08:34 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +            <OsdsRadio value="ovhDomain" className="">
```suggestion
            <OsdsRadio value="ovhDomain">
```

2024-06-13 09:07 UTC, antonymarion commented on packages/manager/apps/zimbra/src/utils/convertOctets.ts
> +    return `${(value / TB).toFixed(1)} ${t('zimbra_emails_datagrid_quota_to')}`;
Maybe create a function here to refactor in case logic change

2024-06-13 09:09 UTC, antonymarion commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +            {data?.map((item: any) => (
avoid any if possible

2024-06-13 09:09 UTC, antonymarion commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +              {domains.map((domain: any) => (
avoid any if possible

2024-06-13 09:10 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +              {domains.map((domain: any) => (
```suggestion
              {domains.map((domain: string) => (
```

2024-06-13 09:35 UTC, antonymarion approved these changes

2024-06-13 09:50 UTC, ghyenne commented on packages/manager/apps/zimbra/src/api/GET/apiv6/services.ts
> +};
```suggestion
```

2024-06-14 06:22 UTC, ghyenne requested changes

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +    setSelectedDomainName(`${event.detail.value}`);
```suggestion
    setSelectedDomainName(event.detail.value);
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +      organizationId: organization?.id,
```suggestion
      organizationId: selectedOrganization,
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +      </div>
```suggestion
        <Subtitle>{t('zimbra_domains_add_domain_title')}</Subtitle>
```
i'm not sure that is needed

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +          <OsdsFormField className=" w-full">
```suggestion
          <OsdsFormField className="w-full">
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +          <OsdsFormField className=" w-full">
```suggestion
          <OsdsFormField className="w-full">
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +              className=""
```suggestion
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +                className=" md:w-1/2"
```suggestion
                className="md:w-1/2"
```

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +                className=" md:w-1/2"
if it's smaller that md what is the behaviour ?

2024-06-14 06:22 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Domains/AddDomain.tsx
> +                className=""
```suggestion
```

2024-06-14 12:46 UTC, ghyenne approved these changes

2024-06-14 14:41 UTC, merged