feat(telecom): delete all softphone devices
ovh/manager pull request #12037
Opened 2024-06-14 17:27 UTC by antonymarion

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Feat#MANAGER-14466
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
~~- [ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-06-19 08:51 UTC, ghyenne approved these changes

2024-06-19 08:51 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/deleteDevice/delete-device.html
> +    data-heading="{{ ($ctrl.deleteAllDevices ? 'telephony_line_softphone_delete_all_devices_modal_title' : 'telephony_line_softphone_delete_device_modal_title') | translate }}"
```suggestion
    data-heading="{{ $ctrl.deleteAllDevices ? 'telephony_line_softphone_delete_all_devices_modal_title' : 'telephony_line_softphone_delete_device_modal_title' | translate }}"
```

2024-06-19 08:51 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/softphone.html
> +        data-ng-if="$ctrl.softphoneDevices.length===3"
```suggestion
        data-ng-if="$ctrl.softphoneDevices.length === 3"
```

2024-06-19 09:42 UTC, anooparveti requested changes
Instead of reusing the existing `delete`, create a new folder `delete-all` with its own module, routing. Maybe you can move the component definition to a common place and reuse it in both actions.
Each new route will require a new folder.

2024-06-21 12:56 UTC, anooparveti approved these changes

2024-06-21 12:56 UTC, anooparveti commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/softphone/index.js
> +  .component('deleteModal', deleteModalComponent)
```suggestion
  .component('telecomTelephonyLineSoftphoneDeleteModal', deleteModalComponent)
```

2024-06-21 13:08 UTC, anooparveti approved these changes

2024-06-21 13:08 UTC, merged