feat(conatiner): load listing page onclick of parent item
ovh/manager pull request #12067
Opened 2024-06-18 11:13 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14361
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2024-06-18 12:04 UTC, MaximeBajeux approved these changes

2024-06-18 13:17 UTC, dectotam approved these changes

2024-06-19 09:23 UTC, anooparveti requested changes
I think we may have to adapt the behaviour in other universe as well. Lets check with POs.

2024-06-20 06:45 UTC, anooparveti commented
> I think we may have to adapt the behaviour in other universe as well. Lets check with POs.

PO gave a GO to apply the change only for this section.

2024-06-20 06:45 UTC, anooparveti approved these changes

2024-06-27 12:42 UTC, merged