feat(dedicated): text corrections
ovh/manager pull request #12060
Opened 2024-06-18 06:50 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14431
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2024-06-19 06:33 UTC, qpavy submitted a review, later dismissed

2024-06-19 06:42 UTC, antonymarion submitted a review, later dismissed

2024-06-19 09:12 UTC, anooparveti requested changes
Be more specific with the commit messages regarding what has been changed.

2024-06-19 11:31 UTC, sachinrameshn commented
> Be more specific with the commit messages regarding what has been changed.

commit message as been modified.

2024-06-27 08:50 UTC, darsene approved these changes

2024-06-27 09:33 UTC, qpavy approved these changes

2024-06-27 12:44 UTC, merged