feat: update pci menu to support bff for db react app
ovh/manager pull request #12073
Opened 2024-06-18 16:10 UTC by abullet33

datatr-1090

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-06-19 15:05 UTC, jperchoc requested changes

2024-06-19 15:05 UTC, jperchoc commented on packages/manager/apps/container/src/container/legacy/server-sidebar/universe/public-cloud/pci-menu.ts
> +            `#/pci/projects/${projectId}/databases-analytics/data-analysis/services`,
```suggestion
            `#/pci/projects/${projectId}/databases-analytics/analysis/services`,
```

2024-06-19 15:05 UTC, jperchoc commented on packages/manager/apps/container/src/container/legacy/server-sidebar/universe/public-cloud/pci-menu.ts
> +            `#/pci/projects/${projectId}/databases-analytics/data-streaming/services`,
```suggestion
            `#/pci/projects/${projectId}/databases-analytics/streaming/services`,
```

2024-06-19 15:05 UTC, jperchoc commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts
> +            hash: '#/pci/projects/{projectId}/databases-analytics/data-streaming/services',
```suggestion
            hash: '#/pci/projects/{projectId}/databases-analytics/streaming/services',
```

2024-06-19 15:05 UTC, jperchoc commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts
> +            hash: '#/pci/projects/{projectId}/databases-analytics/data-analysis/services',
```suggestion
            hash: '#/pci/projects/{projectId}/databases-analytics/analysis/services',
```

2024-06-19 15:13 UTC, jperchoc approved these changes

2024-06-19 15:13 UTC, abullet33 commented on packages/manager/apps/container/src/container/legacy/server-sidebar/universe/public-cloud/pci-menu.ts
> +            `#/pci/projects/${projectId}/databases-analytics/data-analysis/services`,
Yes thanks for our attention

2024-06-20 08:10 UTC, darsene requested changes
@abullet33  : 
Can you update your pull request with those following elements please ?
- description part is not filled
- commit message is not compliant (feat(app): ...)
- ticket reference in the commit message is not well set (ref: XXX)

2024-06-20 08:10 UTC, darsene commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts
The PNR menu is gonna be updated soon so you should have to to update that part

2024-06-20 09:19 UTC, abullet33 commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/publicCloud.ts
Will rebase post change of the file.

2024-06-20 12:13 UTC, jperchoc approved these changes

2024-06-20 12:34 UTC, darsene approved these changes

2024-06-28 13:43 UTC, jperchoc approved these changes

2024-06-28 13:48 UTC, jperchoc approved these changes

2024-06-28 13:48 UTC, merged