feat(log-live-tail): update theme
ovh/manager pull request #12089
Opened 2024-06-20 15:04 UTC by rjamet-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-14318
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Update log-live-tail theme

2024-06-21 08:03 UTC, darsene commented on packages/components/ng-log-live-tail/src/template.html
> +                <span class="separator">|</span>
**niptick**: could be done in css with `.separator::after {content : '|'}` to avoid repeating it in the html view

2024-06-21 10:23 UTC, darsene approved these changes

2024-06-24 07:56 UTC, ghyenne commented on packages/components/ng-log-live-tail/package.json
> +    "@ovhcloud/ods-theme-blue-jeans": "17.2.1",
```suggestion
    "@ovhcloud/ods-theme-blue-jeans": "17.2.2",
```

2024-07-10 08:55 UTC, vovh submitted a review, later dismissed

2024-07-11 08:44 UTC, darsene submitted a review, later dismissed

2024-07-11 11:23 UTC, anooparveti requested changes

2024-07-11 11:23 UTC, anooparveti commented on packages/components/ng-log-live-tail/package.json
> +    "@ovhcloud/ods-theme-blue-jeans": "17.2.2",
**question:** Why to include ods in angularjs component?

2024-07-11 11:33 UTC, anooparveti approved these changes

2024-07-11 11:36 UTC, ghyenne approved these changes

2024-07-11 12:59 UTC, anooparveti approved these changes

2024-07-11 13:01 UTC, acavalloni approved these changes

2024-07-11 13:34 UTC, merged