refactor(key-management-service): apply new folder structure
ovh/manager pull request #12117
Opened 2024-06-24 13:55 UTC by vovh

ref: MANAGER-14283

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-06-28 12:31 UTC, rjamet-ovh submitted a review, later dismissed

2024-06-28 13:28 UTC, darsene approved these changes

2024-06-28 13:52 UTC, anooparveti requested changes
The folder structure in the pages folder is not according to the defined standards. `tabs` folder needs to be removed and `general-information` tab can be a direct child of `dashboard` folder.

2024-06-28 14:36 UTC, rjamet-ovh approved these changes

2024-06-28 14:37 UTC, anooparveti requested changes
Terminate should also be a route and thus need a folder for itself.

2024-06-28 14:37 UTC, darsene submitted a review, later dismissed

2024-07-01 08:03 UTC, rjamet-ovh approved these changes

2024-07-02 08:30 UTC, anooparveti approved these changes

2024-07-02 13:16 UTC, merged