Fix: Fix typo Refs: 12126
ovh/manager pull request #12129
Opened 2024-06-25 12:12 UTC by Victor-D

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | yes (typo in translation)
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #12126
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Fix typo in french translation files

## Related

N/A

2024-07-16 17:46 UTC, anooparveti approved these changes

2024-07-16 17:48 UTC, anooparveti requested changes
@Victor-D, as mentioned in our contributing guidelines https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations, only `Messages_fr_FR.json` can be updated. 
So can you please discard the changes on packages/manager/apps/web/client/app/domain-operation/translations/Messages_fr_CA.json?

2024-07-17 07:55 UTC, ghyenne commented
@Victor-D, thanks for your contribution. I created a dedicated branch for your fix.
Your commit isn't signed. You can follow this guide (https://github.com/ovh/manager/pull/12129/checks?check_run_id=26651535626) for signed your commit.

2024-07-17 08:42 UTC, Victor-D commented
Hello guys,
I've just updated and signed my commit (sorry new workstation).
Have a great day

2024-07-17 09:38 UTC, ghyenne approved these changes

2024-07-17 09:45 UTC, antonymarion approved these changes

2024-07-17 09:52 UTC, merged