feat(container): improve accessibility pnr
ovh/manager pull request #12164
Opened 2024-06-27 15:03 UTC by MaximeBajeux

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14121
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [] Breaking change is mentioned in relevant commits

## Description

improve accessibility on pnr v2 for keyboard navigation and screen reader

## Related

2024-07-01 07:23 UTC, JacquesLarique submitted a review, later dismissed

2024-07-02 07:01 UTC, oalkabouss approved these changes

2024-07-16 17:37 UTC, anooparveti approved these changes

2024-07-16 17:37 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/ProjectSelector/ProjectSelector.tsx
> +      color: isFocused ? '#1A53CF' : '#4E568E',
Can you use the colors provided from the IDS utilities?

2024-07-16 17:38 UTC, anooparveti requested changes
Can you use the colors provided from the ODS utilities?

2024-07-17 15:25 UTC, JacquesLarique approved these changes

2024-07-18 07:51 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/index.tsx
> +    if (firstElem) firstElem.focus();
```suggestion
    const firstElement = window.document.getElementById(getFirstChild(node)?.idAttr);
    if (firstElement) firsfirstElementtElem.focus();
```

2024-07-18 10:32 UTC, anooparveti submitted a review, later dismissed

2024-08-08 13:00 UTC, anooparveti approved these changes

2024-08-08 15:50 UTC, oalkabouss approved these changes

2024-08-09 11:53 UTC, merged