feat(pci-block-storage): use the menu action from the manager component
ovh/manager pull request #12162
Opened 2024-06-27 12:22 UTC by seven-amid

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/pci-block-storage
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | no-ticket
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-06-28 07:50 UTC, anooparveti requested changes
> @github-actions Lint Code Base / Lint Code Base (push) Failing after 1m

Can you fix the failing lint github action?

2024-07-01 09:38 UTC, kqesar approved these changes

2024-07-01 09:39 UTC, kqesar requested changes
Fix build

2024-07-02 08:37 UTC, frenautvh approved these changes

2024-07-02 09:49 UTC, kqesar approved these changes

2024-07-03 14:59 UTC, merged