feat(web.hosting): add status git and action git on multisite
ovh/manager pull request #12216
Opened 2024-07-03 13:16 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/git` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14066 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added status git and action git on multisite datagrid

## Related

2024-07-03 15:05 UTC, darsene requested changes

2024-07-03 15:31 UTC, ghyenne commented on packages/manager/apps/web/client/app/hosting/multisite/hosting-multisite.controller.js
> +          $scope.allowedWebsites === -1 ? 'unlimitedPath' : 'limitedPath';
We have 3 use cases provided by api.
-1 = "true" unlimited
0 = "false" so no allowed
1 = "true" but limited number
But 0 haven't tooltip so no need manage this case.

2024-07-03 15:33 UTC, ghyenne commented on packages/manager/apps/web/client/app/hosting/dashboard/translations/Messages_fr_FR.json
> +  "hosting_tab_DOMAINS_table_git_state_tooltip_lastDeploy": "Consulter les informations du derniers déploiement",
It's fixed.

2024-07-03 15:53 UTC, darsene approved these changes

2024-07-04 15:23 UTC, antonymarion approved these changes

2024-07-05 08:28 UTC, merged