test(pci-ssh-keys): increase code coverage for ssh-keys
ovh/manager pull request #12233
Opened 2024-07-04 13:50 UTC by kqesar

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | DTCORE-2365
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

test(pci-ssh-keys): increase code coverage for ssh-keys

2024-07-04 13:53 UTC, sidlynx approved these changes

2024-07-08 09:38 UTC, qpavy approved these changes

2024-08-12 08:54 UTC, anooparveti requested changes
Can you resolve the conflicts?

2024-08-22 08:20 UTC, chipp972 submitted a review, later dismissed

2024-09-30 12:54 UTC, frenautvh approved these changes

2024-09-30 13:21 UTC, sidlynx approved these changes

2024-10-01 08:10 UTC, seven-amid approved these changes

2024-10-03 14:37 UTC, merged