feat(vrack-services): redirect to hub if app is feature-flipped
ovh/manager pull request #12255
Opened 2024-07-05 15:29 UTC by chipp972

ref: MANAGER-14601

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14601 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-07-09 08:25 UTC, qpavy approved these changes

2024-07-10 03:51 UTC, sachinrameshn approved these changes

2024-07-16 10:06 UTC, anooparveti requested changes
> Lint Code Base / Lint Code Base (push) Failing after 4m

Can you fix the failing error?

2024-07-16 17:30 UTC, anooparveti approved these changes

2024-07-22 09:52 UTC, merged