feat(manager-components): move useFeatureAvailability
ovh/manager pull request #12274
Opened 2024-07-09 09:47 UTC by chipp972

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14719 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-07-09 12:52 UTC, anooparveti requested changes

2024-07-09 12:52 UTC, anooparveti commented on packages/manager-components/src/hooks/2api/hooks/useFeatureAvailability.ts
Isn't it overhead to add a folder named `hooks` inside the folder `hooks`?
Maybe we can follow `hooks -> feature-availability`

2024-07-09 13:29 UTC, chipp972 commented on packages/manager-components/src/hooks/2api/hooks/useFeatureAvailability.ts
Yes good idea

2024-07-09 13:29 UTC, chipp972 commented on packages/manager/core/application/src/hooks/useFeatureAvailability.ts
Yes I though I did it in the second commit
Fixed

2024-07-11 05:36 UTC, anooparveti approved these changes

2024-07-11 08:08 UTC, frenautvh approved these changes

2024-07-11 08:35 UTC, merged