feat(dedicated-cloud): updating IAM on HPC to GA
ovh/manager pull request #12329
Opened 2024-07-11 15:58 UTC by carsso

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated : All languages updated to remove old translation
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Setting IAM on Hosted Private Cloud as GA, removing beta flag and clarifying description and activation messages to remind IAM scope as of today.

![Capture d’écran 2024-07-11 à 17 54 57](https://github.com/ovh/manager/assets/666182/51e6539c-71b4-4815-ae4c-02b6de6ed8f6)
![Capture d’écran 2024-07-11 à 17 54 52](https://github.com/ovh/manager/assets/666182/4e1d0d13-5fb1-4327-b678-027ed2807e5a)

## Related

2024-07-16 14:46 UTC, anooparveti requested changes
For `BETA` translation removal, you can just remove it from packages/manager/apps/dedicated/client/app/components/dedicated-cloud/users/translations/Messages_fr_FR.json and an automated trans cleaner job will take care of removing ti from other files.

2024-07-16 21:25 UTC, carsso commented
> For `BETA` translation removal, you can just remove it from packages/manager/apps/dedicated/client/app/components/dedicated-cloud/users/translations/Messages_fr_FR.json and an automated trans cleaner job will take care of removing ti from other files.

Sure, didn't know that, thanks.

2024-07-17 08:58 UTC, anooparveti approved these changes

2024-08-12 08:13 UTC, rjamet-ovh submitted a review, later dismissed

2024-08-30 08:37 UTC, darsene approved these changes

2024-08-30 08:44 UTC, jmalnuit approved these changes

2024-08-30 08:52 UTC, merged