feat(manager-components): fix onboarding design requirements
ovh/manager pull request #12330
Opened 2024-07-11 16:04 UTC by darsene

resolves: MANAGER-14378

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-14378
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-07-12 07:52 UTC, vovh approved these changes

2024-07-12 07:52 UTC, sachinrameshn approved these changes

2024-07-12 08:57 UTC, vovh requested changes
There sonar issues to fix

2024-07-12 08:58 UTC, vovh approved these changes

2024-07-12 12:03 UTC, anooparveti approved these changes

2024-07-12 15:59 UTC, chipp972 approved these changes

2024-07-16 08:40 UTC, anooparveti approved these changes

2024-07-22 07:50 UTC, vovh submitted a review, later dismissed

2024-07-22 09:13 UTC, aboungnaseng-ovhcloud commented on packages/manager-components/src/components/templates/onboarding/onboarding.component.tsx
> +              className="block text-center xs:pt-2.5 sm:pt-8 max-w-4xl"
L82 we have a component OSDS-DIVIDER we can delete it 👍

2024-07-22 13:55 UTC, anooparveti submitted a review, later dismissed

2024-07-23 08:24 UTC, darsene commented
@aboungnaseng-ovhcloud you can proceed to the update of all the onboarding pages based on that PR

2024-07-24 07:37 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2024-07-24 07:59 UTC, vovh submitted a review, later dismissed

2024-07-29 08:16 UTC, darsene commented on packages/manager-components/src/components/navigation/card/card.spec.tsx
> +      expect(descElement).toHaveAttribute('size', ODS_TEXT_SIZE._400);
@lionel95200x I've fixed a design team feedback as the typo should be like this. So it's to avoid any unintentional changes

2024-07-30 14:08 UTC, vovh approved these changes

2024-07-30 14:10 UTC, anooparveti approved these changes

2024-07-30 14:14 UTC, merged