feat(iplb): move metrics to mimir
ovh/manager pull request #12483
Opened 2024-07-23 08:19 UTC by lizardK

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes/no
| Tickets          | Fix #
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Move IPLB metrics to mimir

2024-07-24 05:47 UTC, anooparveti requested changes

2024-07-24 05:47 UTC, anooparveti commented on packages/components/ng-ovh-chart/src/directive.js
> +        }
**nitpick:** This seems to be duoplicated https://github.com/ovh/manager/blob/d9641a04a91a2e09707e49a5080d821d96142376/packages/components/ng-ovh-chart/src/directive.js#L60-L64.
Can you remove `$scope..$on('destroy')....`?

2024-09-11 13:17 UTC, qpavy approved these changes

2024-09-11 13:24 UTC, anooparveti approved these changes

2024-09-12 12:26 UTC, anooparveti approved these changes

2024-09-12 12:27 UTC, merged