Refactor(pci-rancher): Update folder structure
ovh/manager pull request #12529
Opened 2024-07-24 15:55 UTC by Tsiorifamonjena

ref: TAPC-987

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | TAPC-987
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Refactor rancher app folder structure

https://manager.pages.ovhcloud.tools/guides/manager/development-guidelines/application-folder-structure/#routes

2024-08-01 08:55 UTC, y4nnL commented
Is it possible to create aliases to replace relative paths ?
```javascript
../../../../../dir
```
```javascript
@/dir
```

2024-08-01 08:56 UTC, y4nnL requested changes
Is it possible to create aliases to replace relative paths ?
```javascript
../../../../../dir
```
```javascript
@/dir
```

2024-08-05 07:57 UTC, chipp972 submitted a review, later dismissed

2024-08-05 08:18 UTC, anooparveti requested changes

2024-08-05 08:18 UTC, anooparveti commented on packages/manager/apps/pci-rancher/src/hooks/useGuideLink/useGuideLink.tsx
> +import { OvhSubsidiary } from '@ovhcloud/manager-components/src/enumTypes';
```suggestion
import { OvhSubsidiary } from '@ovhcloud/manager-components';
```

2024-08-06 08:58 UTC, anooparveti approved these changes

2024-08-23 06:41 UTC, merged