feat(pnr): add tracking to pnrv2
ovh/manager pull request #12555
Opened 2024-07-26 13:53 UTC by oalkabouss

ref: MANAGER-13159

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-14102`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-13159
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-07-26 14:17 UTC, MaximeBajeux commented on packages/manager/apps/container/src/container/common/nav-reshuffle-switch-back/Modal.tsx
Just for information we will remove this modal in feat/MANAGER-14688

2024-07-26 14:17 UTC, MaximeBajeux commented on packages/manager/apps/container/src/container/nav-reshuffle/header/user-account-menu/Content.tsx
> +  const onTackNavigation = (name: string) => {
Do you mean OnTrackNavigation ?

2024-07-26 15:19 UTC, MaximeBajeux approved these changes

2024-07-29 15:14 UTC, anooparveti requested changes

2024-07-29 15:14 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/header/user-account-menu/Content.tsx
> +  const onLougoutBtnClick = () => {
```suggestion
  const onLogoutBtnClick = () => {
```

2024-07-29 15:18 UTC, anooparveti requested changes

2024-07-30 10:10 UTC, anooparveti approved these changes

2024-07-30 14:19 UTC, merged