fix(pci-private-network): fixed re-render issue on language change
ovh/manager pull request #12641
Opened 2024-08-05 16:26 UTC by oalkabouss

ref: PRB0041352

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #PRB0041352
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-08-05 17:21 UTC, anooparveti requested changes

2024-08-05 17:21 UTC, anooparveti commented on packages/manager/apps/pci-private-network/src/pages/new/steps/LocalizationStep.tsx
General behavior is Manager refreshes when the user changes the language. What is the issue here?

2024-08-06 05:54 UTC, frenautvh approved these changes

2024-08-06 05:55 UTC, frenautvh commented on packages/manager/apps/pci-private-network/src/pages/new/steps/LocalizationStep.tsx
For react apps changing the language updates the UI without hard refreshing the whole manager ; the manager refreshes only for angularjs apps

2024-08-06 06:17 UTC, qpavy commented on packages/manager/apps/pci-private-network/src/pages/new/steps/LocalizationStep.tsx
In my opinion, even if we re-render the UI when changing the language, it won't change anything on the region list, because changing language is different than changing subsidiary

2024-08-06 06:32 UTC, frenautvh commented on packages/manager/apps/pci-private-network/src/pages/new/steps/LocalizationStep.tsx
@qpavy the mapped region list is using translations (for macro region name) in an useEffect that's why i18n.language has been added to the useEffect dependencies list

2024-08-06 07:31 UTC, qpavy commented on packages/manager/apps/pci-private-network/src/pages/new/steps/LocalizationStep.tsx
ok sorry for the misunderstanding

2024-08-06 07:35 UTC, qpavy approved these changes

2024-10-10 14:34 UTC, merged