feat(container): added switch Standard/beta version on mobile
ovh/manager pull request #12667
Opened 2024-08-07 13:16 UTC by oalkabouss

ref: MANAGER-14945

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-14102`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14945
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-08-07 13:36 UTC, anooparveti requested changes

2024-08-07 13:36 UTC, anooparveti commented on packages/manager/apps/container/src/container/legacy/navbar/navbar.module.scss
> +.smallDevicePnrSwitch {
```suggestion
.small-device-pnr-switch {
```

2024-08-07 13:36 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/header/index.tsx
> +  onUserAccountMenuToggle = () => { },
Unnecessary changes.

2024-08-07 13:36 UTC, anooparveti commented on packages/manager/apps/container/src/container/nav-reshuffle/header/style.module.scss
> +.smallDevicePnrSwitch {
```suggestion
.small-device-pnr-switch {
```

2024-08-08 05:45 UTC, anooparveti approved these changes

2024-08-08 07:57 UTC, MaximeBajeux approved these changes

2024-08-08 08:20 UTC, merged