feat(dedicated-cloud): add region in general view & fix version display
ovh/manager pull request #12749
Opened 2024-08-13 18:37 UTC by carsso

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15038
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Adding region data in HPC general information section.
Also fixes version display (previously not showing minor part of version number).

Before :
![Capture d’écran 2024-08-13 à 20 28 44](https://github.com/user-attachments/assets/5932dbfb-f302-4204-a6b7-e878fe98e90a)

After :
![Capture d’écran 2024-08-13 à 20 28 24](https://github.com/user-attachments/assets/96d81f22-52fa-474f-bc54-70831f05bd60)

# Currently waiting for new API to be prodded.

2024-08-26 07:57 UTC, dectotam approved these changes

2024-08-26 09:11 UTC, darsene requested changes

2024-08-26 09:11 UTC, darsene commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/dashboard/tiles/general-information/general-information.html
> +                    data-ng-if="!$ctrl.locationLoading && $ctrl.locationInfo"
If you use `loading` prop you don't need `ngIf` checks anymore
```suggestion
                    data-ng-if="!$ctrl.locationLoading && $ctrl.locationInfo"
```

2024-08-26 09:11 UTC, darsene commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/list/dedicatedCloud-list.controller.js
> +import get from 'lodash/get';
if possible, try to use native JS functions
```suggestion
```

2024-08-26 11:24 UTC, carsso commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/dashboard/tiles/general-information/general-information.html
> +        <oui-tile-description>
Had to put it on <oui-tile>

2024-08-26 14:50 UTC, darsene approved these changes

2024-08-27 08:39 UTC, dectotam approved these changes

2024-08-29 09:52 UTC, carsso commented
![Capture d’écran 2024-08-29 à 11 50 57](https://github.com/user-attachments/assets/a666dfbc-eb9e-418e-8860-86ec241ece06)

Visual update following QA review

2024-08-30 08:11 UTC, dectotam submitted a review, later dismissed

2024-08-30 11:27 UTC, darsene approved these changes

2024-09-12 08:33 UTC, darsene approved these changes

2024-09-12 08:34 UTC, pauldkn approved these changes

2024-09-12 08:34 UTC, tibs245 approved these changes

2024-09-12 14:45 UTC, merged