feat(hpc-vmware-managed-vcd): add vcdOrga editModal display/validation
ovh/manager pull request #12753
Opened 2024-08-14 07:33 UTC by pauldkn

ref: MANAGER-14526

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/hpc-vcd-beta`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | Feat #MANAGER-14526
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-08-14 08:25 UTC, chipp972 commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/tiles/organization-general-information-tile/OrganizationGeneralInformationTile.component.tsx
> +      )}
Modals have their own route and urls :
https://github.com/ovh/manager/blob/master/packages/manager/apps/pci-rancher/src/routes.tsx

Take example on the pci-rancher project with the EditModal or GenerateAccessModal

2024-08-20 12:39 UTC, rjamet-ovh commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/modal/EditDescriptionModal.tsx
> +      </OsdsText>
you can use the `OsdsModal` `headline` prop for the title

2024-08-20 12:43 UTC, rjamet-ovh commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/modal/EditDescriptionModal.tsx
> +        </OsdsText>
you should be able to use the `label` slot
`<osds-text slot='label' color='text'>Label</osds-text>`

2024-08-21 08:36 UTC, vovh requested changes

2024-08-21 08:36 UTC, vovh commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/modal/EditNameModal.tsx
> +          className={`${isValidName ? 'invisible' : 'visible'}`}
className={isValidName ? 'invisible' : 'visible'}

2024-08-21 08:36 UTC, vovh commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/modal/EditDescriptionModal.tsx
> +          className={`${isValidDesc ? 'invisible' : 'visible'}`}
className={isValidDesc ? 'invisible' : 'visible'}

2024-08-21 15:23 UTC, chipp972 commented on packages/manager/apps/hpc-vmware-managed-vcd/src/components/modal/EditDescriptionModal.tsx
> +      onCloseModal();
We should close the modal on success of the onEdit mutation

2024-08-22 14:27 UTC, chipp972 approved these changes

2024-08-22 14:42 UTC, vovh approved these changes

2024-08-22 14:46 UTC, merged