fix(pci.block-storage): add us link
ovh/manager pull request #12831
Opened 2024-08-23 08:47 UTC by ppprevost

ref: TAPC-663

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

## Related

2024-08-23 08:49 UTC, Eric-ciccotti approved these changes

2024-08-23 08:50 UTC, SimonChaumet approved these changes

2024-08-26 11:16 UTC, anooparveti requested changes

2024-08-26 11:16 UTC, anooparveti commented on packages/manager/apps/pci-block-storage/src/pages/onboarding/onboarding.constants.ts
Why using the same link for `create-attach-volume` and `configure-volume`. Shouldn't it be different be different.

2024-08-28 14:52 UTC, ppprevost commented on packages/manager/apps/pci-block-storage/src/pages/onboarding/onboarding.constants.ts
Question already discussed here from ticket : https://jira.ovhcloud.tools/browse/TAPC-663 :
`` the original request said the following : The first two guides are the same in the EU manager, so we are doing the same for the US. ``

2024-08-29 04:54 UTC, anooparveti approved these changes

2024-09-26 15:18 UTC, merged