fix(veeam-backup): remove sorting and org fetching per column
ovh/manager pull request #12836
Opened 2024-08-26 08:40 UTC by chipp972

ref: MANAGER-14884

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-14884 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-08-26 11:08 UTC, anooparveti requested changes
Can you please separate the changes in `manager-components` into a different PR?

2024-08-26 11:10 UTC, anooparveti requested changes

2024-08-26 11:10 UTC, anooparveti commented on packages/manager/apps/veeam-backup/src/pages/listing/DatagridCell.component.tsx
Can you fix the lint errors?

2024-08-27 07:48 UTC, chipp972 commented
> Can you please separate the changes in `manager-components` into a different PR?

Actually I am reverting manager-components modifications from the epic branch

2024-08-27 07:55 UTC, anooparveti commented on packages/manager/apps/veeam-backup/src/data/api/vcd-organization.api.ts
No need to append `.api` in the file name.

2024-08-27 09:10 UTC, chipp972 commented on packages/manager/apps/veeam-backup/src/data/api/vcd-organization.api.ts
fixed

2024-08-27 10:13 UTC, darsene approved these changes

2024-08-27 14:42 UTC, merged