feat(dedicated.ip): remove parking for ipv6 order
ovh/manager pull request #12852
Opened 2024-08-27 12:08 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-14987
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-08-27 12:47 UTC, anooparveti requested changes

2024-08-27 12:47 UTC, anooparveti commented on yarn.lock
**question:** Why are these changes included? I dont see any new packages included in the PR.

2024-08-27 12:48 UTC, darsene requested changes

2024-08-27 12:49 UTC, qpavy commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/translations/Messages_fr_FR.json
> +  "ip_agora_ipv6_no_services": " Les adresses IPV6 ne peuvent etre attachées qu'a un Réseau privé Vrack. Vous pouvez en créer un ici: ",
Probably not I fix

2024-08-27 13:01 UTC, darsene submitted a review, later dismissed

2024-08-27 13:28 UTC, anooparveti submitted a review, later dismissed

2024-10-17 09:57 UTC, mhelhali-soufien approved these changes

2024-10-24 11:39 UTC, anooparveti approved these changes

2024-11-14 16:36 UTC, darsene approved these changes

2024-11-14 16:36 UTC, mhelhali-soufien approved these changes

2024-11-14 16:40 UTC, merged