feat(pci.rancher): add rancher id
ovh/manager pull request #12857
Opened 2024-08-28 08:06 UTC by ppprevost

ref: TAPC-1024

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

## Related

2024-08-28 13:55 UTC, fredericvilcot submitted a review, later dismissed
👍🏻

2024-08-28 14:01 UTC, y4nnL commented on packages/manager/apps/pci-rancher/src/components/Table/DataGridCell.tsx
> +  cell: Cell<RancherService, unknown>;
```suggestion
  readonly cell: Cell<RancherService, unknown>;
```

2024-08-28 14:09 UTC, Eric-ciccotti submitted a review, later dismissed
do not forget to complet the MR :)

2024-08-28 14:20 UTC, fredericvilcot commented on packages/manager/apps/pci-rancher/src/components/Table/DataGridCell.tsx
> +const ClipboardInput = ({ cell }: Readonly<DisplayCellInterface>) => {
@y4nnL For my own understanding, what's the difference between both? 
The `<Readonly>` type comes to mark all properties as `readonly`, as equivalent to `readonly cell`.
Thanks!

2024-08-28 14:30 UTC, y4nnL approved these changes

2024-08-29 08:08 UTC, anooparveti requested changes

2024-08-29 08:08 UTC, anooparveti commented on packages/manager/apps/pci-rancher/src/components/Table/DataGridCell.tsx
**nitpick:** Use appropriate names for Components. Name suggests that the component is for DatagridCell. But it is very specific to display clipboard in the datagrid.

2024-08-29 20:44 UTC, Tsiorifamonjena reviewed
@ppprevost  the target branch was rebased, and there are conflicts. Can you resolve them please ?

2024-10-27 00:00 UTC, closed without merging