feat(hub): created support tickets component
ovh/manager pull request #12851
Opened 2024-08-27 10:09 UTC by oalkabouss

ref:MANAGER-15067

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/hub-revamp-batch-1`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15067
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-08-27 16:13 UTC, JacquesLarique requested changes
Can you rename the files in the components folder so they respect the target structure: https://manager.pages.ovhcloud.tools/guides/manager/development-guidelines/application-folder-structure/

2024-08-27 16:13 UTC, JacquesLarique commented on packages/manager/apps/hub/src/components/HubSupport/HubSupportTable/HubSupportTableItem.test.tsx
> +    fireEvent.click(linkElement);
```suggestion
    await act(() => fireEvent.click(linkElement));
```

2024-08-27 16:13 UTC, JacquesLarique commented on packages/manager/apps/hub/src/components/HubSupport/HubSupportTable/HubSupportTableItem.test.tsx
Can you add the following test case:
- Test link for US

2024-09-02 07:35 UTC, anooparveti commented on packages/manager/apps/hub/public/translations/hub/Messages_fr_FR.json
> +  "hub_support_error_tile_retry": "Recharger"
**nitpick:** Translations related to Support component can be created in the new namespace and load it along with the Support component.

2024-09-02 08:43 UTC, anooparveti commented on packages/manager/apps/hub/src/components/hub-support/hub-support-table/hub-support-table-item/HubSupportTableItem.component.tsx
> +  const { environment } = context;
**nitpick:** Both these statements can be combined.
```suggestion
  const { shell: {navigation}, environment} = context.shell;
```

2024-09-02 08:48 UTC, anooparveti requested changes

2024-09-02 08:48 UTC, anooparveti commented on packages/manager/apps/hub/src/hooks/guideUtils/useGuideUtils.spec.tsx
**nitpick:** use `renderHook` to test the hook instead of testing the hook through the test component.

2024-09-03 14:52 UTC, anooparveti approved these changes

2024-09-04 08:49 UTC, JacquesLarique approved these changes

2024-09-04 12:02 UTC, merged