feat(pci.project): instances creation reco tracking
ovh/manager pull request #12866
Opened 2024-08-28 16:47 UTC by selm3n

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #...TAPC-1312
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

## Related

2024-09-03 09:38 UTC, oalkabouss submitted a review, later dismissed

2024-09-04 08:28 UTC, Eric-ciccotti commented
manque la description de la MR et le ticket #feat plutôt que fix 😊

2024-09-04 08:31 UTC, Eric-ciccotti approved these changes

2024-09-04 08:33 UTC, y4nnL commented
@selm3n can you squash the two commits into one as they have the same message ?

2024-09-04 08:34 UTC, y4nnL requested changes
@selm3n can you squash the two commits into one as they have the same message ?

2024-09-04 08:46 UTC, y4nnL requested changes

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/flavor-billing/flavor-billing.component.js
> +    onBillingTypeChange: '&?',
```suggestion
    onBillingTypeChange: '&',
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/flavor-billing/flavor-billing.controller.js
> +    }
```suggestion
    this.onBillingTypeChange({
      billing: monthlyBilling ? 'monthly' : 'hourly',
    });
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/flavors-list/flavors-list.component.js
> +    onTabChange: '&?',
```suggestion
    onTabChange: '&',
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/flavors-list/flavors-list.controller.js
> +    }
```suggestion
    this.onTabChange({ category });
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/images-list/images-list.component.js
> +    onTabChange: '&?',
```suggestion
    onTabChange: '&',
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/images-list/images-list.controller.js
> +    }
```suggestion
    this.onTabChange({ type: imageType });
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/components/project/images-list/images-list.controller.js
> +    }
```suggestion
    this.onTabChange({ type });
```

2024-09-04 08:46 UTC, y4nnL commented on packages/manager/modules/pci/src/projects/new/payment/utils.js
> +}
```suggestion
export function getVisitorId() {
  return document.cookie?.match(/clientSideUserId=([a-z0-9]+)?/i)?.[1] || '';
}
```

2024-09-05 11:56 UTC, Eric-ciccotti approved these changes

2024-09-05 12:52 UTC, oalkabouss approved these changes

2024-10-21 00:00 UTC, closed without merging