feat(manager-react-components): upgrade ods version 18
ovh/manager pull request #12865
Opened 2024-08-28 15:57 UTC by aboungnaseng-ovhcloud

ref: MANAGER-14622

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | #14622
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

- upgrade version 18 in manager-react-lib
- update the storybook
- update generator with the new ods version

## Related

2024-09-09 12:39 UTC, antleblanc requested changes
Could you please resolve existing conflicts?

2024-09-26 12:38 UTC, chipp972 commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +            onClick={() => onClick && onClick()}
```suggestion
            onClick={onClick}
```

2024-09-26 12:38 UTC, chipp972 commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +            target={'_blank'}
```suggestion
            target="_blank"
```

2024-09-26 12:39 UTC, chipp972 commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +      className={'mt-3 flex-row'}
```suggestion
      className="mt-3 flex-row"
```

2024-09-26 13:23 UTC, chipp972 commented on packages/manager-react-components/src/components/typography/links/links.component.tsx
> +    {...(type === LinkType.external && { icon: ODS_ICON_NAME.externalLink })}
We could make an object for this :
```
const iconByLinkType = {
  [LinkType.next]: ODS_ICON_NAME.arrowRight,
  [LinkType.external]: ODS_ICON_NAME.externalLink,
  [LinkType.back]: undefined
}
```

Then in the component :
```
icon={iconByLinkType[type]}
```

2024-09-26 14:25 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +            onClick={() => onClick && onClick()}
👍

2024-09-26 14:25 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +            target={'_blank'}
👍

2024-09-26 14:26 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/action-banner/action-banner.component.tsx
> +      className={'mt-3 flex-row'}
👍

2024-09-26 14:27 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/container/step/Step.component.tsx
> +            }
👍

2024-09-26 14:28 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/container/step/Step.component.tsx
>                  {...(edit.isDisabled ? { disabled: true } : {})}
👍

2024-09-26 14:29 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/container/step/Step.component.tsx
>                    {...(next.isDisabled ? { disabled: true } : {})}
👍

2024-09-26 14:31 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/content/dashboard-tile/dashboard-tile.component.tsx
> +        <>
👍

2024-09-26 14:37 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/navigation/menus/action/action.component.tsx
> +        with-arrow="true"
👍

2024-09-26 14:39 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/templates/delete-modal/delete-modal.component.tsx
> +        isDisabled={isDisabled}
👍

2024-09-26 14:39 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/templates/delete-modal/delete-modal.component.tsx
>        )}
👍

2024-09-26 14:42 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/templates/update-name-modal/update-name-modal.component.tsx
>        )}
👍

2024-09-26 14:43 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/templates/update-name-modal/update-name-modal.component.tsx
> +        isDisabled={isLoading || isPatternError}
👍

2024-09-27 07:48 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
>    const { isAuthorized } = useAuthorizationIam(iamActions, urn, isIamTrigger);
yes we can use this isLoading but by default the button is disabled, we have to define the behavior before taking a decision

2024-09-27 14:18 UTC, chipp972 commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
>    const { isAuthorized } = useAuthorizationIam(iamActions, urn, isIamTrigger);
I think it is disabled when loading also

2024-09-27 14:19 UTC, chipp972 commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
> +          content="true"
What does content="true" do on OdsButton ?

2024-09-27 14:20 UTC, chipp972 submitted a review, later dismissed

2024-10-02 08:35 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
> +          content="true"
deleted

2024-10-02 08:36 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
> +  if (!isAuthorized) {
👍

2024-10-02 08:39 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/ManagerButton/ManagerButton.tsx
> +          content="true"
👍

2024-10-02 08:41 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/typography/links/links.component.tsx
> +    href="#"
👍

2024-10-02 08:41 UTC, aboungnaseng-ovhcloud commented on packages/manager-react-components/src/components/navigation/card/card.component.tsx
> +      target={'_blank'}
👍

2024-10-11 09:42 UTC, chipp972 approved these changes

2024-10-11 10:02 UTC, darsene approved these changes

2024-10-11 12:57 UTC, merged