Fix(pci-private-network): Network instead of network
ovh/manager pull request #12892
Opened 2024-08-30 08:24 UTC by Tsiorifamonjena

ref: TAPC-1216

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-1216
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-09-02 08:51 UTC, anooparveti requested changes
As developers can only make change in `Messages_FR_fr.json`, changes in these files must come from the translation team.

2024-09-04 08:48 UTC, y4nnL approved these changes

2024-09-04 08:50 UTC, y4nnL approved these changes
See @anooparveti's comment

2024-09-04 09:57 UTC, fredericvilcot approved these changes

2024-09-10 11:44 UTC, anooparveti approved these changes

2024-09-20 05:18 UTC, merged