feat(instance): add savings plan banner on instance
ovh/manager pull request #13073
Opened 2024-09-12 12:36 UTC by lionel95200x

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/savings-plan-epic` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-1165
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

- Add new banner savings plan on instance with CTA 
- 
## Related

2024-09-12 14:02 UTC, y4nnL requested changes

2024-09-12 14:02 UTC, y4nnL commented on packages/manager/modules/pci/src/projects/project/instances/add/add.controller.js
> +    this.PciProjectsProjectInstanceService.getCommercialCatalog({
```suggestion
    return this.PciProjectsProjectInstanceService.getCommercialCatalog({
```

2024-09-13 13:40 UTC, y4nnL approved these changes

2024-09-16 05:45 UTC, anooparveti requested changes
Removal of translation must only be done on `Messages_fr_FR.json` file.

2024-09-16 07:42 UTC, merged