fix(web): add all subs for offer banner
ovh/manager pull request #13137
Opened 2024-09-17 11:09 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-15055 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added all subs for offer banner

## Related

2024-09-17 11:39 UTC, tristanwagner approved these changes

2024-09-17 12:37 UTC, antonymarion approved these changes

2024-09-17 12:40 UTC, antonymarion commented
Not a fix but a feat here (images for other subs were provided recently)

2024-09-17 12:48 UTC, antonymarion requested changes
on feat branch

2024-09-18 06:55 UTC, anooparveti approved these changes

2024-09-19 14:21 UTC, merged