feat(zimbra): add redirection tab datagrid no api
ovh/manager pull request #13136
Opened 2024-09-17 10:43 UTC by stif59100

ref:MANAGER-15272

| Question         | Answer
| ---------------- | ---
| Branch?          | zimbra-ga
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15272
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] ~~Commits are signed-off~~
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added redirection tabs and datagrid with no api.

## Related

2024-09-17 13:36 UTC, tristanwagner requested changes

2024-09-17 13:36 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/Redirections.tsx
> +export type RediretionsItem = {
RedirectionItem*

2024-09-17 13:42 UTC, tristanwagner approved these changes

2024-09-18 06:57 UTC, anooparveti approved these changes

2024-09-18 08:34 UTC, ghyenne approved these changes

2024-09-18 08:34 UTC, merged