Feat/manager 14180 : Credential step 3
ovh/manager pull request #13157
Opened 2024-09-18 13:03 UTC by vovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-09-19 04:17 UTC, anooparveti requested changes
The components added in the `components` folder are limited to Create Credential. So, add them in the `packages/manager/apps/key-management-service/src/pages/credential/create` folder itself.

2024-09-19 08:14 UTC, tibs245 approved these changes

2024-09-19 09:03 UTC, rjamet-ovh commented on packages/manager/apps/key-management-service/src/components/credential/create/confirmation/CreateCredentialConfirmation.component.tsx
> +        privateKey={okmsCredential.certificatePEM}
```suggestion
        privateKey={okmsCredential.privateKeyPEM}
```

2024-09-19 09:04 UTC, rjamet-ovh commented on packages/manager/apps/key-management-service/src/components/credential/create/confirmation/CreateCredentialConfirmationPrivateKey.component.tsx
> +            )}`}
```suggestion
            href={`data:application/x-pem-file;base64,${btoa(privateKey)}`}
```

2024-09-19 09:07 UTC, rjamet-ovh commented on packages/manager/apps/key-management-service/src/components/credential/create/confirmation/CreateCredentialConfirmation.component.tsx
> +          inline
`onClick` is missing

2024-09-20 12:57 UTC, anooparveti approved these changes

2024-09-20 13:06 UTC, rjamet-ovh approved these changes

2024-09-23 08:09 UTC, merged