fix(pci-kubernetes): es translations
ovh/manager pull request #13166
Opened 2024-09-19 08:57 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTCORE-2616
| License          | BSD 3-Clause

## Description

fix malformed es translation file

2024-09-19 08:59 UTC, kqesar submitted a review, later dismissed

2024-09-19 09:02 UTC, sidlynx approved these changes

2024-09-19 09:40 UTC, kqesar submitted a review, later dismissed

2024-09-19 09:52 UTC, sidlynx submitted a review, later dismissed

2024-09-20 05:50 UTC, anooparveti requested changes
The missing comma has been added on the master branch as part of resolving conflicts https://github.com/ovh/manager/blob/master/packages/manager/apps/pci-kubernetes/public/translations/add/Messages_es_ES.json. 

You can ignore this PR I guess. However i am not sure why the diff is not updated.

2024-09-20 06:58 UTC, frenautvh commented
already has been updated on master branch

2024-09-20 06:58 UTC, closed without merging