feat(pci-workflow): optimize tests and use pci-common
ovh/manager pull request #13165
Opened 2024-09-19 08:42 UTC by kqesar

ref: DTCORE-2614

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/pci-workflow`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | DTCORE-2614
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-09-19 14:55 UTC, frenautvh commented on packages/manager/apps/pci-kubernetes/src/App.tsx
> +  createHashRouter,
```suggestion
```

2024-09-19 15:00 UTC, frenautvh commented on packages/manager/modules/manager-pci-common/src/api/data/instance.ts
> +  flavorName?: string;
if you check the api schema those properties does not exists :
https://eu.api.ovh.com/console/?section=%2Fcloud&branch=v1#get-/cloud/project/-serviceName-/instance

you have to add those props in the pci-workflow app using a new type but the types in pci-common should reflect the api schema

2024-09-20 07:51 UTC, anooparveti requested changes

2024-09-20 07:51 UTC, anooparveti commented on packages/manager/modules/manager-pci-common/src/api/hook/useIntance.ts
Correct the file name. There is a typo `useInstance`.

2024-09-23 08:07 UTC, frenautvh commented on packages/manager/modules/manager-pci-common/src/api/data/instance.ts
> +export type TInstanceAPI = {
i think we should keep TInstance type as API is implicit,
in your app you shoud TWorkflowInstance for example if you need to add custom fields

2024-09-23 08:48 UTC, seven-amid commented on packages/manager/apps/pci-workflow/src/components/DeleteWorkflowRedirect.spec.tsx
> +      <MemoryRouter initialEntries={['/initial']}>
Why MemoryRouter, and not HashRouter used by the App ?

2024-09-23 08:48 UTC, seven-amid commented on packages/manager/modules/manager-pci-common/src/api/hook/useInstance.ts
> +    queryKey: ['instances', instanceId],
maybe add the projectId to the queryKey.

2024-09-23 09:22 UTC, kqesar commented on packages/manager/apps/pci-workflow/src/components/DeleteWorkflowRedirect.spec.tsx
> +    debug(container);
I am missed to delete it, thank you !

2024-09-30 08:55 UTC, sidlynx approved these changes

2024-10-01 13:18 UTC, merged