feat(zimbra): action modify the redirection
ovh/manager pull request #13179
Opened 2024-09-19 14:32 UTC by stif59100

ref:MANAGER-14640

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/zimbra-ga
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15273
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added modal edit redirections.

## Related

2024-09-20 07:40 UTC, anooparveti requested changes

2024-09-20 07:40 UTC, anooparveti commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/AddAndEditRedirections.tsx
**nitpick:** Filename should be `AddAndEditRedirections.page.tsx`

2024-09-20 07:40 UTC, anooparveti commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ActionButtonRedirections.tsx
**nitpick:** File name should be `ActionButtonRedirections.component.tsx`

2024-09-20 07:48 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ActionButtonRedirections.tsx
> +    editRedirectionsAccountId: redirectionsItem.id,
```suggestion
    editRedirectionId: redirectionsItem.id,
```

2024-09-20 07:48 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ActionButtonRedirections.tsx
> +    deleteRedirectionsId: redirectionsItem.id,
```suggestion
    deleteRedirectionId: redirectionsItem.id,
```

2024-09-20 07:48 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/AddAndEditRedirections.tsx
> +                required
inputs are not handled and no form validation

2024-09-20 07:48 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ActionButtonRedirections.tsx
> +    editRedirectionsAccountId: redirectionsItem.id,
for consistency with search params in other pages

2024-09-20 07:51 UTC, tristanwagner reviewed
There's 2 small SonarCube issues [First](https://sonarcloud.io/project/issues?pullRequest=13179&open=AZIKtc8y4Vu3DBypOJQy&id=ovh_manager) and [Second](https://sonarcloud.io/project/issues?pullRequest=13179&open=AZIKtdEo4Vu3DBypOJQz&id=ovh_manager)

2024-09-23 06:47 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/AddAndEditRedirections.page.tsx
> +            }}
```suggestion
            onOdsInputBlur={({ target: { name, value } }) =>
              handleFormChange(name, value.toString())
            }
            onOdsValueChange={({ detail: { name, value } }) => 
              handleFormChange(name, value);
            }
```

2024-09-23 06:47 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/AddAndEditRedirections.page.tsx
> +            }}
```suggestion
            onOdsInputBlur={({ target: { name, value } }) =>
              handleFormChange(name, value.toString())
            }
            onOdsValueChange={({ detail: { name, value } }) => 
              handleFormChange(name, value);
            }
```

2024-09-23 06:47 UTC, ghyenne commented on packages/manager/apps/zimbra/src/routes/routes.tsx
> +              },
No need for now or put a comment (todo: need change url when delete component will be available)

2024-09-23 15:46 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/__test__/ActionButtonRedirections.component.spec.tsx
> +describe('EmailAccounts datagrid action menu', () => {
```suggestion
describe('Redirections datagrid action menu', () => {
```

2024-09-23 15:46 UTC, ghyenne commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/__test__/Redirections.spec.tsx
> +describe('Organizations page', () => {
```suggestion
describe('Redirections page', () => {
```

2024-09-24 08:42 UTC, ghyenne approved these changes

2024-09-24 08:50 UTC, anooparveti commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ModalAddAndEditRedirections.page.tsx
> +  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
**suggestion:** This can be moved to constant file.

2024-09-24 08:51 UTC, anooparveti commented on packages/manager/apps/zimbra/src/pages/dashboard/Redirections/ModalAddAndEditRedirections.page.tsx
> +  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
**nitpick:** Define constants with `SCREAMING_SNAKE_CASE`
```suggestion
  const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
```

2024-09-24 10:07 UTC, tristanwagner approved these changes

2024-09-24 11:06 UTC, anooparveti approved these changes

2024-09-24 12:02 UTC, merged