fix(web): add banner eol webpass and remove order
ovh/manager pull request #13198
Opened 2024-09-20 13:00 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-15255 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added banner eol for webpass product and remove order button.

## Related

2024-09-20 13:38 UTC, anooparveti requested changes
You also need to remove the entry from PNR https://github.com/ovh/manager/blob/master/packages/manager/apps/container/src/container/nav-reshuffle/sidebar/navigation-tree/services/webCloud.ts#L99-L119

2024-09-20 13:39 UTC, anooparveti submitted a review, later dismissed

2024-09-21 07:54 UTC, antonymarion approved these changes

2024-09-23 15:31 UTC, antonymarion approved these changes

2024-09-23 15:32 UTC, tristanwagner approved these changes

2024-10-09 07:32 UTC, antonymarion approved these changes

2024-10-09 07:32 UTC, tristanwagner approved these changes

2024-10-09 09:51 UTC, antonymarion approved these changes

2024-10-09 09:52 UTC, tristanwagner approved these changes

2024-10-10 14:13 UTC, merged