refactor(*): add retry on universes and availability requests
ovh/manager pull request #13200
Opened 2024-09-20 13:41 UTC by tibs245

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| ~Tickets~          | 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~Only FR translations have been updated~
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

2024-09-20 13:57 UTC, darsene commented on packages/manager/apps/container/src/hooks/useUniverses.ts
> +    queryKey: ["universe"],
```suggestion
    queryKey: ["universes"],
```

2024-09-20 13:57 UTC, darsene commented on packages/manager/apps/container/src/hooks/useUniverses.ts
> +      return (universes ?? []).find(({ universe }) => universe === 'hub');
```suggestion
      return universes?.find(({ universe }) => universe === 'hub');
```

2024-09-20 14:03 UTC, anooparveti requested changes
**question:** Do we have any ticket which requires this change?

2024-09-20 14:11 UTC, darsene commented
> **question:** Do we have any ticket which requires this change?

@anooparveti it's to fix the issue with BFF ran locally 

```
{
    "message": "CDN's redirect mechanism has been triggered due to many calls to the same API route in a small amount of time. You probably need to optimize your code to avoid this.",
    "class": "Client::TooManyRequests"
}
```

2024-09-20 14:15 UTC, darsene approved these changes

2024-09-20 14:18 UTC, anooparveti commented
Can you please create a ticket?

2024-09-20 14:29 UTC, tibs245 commented
> Can you please create a ticket?

Ticket created 🚀 MANAGER-15346

2024-09-25 08:42 UTC, darsene submitted a review, later dismissed

2024-09-25 09:46 UTC, pauldkn approved these changes

2024-09-27 12:19 UTC, anooparveti approved these changes

2024-10-21 09:05 UTC, darsene approved these changes

2024-10-21 09:07 UTC, pauldkn approved these changes

2024-10-21 09:18 UTC, merged