fix(dedicated-cloud): use description vs id in PCC list and breadcrumb
ovh/manager pull request #13345
Opened 2024-09-27 17:50 UTC by ThibaudCrespin

ref: MANAGER-14705

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-14705 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Replace ID with description in PCC list page and breadcrumb in details page

## Related

2024-09-30 08:13 UTC, darsene requested changes

2024-09-30 08:13 UTC, darsene commented on packages/manager/apps/dedicated/client/app/dedicatedCloud/details/dedicatedCloud.routing.js
> +        dedicatedCloudDescription.description || serviceName, // Si jamais le champ description (le nom) n'est pas rempli
Comment to put in English. Here, it's quite obvious so you can remove it

2024-10-02 08:22 UTC, darsene approved these changes

2024-10-02 08:23 UTC, tibs245 approved these changes

2024-10-18 06:51 UTC, merged