feat(dedicated): filter organizations when order ipv4 block
ovh/manager pull request #13464
Opened 2024-10-07 07:39 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #MANAGER-15314
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-10-08 01:22 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ipv4/ipv4.constant.js
> +  EUROP: 'EUROPE',
```suggestion
  EUROPE: 'EUROPE',
```

2024-10-08 01:22 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ipv4/ipv4.controller.js
> +      return SERVER_REGION.EUROP;
```suggestion
      return SERVER_REGION.EUROPE;
```

2024-10-08 01:32 UTC, sachinrameshn requested changes

2024-10-08 01:32 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ipv4/ipv4.controller.js
> +        } else {
I guess we should't have a else case. This change is for all the service not only for dedicated server. We need to retain this for all service type.

2024-10-08 06:51 UTC, qpavy submitted a review, later dismissed

2024-10-10 09:30 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ipv4/ipv4.controller.js
> +            registry = null;
```suggestion
          case SERVER_REGION.EUROPE:
            registry = ORGANISATION_GROUP.RIPE;
            break;
          case SERVER_REGION.CANADA:
            registry = ORGANISATION_GROUP.ARIN;
            break;
          default:
            registry = null;
```

2024-10-10 09:31 UTC, sachinrameshn requested changes
I believe we need to show both the organisation for US region.

2024-10-10 10:50 UTC, qpavy approved these changes

2024-10-11 06:58 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/components/ip/agoraOrder/ipv4/ipv4.controller.js
>              let countries = data;
If at all we have countries coming from API how will we handling the organization filter ? 
We are dependent on region from service name if the country is coming as empty. And I see you have removed this logic. Shouldn't we need to keep as is and get the region based on countries ?

2024-10-31 10:00 UTC, sachinrameshn submitted a review, later dismissed

2024-10-31 14:26 UTC, qpavy submitted a review, later dismissed

2024-11-14 16:46 UTC, merged