fix(*): remove ovh-banner from universes
ovh/manager pull request #13496
Opened 2024-10-08 13:49 UTC by MaximeBajeux

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-15596
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-10-08 14:04 UTC, JacquesLarique commented on packages/manager/modules/pci/src/index.js
Be careful, Dedicated, Public Cloud and Web are using manager-banner-text (exposed in the module ovhManagerBanner), by removing this you'll certainly break some injection in these applications (at the top of packages/manager/modules/pci/src/projects/projects.html you can find such case)

2024-10-08 15:56 UTC, MaximeBajeux commented on packages/manager/modules/pci/src/index.js
fixed

2024-10-08 15:58 UTC, JacquesLarique submitted a review, later dismissed

2024-10-08 17:28 UTC, anooparveti requested changes
`@ovh-ux/manager-banner` module can be removed from the corresponding `package.json` as well.

2024-10-09 10:58 UTC, anooparveti approved these changes

2024-10-17 11:49 UTC, anooparveti approved these changes

2024-10-17 11:49 UTC, merged