feat(zimbra): migrate to @ovhcloud/ods-components v18.3.1
ovh/manager pull request #13633
Opened 2024-10-17 08:09 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15662 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-10-24 15:23 UTC, tristanwagner commented
Known issues:

- Breadcrumb has a bug where some items are not clickable
- Some tooltips are having a weird behavior
- Select that are disabled while fetching option data get stuck in disabled state
- ManagerButton IAM seems to have an issue ?
- Modals have a fixed `max-height: 50vh;`

2024-11-18 09:39 UTC, antonymarion commented on packages/manager/apps/zimbra/src/pages/dashboard/AutoReplies/__test__/AddAutoReply.page.spec.tsx
> +    // const radioTemporary = getByTestId(AutoReplyDurations.TEMPORARY);
same

2024-11-18 09:40 UTC, antonymarion commented on packages/manager/apps/zimbra/src/pages/dashboard/GeneralInformation/GeneralInformation.tsx
>  // import { OngoingTasks } from './OngoingTasks';
same

2024-11-18 09:40 UTC, antonymarion submitted a review, later dismissed

2024-11-18 09:46 UTC, tristanwagner commented on packages/manager/apps/zimbra/src/pages/dashboard/AutoReplies/__test__/AddAutoReply.page.spec.tsx
> +    expect(button).toHaveAttribute('is-disabled', 'false');
yeah actually that's one of the test I have trouble to fix, it will be skipped for now

2024-11-18 13:50 UTC, ghyenne approved these changes

2024-11-22 11:07 UTC, tristanwagner requested changes
first 2 commits should be dropped when they will be merged into master

2024-11-25 11:49 UTC, tristanwagner submitted a review, later dismissed

2024-11-25 13:09 UTC, tristanwagner submitted a review, later dismissed

2024-11-29 08:39 UTC, merged