feat(procedures): implement gdpr document upload and confirmation
ovh/manager pull request #13654
Opened 2024-10-17 16:18 UTC by oalkabouss

ref: MANAGER-15368

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-15339`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15368
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-10-18 07:12 UTC, JacquesLarique requested changes

2024-10-18 07:12 UTC, JacquesLarique commented on packages/manager/apps/procedures/src/pages/rgdp/rgdpForm/RGDPForm.test.tsx
Can you add test on the display of modals please

2024-10-18 07:12 UTC, JacquesLarique commented on packages/manager/apps/procedures/src/data/hooks/rgdp/useRGDP.tsx
> +export const useRGDPUploadLinks = ({
Reading the doc from SIA, the form data will be sent in this call, so you need to update these two functions

2024-10-18 07:12 UTC, JacquesLarique commented on packages/manager/apps/procedures/src/data/api/rgdp/rgdpApi.ts
> +export type FormValue = {
Same as https://github.com/ovh/manager/pull/13654#discussion_r1805989584

2024-10-21 08:51 UTC, JacquesLarique approved these changes

2024-10-21 11:29 UTC, MaximeBajeux approved these changes

2024-10-21 12:14 UTC, merged