feat(hub): rewrote hub in react
ovh/manager pull request #13689
Opened 2024-10-21 09:57 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/hub-revamp`
| Bug fix?         | no
| New feature?     | yes/no
| Breaking change? | no
| Tickets          | MANAGER-14935
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Rewrote hub in react
Added skeleton as well as making the app display a bit sooner

## Related

2024-10-21 10:42 UTC, anooparveti requested changes

2024-10-21 10:42 UTC, anooparveti commented on packages/manager/apps/hub-react/package.json
> +    "@tanstack/react-query-devtools": "^5.51.21",
This should be a `devDependency`

2024-10-21 10:42 UTC, anooparveti commented on packages/manager/apps/hub-react/package.json
> +    "tailwindcss": "^3.4.4"
This should be a `devDependency`

2024-10-22 08:28 UTC, anooparveti approved these changes

2024-10-22 08:30 UTC, oalkabouss approved these changes

2024-10-22 09:35 UTC, merged