feat(ips): init ips react app
ovh/manager pull request #13742
Opened 2024-10-23 11:23 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `project/ip-revamp`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-15657
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- ~~[ ] Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-10-25 10:44 UTC, darsene reviewed
Can you fix e2e tests, they should work by default once app is generated

2024-10-25 12:20 UTC, darsene submitted a review, later dismissed

2024-10-30 09:07 UTC, anooparveti requested changes
Since we need to remove e2e configs from generator, it's redundant. Can you remove it manually?

2024-10-30 09:10 UTC, anooparveti commented on packages/manager/apps/ips/package.json
> +    "tailwindcss": "^3.4.4"
This can be moved to devDeps

2024-10-30 09:10 UTC, anooparveti commented on packages/manager/apps/ips/playwright.config.ts
Playwright is not required as well.

2024-10-30 09:12 UTC, anooparveti commented on packages/manager/apps/ips/src/data/api/ips.ts
> +export const getipListQueryKey = ['get/ip'];
```suggestion
export const getIpListQueryKey = ['get/ip'];
```

2024-10-30 09:12 UTC, anooparveti commented on packages/manager/apps/ips/src/data/api/ips.ts
> +export const getipList = async (params: GetipListParams): Promise<any> =>
```suggestion
export const getIpList = async (params: GetipListParams): Promise<any> =>
```

2024-10-30 09:13 UTC, anooparveti commented on packages/manager/apps/ips/src/data/api/ips.ts
> +export const getipIpQueryKey = (params: GetipIpParams) => [
```suggestion
export const getIpIpQueryKey = (params: GetipIpParams) => [
```

2024-10-30 09:13 UTC, anooparveti commented on packages/manager/apps/ips/src/data/api/ips.ts
> +export const getipIp = async (params: GetipIpParams): Promise<any> =>
```suggestion
export const getIp = async (params: GetipIpParams): Promise<any> =>
```

2024-11-05 06:53 UTC, mhelhali-soufien submitted a review, later dismissed

2024-11-14 12:48 UTC, anooparveti reviewed
If `mocks` folder is not used, can you remove it?

2024-11-14 12:50 UTC, anooparveti commented on packages/manager/apps/ips/package.json
> +  "description": "ips manager app",
```suggestion
  "description": "Ips manager app",
```

2024-11-14 12:50 UTC, anooparveti commented on packages/manager/apps/ips/package.json
> +    "@ovh-ux/manager-react-components": "*",
To use v1 of MRC
```suggestion
    "@ovh-ux/manager-react-components": "^1.14.1",
```

2024-11-14 12:55 UTC, anooparveti commented on packages/manager/apps/ips/src/tracking.constant.ts
> +  },
Refer -> https://github.com/ovh/manager/blob/596170e7b496f367ad75ab8273e6308d27e7b7a3/packages/manager/apps/dedicated/client/app/at-internet.constants.js
```suggestion
  EU: {
    config: {
      level2: '85',
    },
  },
  CA: {
    config: {
      level2: '85',
    },
  },
  US: {
    config: {
      level2: '57',
    },
  },
```

2024-11-18 07:50 UTC, sachinrameshn approved these changes

2024-11-18 08:27 UTC, darsene approved these changes

2024-11-18 08:37 UTC, merged