feat(dedicated): delete vrack from billing autorenew page
ovh/manager pull request #13823
Opened 2024-10-29 07:08 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-15077
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-11-06 09:55 UTC, qpavy requested changes

2024-11-06 09:55 UTC, qpavy commented on packages/manager/modules/billing/src/autoRenew/actions/terminate-vrack/controller.js
> +      });
This can be done on routing resolve so it is executed before page load

2024-11-06 09:55 UTC, qpavy commented on packages/manager/modules/billing/src/autoRenew/actions/terminate-vrack/component.js
> +    serviceType: '<',
```suggestion
    serviceType: '<',
    isEmpty: '<'
```

2024-11-06 09:55 UTC, qpavy commented on packages/manager/modules/billing/src/autoRenew/actions/terminate-vrack/routing.js
> +      breadcrumb: () => null,
```suggestion
      breadcrumb: () => null,
      isEmpty: // move isEmpty here
```

2024-11-13 13:51 UTC, sachinrameshn commented on packages/manager/modules/billing/src/autoRenew/actions/terminate-vrack/controller.js
> +    this.$scope = $scope;
$scope should be removed.

2024-11-14 08:05 UTC, qpavy requested changes

2024-11-14 08:05 UTC, qpavy commented on packages/manager/modules/billing/src/autoRenew/actions/terminate-vrack/routing.js
> +          .services({ serviceName: $transition$.params().service })
```suggestion
      isEmpty: /* @ngInject */ (OvhApiVrack, service) =>
        OvhApiVrack.Aapi()
          .services({ serviceName: service })
```

2024-11-15 09:23 UTC, qpavy approved these changes

2024-11-15 09:26 UTC, sachinrameshn submitted a review, later dismissed

2025-01-13 16:04 UTC, chipp972 approved these changes

2025-01-13 16:05 UTC, darsene approved these changes

2025-01-13 16:45 UTC, merged