feat(container): animation improvement & add skeleton on entry menu
ovh/manager pull request #13867
Opened 2024-10-31 07:43 UTC by oalkabouss

ref: MANAGER-14921

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-14461`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-11-06 09:18 UTC, SimonChaumet requested changes

2024-11-06 09:18 UTC, SimonChaumet commented on packages/manager/apps/container/src/container/nav-reshuffle/sidebar/Assistance/AssistanceLinkItem.tsx
> +            {isLoading ? <OsdsSkeleton randomized className='mx-8' /> : <SidebarLink
Please run formatter

2024-11-06 09:35 UTC, SimonChaumet reviewed
Maybe check formatter

2024-11-13 15:22 UTC, MaximeBajeux approved these changes

2024-11-18 10:23 UTC, JacquesLarique approved these changes

2024-12-20 09:21 UTC, merged