feat(dedicated): add tile tags on server page
ovh/manager pull request #14014
Opened 2024-11-08 08:52 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/ovh-tagging`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #MANAGER-15556
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-11-08 09:50 UTC, qpavy requested changes

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/controller.js
> +    this.$scope = $scope;
```suggestion
```
Don't use $scope but directly 'this'

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/controller.js
> +    }
```suggestion
    this.tags = null;
    const { tags } = this.server.iam;
    if (tags) {
      this.tags = Object.keys(tags).map((key) => `${key}:${tags[key]}`);

      if (tags.length > 10) {
        this.tags = [...this.tags.slice(0, 10), '...'];
      }
    }
```

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/template.html
> +    <oui-tile-definition ng-if="!tags">
```suggestion
    <oui-tile-definition ng-if="!$ctrl.tags">
```

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/template.html
> +    <oui-tile-definition ng-if="tags">
```suggestion
    <oui-tile-definition ng-if="$ctrl.tags">
```

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/template.html
> +            >
```suggestion
            <span
                class="oui-badge ng-scope oui-badge_info"
                data-ng-repeat="tag in $ctrl.tags track by $index"
                data-ng-bind="tag"
            ></span>
```

2024-11-08 09:50 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/template.html
> +                data-translate="{{:: tags ? 'server_tags_link' : 'server_tags_add_link' }}"
```suggestion
                data-translate="{{:: $ctrl.tags ? 'server_tags_link' : 'server_tags_add_link' }}"
```

2024-11-14 08:28 UTC, qpavy requested changes

2024-11-14 08:28 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/component.js
> +  transclude: true,
Why use transclude without transclude in the template  ?

2024-11-14 08:28 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/template.html
> +    <div ovh-alert="bandwithError" data-ng-if="bandwithError"></div>
Is this working ? I don't find "bandwidthError" within the module

2024-11-15 09:27 UTC, sachinrameshn approved these changes

2024-11-15 09:29 UTC, qpavy requested changes

2024-11-15 09:29 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/controller.js
> +    this.$state.go('app.dedicated-server.server.tags');
```suggestion
    this.goToTags();
```
Can you make this more generic and use a function as component input to move the logic outside of the component ?

2024-11-15 09:29 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/component.js
> +    server: '<',
```suggestion
    server: '<',
    goToTags: '<'
```

2024-11-18 10:58 UTC, sachinrameshn requested changes

2024-11-18 10:58 UTC, sachinrameshn commented on packages/manager/modules/bm-server-components/src/tags-tile/controller.js
> +
I guess you need to filter out the tags which starts with "ovh:cluster"

2024-11-20 07:39 UTC, sachinrameshn approved these changes

2024-11-20 09:20 UTC, qpavy requested changes

2024-11-20 09:20 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/server-dashboard/dashboard.html
> +                data-go-to-tags="$ctrl.goToTags()"
```suggestion
                data-go-to-tags="$ctrl.goToTags"
```

2024-11-20 09:20 UTC, qpavy commented on packages/manager/modules/bm-server-components/src/tags-tile/component.js
> +    goToTags: '&',
```suggestion
    goToTags: '<',
```

2024-11-21 14:32 UTC, qpavy approved these changes

2025-01-08 07:18 UTC, merged