Fix/manager 15969
ovh/manager pull request #14010
Opened 2024-11-07 17:03 UTC by JayBeeDe

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix MANAGER-15969
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)

## Description

Fix french translation typo and minor margin issues around sshKey component

## Related

ref: MANAGER-15969

2024-11-20 10:38 UTC, anooparveti reviewed
Question: Why do you want to also update `Messages_fr_CA.json`?

2024-11-20 10:56 UTC, JayBeeDe commented
> Question: Why do you want to also update `Messages_fr_CA.json`?
Because translation issue is only in french language, other language are fine

2024-11-21 08:00 UTC, qpavy approved these changes

2024-11-21 08:13 UTC, sachinrameshn approved these changes

2024-11-21 08:24 UTC, sachinrameshn reviewed
Hello @JayBeeDe , 
Can you please split the changes on manager-components into separate PR ? 

This will help us to gain some time during the release. 
Need is: 
Just create another PR with the changes on manager-components and target develop.

2024-11-21 08:57 UTC, mhelhali-soufien submitted a review, later dismissed

2024-11-22 05:22 UTC, sachinrameshn requested changes
Hello @JayBeeDe ,
Can you please split the changes on manager-components into separate PR ?

This will help us to gain some time during the release.
Need is:
Just create another PR with the changes on manager-components and target develop.

2024-11-25 11:03 UTC, JayBeeDe commented
> Hello @JayBeeDe , Can you please split the changes on manager-components into separate PR ?
> 
> This will help us to gain some time during the release. Need is: Just create another PR with the changes on manager-components and target develop.

[fix(manager-components): ssh-key-selector margin issues by JayBeeDe · Pull Request #14245 · ovh/manager](https://github.com/ovh/manager/pull/14245)

2024-11-26 05:25 UTC, sachinrameshn submitted a review, later dismissed

2025-03-05 17:08 UTC, tristanwagner commented on packages/manager/apps/dedicated/client/app/dedicated/dedicated-server/clusters/nodes/node/translations/Messages_fr_CA.json
> +  "server_configuration_installation_progress_cancel_button_confirm": "Confirmer",
only `Messages_fr_FR.json` should be updated

2025-03-05 17:08 UTC, tristanwagner submitted a review, later dismissed

2025-03-05 17:37 UTC, tristanwagner approved these changes

2025-03-07 10:02 UTC, qpavy approved these changes

2025-03-10 02:01 UTC, sachinrameshn approved these changes

2025-03-21 14:34 UTC, merged