feat(container): added an invitation modal to accept contract
ovh/manager pull request #14041
Opened 2024-11-12 16:05 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-14722
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (n/a)

## Description

Reworked modal display in order to avoid the possibility of having multiple modals displayed at the same time
Set up a new modal to invite customer to accept new / updated contracts
Fix a small tracking issue on KYC India modal

## Related

2024-11-13 13:18 UTC, MaximeBajeux commented on packages/components/ovh-shell/src/plugin/ux/index.ts
Should we not do a separated PR for the common changes ?

2024-11-13 13:22 UTC, JacquesLarique commented on packages/components/ovh-shell/src/plugin/ux/index.ts
They will disappear once their dedicated PR will be merged (https://github.com/ovh/manager/pull/14025)

2024-11-13 13:23 UTC, MaximeBajeux approved these changes

2024-11-13 14:06 UTC, oalkabouss commented on packages/manager/apps/container/src/api/authorizations.ts
> +  /*
Add a note to say why it s commented

2024-11-13 14:06 UTC, oalkabouss commented on packages/manager/apps/container/src/components/AgreementsUpdateModal/AgreementsUpdateModal.component.tsx
> +  const { data: agreements, isLoading } = useAgreementsUpdate({ enabled: canUserAcceptAgreements });
isloading is not used

2024-11-13 14:06 UTC, oalkabouss commented on packages/manager/apps/container/src/container/index.tsx
> +  useModals();
i guess it is on oversight ?

2024-11-13 14:46 UTC, oalkabouss submitted a review, later dismissed

2024-11-13 15:20 UTC, MaximeBajeux submitted a review, later dismissed

2024-11-20 10:38 UTC, MaximeBajeux submitted a review, later dismissed

2024-11-20 14:03 UTC, oalkabouss approved these changes

2024-12-05 11:06 UTC, oalkabouss submitted a review, later dismissed

2024-12-05 11:35 UTC, MaximeBajeux submitted a review, later dismissed

2025-01-02 14:44 UTC, MaximeBajeux approved these changes

2025-01-03 08:08 UTC, sachinrameshn submitted a review, later dismissed

2025-01-03 08:18 UTC, anooparveti commented on packages/manager/apps/container/src/api/agreements.ts
> +const fetchAgreementsUpdates = async () => {
**nitpick:** Considering the filters applied, it would make more sense to use more precise function name.
```suggestion
const fetchPendingAgreements = async () => {
```

2025-01-03 08:23 UTC, anooparveti requested changes

2025-01-03 08:23 UTC, anooparveti commented on packages/manager/apps/container/src/hooks/agreements/useAgreementsUpdate.tsx
> +  });
Same as https://github.com/ovh/manager/pull/14041/files#r1901556827 + Query key is too subtle with no info regarding the applied filters. It can easily induce errors if same key is used with different filters.
```suggestion
const usePendingAgreements = (options?: Partial<DefinedInitialDataOptions<Agreements[]>>) =>
  useQuery({
    ...options,
    queryKey: ['agreements'],
    queryFn: fetchAgreementsUpdates,
  });
```

2025-01-03 13:26 UTC, anooparveti commented on packages/manager/apps/container/src/components/AgreementsUpdateModal/AgreementsUpdateModal.component.tsx
> +    const shouldManageModal = region !== 'US' && current === ModalTypes.agreements && window.location.href !== myContractsLink;
**nitpick:** This logic is repeated in L29. I think we should extract it to function.

2025-01-03 13:28 UTC, anooparveti commented on packages/manager/apps/container/src/components/AgreementsUpdateModal/AgreementsUpdateModal.component.tsx
> +      }
**suggestion:** Instead of spreading the comments per line, it's better to comment the business requirements at the top of `useEffect`. This way we create distinction between code and comment and does not break the continuity if one wants to read only the code/comment.

2025-01-03 13:31 UTC, anooparveti commented on packages/manager/apps/container/src/identity-documents-modal/IdentityDocumentsModal.tsx
> +  }, [current, isFeatureAvailabilityLoading, availability, isKycAvailable, isProcedureStatusLoading, statusDataResponse]);
Same as https://github.com/ovh/manager/pull/14041/files#r1901783946

2025-01-07 09:29 UTC, anooparveti approved these changes

2025-01-10 10:02 UTC, MaximeBajeux approved these changes

2025-01-13 10:03 UTC, MaximeBajeux approved these changes

2025-01-13 10:29 UTC, aottr commented on packages/manager/apps/container/src/context/modals/useModals.tsx
> +const useModals = () => useContext(ModalsContext);
A custom hook should imho check if the hook is used inside the provider and otherwise throw an error. Sth like:
```js
import { useContext } from 'react';
import ModalsContext from '@/context/modals/modals.context';

const useModals = () => {
  const context = useContext(ModalsContext);
  if (!context) throw new Error('useModals must be inside ModalsProvider');
  return context;
}
export default useModals;
```

2025-01-13 10:41 UTC, aottr approved these changes

2025-01-13 12:47 UTC, merged