feat(pci.kubernetes): refacto oidc provider
ovh/manager pull request #14071
Opened 2024-11-13 13:59 UTC by Eric-ciccotti

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix TAPC-2088
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Refacto of oidc provider form

## Related

2024-11-13 16:22 UTC, SimonChaumet commented on packages/manager/apps/pci-kubernetes/src/api/data/kubernetes.ts
> +  requiredClaim?: string | null;
string undefined or null it seems like a lot isn't it ?

2024-11-13 16:22 UTC, SimonChaumet commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +      message: 'Issuer URL must use HTTPS protocol',
this needs translation ?

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +    .min(1, { message: 'common:common_field_error_required' }),
exemple of translate

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +                  'pci_projects_project_kubernetes_details_service_add_oidc_provider_field_url_extra',
add only ?

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +                'pci_projects_project_kubernetes_details_service_add_oidc_provider_description',
add only ?

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +                  'pci_projects_project_kubernetes_details_service_add_oidc_provider_field_client_id_extra',
idem

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +                  error?.response?.data?.message || error?.message || null,
error is defined

2024-11-13 16:41 UTC, ppprevost commented on packages/manager/apps/pci-kubernetes/src/pages/oidc-provider/AddOrUpdateOIDCProvider.page.tsx
> +  Required<{ issuerUrl: string; clientId: string }>;
way ==> Omit<d, 'issuerUrl'> & { issuerUrl: string };

2024-11-14 06:00 UTC, anooparveti requested changes

2024-11-14 06:00 UTC, anooparveti commented on packages/manager/apps/pci-kubernetes/src/api/hooks/useKubernetes.ts
> +import { OidcFormValues } from '@/pages/oidc-provider/AddOrUpdateOIDCProvider.page';
**nitpick:** if it needs to be reused, define it in "types" folder and use it. `pages` is not the correct folder to have reusable types.

2024-11-14 06:04 UTC, anooparveti requested changes

2024-11-14 06:04 UTC, anooparveti commented on packages/manager/apps/pci-kubernetes/src/routes.tsx
> +                  import('@/pages/oidc-provider/AddOrUpdateOIDCProvider.page'),
**nitpick:** Each page/route must be a folder according to the defined folder structure.Can you please correct it?
```suggestion
                  import('@/pages/oidc-provider/add/AddOrUpdateOIDCProvider.page'),
```

2024-11-14 06:04 UTC, anooparveti commented on packages/manager/apps/pci-kubernetes/src/routes.tsx
> +                  import('@/pages/oidc-provider/AddOrUpdateOIDCProvider.page'),
**nitpick:** Each page/route must be a folder according to the defined folder structure.Can you please correct it?
```suggestion
                  import('@/pages/oidc-provider/update/AddOrUpdateOIDCProvider.page'),
```

2024-11-18 17:01 UTC, SimonChaumet submitted a review, later dismissed

2024-11-20 06:53 UTC, anooparveti submitted a review, later dismissed

2024-11-21 16:32 UTC, SimonChaumet submitted a review, later dismissed

2024-11-22 09:21 UTC, anooparveti submitted a review, later dismissed

2024-11-28 08:49 UTC, SimonChaumet submitted a review, later dismissed

2024-11-28 10:16 UTC, selm3n approved these changes

2024-11-28 10:26 UTC, anooparveti approved these changes

2024-11-29 09:05 UTC, merged