feat(pci): remove angularJS section workflow
ovh/manager pull request #14075
Opened 2024-11-13 15:01 UTC by kqesar

ref: DTCORE-2857

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | DTCORE-2857
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-11-14 05:55 UTC, anooparveti requested changes

2024-11-14 05:55 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/workflow/workflow.module.js
**question:** Why not remove the add and workflow component?

2024-11-22 10:42 UTC, kqesar commented on packages/manager/modules/pci/src/projects/project/workflow/workflow.module.js
because it's used here https://github.com/ovh/manager/blob/master/packages/manager/modules/pci/src/projects/project/instances/add/index.js#L4

2024-12-02 15:01 UTC, frenautvh approved these changes

2024-12-05 10:20 UTC, kqesar commented on packages/manager/modules/pci/src/projects/project/workflow/workflow.module.js
@anooparveti it's ok for you ?

2024-12-05 10:24 UTC, sidlynx approved these changes

2024-12-05 10:25 UTC, anooparveti approved these changes

2024-12-06 05:43 UTC, merged