feat(quota): add quota support in page
ovh/manager pull request #14117
Opened 2024-11-15 09:23 UTC by lionel95200x

ref: TAPC-1031

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-1031
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Convert contact support modal to a page

## Related

TAPC-1031

2024-11-18 09:56 UTC, qpavy requested changes

2024-11-18 09:56 UTC, qpavy commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.module.js
> +  .run(/* @ngTranslationsInject:json ../increase-request/translations */);
Normally you don't need to inject translations here as it is already injected by parent module

2024-11-18 09:56 UTC, qpavy commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.service.js
> +import get from 'lodash/get';
Can you remove lodash and use native js ?

2024-11-18 09:56 UTC, qpavy commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.controller.js
> +    console.log(this.issueType);
to remove
```suggestion
```

2024-11-18 09:56 UTC, qpavy commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.controller.js
> +    console.log(body);
```suggestion
```

2024-11-18 10:00 UTC, tibs245 commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +import isNil from 'lodash/isNil';
It seems to me that we are now avoiding using lodash when possible

2024-11-18 10:01 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.html
> +    data-translate="pci_projects_project_quota_increase_title"
Duplicate translation.

2024-11-18 10:06 UTC, tibs245 commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.controller.js
> +    this.issueFields = get(this.issueType, 'fields', []).map((issueType) =>
If possible to not use lodash

2024-11-18 10:09 UTC, tibs245 commented on packages/manager/modules/pci/src/projects/project/quota/quota.controller.js
> +      // TODO : CHANGE href to the real page
We have a ticket for this todo or this done ?

2024-11-18 10:10 UTC, sachinrameshn requested changes

2024-11-18 10:10 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.html
> +                    Cloturer
```suggestion
```

2024-11-18 10:10 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.service.js
> +        ovhSubsidiary: get(this.coreConfig.getUser(), 'ovhSubsidiary'),
```suggestion
        ovhSubsidiary: this.coreConfig.getUser();,
```

2024-11-18 10:10 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.module.js
> +  .service('pciProjectQuotaIncreaseCredits', service)
```suggestion
  .service('pciProjectQuotaIncreaseCreditsService', service)
```

2024-11-18 10:10 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +              message: get(err, 'data.message', null),
```suggestion
              message: data?.message,
```

2024-11-18 10:15 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +    this.coreConfig = coreConfig;
Is it needed ? 
```suggestion
   
```

2024-11-18 10:15 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +    this.user = this.coreConfig.getUser();
```suggestion

```

2024-11-18 13:00 UTC, ghyenne commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +    if (this.serviceOptions === null || this.serviceOptions === undefined) {
```suggestion
    if (!this.serviceOptions) {
```

2024-11-18 13:00 UTC, ghyenne commented on packages/manager/modules/pci/src/projects/project/quota/increase-request-credits/increase-request-credits.controller.js
> +          },
```suggestion
```

2024-11-18 13:00 UTC, ghyenne commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.controller.js
> +    if (this.issueType === null || this.issueType === undefined) {
```suggestion
    if (!this.issueType) {
```

2024-11-18 13:00 UTC, ghyenne commented on packages/manager/modules/pci/src/projects/project/quota/quota.html
> +            </p>
```suggestion
            <p write-right-required data-translate="pci_projects_project_quota_protect_more">
            </p>
```
what is "write-right-required" ? is it a class for place the text to right alignement ?

2024-11-18 13:00 UTC, ghyenne commented on packages/manager/modules/pci/src/projects/project/quota/quota.html
> +                    oui-popover="{{ :: ('pci_projects_project_quota_autoscaling_help' | translate ) }}"
```suggestion
                    data-oui-popover="{{ :: 'pci_projects_project_quota_autoscaling_help' | translate  }}"
```

2024-11-18 16:35 UTC, tibs245 approved these changes

2024-11-19 07:05 UTC, qpavy approved these changes

2024-11-19 11:41 UTC, ghyenne approved these changes

2024-11-19 13:48 UTC, sachinrameshn approved these changes

2025-01-02 10:05 UTC, ghyenne approved these changes

2025-01-02 10:10 UTC, qpavy approved these changes

2025-01-03 07:48 UTC, merged