fix(kms): remove kms contact management from US
ovh/manager pull request #14145
Opened 2024-11-18 12:42 UTC by vovh

| Question         | Answer
| ---------------- | ---
| Branch?          |  `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-15856
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] ~Only FR translations have been updated~
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

## Related

2024-11-19 06:41 UTC, anooparveti requested changes

2024-11-19 06:41 UTC, anooparveti commented on packages/manager/apps/key-management-service/src/components/layout-helpers/Dashboard/GeneralInformationsTiles/BillingInformationsTile.tsx
Classic case of feature-flipping. Can you please implement it using feature-availability?

2024-11-19 13:57 UTC, vovh commented on packages/manager/apps/key-management-service/src/components/layout-helpers/Dashboard/GeneralInformationsTiles/BillingInformationsTile.tsx
Refactored to use feature-availability.

2024-11-20 09:39 UTC, rjamet-ovh approved these changes

2024-11-20 09:40 UTC, anooparveti approved these changes

2024-11-21 16:44 UTC, merged