feat(pci-quota): initialize react app
ovh/manager pull request #14153
Opened 2024-11-18 15:40 UTC by kqesar

ref: DTCORE-2865

| Question         | Answer
| ---------------- | ---
| Branch?          | `pci-quota`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-11-18 15:42 UTC, frenautvh commented on packages/manager/apps/pci-quota/package.json
> +  "version": "0.0.0",
please add description field

2024-11-18 15:44 UTC, frenautvh commented on packages/manager/apps/pci-quota/tailwind.config.js
> +    '../../../manager-react-components/src/**/*.{js,jsx,ts,tsx}',
since manager-react-component is bundled we don't need to have this config line

but could you add pci-common please ?

2024-11-18 15:44 UTC, frenautvh commented on packages/manager/apps/pci-quota/package.json
> +    "@ovh-ux/manager-config": "^0.4.0",
i think some deps are not up to date such as manager-config for example

2024-11-18 15:56 UTC, kqesar commented on packages/manager/apps/pci-quota/package.json
> +  "version": "0.0.0",
done

2024-11-19 06:38 UTC, anooparveti requested changes

2024-11-19 06:38 UTC, anooparveti commented on packages/manager/apps/pci-quota/package.json
> +    "@ovh-ux/manager-react-shell-client": "^0.8.0-alpha.0",
**nitpick:** Use the appropriate latest versions

2024-11-19 06:38 UTC, anooparveti commented on packages/manager/apps/pci-quota/package.json
> +    "@tanstack/react-query-devtools": "^5.50.1",
This should be a devdependency

2024-11-25 09:52 UTC, seven-amid approved these changes

2024-11-25 10:37 UTC, merged