fix(dedicated-server): change route name of installation-ovh
ovh/manager pull request #14164
Opened 2024-11-19 08:32 UTC by tibs245

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~Only FR translations have been updated~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

2024-11-20 06:18 UTC, anooparveti requested changes
**question:** Have you verified the fix in LABEU? Because i dont think changing the state name will resolve the issue rather you should change the url of state if your analysis is correct.

2024-11-20 07:47 UTC, tibs245 commented
> **question:** Have you verified the fix in LABEU? Because i dont think changing the state name will resolve the issue rather you should change the url of state if your analysis is correct.

Yes I tested and It's work. I don't known why this work well with this configuration but for that I need known what the CI/CD do really and how.

2024-11-20 08:52 UTC, darsene approved these changes

2024-11-25 14:28 UTC, JayBeeDe approved these changes

2024-11-25 14:32 UTC, darsene approved these changes

2025-01-10 00:00 UTC, closed without merging