feat(manager-components): disable update name button if no change
ovh/manager pull request #14169
Opened 2024-11-19 09:31 UTC by chipp972

ref: ISSUE-13807

| Question         | Answer
| ---------------- | ---
| Branch?          | `maintenance/manager-react-components-v1.x` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | ISSUE-13807 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-11-19 11:08 UTC, tibs245 approved these changes

2024-11-19 11:39 UTC, tristanwagner reviewed
tests are not passing @chipp972

2024-11-19 12:10 UTC, anooparveti requested changes
Can you fix the failing test case?

2024-11-21 09:10 UTC, pauldkn approved these changes

2024-11-21 09:57 UTC, anooparveti approved these changes

2024-11-21 17:56 UTC, merged