fix(tailwind-conf): use ODS18 var for borderR adius
ovh/manager pull request #14209
Opened 2024-11-21 09:00 UTC by tristanwagner

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-11-21 09:12 UTC, qpavy approved these changes

2024-11-21 11:42 UTC, tristanwagner reviewed
as discussed with @anooparveti this PR includes a breaking change and needs some actions before being merged so please DO NOT MERGE

2024-11-21 12:33 UTC, anooparveti requested changes
Okay with the changes. But dont merge it yet.

2024-11-21 12:59 UTC, Eric-ciccotti approved these changes

2024-11-21 13:31 UTC, SimonChaumet reviewed
I don't know if it will break other projects using ODS 17, I don't seem to reproduce anything related when dpeloying

Could you provide where we should see something different with this to tests ?

2024-11-26 15:08 UTC, tristanwagner commented
> I don't know if it will break other projects using ODS 17, I don't seem to reproduce anything related when dpeloying
> 
> Could you provide where we should see something different with this to tests ?

It should break only if you use [any tailwindcss borderRadius related classes]  with a size other than `full`, but to be honest, I'm not sure if any project use that, if so it's probably just a few

2025-01-16 10:33 UTC, tristanwagner commented
@anooparveti @aboungnaseng-ovhcloud any update on this ? please close it back if we abandon this subject ty :)

2025-02-11 07:25 UTC, anooparveti approved these changes

2025-03-28 09:58 UTC, tristanwagner commented
closing this one in favor of #16262

2025-03-28 09:58 UTC, closed without merging