fix(hub-react): adapted skeletons display to reduce cls kpi
ovh/manager pull request #14275
Opened 2024-11-26 09:54 UTC by JacquesLarique

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-15784
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ (n/a)
- [ ] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (n/a)

## Description

Reorganized skeletons in order to match as best as possible the final display of the page to reduce / enhance CLS Web Vital

## Related

2024-12-03 07:29 UTC, anooparveti requested changes

2024-12-03 07:29 UTC, anooparveti commented on packages/manager/apps/hub-react/src/components/hub-order-tracking/OrderTracking.skeleton.tsx
**nitpick:** This creates more technical debt to maintain. Lets say we have to add new content to this component, then we will have to make it in 2 components. Instead, in the same component `OrderTracking` and display the skeleton only for the dynamic content.

2024-12-20 09:46 UTC, anooparveti commented on packages/manager/apps/hub-react/src/components/hub-order-tracking/HubOrderTracking.component.tsx
> +                ></OsdsIcon>
**question:** After loading the response, 2 text box and an icon is displayed, does the skeleton match the final layout?

2025-01-06 08:28 UTC, JacquesLarique commented on packages/manager/apps/hub-react/src/components/hub-order-tracking/HubOrderTracking.component.tsx
> +                ></OsdsIcon>
Yes as both text boxes and icon are displayed inline, a signle skeleton match the final layout

2025-01-07 09:26 UTC, anooparveti approved these changes

2025-01-13 15:05 UTC, anooparveti approved these changes

2025-02-06 16:34 UTC, merged