feat(instance): replace savings plan banner on edition instance
ovh/manager pull request #14306
Opened 2024-11-27 14:54 UTC by lionel95200x

ref:TAPC-2108

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-2108
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Replace savings plan banner on edition instance

## Related

2024-11-28 09:37 UTC, tristanwagner commented on packages/manager/modules/pci/src/projects/project/instances/instance/edit/edit.controller.js
> +      console.log({ url });
console log

2025-01-03 08:01 UTC, anooparveti requested changes

2025-01-03 08:01 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/instances/instance/edit/edit.module.js
**question:** Why would you want to load unnecessary trans? Loading add trans for edit does not seem like a good design. If there's a need to duplicate the trans, try loading them from reusable place.

2025-01-09 09:07 UTC, fredericvilcot approved these changes

2025-01-09 09:32 UTC, Eric-ciccotti approved these changes

2025-01-09 10:13 UTC, anooparveti approved these changes

2025-01-10 06:03 UTC, merged