feat(dedicated): revamp my services datagrid
ovh/manager pull request #14357
Opened 2024-11-29 14:40 UTC by oalkabouss

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/my-services-revamp`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-15405 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-11-29 15:07 UTC, JacquesLarique requested changes

2024-11-29 15:07 UTC, JacquesLarique commented on packages/manager/modules/billing/src/autoRenew/autorenew.controller.js
> +    console.log('services', this.billingServices);
Cleanup needed

2024-11-29 15:07 UTC, JacquesLarique commented on packages/manager/modules/billing/src/autoRenew/autorenew.html
> +            <span
Was it requested to remove the link to the service dashboard ?

2024-12-03 08:51 UTC, JacquesLarique approved these changes

2024-12-04 09:31 UTC, MaximeBajeux approved these changes

2024-12-04 09:38 UTC, merged