feat(vrack-services): fix automatique creat vs
ovh/manager pull request #14365
Opened 2024-12-02 07:02 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix MANAGER-14440
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-03 07:10 UTC, anooparveti submitted a review, later dismissed

2024-12-03 09:05 UTC, sachinrameshn submitted a review, later dismissed

2024-12-03 09:43 UTC, qpavy approved these changes

2024-12-09 09:56 UTC, qpavy approved these changes

2024-12-09 17:05 UTC, darsene requested changes
Can you fix your commits (only one and fix french typo)

2024-12-10 08:35 UTC, darsene approved these changes

2024-12-11 08:04 UTC, fredericvilcot approved these changes

2024-12-11 13:58 UTC, merged