feat(pci-object-storage): add rclone download modal
ovh/manager pull request #14377
Opened 2024-12-02 14:16 UTC by seven-amid

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-03 13:30 UTC, kqesar commented on packages/manager/apps/pci-users/src/setupTests.ts
> +// vi.mock('@ovh-ux/manager-react-shell-client', async () => ({
Can you remove comment ?

2024-12-03 15:55 UTC, kqesar approved these changes

2024-12-05 09:41 UTC, sachinrameshn approved these changes

2024-12-05 09:41 UTC, sachinrameshn requested changes
Resolve conflicts

2024-12-10 09:07 UTC, merged