feat(nutanix): display BYOL instead of pack type in dashboard
ovh/manager pull request #14408
Opened 2024-12-03 19:03 UTC by ThibaudCrespin

ref: MANAGER-15284

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-15284 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~Only FR translations have been updated~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

## Related

2024-12-04 13:29 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/general-info/template.html
> +                            data-ng-bind="'BYOL'"
To define as a constant

2024-12-11 10:37 UTC, tibs245 requested changes

2024-12-11 10:37 UTC, tibs245 commented on packages/manager/modules/nutanix/src/dashboard/general-info/template.html
> +                    <<<<<<< HEAD
Rebase problem 🙄

2024-12-12 09:16 UTC, darsene approved these changes

2024-12-12 09:18 UTC, darsene requested changes

2024-12-12 09:18 UTC, darsene commented on packages/manager/modules/nutanix/src/dashboard/general-info/template.html
> +                                data-ng-bind="$ctrl.NUTANIX_BYOL"
constant is not binded in the controller

2024-12-12 09:23 UTC, tibs245 commented on packages/manager/modules/nutanix/src/dashboard/general-info/template.html
> +                                data-ng-bind="$ctrl.NUTANIX_BYOL"
This works ? I see no binding with the controller

2024-12-13 16:30 UTC, darsene approved these changes

2024-12-13 16:42 UTC, tibs245 approved these changes

2025-01-13 15:29 UTC, merged