fix(pci-common): fix flashing effect on shapes input component
ovh/manager pull request #14416
Opened 2024-12-04 13:41 UTC by sidlynx

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTCORE-2918
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-04 14:00 UTC, kqesar submitted a review, later dismissed

2024-12-17 08:19 UTC, frenautvh submitted a review, later dismissed

2025-01-03 07:32 UTC, anooparveti requested changes

2025-01-03 07:32 UTC, anooparveti commented on yarn.lock
`yarn.lock` changes does seem to be relevant with the changes in the PR.

2025-01-03 08:26 UTC, sidlynx commented on yarn.lock
indeed, but i haven't changed the package.json file, meaning that someone has forgot to push yarn.lock file before me, at some point someone has to update the yarn.lock file without reflecting the package.json changes, i'm not the problem, i'm trying to be the solution here, if i revert the changes, at some point another developer should push those changes

2025-01-03 10:07 UTC, anooparveti approved these changes

2025-01-03 10:28 UTC, anooparveti commented on yarn.lock
Seen in DM.

2025-01-03 10:28 UTC, merged