fix(i18n): add missing translations [CDS 3537]
ovh/manager pull request #14438
Opened 2024-12-05 11:08 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-05 12:12 UTC, anooparveti requested changes

2024-12-05 12:12 UTC, anooparveti commented on packages/manager/modules/netapp/src/order/translations/Messages_en_GB.json
**nitpick(blocking):**  Trailing comma after the last key-value pair makes it invalid JSON.
Can you please correct them?

2024-12-05 12:35 UTC, mhelhali-soufien approved these changes

2024-12-06 04:23 UTC, sachinrameshn approved these changes

2024-12-06 08:11 UTC, merged