feat(dedicated): add occ diagnostic
ovh/manager pull request #14479
Opened 2024-12-09 06:36 UTC by mhelhali-soufien

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-15807
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-10 09:52 UTC, sachinrameshn requested changes

2024-12-10 09:52 UTC, sachinrameshn commented on packages/manager/modules/cloud-connect/src/details/overview/overview.routing.js
> +        console.log(data);
```suggestion
```

2024-12-10 09:59 UTC, sachinrameshn commented on packages/manager/modules/cloud-connect/src/details/overview/template.html
> +                                    data-ng-click="$ctrl.goToTags()"
Is this a valid call ?

2024-12-19 09:32 UTC, qpavy requested changes

2024-12-19 09:32 UTC, qpavy commented on packages/manager/modules/cloud-connect/src/details/overview/components/datacenter-extra/template.html
> +                                data-on-click="$ctrl.testBgpPeering()({ popConfigId: $ctrl.datacenter.datacenterId , dcConfigId: $ctrl.datacenter.id, isExtar: true, extraConfigId: extraConfig.id })"
- IMO popConfigId should not be datacenterId but Pop id.
- isExtar -> isExtra

2024-12-19 09:32 UTC, qpavy commented on packages/manager/modules/cloud-connect/src/details/overview/template.html
> +                                    data-on-click="$ctrl.goToTestBGPPeeringPage({popConfigId: $ctrl.datacenter.datacenterId , dcConfigId: $ctrl.datacenter.id })"
popConfigId should not be datacenterId but Pop ID

2024-12-24 11:18 UTC, qpavy requested changes

2024-12-24 11:18 UTC, qpavy commented on packages/manager/modules/cloud-connect/src/details/overview/components/datacenter-extra/template.html
> +                                data-on-click="$ctrl.checkBgpPeering()({ popConfigId: $ctrl.datacenter.popConfigId , dcConfigId: $ctrl.datacenter.id, isExtar: true, extraConfigId: extraConfig.id })"
```suggestion
                                data-on-click="$ctrl.checkBgpPeering({ popConfigId: $ctrl.datacenter.popConfigId , dcConfigId: $ctrl.datacenter.id, isExtar: true, extraConfigId: extraConfig.id })"
```

2024-12-24 11:18 UTC, qpavy commented on packages/manager/modules/cloud-connect/src/details/overview/components/datacenter-extra/datacenter-extra.component.js
> +    checkBgpPeering: '&',
```suggestion
    checkBgpPeering: '<',
```

2024-12-31 09:12 UTC, qpavy approved these changes

2025-01-02 09:48 UTC, chipp972 approved these changes

2025-01-03 05:21 UTC, sachinrameshn approved these changes

2025-01-08 06:19 UTC, merged