fix(veeam-backup): fix space unit displayed
ovh/manager pull request #14508
Opened 2024-12-09 16:23 UTC by pauldkn

ref: MANAGER-16236

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/vcd-veeam-postga`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | fix/MANAGER-16236
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-10 08:44 UTC, chipp972 approved these changes

2024-12-12 09:11 UTC, darsene requested changes

2024-12-12 09:11 UTC, darsene commented on packages/manager/apps/veeam-backup/public/translations/dashboard/Messages_fr_FR.json
> +  "teraoctet": "To"
keys should be in english

2024-12-12 09:26 UTC, darsene approved these changes

2024-12-18 14:10 UTC, tibs245 approved these changes

2024-12-18 14:10 UTC, darsene submitted a review, later dismissed

2024-12-18 14:12 UTC, chipp972 approved these changes

2025-01-07 10:13 UTC, tibs245 approved these changes

2025-01-07 10:21 UTC, ThibaudCrespin approved these changes

2025-01-10 11:25 UTC, merged