feat(pci-object-storage): download object implementation
ovh/manager pull request #14568
Opened 2024-12-13 10:13 UTC by seven-amid

ense          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2024-12-16 10:10 UTC, kqesar approved these changes

2024-12-17 09:06 UTC, tibs245 requested changes

2024-12-17 09:06 UTC, tibs245 commented on packages/manager/apps/pci-object-storage/public/translations/objects/Messages_de_DE.json
> +  "pci_projects_project_storages_containers_container_object_error_download": "Beim Download des Objekts ist ein Fehler aufgetreten: {{ message }}.",
The translation is provided from CMT ?

2024-12-17 09:06 UTC, tibs245 commented on packages/manager/apps/pci-object-storage/src/pages/objects/container/object/download/Download.page.tsx
> +  return <></>;
I not agree this conception. Can you speak it together ?

2024-12-17 09:06 UTC, tibs245 commented on packages/manager/apps/pci-object-storage/src/api/data/objects.ts
> +};
Use hook "use..." and maybe use mutation

2024-12-17 09:06 UTC, tibs245 commented on packages/manager/apps/pci-object-storage/package.json
> +    "zustand": "^4.5.5",
Why this is added but not used ?

2024-12-19 13:39 UTC, closed without merging