feat(pci.instances): open auto backup option  to LZ regions
ovh/manager pull request #14605
Opened 2024-12-17 07:51 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `TAPC-1429`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-1275
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2024-12-17 16:34 UTC, darsene commented on packages/manager/modules/pci/src/projects/project/instances/instance/instance.html
> +                        && ($ctrl.instance.isLocalZone ? $ctrl.isInstanceLocalZoneAutoBackupAvailable : true)
```suggestion
                        && (!$ctrl.instance.isLocalZone || $ctrl.isInstanceLocalZoneAutoBackupAvailable)
```

2024-12-17 16:34 UTC, darsene commented on packages/manager/modules/pci/src/projects/project/instances/instances.html
> +                    && ($row.isLocalZone ? $ctrl.isInstanceLocalZoneAutoBackupAvailable : true)
```suggestion
                    && (!$row.isLocalZone || $ctrl.isInstanceLocalZoneAutoBackupAvailable)
```

2024-12-19 14:54 UTC, SimonChaumet approved these changes
Good except other comments

2025-01-30 09:56 UTC, darsene commented on packages/manager/modules/pci/src/projects/project/instances/add/add.html
> +        data-valid="$ctrl.automatedBackup.selected ? !!$ctrl.automatedBackup.schedule : true"
```suggestion
        data-valid="!$ctrl.automatedBackup.selected || !!$ctrl.automatedBackup.schedule"
```

2025-01-30 09:57 UTC, darsene requested changes
Lint job is KO

2025-02-13 11:06 UTC, closed without merging