Feat/ips region selector
ovh/manager pull request #14687
Opened 2024-12-19 17:23 UTC by chipp972

| Question         | Answer
| ---------------- | ---
| Branch?          | `project/ip-revamp` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-16479 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-12-20 06:37 UTC, anooparveti requested changes

2024-12-20 06:37 UTC, anooparveti commented on packages/manager/apps/ips/public/translations/region-selector/Messages_fr_FR.json
Most of the translations are already from MRC. Avoid duplicating them.

2024-12-20 07:03 UTC, anooparveti requested changes

2024-12-20 07:03 UTC, anooparveti commented on packages/manager/apps/ips/src/components/RegionSelector/regionSelector.utils.ts
> +export const isUs = (region: string) => region.includes('us-');
**suggestion:** 
```suggestion
export const isRegionInEu = (region: string) =>
  region.includes('eu-') || region.includes('labeu-');

export const isRegionInCa = (region: string) => region.includes('ca-');

export const isRegionInUs = (region: string) => region.includes('us-');
```

2024-12-20 08:23 UTC, chipp972 commented on packages/manager/apps/ips/src/components/RegionSelector/regionSelector.utils.ts
> +export const isUs = (region: string) => region.includes('us-');
done fixed

2024-12-20 08:23 UTC, chipp972 commented on packages/manager/apps/ips/src/components/RegionSelector/RegionSelector.spec.tsx
> +    ({ regionList, disabledFilters }) => {
done

2024-12-20 08:26 UTC, chipp972 commented on packages/manager/apps/ips/public/translations/region-selector/Messages_fr_FR.json
Actually the region component does not provide these translations
The country and city names are in the same translation key so we can't use this component to implement the new region selector

2024-12-20 14:24 UTC, qpavy approved these changes

2025-01-09 14:40 UTC, mhelhali-soufien approved these changes

2025-01-20 14:23 UTC, merged