fix(vrack-services): content fixes
ovh/manager pull request #14697
Opened 2024-12-20 14:05 UTC by chipp972

ref: MANAGER-16527

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-16527 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2024-12-23 08:57 UTC, sachinrameshn approved these changes

2024-12-23 14:11 UTC, qpavy approved these changes

2025-01-23 14:31 UTC, qpavy requested changes

2025-01-23 14:31 UTC, qpavy commented on packages/manager/apps/vrack-services/public/translations/vrack-services/create/Messages_pl_PL.json
> +  "modalDescriptionLine4": "Zleciłeś utworzenie vRacka podczas aktywacji vRack Services.",
```suggestion
  "modalDescriptionLine4": "Zleciłeś utworzenie vRack podczas aktywacji vRack Services.",
```

2025-01-23 14:31 UTC, qpavy commented on packages/manager/modules/vrack/src/order/translations/Messages_pl_PL.json
> +  "vrack_order_error": "Wystąpił błąd podczas zamawiania vRacka <br> {{message}} <br> request-id: {{queryId}}"
```suggestion
  "vrack_order_error": "Wystąpił błąd podczas zamawiania vRack <br> {{message}} <br> request-id: {{queryId}}"
```

2025-02-18 09:30 UTC, qpavy approved these changes

2025-02-28 07:15 UTC, merged