feat(pci-public-ip): Public IP 3AZ beta
ovh/manager pull request #14708
Opened 2024-12-23 12:43 UTC by Tsiorifamonjena

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-2309
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

- TAPC-2309

## Related

2024-12-27 08:35 UTC, ppprevost requested changes

2024-12-27 08:35 UTC, ppprevost commented on packages/manager/apps/pci-public-ip/src/pages/order/steps/FloatingSteps.tsx
> +        {form.floatingRegion?.type === 'region-3-az' && (
use a const

2024-12-27 08:39 UTC, sachinrameshn commented on packages/manager/apps/pci-public-ip/src/api/hooks/useData.ts
> +      instance.ipAddresses?.some((ip) => ip.type === 'public'),
Can you please use const here for 'public'

2025-01-03 16:07 UTC, ppprevost requested changes

2025-01-03 16:07 UTC, ppprevost commented on packages/manager/apps/pci-public-ip/src/api/types.ts
> +  '3AZ' = 'region-3-az',
why '3AZ' instead of 3AZ

2025-01-06 08:55 UTC, ppprevost commented on packages/manager/apps/pci-public-ip/src/api/types.ts
> +  '3AZ' = 'region-3-az',
ONE_AZ = 'region',
THREE_AZ = 'region-3-az', ?

2025-01-06 10:12 UTC, Tsiorifamonjena commented on packages/manager/apps/pci-public-ip/src/api/types.ts
> +  '3AZ' = 'region-3-az',
I see the point but I am not sur it's the conventional name for the product. I prefer to leave it like that juste for convetion and understanding of the product if it's not a problem for you

2025-01-17 14:21 UTC, fredericvilcot commented on packages/manager/apps/pci-public-ip/src/pages/order/steps/FloatingSteps.tsx
> +  const pciCommonProperties = usePCICommonContextFactory({ has3AZ });
Name should be agnostic from library :)

As an example, if you are using tanstack query provider, you will not give as value something like `const tanstakQueryContext` ;)

2025-01-17 14:21 UTC, fredericvilcot commented on packages/manager/apps/pci-public-ip/src/pages/order/steps/FloatingSteps.tsx
> +              setForm({ ...form, floatingRegion: undefined });
Please, make a dedicated memoized function to lighten JSX part

2025-01-21 10:41 UTC, SimonChaumet commented on packages/manager/apps/pci-public-ip/src/pages/order/steps/FloatingSteps.tsx
> +  }, []);
There are some dependencies missing like form

2025-01-21 10:51 UTC, fredericvilcot commented on packages/manager/apps/pci-public-ip/src/pages/order/steps/FloatingSteps.tsx
> +    setForm({ ...form, floatingRegion: undefined });
```suggestion
    setForm({ ...form, floatingRegion: null });
```

2025-01-21 14:33 UTC, fredericvilcot approved these changes
👍🏻

2025-01-24 09:07 UTC, sachinrameshn approved these changes

2025-01-29 16:24 UTC, merged