fix(svp): design issue after bump ods18
ovh/manager pull request #14741
Opened 2024-12-31 08:45 UTC by lionel95200x

| Question         | Answer
| ---------------- | ---
| Branch?          | `tapc-2456` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #TAPC-2456
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Update some design on ODS 18

## Related

2025-01-02 14:00 UTC, ppprevost requested changes

2025-01-03 10:27 UTC, Eric-ciccotti approved these changes

2025-01-03 10:27 UTC, Eric-ciccotti commented on packages/manager/apps/pci-savings-plan/src/components/SimpleTile/SimpleTile.tsx
>      className={`flex items-center flex-col justify-center w-1/2 shrink-0 md:shrink md:w-1/4  mr-5 text-center p-3 ${
```
const baseClass = "flex items-center flex-col justify-center w-1/2 shrink-0 md:shrink md:w-1/4 mr-5 text-center p-3";
const cursorClass = onClick ? 'cursor-pointer' : 'cursor-default';
const activeClass = isActive ? 'bg-[--ods-color-blue-100] border-[--ods-color-blue-600]' : '';

into the className => `${baseClass} ${cursorClass} ${activeClass} ${className}`; 
```

2025-01-03 10:30 UTC, Eric-ciccotti commented on packages/manager/apps/pci-savings-plan/src/components/SimpleTile/SimpleTile.tsx
>      className={`flex items-center flex-col justify-center w-1/2 shrink-0 md:shrink md:w-1/4  mr-5 text-center p-3 ${
a little bit hard to read

2025-01-03 10:58 UTC, ppprevost approved these changes

2025-01-03 11:00 UTC, merged

2025-01-03 14:41 UTC, ppprevost commented on packages/manager/apps/pci-savings-plan/src/components/SimpleTile/SimpleTile.tsx
>      className={`flex items-center flex-col justify-center w-1/2 shrink-0 md:shrink md:w-1/4  mr-5 text-center p-3 ${
a great idea is to use clsx