fix(domain): dynhost tab display
ovh/manager pull request #3532
Opened 2020-08-28 13:16 UTC by lizardK

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-18229
| License          | BSD 3-Clause

## Description

Fix dynhost tab display 

ref: DTRSD-18229

Signed-off-by: Cyril Biencourt <cyril.biencourt@ovhcloud.com>

2020-08-28 13:25 UTC, frenautvh requested changes

2020-08-28 13:25 UTC, frenautvh commented on packages/manager/apps/web/client/app/domain/domain.routing.js
>    zoneOption: /* @ngInject */ ($http, domainName) =>
it's not zoneOption anymore then it's just zone :)

2020-08-28 13:27 UTC, frenautvh approved these changes

2020-08-28 15:32 UTC, marie-j approved these changes

2020-08-31 06:49 UTC, JeremyDec approved these changes

2020-08-31 07:29 UTC, merged