Feat/kube anti-affinity
ovh/manager pull request #3860
Opened 2020-10-16 13:16 UTC by radireddy

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-5524
| License          | BSD 3-Clause

## Description

Added anti-affinity support while creating node pool and kube cluster. Refer to jira MANAGER-5524 for more details.

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/add/add.controller.js
> +    if (this.cluster.nodePool.nodeCount > 5) {
5 could be stored as a constant

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/add/add.html
> +        data-header="{{:: 'kubernetes_add_billing_anti_affinite_title' | translate }}"
```suggestion
        data-header="{{:: 'kubernetes_add_billing_anti_affinity_title' | translate }}"
```

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/components/anti-affinity/anti-affinity.controller.js
> +      omit(this.nodePool, ['maxNodes']);
No need to set a new value ? Im' not sure `omit` mutates the object (https://lodash.com/docs/4.17.15#omit)

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/components/anti-affinity/anti-affinity.html
> +    disabled="$ctrl.nodePool.nodeCount > 5"
The `5` value is repeated quite a few times, a constant or exposing it through a method like `getMaxNodeCount()` would be better to maintain

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/add/add.html
> +        data-header="{{:: 'kube_add_billing_anti_affinite_title' | translate }}"
```suggestion
        data-header="{{:: 'kube_add_billing_anti_affinity_title' | translate }}"
```

2020-10-19 06:43 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/node-pool.html
> +                <i class="oui-icon oui-icon-check" aria-hidden="true"></i>
```suggestion
                <span class="oui-icon oui-icon-check" aria-hidden="true"></span>
```
Also missing a `span` to describe the value

2020-10-20 07:28 UTC, JeremyDec approved these changes

2020-10-20 13:05 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/node-pool.html
> +                <span class="oui-icon oui-icon-check" aria-hidden="true"></span>
A description should be added to describe the icons. We can use `sr-only` class if we only want it diplayed for screen readers

2020-10-20 13:06 UTC, marie-j requested changes

2020-10-20 13:06 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/node-pool.html
> +                <span class="oui-icon oui-icon-check" aria-hidden="true"></span>
A description should be added to describe the icons. We can use `sr-only` class if we only want it diplayed for screen readers

2020-10-21 08:35 UTC, JeremyDec requested changes

2020-10-21 08:35 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/nodes/add/translations/Messages_fr_FR.json
> +  "kube_nodes_add_anti_affinity_active_info": "L'anti-affinité est activée : le pool de nœuds ne pourra pas contenir plus de {{ maxNodes }} noeuds"
```suggestion
  "kube_nodes_add_anti_affinity_active_info": "L'anti-affinité est activée : le pool de nœuds ne pourra pas contenir plus de {{ maxNodes }} nœuds"
```

2020-10-23 12:09 UTC, ovh-cds commented
CDS Report build#16481.0 ✘  
* 
  * Build ✘

2020-11-09 07:26 UTC, antleblanc requested changes
@radireddy Could you please signing following commit: 28e2d93f1e7e1ca1733b5d20d43d4e727249baa8

2020-11-12 17:50 UTC, antleblanc approved these changes

2020-11-12 17:51 UTC, merged