feat(dedicated): add technical details tile to dashboard
ovh/manager pull request #3981
Opened 2020-11-05 08:02 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | internal MANAGER-5537
| License          | BSD 3-Clause

## Description

add technical details tile to bare metal cloud dashboard

draft : missing some api data

2020-11-06 07:02 UTC, radireddy approved these changes

2020-11-06 09:04 UTC, frenautvh commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/technical-details/technical-details.html
> +        <oui-tile-description> </oui-tile-description>
template is not done yet, i'll complete it when i'll have all the needed data from api (it's still a draft)

2020-12-21 09:39 UTC, cbourgois approved these changes

2020-12-21 09:39 UTC, cbourgois commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/technical-details/technical-details.html
> +    <!--
Should we keep-it ?

2020-12-21 09:39 UTC, cbourgois commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/dashboard.html
> +                world-part="$ctrl.worldPart"
Or use `Environment` in the component ?

2020-12-22 09:52 UTC, antleblanc requested changes

2020-12-22 09:52 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/technical-details/translations/Messages_fr_FR.json
> +  "dedicated_server_dashboard_technical_details_cpu_frequency_unit": "Ghz",
```suggestion
  "dedicated_server_dashboard_technical_details_cpu_frequency_unit": "GHz",
```

2020-12-22 09:52 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/technical-details/translations/Messages_fr_FR.json
> +  "dedicated_server_dashboard_technical_details_ram_frequency_unit": "Mhz",
```suggestion
  "dedicated_server_dashboard_technical_details_ram_frequency_unit": "MHz",
```

2021-01-20 12:00 UTC, Heiiji commented
i have merge my modification approved on https://github.com/ovh/manager/pull/4188

2021-01-20 13:32 UTC, frenautvh commented
closed in favor of : https://github.com/ovh/manager/pull/4313

2021-01-20 13:32 UTC, closed without merging