fix(dedicated-cloud): switch datastore from hourly to monthly
ovh/manager pull request #4000
Opened 2020-11-11 10:28 UTC by radireddy

use exact plan code while getting plan details from datastore service options

ref #DTRSD-23106

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-23106
| License          | BSD 3-Clause

## Description

Use exact plan code while getting plan details from datastore service options

2020-11-11 12:09 UTC, antleblanc requested changes
Could you please use signing commit.

2020-11-12 09:21 UTC, Heiiji approved these changes

2020-11-12 11:10 UTC, marie-j approved these changes

2020-11-13 08:43 UTC, JeremyDec submitted a review, later dismissed

2020-11-13 08:54 UTC, cbourgois approved these changes

2020-11-13 09:09 UTC, antleblanc approved these changes

2020-12-09 08:38 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/resource/upgrade/upgrade.controller.js
> +    console.log('fetchCatalog');
Probably missed

2021-01-19 07:27 UTC, ovh-cds commented
CDS Report translator-push#13869.0 ✘  
* 
  * push ✘

2021-02-09 07:48 UTC, antleblanc commented
Rewriting history (first commit)

2021-02-09 07:52 UTC, antleblanc commented
History has been rewrite successfully.

2021-02-09 08:08 UTC, antleblanc approved these changes

2021-02-09 08:13 UTC, merged