fix(bare-metal-cloud): fix cloud connect issues
ovh/manager pull request #4069
Opened 2020-11-20 11:02 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-22072 Fix #DTRSD-22065
| License          | BSD 3-Clause

## Description

fix translation issues
fix service key regenerate disable button

2020-11-20 13:24 UTC, cbourgois requested changes

2020-11-20 13:24 UTC, cbourgois commented on packages/manager/modules/cloud-connect/src/cloud-connect.class.js
> +    });
Please avoid to use `lodash`
```suggestion
    this.validServiceKey = serviceKeys.some(({status}) => [STATUS.ACTIVE, STATUS.DOING, STATUS.TO_CHECK].includes(status));
    this.serviceKeys = serviceKeys;
```

2020-11-23 07:31 UTC, marie-j reviewed
The scope of the commit `bare-metal-cloud` is not following any module/app architecture. As all the changes are located in the occ module maybe we can split into two commits
`fix: update wording` and `fix: update service key check`

2020-11-23 07:31 UTC, marie-j commented on packages/manager/modules/cloud-connect/src/cloud-connect.class.js
> +    set(this, 'validServiceKey', false);
```suggestion

```

2020-11-23 09:22 UTC, JeremyDec submitted a review, later dismissed

2020-11-23 13:28 UTC, cbourgois approved these changes

2020-12-11 09:48 UTC, ovh-cds commented
CDS Report translator-push#13201.0 ✘  
* 
  * push ✘

2020-12-11 09:55 UTC, ovh-cds commented
CDS Report translator-push#13201.1 ✘  
* 
  * push ✘

2020-12-16 09:04 UTC, antleblanc submitted a review, later dismissed

2020-12-16 09:12 UTC, antleblanc commented
Rebasing on `develop` branch.

2020-12-16 09:21 UTC, antleblanc commented
Rebased successfully on `develop` branch.

2020-12-16 09:49 UTC, antleblanc approved these changes

2020-12-16 09:49 UTC, merged