fix(i18n): add missing translations [CDS 719]
ovh/manager pull request #4192
Opened 2020-12-21 05:24 UTC by radireddy

Signed-off-by: CDS Translator Agent <opensource@ovh.net>

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-25778
| License          | BSD 3-Clause

## Description

The text was not translated properly from French to English.

2020-12-21 05:45 UTC, varun257 submitted a review, later dismissed

2020-12-21 08:50 UTC, cbourgois submitted a review, later dismissed

2020-12-21 13:02 UTC, mohammed-zahaf approved these changes

2020-12-22 08:22 UTC, antleblanc requested changes
@radireddy Changes looks good to me.
In addition, could you please apply changes also into these files:
- packages/manager/apps/dedicated/client/app/components/dedicated-cloud/datacenter/backup/translations/Messages_fi_FI.json
- packages/manager/apps/dedicated/client/app/components/dedicated-cloud/datacenter/backup/translations/Messages_lt_LT.json
Thank you!

2020-12-22 09:53 UTC, Jisay approved these changes

2020-12-22 12:42 UTC, antleblanc commented
Applying changes.

2020-12-22 12:43 UTC, antleblanc commented
Changes has been applied.

2020-12-22 12:44 UTC, antleblanc approved these changes

2020-12-22 13:09 UTC, merged