feat(web-cloud): add tracking to termination
ovh/manager pull request #4196
Opened 2020-12-22 10:24 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-5850
| License          | BSD 3-Clause

## Description

add at internet tracking to termination of services

2020-12-22 15:51 UTC, antleblanc submitted a review, later dismissed

2020-12-22 16:26 UTC, JeremyDec approved these changes

2020-12-22 16:29 UTC, cbourgois submitted a review, later dismissed

2021-01-06 07:39 UTC, marie-j commented on packages/manager/apps/web/client/app/email-domain/general-informations/email-domain-general-informations.controller.js
> +      this.$window.location = this.urls.delete;
Maybe the element listening to the onClick event should be a link in that case

2021-01-06 07:39 UTC, marie-j commented on packages/manager/modules/exchange/src/header/header.service.js
> +    this.atInternet = atInternet;
doesn't seem needed 
```suggestion

```

2021-02-23 07:24 UTC, JeremyDec approved these changes

2021-03-02 07:40 UTC, marie-j commented
I think commit scopes should represent file architecture and not what we expose to customer to have a coherent technical changelog 
`feat(web): add termination tracking` and as only web files are impacted maybe we can just stick with `feat: add termination tracking`

2021-03-09 08:11 UTC, JeremyDec requested changes

2021-03-09 08:11 UTC, JeremyDec commented on packages/manager/modules/exchange/src/header/header.controller.js
> +    switch (this.Exchange.value.domain.split('-')[0]) {
**nitpick**
The switch could be simplified by setting the name of the hit into each case, and after call the two types of hit

2021-03-09 08:11 UTC, JeremyDec commented on packages/manager/modules/overthebox/src/overthebox/details/overTheBox-details.controller.js
> +      });
This hits should not be done into a method which test if the action button is displayed. (On `resiliate` or `$onInit` maybe ?)

2021-03-17 08:07 UTC, marie-j commented on packages/manager/apps/dedicated/client/app/license/license.controller.js
> +        name: 'dedicated::license::delete',
Not possible to rename tracking name in the routing or when entering the page ?

2021-03-17 08:07 UTC, marie-j commented on packages/manager/apps/dedicated/client/app/license/license.html
> +                    on-click="setAction('delete/license-delete', { 'license': $row }); trackDelete()"
Maybe a function should be created to avoid chaining function calls in `on-click`

2021-03-17 08:07 UTC, marie-j commented on packages/manager/apps/telecom/src/app/telecom/telephony/line/management/terminate/terminate.controller.js
> +    console.log('bulk terminate');
```suggestion
```

2021-03-17 08:07 UTC, marie-j commented on packages/manager/modules/exchange/src/header/header.controller.js
> +  removeExchangeDialog() {
```suggestion
  removeExchangeDialog() {
   const exchangeType = this.wucExchange.value.domain.split('-')[0];
   const category = ['private', 'exchange'].includes(exchangeType) ? 'dedicated' : exchangeType;
   atInternet.trackClick({
     name: `web::microsoft::exchange::${category}::delete`,
     type: 'action'
     });
```

2021-04-16 12:14 UTC, antleblanc requested changes
Hi @varun257!

In addition to @marie-j comments, could you please resolve existing conflicts?

Thank you!

2022-02-25 08:28 UTC, closed without merging

2022-02-25 08:29 UTC, varun257 commented
Not relevant anymore