AI Training: add job resubmit feature
ovh/manager pull request #4523
Opened 2021-03-11 10:24 UTC by CLevasseur

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

## Description

This PR is related to the following jira task in AI Training project:

https://projects.dsi.ovh/browse/MLS-1082: add a resubmit button in ai training dashboard, ai training job list, and ai training job info pages, to launch a new job with the same specification as the one selected

https://projects.dsi.ovh/browse/MLS-1178: some fields were not displayed properly when stopping a job in the dedicated modal

https://projects.dsi.ovh/browse/MLS-1117: add a dropdown in the shared registry modal to change URLs depending on the selected region

https://projects.dsi.ovh/browse/MLS-1164: volume permission was Read &amp Write instead of Read & Write

2021-03-12 13:18 UTC, antleblanc requested changes
Hi @CLevasseur and thank you for your contribution on this project!

According to our [CONTRIBUTING.md](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations) file, could you please avoid adding updates on translation's
files except on `**/Messages_fr_FR.json`?

Thank you!

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/dashboard/dashboard.module.js
> +  .run(/* @ngTranslationsInject:json ./translations ../jobs/translations */);
We tend to scope translations into its own AngularJS module (here: `ovhManagerPciTrainingDashboard`).

Can you avoid relying on translations located in parents translation folders?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/info/info.module.js
> +  .run(/* @ngTranslationsInject:json ./translations ../translations */);
Can you avoid relying on translations located in parents translation folders?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/kill/kill.module.js
> +  .run(/* @ngTranslationsInject:json ./translations ../translations */);
Can you avoid relying on translations located in parents translation folders?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/resubmit/resubmit.module.js
> +  .run(/* @ngTranslationsInject:json ../translations */);
Can you avoid relying on translations located in parents translation folders?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/resubmit/resubmit.routing.js
> +        return `job run --from ${jobId}`;
Does it make sense to rely on this info from routing part here?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/command_line_converter.js
> +  // readUser, sshpublickeys,
These comments are needed?

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/dashboard/registry/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_registry_select_region": "Sélectionnez la région que vous souhaitez utiliser:",
```suggestion
  "pci_projects_project_training_registry_select_region": "Sélectionnez la région que vous souhaitez utiliser :",
```

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/dashboard/registry/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_registry_docker_registry": "Docker Registry",
Are you expecting that `Docker Registry` to be translated in other languages?
If not, then you should remove it from here.

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/resubmit/resubmit.html
> +<code class="ng-binding">{{:: 'pci_projects_project_training_parter_cli_name' | translate }} {{ $ctrl.getResubmitCliCommand() }} </code></pre>
Following `ng-binding` class can be removed (and remove extra white space).

```suggestion
<code>{{:: 'pci_projects_project_training_parter_cli_name' | translate }} {{ $ctrl.getResubmitCliCommand() }}</code></pre>
```

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_jobs_id": "Job ID",
Are you expecting that `Job ID` to be translated in other languages?
If not, then you should remove it from here.

2021-03-12 13:18 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_jobs_resubmit_error": "Une erreur s'est produite durant le relancement du job: {{ message }}"
```suggestion
  "pci_projects_project_training_jobs_resubmit_error": "Une erreur s'est produite durant le relancement du job : {{ message }}"
```

2021-03-15 13:26 UTC, christophe-rannou submitted a review, later dismissed

2021-03-22 08:44 UTC, CLevasseur commented on packages/manager/modules/pci/src/projects/project/training/jobs/kill/kill.html
> +            <oui-tile-definition data-term="Job ID">
@antleblanc suggested that this text might not be translated. Also, this translation is available on parent translations which I can't use in a child module if I follow the guidelines. I decided it wasn't worth it to duplicate that translation which might not be translated anyway

2021-03-22 09:25 UTC, marie-j commented
Manager ref for QA follow up: MANAGER-6617

2021-04-01 05:58 UTC, antleblanc submitted a review, later dismissed

2021-04-02 14:26 UTC, CLevasseur commented on packages/manager/modules/pci/src/projects/project/training/job.service.js
> +    if (Object.prototype.hasOwnProperty.call(jobSpec, 'shutdown')) {
eslint does not accept the use of this method when I try to commit this change, that's why I am using Object.prototype.hasOwnProperty instead

2021-04-13 08:10 UTC, antleblanc requested changes
@CLevasseur Test pipeline failed.

Coudl you please have a look? Seems to be a code format error.
Thank you!

2021-04-13 08:52 UTC, antleblanc approved these changes

2021-04-13 09:38 UTC, merged

2021-04-26 05:33 UTC, radireddy commented on packages/manager/modules/pci/src/projects/project/training/dashboard/registry/registry.html
> +            <option ng-repeat="region in $ctrl.regions" ng-value="region"
can you please use track by in ng-repeat

2021-04-26 05:33 UTC, radireddy commented on packages/manager/modules/pci/src/projects/project/training/dashboard/registry/registry.html
> +            Docker Registry
no need to translate this text?