feat(project.kubernetes.details.service): add maintenance status
ovh/manager pull request #4724
Opened 2021-04-08 15:51 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-6631
| License          | BSD 3-Clause

## Description

Aims of this PR is to add a new Kube status: `MAINTENANCE`
Scope: WW

### :flags: Translations

- [] TRANS-xxxxx

2021-04-09 13:30 UTC, cbourgois requested changes

2021-04-09 13:30 UTC, cbourgois commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/service/translations/Messages_fr_FR.json
> +  "kube_service_cluster_status_MAINTENANCE": "En cours de maintenanace",
```suggestion
  "kube_service_cluster_status_MAINTENANCE": "En cours de maintenance",
```

2021-04-12 08:01 UTC, JeremyDec approved these changes

2021-04-12 08:26 UTC, cbourgois submitted a review, later dismissed

2021-04-13 06:40 UTC, antleblanc submitted a review, later dismissed

2021-04-13 07:20 UTC, marie-j submitted a review, later dismissed

2021-04-16 11:10 UTC, antleblanc commented
Retrieving translations.

2021-04-16 11:11 UTC, antleblanc commented
Translations has been retrieved successfully.

2021-04-16 11:12 UTC, antleblanc approved these changes

2021-04-16 11:13 UTC, merged