Feature/account sidebar fragment
ovh/manager pull request #4744
Opened 2021-04-12 13:59 UTC by zakariasahmane

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| License          | BSD 3-Clause

## Description

Create Account Sidebar fragment. Currently still missing logic for payment-mean.

2021-04-12 14:07 UTC, zakariasahmane commented on packages/manager/fragments/account-sidebar/src/components/AccountSidebarPayment.vue
> +</script>
This whole component is missing payment logic. Working on it.

2021-04-23 12:33 UTC, cbourgois requested changes

2021-04-23 12:33 UTC, cbourgois commented on packages/manager/fragments/account-sidebar/src/components/AccountSidebar.vue
> +import { Environment } from '@ovh-ux/manager-config';
`Environment` is no more a singleton on `develop`. With React we use Context (https://reactjs.org/docs/context.html) to make `environment` available everywhere.

2021-04-23 12:33 UTC, cbourgois commented on packages/manager/fragments/account-sidebar/src/main.ts
> +registerFragment('account-sidebar').then(({ parent, config }: { parent: string; config: any }) => {
`registerFragment` signature changed in `develop`: `config` object is replaced by `environment`.

2021-12-29 08:59 UTC, closed without merging