Feat/bm components support
ovh/manager pull request #4992
Opened 2021-05-24 06:46 UTC by radireddy

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/baremetal-server-components
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-6936
| License          | BSD 3-Clause

## Description

Add reusable support tile component.

2021-05-24 06:57 UTC, frenautvh commented
is it planned to refactor this part using this module ? https://github.com/ovh/manager/blob/develop/packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/technical-details/technical-details.controller.js

2021-05-24 06:57 UTC, frenautvh approved these changes

2021-05-24 06:58 UTC, frenautvh requested changes
mixing commits with https://github.com/ovh/manager/pull/4991

2021-05-26 11:05 UTC, varun257 commented on packages/manager/modules/bm-server-components/src/technical-details/controller.js
> +    const ramSize = ram.size ? `${ram.size} GB` : '';
`GB` should be translated here

2021-05-26 11:09 UTC, varun257 commented on packages/manager/modules/bm-server-components/src/technical-details/controller.js
> +        capacity = `${Math.round((100 * capacity) / 1000, 2) / 100} TB`;
`TB` needs translation

2021-05-26 11:09 UTC, varun257 commented on packages/manager/modules/bm-server-components/src/technical-details/controller.js
> +        capacity = `${capacity} GB`;
Same as above ?

2021-06-01 09:54 UTC, ganeshkumar1989 approved these changes

2021-06-01 09:55 UTC, ganeshkumar1989 requested changes
Seems to contain commits other than the intended ones...

2021-06-01 11:35 UTC, merged