fix(*): remove less tilde imports
ovh/manager pull request #5015
Opened 2021-05-28 07:05 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | internal MANAGER-7041
| License          | BSD 3-Clause

## Description

remove @ovh-ux/rollup-plugin-less-tilde-importer usage (~ import syntax in less files)as the dependency is deprecated
also the benefits is to make our stack simpler and more respectful of standards

2021-05-28 07:21 UTC, cbourgois approved these changes

2021-05-28 07:21 UTC, cbourgois commented on yarn.lock
> -"@ovh-ux/rollup-plugin-less-tilde-importer@^1.0.3":
👍

2021-05-28 07:27 UTC, antleblanc commented on packages/manager/tools/component-rollup-config/src/index.ts
> -        lessTildeImporter(pluginsOpts.lessTildeImporter),
Breaking Changes, isn't it?

2021-05-28 13:29 UTC, zakariasahmane approved these changes

2021-05-31 09:02 UTC, marie-j submitted a review, later dismissed

2021-05-31 12:54 UTC, Jisay approved these changes

2021-05-31 13:46 UTC, JeremyDec submitted a review, later dismissed

2021-05-31 14:01 UTC, Heiiji approved these changes

2021-06-01 06:09 UTC, antleblanc requested changes
According to the diff introduced into following file, `packages/manager/tools/component-rollup-config/src/index.ts`, could you please amend your commit to add a `BREAKING CHANGE` message?

Thanks

**Edit**
Additional question: Does it mean that `@ovh-ux/rollup-plugin-less-tilde-importer` must be deprecated too?

2021-06-01 13:09 UTC, frenautvh commented
> Additional question: Does it mean that `@ovh-ux/rollup-plugin-less-tilde-importer` must be deprecated too?

yes :)

2021-06-03 08:00 UTC, frenautvh commented
rebased on 0a30f6da7109b85aa33bb8c2adfdf47831eaae94

2021-06-07 15:53 UTC, cbourgois submitted a review, later dismissed

2021-06-09 07:13 UTC, antleblanc submitted a review, later dismissed

2021-06-09 15:28 UTC, frenautvh commented
rebased on develop 08593b7e8c2290dd2ef34bf380534edde85e2f5b

2021-06-10 08:25 UTC, JeremyDec approved these changes

2021-06-11 09:29 UTC, marie-j submitted a review, later dismissed

2021-06-17 12:09 UTC, antleblanc commented
Rebasing on `develop` branch due to conflict on following file `packages/manager/tools/webpack-config/package.json`.

2021-06-17 12:14 UTC, antleblanc commented
Rebased successfully on `develop` branch.

2021-06-17 12:28 UTC, antleblanc commented
Rebased successfully on `develop` branch.

2021-06-17 15:40 UTC, antleblanc approved these changes

2021-06-17 15:40 UTC, merged