feat(ai.training): add ai training translation
ovh/manager pull request #5024
Opened 2021-06-01 11:24 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-7029
| License          | BSD 3-Clause

## Description

Add ai training translation in ticket

2021-06-01 12:19 UTC, Heiiji submitted a review, later dismissed

2021-06-01 14:15 UTC, antleblanc requested changes

2021-06-01 14:15 UTC, antleblanc commented on packages/manager/modules/support/src/tickets/new-ticket/translations/Messages_fr_FR.json
> +  "ovhManagerSupport_new_serviceType_ai_training_job": "Ai Training",
Shouldn't be:

```suggestion
  "ovhManagerSupport_new_serviceType_ai_training_job": "AI Training",
```

see: https://github.com/ovh/manager/blob/master/packages/manager/modules/pci/src/projects/project/sidebar/sidebar.constant.js#L134

2021-06-02 05:52 UTC, antleblanc commented
Rebasing on `master` branch and fixing both `fr_FR` and `fr_CA` translation files (`s/Ai/AI/g`).

2021-06-02 05:56 UTC, antleblanc commented
Rebased successfully on `master` branch.

2021-06-02 05:56 UTC, antleblanc commented on packages/manager/modules/support/src/tickets/new-ticket/translations/Messages_fr_FR.json
> +  "ovhManagerSupport_new_serviceType_ai_training_job": "Ai Training",
Fixed via the rebase on `master` branch.

2021-06-02 05:56 UTC, antleblanc approved these changes

2021-06-02 05:57 UTC, antleblanc approved these changes

2021-06-02 06:26 UTC, merged