fix(repayment): get filtered repayment for servicename
ovh/manager pull request #5098
Opened 2021-06-10 13:40 UTC by Heiiji

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-6854
| License          | BSD 3-Clause

## Description

Use new query parameter of repayment 2api endpoint to get a filtered result for a specific number (serviceName).

2021-06-11 07:11 UTC, antleblanc requested changes

2021-06-11 07:11 UTC, antleblanc commented on packages/manager/apps/telecom/src/app/telecom/telephony/alias/special/repayments/repayments.controller.js
> -    return this.OvhApiTelephony.Service()
`OvhApiTelephony` still needed?

2021-06-11 07:11 UTC, antleblanc commented on packages/manager/apps/telecom/src/app/telecom/telephony/alias/special/repayments/repayments.controller.js
> +    return this.OvhHttp.get('/telephony/{billingAccount}/repayment', {
Both `OvhHttp` and `OvhApi*` services are deprecated.

We tend to use `$http`. Is it possible to use it here?

2021-06-11 09:42 UTC, marie-j commented on packages/manager/apps/telecom/src/app/telecom/telephony/alias/special/repayments/repayments.controller.js
> +    this.OvhHttp = OvhHttp;
```suggestion
```

2021-06-11 11:53 UTC, marie-j approved these changes

2021-06-14 07:01 UTC, frenautvh approved these changes

2021-06-14 08:07 UTC, jasi232 approved these changes

2021-06-14 12:15 UTC, JeremyDec approved these changes

2021-06-14 13:46 UTC, jasi232 commented on packages/manager/apps/telecom/src/app/telecom/telephony/alias/special/repayments/repayments.controller.js
> +    this.OvhHttp = OvhHttp;
Dont do it to ur self

2021-06-14 13:49 UTC, jasi232 commented
Don't do it to ur self stupid

2021-06-15 05:51 UTC, antleblanc approved these changes

2021-06-15 05:51 UTC, merged