Databases - Block Actions when not in Ready state
ovh/manager pull request #5134
Opened 2021-06-17 09:39 UTC by ganeshkumar1989

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7159
| License          | BSD 3-Clause

## Description

Block actions on Users, IP and Backup management page, when the database is not in ready state

2021-06-17 09:41 UTC, antleblanc requested changes
@ganeshkumar1989 Could you please rebase your branch on `master`?
Thank you!

2021-06-17 10:21 UTC, ganeshkumar1989 commented
> @ganeshkumar1989 Could you please rebase your branch on `master`?
> Thank you!

Sorry I missed that. Its done now. Thanks

2021-06-17 11:21 UTC, antleblanc approved these changes

2021-06-18 07:09 UTC, cbourgois approved these changes

2021-06-18 08:16 UTC, JeremyDec approved these changes

2021-06-18 09:23 UTC, Jisay approved these changes

2021-06-21 06:39 UTC, antleblanc commented
Updating target branch to `release/2021-w24`.

2021-06-21 06:41 UTC, merged