Feat/pci uuids
ovh/manager pull request #5138
Opened 2021-06-17 13:44 UTC by marie-j

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-7096
| License          | BSD 3-Clause

## Description

2021-06-18 12:12 UTC, frenautvh approved these changes

2021-06-18 12:42 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/data-processing/data-processing.controller.js
> +    console.log(criteria);
No :D

2021-06-18 13:36 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/data-processing/data-processing.controller.js
> +    console.log(criteria);
Forgot this one 🤭

2021-06-21 07:26 UTC, antleblanc requested changes

2021-06-21 07:26 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/analytics-data-platform/analytics-data-platform.routing.js
> +      clusterId: /* n@gInject */ ($transition$) => $transition$.params().id,
```suggestion
      clusterId: /* @ngInject */ ($transition$) => $transition$.params().id,
```

2021-06-22 12:44 UTC, ovh-cds commented
CDS Report translations-checker#17928.0 ✘  
* Stage 1
  * Check ✘

2021-06-25 06:13 UTC, antleblanc submitted a review, later dismissed

2021-06-28 14:25 UTC, antleblanc approved these changes

2021-06-28 14:28 UTC, merged