Perf/sso auth
ovh/manager pull request #5163
Opened 2021-06-23 15:14 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

## Description

reuse environment user data for sso auth (avoid making an unecessary call to /me on manager startup)

2021-06-23 15:17 UTC, cbourgois submitted a review, later dismissed

2021-06-24 10:40 UTC, Jisay submitted a review, later dismissed

2021-06-24 11:53 UTC, antleblanc requested changes
Nice addition! Just found a wrong definition inside the ngDoc comment block (wrong function name).

2021-06-24 11:53 UTC, antleblanc commented on packages/components/ng-ovh-sso-auth/src/provider.js
> +     * @name login
```suggestion
     * @name setLoggedIn
```

2021-06-24 11:53 UTC, antleblanc commented on packages/components/ng-ovh-sso-auth/src/provider.js
> +      }
**suggestions:** Seems to duplicate logic from `this.login` method just below (L343).
Maybe we can apply some refactoring.

2021-06-25 05:44 UTC, antleblanc submitted a review, later dismissed

2021-06-25 06:14 UTC, antleblanc commented
Rewriting git commit history.

2021-06-25 06:22 UTC, antleblanc commented
Git commit history has been successfully rewritten.

2021-06-25 06:22 UTC, antleblanc approved these changes

2021-06-25 07:23 UTC, merged