fix(webpaas): enable webPaas subscription environment upgrade
ovh/manager pull request #5218
Opened 2021-07-06 11:13 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #DTRSD-42203
| License          | BSD 3-Clause

## Description

enable webPaas subscription environment upgrade

2021-07-06 12:21 UTC, frenautvh submitted a review, later dismissed

2021-07-07 03:23 UTC, radireddy approved these changes

2021-07-07 06:11 UTC, antleblanc approved these changes

2021-07-07 07:40 UTC, JeremyDec approved these changes

2021-07-12 06:55 UTC, marie-j commented on packages/manager/modules/web-paas/src/components/addon/controller.js
> +      return addonPrice * (this.quantity - DEFAULT_ENVIRONMENT);
I expect `DEFAULT_ENVIRONMENT` to be something like a `string` not a `number`

2021-07-29 12:23 UTC, ganeshkumar1989 commented on packages/manager/modules/web-paas/src/components/additional-option/constants.js
> +export const DEFAULT_ENVIRONMENT_COUNT = 2;
Can we reuse this from packages/manager/modules/web-paas/src/web-paas.constants.js?

2021-07-30 08:47 UTC, radireddy approved these changes

2021-08-02 06:01 UTC, ganeshkumar1989 submitted a review, later dismissed

2021-08-02 06:44 UTC, antleblanc requested changes
Found some existing some typos.
Could you please make sure that there's no more typos before releasing it?
Thank  you!

2021-08-02 06:44 UTC, antleblanc commented on packages/manager/modules/web-paas/src/components/addon/translations/Messages_fr_FR.json
> +  "web_paas_service_add_addon_environment_info": "Attention, il n'est pas possible de réduire le nombre d’environnements de test d'un projet une fois l’environnements additionnel commandé."
> (...) une fois l’environnement**s** ...

Looks like there is a typo. `l'*` is singular so I think you can safely remove the extra `s`.

```suggestion
  "web_paas_service_add_addon_environment_info": "Attention, il n'est pas possible de réduire le nombre d’environnements de test d'un projet une fois l’environnement additionnel commandé."
```

2021-08-02 06:44 UTC, antleblanc commented on packages/manager/modules/web-paas/src/components/addon/translations/Messages_en_GB.json
> +  "web_paas_service_add_addon_environment_info": "Warning: The number of test environments for a project cannot be reduced once the additional environments have been ordered."
**question:** Please refer to my previous comment. Looks like there is a typo, isn't it?

```suggestion
  "web_paas_service_add_addon_environment_info": "Warning: The number of test environments for a project cannot be reduced once the additional environment have been ordered."
```

2021-08-02 06:44 UTC, antleblanc commented on packages/manager/modules/web-paas/src/web-paas.constants.js
> +export const DEFAULT_ENVIRONMENT_COUNT = 2;
**question:** Any reason to not export it also as `default` ? (see below L60-73)

2021-08-02 07:13 UTC, varun257 commented
@antleblanc have taken care of the changes requested

2021-08-03 11:14 UTC, antleblanc requested changes
Changes looks good to me. Only some recent changes around the content implies
to redo the translation process I think.

For instance, `Messages_fr_CA.json` is no more aligned with` Messages_fr_FR.json`.

2021-08-04 08:11 UTC, ovh-cds commented
CDS Report translator-push#19011.0 ✘  
* 
  * push ✘

2021-08-09 06:05 UTC, varun257 commented
> Changes looks good to me. Only some recent changes around the content implies
> to redo the translation process I think.
> 
> For instance, `Messages_fr_CA.json` is no more aligned with` Messages_fr_FR.json`.

Hi @antleblanc , They are okay with the translation as is for now as they need to get this prodded as soon as possible and translation process might take more time. So we have a go ahead to prod this with FR fix. PU can raise an issue for this later.

2021-08-09 08:47 UTC, varun257 commented
QA done and approved by QA_TEAM, We can include this in the next release

2021-08-11 06:22 UTC, antleblanc commented
Updating target branch from `master` to `develop`.

2021-08-11 06:23 UTC, antleblanc commented
Target branch has been updated successfully. Now target `develop`.

2021-08-11 06:24 UTC, antleblanc approved these changes

2021-08-11 06:24 UTC, merged