refactor(*): move dedicated server tasks code to a separate module
ovh/manager pull request #5224
Opened 2021-07-07 06:32 UTC by radireddy

ref #MANAGER-7282

Signed-off-by: Ravindra Adireddy <ravindra.adireddy@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/server-os-install`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7282
| License          | BSD 3-Clause

## Description

1. Extract tasks code into bm-server-components as a reusable component
2. Use this component in dedicated server.
3. Cleanup the old code.

2021-07-12 06:50 UTC, frenautvh requested changes
please fix linting issues

2021-07-13 08:15 UTC, radireddy commented
> please fix linting issues

fixed all linting errors

2021-07-16 07:37 UTC, frenautvh approved these changes

2021-07-20 07:49 UTC, varun257 approved these changes

2021-07-20 08:00 UTC, ganeshkumar1989 approved these changes

2021-07-20 12:56 UTC, merged