fix(exchange): not able to export external contacts
ovh/manager pull request #5258
Opened 2021-07-15 12:12 UTC by radireddy

ref: #DTRSD-41456

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-41456
| License          | BSD 3-Clause

## Description

Export external contacts of exchange is not working

2021-07-15 12:23 UTC, JeremyDec commented
Hello @radireddy, related to the priority of the referenced ticket, maybe this PR can target `develop` ?

2021-07-15 13:52 UTC, cbourgois requested changes

2021-07-15 13:52 UTC, cbourgois commented on packages/manager/modules/exchange/src/account/export-as-csv/account-export-as-csv.controller.js
> +    exportCsv,
`@ovh-ux/ng-ovh-export-csv` module is declared as a peer-dependency but never imported in module

2021-07-16 04:56 UTC, radireddy commented
> Hello @radireddy, related to the priority of the referenced ticket, maybe this PR can target `develop` ?

@JeremyDec Its not a hotfix. Yet, I have targeted master because it allows us to prod it during the sprint or at the end of the sprint. Not necessary that it needs to put in prod immediately. Let me know if you think otherwise.  I can change it to target develop.

2021-07-16 06:22 UTC, JeremyDec commented
@radireddy the release of the last sprint hasn't been prodded yet. It will be able to take all of the DTRSD fixes with it, in order to release them at the same time. So yes, please target `develop` :)

2021-07-16 06:48 UTC, frenautvh submitted a review, later dismissed

2021-07-16 07:39 UTC, marie-j submitted a review, later dismissed

2021-07-16 07:39 UTC, marie-j approved these changes

2021-07-16 07:40 UTC, JeremyDec approved these changes

2021-07-16 08:00 UTC, cbourgois approved these changes

2021-07-16 08:00 UTC, merged