feat(kube): add autoscaling to node pools
ovh/manager pull request #5268
Opened 2021-07-16 16:35 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-7286
| License          | BSD 3-Clause

## Description

Allow customers to scale their k8s cluster.
This reverts commit 4f14978c

2021-07-16 16:39 UTC, mohammed-zahaf commented
Hello @antleblanc and @marie-j, i reverted this feature.
I completed it by adding the required fix.

2021-07-19 10:07 UTC, radireddy approved these changes

2021-07-19 10:17 UTC, varun257 submitted a review, later dismissed

2021-07-20 06:42 UTC, marie-j commented
Hello @mohammed-zahaf 
I notice that the reference in the PR description doesn't match the one in the commit, which one should be taken into account ? 
Thanks

2021-07-20 07:01 UTC, mohammed-zahaf commented
Hello@marie-j, I updated the description.
It must be MANAGER-6681.

Thanks.

2021-07-20 08:49 UTC, marie-j submitted a review, later dismissed

2021-07-20 08:50 UTC, marie-j commented
@mohammed-zahaf could you please solve existing conflicts ? 
Thanks

2021-07-20 09:50 UTC, mohammed-zahaf commented
Hello @JeremyDec and @marie-j.
I juste rebased this branch on master.

2021-07-20 10:01 UTC, radireddy approved these changes

2021-07-22 06:30 UTC, radireddy approved these changes

2021-07-22 08:01 UTC, mohammed-zahaf commented
Hello @marie-j and @JeremyDec.
The reporter has made and validate QA on master branch.

2021-07-23 14:03 UTC, JeremyDec requested changes
Hello @mohammed-zahaf, I see only `fr_CA` / `fr_FR` translations files for `packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/scale/translations/Messages_fr_FR.json`.

Is there missing translations ?

2021-07-23 14:03 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/scale/translations/Messages_fr_CA.json
> +{
No translation for other languages ?

2021-07-23 14:11 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/node-pool/scale/translations/Messages_fr_CA.json
> +{
Ok, other translations already exists in `master`

2021-07-23 14:12 UTC, JeremyDec commented
Seen together, other files already exists in `master`

2021-07-23 14:12 UTC, JeremyDec approved these changes

2021-07-27 06:06 UTC, merged