feat(dedicated): enable veeam enterprise order for US
ovh/manager pull request #5284
Opened 2021-07-20 10:48 UTC by radireddy

ref: #MANAGER-7208

Signed-off-by: Ravindra Adireddy <ravindra.adireddy@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          |develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-7208
| License          | BSD 3-Clause

## Description

Enable veeam enterprise order for US region

2021-07-21 08:25 UTC, frenautvh approved these changes

2021-07-23 06:41 UTC, marie-j commented on packages/manager/modules/server-sidebar/src/order.constants.js
> +    regions: ['EU', 'CA', 'US'],
Could we use feature flipping instead ?

2021-09-15 19:47 UTC, antleblanc requested changes
@radireddy  Could you please resolve existing conflicts?
Thank you!

Side note: Conflicts mainly come from #4589

2021-11-30 17:13 UTC, antleblanc approved these changes

2021-11-30 17:14 UTC, merged