fix(server-sidebar): add anthos entry
ovh/manager pull request #5349
Opened 2021-07-29 13:58 UTC by ganeshkumar1989

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/anthos`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7384
| License          | BSD 3-Clause

## Description

- Add Anthos entry in the sidebar
- Rename Hosted Private Cloud to VMWare

2021-07-29 14:11 UTC, varun257 approved these changes

2021-07-30 04:42 UTC, radireddy requested changes

2021-07-30 04:42 UTC, radireddy commented on packages/manager/modules/server-sidebar/src/sidebar.constants.js
> +  regions: ['EU', 'CA'],
please use feature flipping

2021-07-30 07:37 UTC, ganeshkumar1989 commented on packages/manager/modules/server-sidebar/src/sidebar.constants.js
> +  regions: ['EU', 'CA'],
This has been done :)

2021-07-30 07:58 UTC, radireddy approved these changes

2021-08-03 07:00 UTC, mohammed-zahaf approved these changes

2021-08-03 08:04 UTC, antleblanc requested changes
Tests failed. Looks like the issue is located into the targeted branch `feat/anthos`.
A rebase will be required.

2021-08-03 11:46 UTC, ganeshkumar1989 commented
> Tests failed. Looks like the issue is located into the targeted branch `feat/anthos`.
> A rebase will be required.

This is done. Thanks!

2021-08-04 06:58 UTC, marie-j approved these changes

2021-08-04 09:34 UTC, antleblanc approved these changes

2021-08-10 08:31 UTC, merged