Feat/netapp dashboard
ovh/manager pull request #5351
Opened 2021-07-29 16:11 UTC by marie-j

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/netapp`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-7146
| License          | BSD 3-Clause

## Description

2021-07-30 07:29 UTC, marie-j commented on packages/manager/modules/netapp/src/dashboard/translations/Messages_fr_FR.json
> +  "netapp_dashboard_configuration_status_creating": "En cours de création",
Waiting content validation on status

2021-07-30 07:40 UTC, JeremyDec commented on packages/manager/modules/netapp/src/dashboard/routing.js
> +        $state.href('netapp.dashboard.volume.create', $transition$.params()),
State `netapp.dashboard.volumes` will be corresponding to Volumes tab, where `netapp.dashboard.volume` will be the volume detail, so:
```suggestion
        $state.href('netapp.dashboard.volumes.create', $transition$.params()),
```

2021-07-30 12:57 UTC, JeremyDec requested changes

2021-07-30 12:57 UTC, JeremyDec commented on packages/manager/modules/netapp/src/dashboard/component.js
> +    serviceInfos: '<',
`serviceInfos` is missing in routing

2021-07-30 13:02 UTC, marie-j commented on packages/manager/modules/netapp/src/dashboard/component.js
> +    serviceInfos: '<',
Not needed, forgot to remove it

2021-07-30 13:20 UTC, JeremyDec approved these changes

2021-08-03 09:42 UTC, antleblanc approved these changes

2021-08-03 13:03 UTC, merged