fix: add anthos to services and contacts page
ovh/manager pull request #5357
Opened 2021-08-02 07:21 UTC by ganeshkumar1989

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/anthos`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7385
| License          | BSD 3-Clause

## Description

Add Anthos to the Services and Contacts management page

2021-08-03 06:59 UTC, mohammed-zahaf approved these changes

2021-08-03 08:03 UTC, antleblanc requested changes
Tests failed. Looks like the issue is located into the targeted branch `feat/anthos`.
A rebase will be required.

2021-08-03 11:46 UTC, ganeshkumar1989 commented
> Tests failed. Looks like the issue is located into the targeted branch `feat/anthos`.
> A rebase will be required.

This is fixed. Thanks!

2021-08-04 06:59 UTC, marie-j approved these changes

2021-08-04 09:36 UTC, antleblanc approved these changes

2021-08-10 08:31 UTC, merged