fix(pci): fix project quota auto-scaling issue
ovh/manager pull request #5359
Opened 2021-08-02 14:23 UTC by reenjii

For https://github.com/ovh/manager/issues/5358

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | #5358
| License          | BSD 3-Clause

## Description

Fix PCI auto scaling issue

2021-08-02 14:24 UTC, antleblanc requested changes
Changes looks good to me.

Could you please use a signed commit message?
see: https://github.com/ovh/manager/blob/master/CONTRIBUTING.md

2021-08-03 06:57 UTC, marie-j submitted a review, later dismissed

2021-08-03 07:14 UTC, JeremyDec submitted a review, later dismissed

2021-08-03 07:58 UTC, antleblanc approved these changes

2021-08-03 09:09 UTC, reenjii commented
There was a typo between
`onAutoScalingQuotaSwitchChange` and
`data-on-change="$ctrl.onAutoScalingSwitchChange(modelValue)"`.

I amended the fix.

2021-08-03 09:22 UTC, antleblanc approved these changes

2021-08-03 09:25 UTC, JeremyDec approved these changes

2021-08-03 11:09 UTC, antleblanc commented
Update target branch to `release/2021-w31`.

2021-08-03 11:10 UTC, merged