feat(pci.storages.objects): tracking implementation
ovh/manager pull request #5396
Opened 2021-08-10 10:41 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/high-pserf-storage`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-7374
| License          | BSD 3-Clause

## Description
Tracking implementation for high performance storage

2021-08-10 12:23 UTC, antleblanc requested changes

2021-08-10 12:23 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/object-storage/object-storage.html
> +                data-no-click="$ctrl.onGuideLinkClick()"
```suggestion
                data-on-click="$ctrl.onGuideLinkClick()"
```

2021-08-11 06:14 UTC, antleblanc requested changes
Changes looks good to me!

There is a typo in the commit message (`trackign` => `tracking`).
Side note: Commit message summary must use present tense.
see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-header

2021-08-25 09:10 UTC, marie-j commented on packages/manager/apps/public-cloud/src/app.module.js
> +            console.log(error);
```suggestion
```

2021-08-25 09:13 UTC, marie-j commented on packages/manager/modules/pci/src/projects/project/storages/containers/add/add.controller.js
> +  trackCancel() {
No going back ?

2021-08-30 07:07 UTC, marie-j approved these changes

2021-09-07 08:13 UTC, JeremyDec approved these changes

2021-09-08 08:27 UTC, merged