refactor(dedicated): move account section into module
ovh/manager pull request #5421
Opened 2021-08-16 10:10 UTC by Jisay

Signed-off-by: Jisay <jean-christophe.alleman@corp.ovh.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-5820
| License          | BSD 3-Clause

## Description

Move account section into modules.

2021-08-30 08:13 UTC, frenautvh commented
can you please rebase, PR has some conflicts

2021-09-02 07:39 UTC, zakariasahmane submitted a review, later dismissed

2021-09-08 07:59 UTC, zakariasahmane approved these changes

2021-09-15 19:44 UTC, antleblanc requested changes
@Jisay Could you please resolve existing conflicts?
Thank you!

Side note: Conflicts mainly come from #4589

2021-12-01 07:58 UTC, JeremyDec requested changes
Hello @Jisay, It seems that your branch fails on installation step. Maybe a rebase is needed to fix the issue?

2022-06-24 00:00 UTC, closed without merging