feat(private-database): add private-database application
ovh/manager pull request #5485
Opened 2021-09-06 13:37 UTC by cbourgois

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | Fix MANAGER-7168
| License          | BSD 3-Clause

Create Private Database standalone application.

2021-09-09 09:34 UTC, Jisay approved these changes

2021-09-23 16:22 UTC, antleblanc requested changes

2021-09-23 16:22 UTC, antleblanc commented on packages/manager/apps/private-database/src/app.module.js
> +          console.log(error);
**question:** Is it needed?

2021-09-23 16:22 UTC, antleblanc commented on packages/manager/apps/private-database/package.json
> +  "description": "OVHCloud Private Database app",
```suggestion
  "description": "OVHcloud Private Database app",
```

2021-09-27 08:10 UTC, zakariasahmane approved these changes

2021-11-25 15:55 UTC, Jisay approved these changes

2021-11-30 07:16 UTC, antleblanc approved these changes

2021-11-30 07:16 UTC, merged