[Cloud][AINotebook] Keep consistency for AI product flavor display
ovh/manager pull request #5514
Opened 2021-09-10 13:07 UTC by jqueguiner

Fix consistency for AI product flavor display in GiB.

2021-09-10 14:39 UTC, cbourgois commented
Hello @jqueguiner, 

Thanks for your contributions 🎉 

Your changes sounds good. 
Could you check and add `sign-off` on your commits to be compliant with the DCO (https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-dco).

Thanks,
Cyrille

2021-09-11 18:35 UTC, jqueguiner commented
@cbourgois  : done

2021-09-13 14:44 UTC, antleblanc requested changes
Hi @jqueguiner!

Unfortunately your commit message doesn't have the requested `Signed-off-by`
footer to pass our GitHub checks.

see: https://github.com/ovh/manager/runs/3567446517

As you probably noticed, we are using a commit convention which is configured
here: https://github.com/ovh/manager/blob/master/.commitlintrc.json

Basically, we are using these guidelines:
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit

So, based on your changes, I would recommend you the following commit message:

```txt
fix(notebooks.add): keep consistency for AI product flavor display

Signed-off-by: Jean-Louis Queguiner <jean-louis.queguiner@gadz.org>
```

Please let us know if you have additional question.

Thanks for your contribution!

2021-09-23 14:07 UTC, antleblanc approved these changes

2021-09-23 14:09 UTC, JeremyDec approved these changes

2021-09-24 08:31 UTC, merged