Feat/email domain standalone
ovh/manager pull request #5527
Opened 2021-09-14 06:47 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/email-domain-module
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-7169
| License          | BSD 3-Clause

## Description

email domain standalone application

2021-09-14 06:50 UTC, ovh-cds commented
CDS Report translator-push#19896.0 ✘  
* 
  * push ✘

2021-09-16 07:51 UTC, marie-j commented on packages/manager/apps/email-domain/package.json
> +  "version": "0.3.0",
Already been released ?

2021-09-16 13:59 UTC, antleblanc commented on packages/manager/apps/email-domain/package.json
> +  "version": "0.3.0",
Good catch!

2021-09-21 06:40 UTC, antleblanc commented
**question:** Assets folder couldn't be located into `src`?

From `packages/manager/apps/email-domain/assets/**` to `packages/manager/apps/email-domain/src/assets/**`.

2021-09-27 08:34 UTC, zakariasahmane approved these changes

2021-09-28 07:47 UTC, JeremyDec commented
No translations for `DE/GB/ES/IT`?

2021-10-04 06:13 UTC, antleblanc requested changes
We tend to use `BREAKING CHANGE:` commit when it comes to apps/module scaffolding.

Could you please update following commit `10a8f9f2b44b591db196bd918cc6bbfd577d3e8a`?

Thank you!

2021-11-03 07:39 UTC, JeremyDec approved these changes

2021-11-04 08:19 UTC, merged