fix(overthebox.remote): fix error on remove remote access
ovh/manager pull request #5537
Opened 2021-09-14 14:24 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #UXCT-418
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch 
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally 
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Call the right function after removing remote access

## Related

2021-09-14 14:40 UTC, antleblanc requested changes
Good catch!

Small suggestions around extra space :)

2021-09-14 14:40 UTC, antleblanc commented on packages/manager/modules/overthebox/src/overthebox/remote/overTheBox-remote.controller.js
> +   reloadRemote(remote) {
```suggestion
  reloadRemote(remote) {
```

2021-09-14 15:05 UTC, antleblanc approved these changes

2021-09-14 15:06 UTC, marie-j approved these changes

2021-09-16 09:22 UTC, radireddy approved these changes

2021-09-20 06:48 UTC, merged