ci: auto PR develop for release
ovh/manager pull request #5556
Opened 2021-09-16 10:20 UTC by marie-j

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ (not applicable)
- [x] Branch is up-to-date with target branch 
- [x] Lint has passed locally
- [ ] ~~Standalone app was ran and tested locally~~(not applicable)
- [ ] ~~Ticket reference is mentioned in linked commits (internal only)~~ (not applicable)
- [ ] ~~Breaking change is mentioned in relevant commits~~(not applicable)

## Description

Add Release PR template and action to automatically trigger PR on develop

## Related

2021-09-17 05:53 UTC, antleblanc requested changes

2021-09-17 05:53 UTC, antleblanc commented on .github/workflows/auto-pr-release.yaml
> +    - develop
```suggestion
    - develop
    - "release/*"
```

2021-09-17 19:14 UTC, antleblanc approved these changes

2021-09-20 06:23 UTC, JeremyDec approved these changes

2021-09-20 06:51 UTC, merged