fix(anthos): fixes and improvement
ovh/manager pull request #5569
Opened 2021-09-17 13:31 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/anthos`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-7296
| License          | BSD 3-Clause

## Description

Anthos dedicated bugfixes PR.

## Related
Anthos: https://github.com/ovh/manager/pull/5380

2021-09-20 06:33 UTC, JeremyDec approved these changes

2021-09-20 06:33 UTC, JeremyDec commented on packages/manager/modules/anthos/src/dashboard/routing.js
> +        return AnthosTenantsService.getTenantDetails(serviceName).then(
**nitpick**
You could use return shortcut (`=> AnthosTenantsService.getTenantDetails(…) ...`)

2021-09-21 06:34 UTC, antleblanc requested changes
Some checks were not successful.
Could you please have a look?
Thanks!

2021-09-23 05:37 UTC, radireddy approved these changes

2021-09-23 10:08 UTC, ganeshkumar1989 commented
> Some checks were not successful.
> Could you please have a look?
> Thanks!

This is fixed :)

2021-09-23 10:10 UTC, merged