fix(high.perf.storage): fix translations
ovh/manager pull request #5577
Opened 2021-09-21 08:17 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7650, #MANAGER-7648
| License          | BSD 3-Clause

## Description

add message to show access and key
fix translation

2021-09-21 13:21 UTC, antleblanc requested changes

2021-09-21 13:21 UTC, antleblanc commented on packages/manager/modules/pci/src/components/project/users/translations/Messages_fr_FR.json
> +  "pci_projects_project_users_generate_s3_credentials_success": "Les informations d'identification S3 pour l'utilisateur {{user}} ont été regénérées. Votre clé d'accès est {{access}} and la clé secrè
```suggestion
  "pci_projects_project_users_generate_s3_credentials_success": "Les informations d'identification S3 pour l'utilisateur {{user}} ont été regénérées. Votre clé d'accès est {{access}} et la clé secrète est {{secret}}.",
```

2021-09-22 06:21 UTC, JeremyDec approved these changes

2021-09-22 08:39 UTC, radireddy approved these changes

2021-10-04 05:56 UTC, antleblanc approved these changes

2021-10-04 15:37 UTC, marie-j approved these changes

2021-10-05 08:36 UTC, JeremyDec approved these changes

2021-11-22 05:46 UTC, varun257 commented on packages/manager/modules/pci/src/projects/project/storages/object-storage/translations/Messages_fr_FR.json
> +  "pci_projects_project_storages_containers_s3_users_label": "Utilisateurs S3",
Will push for translations again for this label

2021-12-01 08:35 UTC, JeremyDec approved these changes

2021-12-03 08:35 UTC, antleblanc approved these changes

2021-12-03 08:38 UTC, merged