Fix/banner tracking
ovh/manager pull request #5593
Opened 2021-09-22 12:14 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7503
| License          | BSD 3-Clause

## Description

Pick tracker from API on priority

2021-09-22 15:22 UTC, antleblanc requested changes
Internal ticket ID provided into the description is not the correct one.

Could you please provide the right internal ticket ID?
Thanks!

2021-09-23 05:29 UTC, radireddy approved these changes

2021-09-24 08:18 UTC, ganeshkumar1989 approved these changes

2021-09-24 08:35 UTC, antleblanc approved these changes

2021-09-24 08:36 UTC, merged