feat/PUD-833
ovh/manager pull request #5605
Opened 2021-09-23 09:21 UTC by jperchoc

Signed-off-by: Jonathan Perchoc <jonathan.perchoc@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/PUD-748`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Second lot of new engines

2021-10-28 07:35 UTC, radireddy submitted a review, later dismissed

2021-11-02 12:49 UTC, antleblanc requested changes
@jperchoc Could you please resolve existing conflict?
Thank you!

2021-11-04 09:22 UTC, JeremyDec approved these changes

2021-11-22 14:45 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/indexes/indexes.html
> +                    class="oui-button oui-button_s oui-button_secondary"
```suggestion
                    type="button"
                    class="oui-button oui-button_s oui-button_secondary"
```

2021-11-22 14:45 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/indexes/indexes.html
> +                    class="oui-button oui-button_s oui-button_secondary"
```suggestion
                    type="button"
                    class="oui-button oui-button_s oui-button_secondary"
```

2021-11-23 08:02 UTC, antleblanc approved these changes

2021-11-23 09:33 UTC, merged