feat(nutanix.support): add support tile component
ovh/manager pull request #5633
Opened 2021-09-28 06:47 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/nutanix`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-7557
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Add support tile to nutanix node dashboard

2021-09-28 13:23 UTC, antleblanc requested changes

2021-09-28 13:23 UTC, antleblanc commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/translations/Messages_fr_FR.json
> +  "nutanix_node_general_info_support_issue_question": "Un probleme sur vos produits?",
```suggestion
  "nutanix_node_general_info_support_issue_question": "Un problème sur vos produits ?",
```

2021-09-28 13:23 UTC, antleblanc commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/translations/Messages_fr_FR.json
> +  "nutanix_node_general_info_support_issue_link_text": "Consulter nos taches travaux"
```suggestion
  "nutanix_node_general_info_support_issue_link_text": "Consulter nos tâches travaux"
```

2021-09-28 13:23 UTC, antleblanc commented on packages/manager/modules/nutanix/src/dashboard/nodes/node/general-info/translations/Messages_fr_FR.json
> +  "nutanix_node_general_info_support_level_title": "Support level",
**question:** Shouldn't be:

```suggestion
  "nutanix_node_general_info_support_level_title": "Niveau de support",
```

Instead?

2021-09-29 08:37 UTC, antleblanc approved these changes

2021-09-29 08:37 UTC, antleblanc commented
Just noticed that "Some checks were not successful". Could you please have a look?
Thank you!

2021-09-29 08:57 UTC, radireddy approved these changes

2021-09-29 10:51 UTC, merged