fix(telecom.alias.css): modification regex internal or external agent detection
ovh/manager pull request #5751
Opened 2021-10-16 12:06 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-8039
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Fixed the bug of detection of internal OVHcloud or external line when the number contains 33 / 34 / 41 or 0033 / 0034 / 0041 in the number when adding a member in the CCS. If the number contains 33 / 34 / 41 or 0033 / 0034 / 0041 in a place other than the beginning, the number is detected externally and displays a potential billing message (wrongly). Changing the regex corrects the anomaly.

## Related

2021-10-22 05:30 UTC, radireddy submitted a review, later dismissed

2021-11-04 09:07 UTC, JeremyDec requested changes
Hello @outilspartenairesovh, 

Can you please amend your commit to:
- format the commit scope as following: `(telecom.alias.css)` => `new_css` doesn't exist as folder or feature in the code source.
- write commit message in english

Thanks

2021-11-08 07:49 UTC, JeremyDec approved these changes

2021-11-15 07:43 UTC, antleblanc submitted a review, later dismissed

2022-01-05 07:21 UTC, JeremyDec commented
Hello @ghyenne , Test pipeline has failed, you may need to rebase your branch. Also can you set the ref of the ticket in the commit as following: `ref: MANAGER-8039` please? (Be careful to keep the reference above the `Signed-off-by`line. )

2022-01-07 12:47 UTC, antleblanc approved these changes

2022-01-26 07:18 UTC, merged