fix(telecom.alias.ccs): fix no external agent alert - resolves #5795
ovh/manager pull request #5799
Opened 2021-10-22 08:58 UTC by ghyenne

Signed-off-by: Guillaume Hyenne <hyenne.guillaume@neuf.fr>

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #5795 / MANAGER-8470
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Fix issue #5795

## Related

2021-11-02 12:37 UTC, outilspartenairesovh commented on packages/manager/apps/telecom/src/app/telecom/telephony/alias/configuration/agents/ovhPabx/ovh-pabx.controller.js
> +    if (detailNumber.AnyExternalNumber === true) {
I just made a new commit with this change.

2021-11-04 09:00 UTC, JeremyDec requested changes
Hello @outilspartenairesovh, thanks for your contributions!

Few comments on commit list:

- Can you please format the scope to `fix:(telecom.alias.css): […]`?
- Can you amend the commit to add `resolves #5795` (Or another key word, see the following list: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

I've added additional remarks on the code.

2021-12-28 11:03 UTC, JeremyDec approved these changes

2022-01-05 07:47 UTC, JeremyDec approved these changes

2022-01-05 08:32 UTC, JeremyDec approved these changes

2022-01-07 12:48 UTC, antleblanc approved these changes

2022-01-20 12:42 UTC, merged