Feat/replace community url by discord
ovh/manager pull request #5806
Opened 2021-10-25 08:11 UTC by christophe-rannou

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MLS-2159
| License          | BSD 3-Clause

## Description

Replace community URL by Discord URL

### :flags: Translations

- [x] TRANS-39367

2021-11-05 08:36 UTC, christophe-rannou commented on packages/manager/modules/pci/src/projects/project/training/training.html
> +                data-href="{{ $ctrl.discordUrl }}"
Done

2021-11-08 09:02 UTC, mohammed-zahaf submitted a review, later dismissed

2021-11-15 08:49 UTC, frenautvh requested changes
you have a merge commit in your history, could you please rebase on develop instead ?

2021-11-15 13:34 UTC, mohammed-zahaf approved these changes

2021-11-23 08:53 UTC, antleblanc submitted a review, later dismissed

2021-12-08 08:22 UTC, marie-j approved these changes

2021-12-13 14:36 UTC, marie-j submitted a review, later dismissed

2021-12-13 14:39 UTC, marie-j commented
Rebased on `develop`

2021-12-13 15:52 UTC, merged