fix(pci.image): add missing translations
ovh/manager pull request #5881
Opened 2021-11-04 08:06 UTC by marie-j

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-54703
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2021-11-04 08:11 UTC, JeremyDec approved these changes

2021-11-04 08:45 UTC, antleblanc requested changes

2021-11-04 08:45 UTC, antleblanc commented on packages/manager/modules/pci/src/components/project/images-list/translations/Messages_fr_FR.json
> +  "pci_project_instances_distribution_unknown": "Baremetal distributions",
```suggestion
  "pci_project_instances_distribution_unknown": "Bare Metal distributions",
```

2021-11-04 08:56 UTC, antleblanc approved these changes

2021-11-04 09:27 UTC, mohammed-zahaf approved these changes

2021-11-18 14:45 UTC, antleblanc approved these changes

2021-11-18 14:45 UTC, frenautvh approved these changes

2021-11-18 14:45 UTC, JeremyDec approved these changes

2021-11-19 09:48 UTC, merged