build(*): bump ng-ovh-api-wrappers to version 4.0.9
ovh/manager pull request #5911
Opened 2021-11-08 09:29 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-7878
| License          | BSD 3-Clause

## Description

bump @ovh-ux/ng-ovh-api-wrappers to version 4.0.9

2021-11-08 13:37 UTC, Jisay approved these changes

2021-11-09 07:14 UTC, antleblanc requested changes
@frenautvh Could you please resolve existing conflict? Thank you!

2021-11-15 07:56 UTC, frenautvh commented
rebased on develop f02b064626f3f878df6ab8300016e637221703a4

2021-11-15 08:15 UTC, antleblanc approved these changes

2021-11-15 08:16 UTC, merged