Fix/email message payment alert
ovh/manager pull request #5931
Opened 2021-11-09 07:59 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-50951
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

add pre wrap and word break to remove horizontal scroll
fix accounts alert issue

2021-11-09 08:08 UTC, JeremyDec reviewed
Hello @varun257,

Changes looks good to me! Can you please rebase your branch to `develop` please?

I didn't change the base branch myself to avoid making potentially your PR being in conflicts.

Thanks

2021-11-09 08:20 UTC, antleblanc approved these changes

2021-11-09 14:21 UTC, JeremyDec submitted a review, later dismissed

2021-11-16 07:47 UTC, antleblanc requested changes
@varun257, Some checks were not successful, could you please have a look? Thank you!

2021-11-17 05:37 UTC, closed without merging