feat(baremetal.commitment): fix issue with upfront price
ovh/manager pull request #5947
Opened 2021-11-11 11:11 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-56164
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

fix issue with upfront price

2021-11-12 08:05 UTC, frenautvh requested changes
please rename commit to fix(...) instead of feat(...)

2021-11-12 14:33 UTC, antleblanc commented on packages/manager/modules/billing-components/src/components/commitment-pricing-mode/commitment-pricing-mode.html
> +    <div class="row mb-2 mt-2">
```suggestion
    <div class="row my-2">
```

2021-11-15 07:21 UTC, antleblanc approved these changes

2021-11-15 08:11 UTC, antleblanc approved these changes

2021-11-15 08:15 UTC, frenautvh approved these changes

2021-11-15 14:09 UTC, merged