feat(account-sidebar, dedicated): change of url to status-ovhcloud
ovh/manager pull request #5958
Opened 2021-11-15 12:21 UTC by anooparveti

Change of URL from travaux to status-ovhcloud
 ref: MANAGER-6669

Signed-off-by: Anoop <anooparveti@gmail.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-6669
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Change of URL from Travaux to status-ovhcloud

## Related

2021-11-16 04:39 UTC, radireddy approved these changes

2021-11-16 04:54 UTC, varun257 approved these changes

2021-11-16 06:42 UTC, antleblanc requested changes

2021-11-16 06:42 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/config/constants.config.js
> +    travauxUrl: 'https://www.status-ovhcloud.com/',
```suggestion
    statusUrl: 'https://www.status-ovhcloud.com/',
```

2021-11-16 06:42 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/config/constants.config.js
> +    travauxUrl: 'https://www.status-ovhcloud.com/',
Should be reflected here:

```txt
packages/manager/apps/dedicated/client/app/app.module.js
packages/manager/apps/dedicated/client/app/config/constants.config.js
packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/dashboard.controller.js
```

2021-11-16 06:42 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/config/constants.config.js
> +    travauxUrl: 'https://www.status-ovhcloud.com/',
```suggestion
    statusUrl: 'https://www.status-ovhcloud.com/',
```

2021-11-16 13:09 UTC, radireddy approved these changes

2021-11-16 14:25 UTC, antleblanc requested changes

2021-11-16 14:25 UTC, antleblanc commented on packages/manager/apps/dedicated/client/app/dedicated/server/dashboard/dashboard.controller.js
> +      travaux: this.constants.statusUrl,
```suggestion
      status: this.constants.statusUrl,
```

2021-11-17 06:46 UTC, radireddy approved these changes

2021-11-17 08:09 UTC, mohammed-zahaf approved these changes

2021-11-17 12:26 UTC, antleblanc approved these changes

2021-11-26 08:52 UTC, antleblanc commented
@anooparveti Could you please rebase it against `master` branch?
Thank you!

2021-11-29 11:06 UTC, antleblanc approved these changes

2021-11-29 11:07 UTC, merged