feat(shell): add docs for shell library
ovh/manager pull request #5963
Opened 2021-11-16 10:56 UTC by zakariasahmane

| Question         | Answer
| ---------------- | ---
| Branch?          |  feat/manager-shell
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

## Description

Documentation for @ovh-ux/shell

2021-11-16 14:42 UTC, marie-j commented
Maybe a `docs` commit would be more suitable in this case

2021-11-17 12:20 UTC, antleblanc approved these changes
Changes looks good to me!
I've left some comments, please let me know if you're OK with.
Thanks!

2021-11-17 12:20 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +### Plugin
```suggestion
### Plugins
```

2021-11-17 12:20 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +  - [Plugins API](#plugin)
```suggestion
  - [Plugins API](#plugins)
```

2021-11-17 12:20 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +```js
For consistency:
```suggestion
```ts
```

2021-11-17 12:20 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +```js
For consistency:
```suggestion
```ts
```

2021-11-17 12:20 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +```js
For consistency:
```suggestion
```ts
```

2021-11-17 14:36 UTC, zakariasahmane commented
> Changes looks good to me! I've left some comments, please let me know if you're OK with. Thanks!

@antleblanc I'm okay with all the suggested changes, will apply them ! Thanks !

2021-12-30 13:37 UTC, antleblanc requested changes
Could you please resolve existing conflicts?
Thanks

2022-02-21 17:12 UTC, antleblanc requested changes
@zakariasahmane Could you please resolve existing conflicts?
Thank you!

2022-03-25 14:26 UTC, closed without merging