feat(ai-training-notebooks): add possibility to attach ssh keys
ovh/manager pull request #6058
Opened 2021-11-30 15:18 UTC by mael-le-gal

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MLS-2321
| License          | BSD 3-Clause

## Description

On AI Notebooks add the possibility to attach an ssh key when submiting a new notebook

2021-12-01 07:37 UTC, JeremyDec requested changes

2021-12-01 09:54 UTC, mael-le-gal commented on packages/manager/modules/pci/src/projects/project/notebooks/notebooks.service.js
> +    return this.$http.get(`/cloud/project/${serviceName}/sshkey`);
fixed

2021-12-01 09:54 UTC, mael-le-gal commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/notebook-ssh-keys.controller.js
> +    console.log(this.notebookModel);
fixed

2021-12-01 09:54 UTC, mael-le-gal commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_notebook_add_select_ssh_name_tips": "Choisir le nom de la clé parmis celles enregistrées",
fixed

2021-12-28 09:33 UTC, JeremyDec commented
Hello @mael-le-gal, your branch needs to be rebase on `develop`. Can you check please?

2022-01-05 08:50 UTC, JeremyDec approved these changes

2022-01-17 08:48 UTC, mael-le-gal commented
QA done on this one. Needs approvals before merging.

2022-01-17 12:50 UTC, antleblanc requested changes

2022-01-17 12:50 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/notebook-ssh-keys.component.js
> +  require: {},
```suggestion
```

2022-01-17 12:50 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/notebook-ssh-keys.controller.js
> +  constructor(coreConfig, NotebookService) {
**suggestion:** AFAIK `coreConfig` is not used so it could be removed.

```suggestion
  constructor(NotebookService) {
```

2022-01-17 12:50 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/notebook-ssh-keys.controller.js
> +    this.coreConfig = coreConfig;
```suggestion
```

2022-01-17 12:50 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/notebook-ssh-keys.controller.js
> +    // Option set by user indicating if he wants to add ssh keys
```suggestion
    // Option indicating if the user wants to add ssh keys
```

2022-01-18 13:18 UTC, JeremyDec submitted a review, later dismissed

2022-01-20 19:33 UTC, antleblanc approved these changes

2022-02-17 08:23 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_notebook_add_select_ssh": "Attacher des clés publiques ssh (optionnel)",
```suggestion
  "pci_projects_project_training_notebook_add_select_ssh": "Attacher des clés publiques SSH (optionnel)",
```

2022-02-17 08:24 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_notebook_add_select_ssh_tips_1": "Attacher une clé publique ssh vous permet par la suite d'accéder à distance au notebook via le protocole ssh ou scp",
```suggestion
  "pci_projects_project_training_notebook_add_select_ssh_tips_1": "Attacher une clé publique SSH vous permet par la suite d'accéder à distance au notebook via le protocole ssh ou scp",
```

2022-02-17 08:24 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/notebooks/add/components/notebook-ssh-keys/translations/Messages_fr_FR.json
> +  "pci_projects_project_training_notebook_add_select_ssh_quantity": "{{ numberOfSshKeys }} / {{ maxSshKeys }} clé(s) ssh",
replace ssh by `SSH`

2022-02-17 08:25 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/notebooks/add/translations/Messages_fr_FR.json
> +  "pci_notebook_add_ssh_keys_selected": "Clés publiques ssh attachées : {{quantity}}"
Same as here: https://github.com/ovh/manager/pull/6058/files#r808782968

2022-02-21 07:35 UTC, antleblanc commented
Pulling translations.

2022-02-21 08:04 UTC, antleblanc commented
Thanks @mohammed-zahaf for all suggestions.
@mael-le-gal Would you take it into in account (on a separate Pull Request)?

2022-02-21 08:04 UTC, merged

2022-02-21 08:06 UTC, mohammed-zahaf commented
Ok for me