fix(pci.kube.oidc): update translation files
ovh/manager pull request #6112
Opened 2021-12-08 08:36 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-7483`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-58923
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
Update OIDC Provider translations

## Related
- [ ] TRANS-xxxxx

2021-12-09 07:44 UTC, frenautvh requested changes

2021-12-09 07:44 UTC, frenautvh commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/service/oidc-provider/add-oidc-provider/translations/Messages_fr_FR.json
> +  "pci_projects_project_kubernetes_details_service_add_oidc_provider_description": "Vous pouvez utilisez la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition qu
vous pouvez utiliser

2021-12-09 09:00 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/service/oidc-provider/add-oidc-provider/translations/Messages_fr_FR.json
> +  "pci_projects_project_kubernetes_details_service_add_oidc_provider_description": "Vous pouvez utilisez la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition qu
Thanks.

2021-12-10 05:08 UTC, anooparveti submitted a review, later dismissed

2021-12-10 05:13 UTC, varun257 approved these changes

2021-12-13 08:19 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/service/oidc-provider/add-oidc-provider/translations/Messages_fr_FR.json
> +  "pci_projects_project_kubernetes_details_service_add_oidc_provider_description": "Vous pouvez utiliser la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition qu
```suggestion
  "pci_projects_project_kubernetes_details_service_add_oidc_provider_description": "Vous pouvez utiliser la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition qu'ils exposent la fonctionnalité \"OpenID Connect discovery”. Le fournisseur OIDC doit être accessible depuis une URL en HTTPS et un certificat CA signé est obligatoire.",
```

2021-12-13 08:19 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/kubernetes/details/service/oidc-provider/update-oidc-provider/translations/Messages_fr_FR.json
> +  "pci_projects_project_kubernetes_details_service_update_oidc_provider_description": "Vous pouvez utiliser la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition
Same here
```suggestion
  "pci_projects_project_kubernetes_details_service_update_oidc_provider_description": "Vous pouvez utiliser la plupart des fournisseurs OIDC comme Dex, Keycloak ou un fournisseur SaaS, à la condition qu'ils exposent la fonctionnalité \"OpenID Connect discovery”. Le fournisseur OIDC doit être accessible depuis une URL en HTTPS et un certificat CA signé est obligatoire.",
```

2021-12-15 09:54 UTC, radireddy submitted a review, later dismissed

2021-12-17 17:26 UTC, antleblanc approved these changes

2021-12-23 10:10 UTC, antleblanc approved these changes

2021-12-23 10:11 UTC, merged