feat(public cloud project dashboard): add products and new links in project dashboard EU/CA
ovh/manager pull request #6130
Opened 2021-12-14 12:42 UTC by baaastijn

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? no
| Tickets          | no tickets
| License          | BSD 3-Clause

## Description

The public cloud universe added lot of products and services but not the dashboard.
Added more buttons, with graphical style

- Before : Instance, volume, container OS, private network, kubernetes
- After : Instances, Kubernetes, volume, container OS, Databases, AI notebooks, PRivate network, Failover IP

Why these 8 : it's the top8 of clicks in the left menu

Images : took official website images, validated with OVH CX their use

Documentation Links : validated internally with the Steerco PCI
Community :Links : same

## Local tests : Firefox 92 MacOS ans Safari
used basic bootstrap rules

Desktop view :
![pr1](https://user-images.githubusercontent.com/16922182/146000155-34ff8112-3718-4f70-860b-6c48b7e99b31.png)

Smartphone :
![pr2](https://user-images.githubusercontent.com/16922182/146000160-53644652-78f4-4817-91ef-3c123c836b4d.png)
![pr3](https://user-images.githubusercontent.com/16922182/146000165-5f444e4a-2140-47f6-8721-fea3a5aeec5a.png)

Signed-off-by: Bastien Verdebout (bastien.verdebout at ovhcloud dot com)

2021-12-17 20:47 UTC, baaastijn commented
added status and signed-off my 2 commits

2021-12-22 07:59 UTC, antleblanc requested changes

2021-12-22 07:59 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/project.html
> +                                        class="d-inline-block col-sm-6 col-lg-4 col-xl-3 mb-4"
```suggestion
                                        class="col-sm-6 col-md-4 col-lg-3 mb-4"
```

2021-12-22 07:59 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/project.html
> +                                                class="inline-block"
```suggestion
```

2021-12-24 14:56 UTC, antleblanc requested changes

2021-12-24 14:56 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/project.html
>                                      <div class="col-sm-6 mb-4">
```suggestion
                                    <div
                                        class="col-sm-6 mb-4"
                                        data-ng-if="$ctrl.coreConfig.getRegion() !== 'US'"
                                    >
```

2021-12-30 09:19 UTC, baaastijn commented on packages/manager/modules/pci/src/projects/project/project.html
>                                      <div class="col-sm-6 mb-4">
taken into account int he last commit

2021-12-30 14:09 UTC, antleblanc approved these changes

2022-01-04 14:36 UTC, merged