feat(identity-check) add tracking
ovh/manager pull request #6180
Opened 2021-12-22 15:18 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/identity-check-confirm-cancel-procedure` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-8382 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated (n/a)
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

I have add tracking (ticket: MANAGER-8382)

## Related

2021-12-23 11:24 UTC, anooparveti requested changes

2021-12-23 11:24 UTC, anooparveti commented on packages/manager/modules/telecom-dashboard/src/identity-check/form/telecom-dashboard-identity-check-form.controller.js
> +    $state,
nitpick(blocking): Avoid using $state in controller files.
You can move the $state.go to routing.js

2021-12-23 14:50 UTC, antleblanc approved these changes

2021-12-28 09:28 UTC, y4nnL approved these changes

2021-12-29 11:54 UTC, y4nnL commented
Closing because of errors in git manipulations

2021-12-29 11:54 UTC, closed without merging