feat(ai.training): use new job logs
ovh/manager pull request #6265
Opened 2022-01-07 15:01 UTC by co42

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix MLS-2123
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

Logs not available in Object Storage anymore, but always available via API. Always get logs via API even if the job is terminated

2022-01-07 15:09 UTC, antleblanc requested changes

2022-01-07 15:09 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/info/logs/logs.html
> -    <p data-translate="pci_projects_project_training_job_logs_text_5"></p>
**nitpick(blocking):** Following translation can be removed then from `packages/manager/modules/pci/src/projects/project/training/jobs/info/translations/Messages_fr_FR.json`.

2022-01-07 16:59 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/training/jobs/info/logs/logs.html
> -    <p data-translate="pci_projects_project_training_job_logs_text_5"></p>
Mark as unresolved. Translations are still there. Could you please remove them?

2022-01-07 17:00 UTC, antleblanc requested changes
Could you please remove extra translations?

see: https://github.com/ovh/manager/pull/6265#discussion_r780325029

2022-01-17 17:07 UTC, antleblanc approved these changes

2022-01-18 09:09 UTC, JeremyDec approved these changes

2022-01-21 16:31 UTC, merged