feat(modules.netapp): replace button by action menu
ovh/manager pull request #6343
Opened 2022-01-21 16:44 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `MANAGER-8208`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-8136
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
To avoid the overlap between left button and search bar, we replace button by Actions menu.

2022-01-21 17:05 UTC, antleblanc approved these changes

2022-01-21 17:07 UTC, antleblanc requested changes
Some checks were not successful
> CDS/UXMAN-manager-test-v3 — test-v3: Fail 

Could you please have a look?
Thanks!

2022-01-25 08:30 UTC, ghyenne approved these changes

2022-01-25 11:24 UTC, mohammed-zahaf commented
> Some checks were not successful
> 
> > CDS/UXMAN-manager-test-v3 — test-v3: Fail
> 
> Could you please have a look? Thanks!

@antleblanc, thanks to have report this issue.

All issues are related to updated markdown files not to development issue.
I think we can validate that one and i will open another PR for the issue with markdown issues.

With @ravindra we are looking how to fix them.

2022-01-25 11:27 UTC, radireddy approved these changes

2022-01-25 11:27 UTC, merged