Feat PUD-1231 (pci.storage.databases): add grafana engine
ovh/manager pull request #6376
Opened 2022-01-27 17:03 UTC by jperchoc

PUD-1231

Signed-off-by: Jonathan Perchoc <jonathan.perchoc@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #PUD-1230
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Adding Cassandra engine to cloud databases

2022-02-01 21:20 UTC, antleblanc requested changes

2022-02-01 21:20 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/general-information/general-information.html
> +                            data-ng-click="$ctrl.resetPassword()"
```suggestion
                        <button
                            type="button"                        
                            class="oui-tile__button oui-button oui-button_ghost oui-button_block"
                            data-ng-click="$ctrl.resetPassword()"
```

2022-02-01 21:20 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/general-information/translations/Messages_fr_FR.json
> +  "pci_databases_general_information_reset_password_success": "Le mot de passe de l'utilisateur {{ user }} a été régénéré avec succès: <code>{{ password }}</code>. Veuillez le noter car il ne pourra
```suggestion
  "pci_databases_general_information_reset_password_success": "Le mot de passe de l'utilisateur {{ user }} a été régénéré avec succès : <code>{{ password }}</code>. Veuillez le noter car il ne pourra pas être récupéré par la suite.",
```

2022-02-02 08:29 UTC, jperchoc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/general-information/general-information.html
> +                            data-ng-click="$ctrl.resetPassword()"
Added: https://github.com/ovh/manager/pull/6376/commits/c216fcefcaa71dc9e0b306a04c2667fab5636544

2022-02-02 08:29 UTC, jperchoc commented on packages/manager/modules/pci/src/projects/project/storages/databases/database/general-information/translations/Messages_fr_FR.json
> +  "pci_databases_general_information_reset_password_success": "Le mot de passe de l'utilisateur {{ user }} a été régénéré avec succès: <code>{{ password }}</code>. Veuillez le noter car il ne pourra
Changed: https://github.com/ovh/manager/pull/6376/commits/c216fcefcaa71dc9e0b306a04c2667fab5636544

2022-02-02 09:33 UTC, Jisay approved these changes

2022-02-03 08:53 UTC, antleblanc approved these changes

2022-02-03 08:55 UTC, merged