fix(nutanix): fix tracking for nutanix
ovh/manager pull request #6391
Opened 2022-02-01 04:35 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/nutanix`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-7944
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Fix missing nutanix tracking

## Related

2022-02-01 08:44 UTC, JeremyDec approved these changes

2022-02-02 07:26 UTC, ghyenne approved these changes

2022-02-02 07:55 UTC, JeremyDec requested changes
Hello @varun257, the **test** has failed on CDS, could you please take a look? Thanks

2022-02-02 09:36 UTC, marie-j approved these changes

2022-02-03 06:20 UTC, radireddy commented
> Hello @varun257, the **test** has failed on CDS, could you please take a look? Thanks

This is because the parent branch itself has this issue. We will take care of this issue in parent branch instead of taking care in all child branches. We have more than 10 child branches.

2022-02-03 06:20 UTC, radireddy approved these changes

2022-02-03 06:21 UTC, merged