feat: nutanix licence tile
ovh/manager pull request #6392
Opened 2022-02-01 05:43 UTC by radireddy

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/nutanix
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-7851
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2022-02-01 08:38 UTC, JeremyDec requested changes

2022-02-01 08:38 UTC, JeremyDec commented on packages/manager/modules/nutanix/src/dashboard/component/licence-tile/licences.class.js
> +    return this.getFeatureByName(featureName) !== null;
```suggestion
    return this.getFeatureByName(featureName) !== undefined;
```

or 
```suggestion
    return this.getFeatureByName(featureName) != null;
```

2022-02-01 08:38 UTC, JeremyDec commented on packages/manager/modules/nutanix/src/dashboard/component/licence-tile/translations/Messages_fr_FR.json
> +  "nutanix_cluster_licence_disabled": "Desactivar"
```suggestion
  "nutanix_cluster_licence_enabled": "Activer",
  "nutanix_cluster_licence_disabled": "Désactiver"
```

2022-02-01 08:38 UTC, JeremyDec commented on packages/manager/modules/nutanix/src/dashboard/general-info/routing.js
> +        console.log(error);
```suggestion
```

2022-02-01 10:08 UTC, varun257 commented on packages/manager/modules/nutanix/src/dashboard/component/licence-tile/controller.js
> +        const licenceFeatures = isArray(res.license.features)
```suggestion
.then(({ license }) => {
        const licenceFeatures = isArray(license.features)
```

2022-02-02 06:46 UTC, varun257 approved these changes

2022-02-02 06:58 UTC, ghyenne approved these changes

2022-02-02 07:10 UTC, JeremyDec approved these changes

2022-02-02 09:34 UTC, antleblanc requested changes
Some checks were not successful

> CDS/UXMAN-manager-build-v2 — build-v2: Fail
> CDS/UXMAN-manager-test-v3 — test-v3: Fail

2022-02-03 05:34 UTC, radireddy commented
> Some checks were not successful
> 
> > CDS/UXMAN-manager-build-v2 — build-v2: Fail
> > CDS/UXMAN-manager-test-v3 — test-v3: Fail

build is ok now, https://cds.ovhcloud.tools/project/UXMAN/workflow/manager/run/28472

2022-02-03 05:35 UTC, merged