feat(overthebox.autoconfigure): add firewall configuration
ovh/manager pull request #6396
Opened 2022-02-01 08:33 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-433
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Into OverTheBox autoconfigure, add the Firewall configuration

2022-02-09 08:52 UTC, JeremyDec requested changes

2022-02-09 08:52 UTC, JeremyDec commented on packages/manager/modules/overthebox/src/overthebox/autoconfigure/firewall/autoconfigure-firewall.controller.js
> +    }
Same story here than for https://github.com/ovh/manager/pull/6398 PR

2022-03-17 20:43 UTC, antleblanc requested changes

2022-03-17 20:43 UTC, antleblanc commented on packages/manager/modules/overthebox/src/overthebox/autoconfigure/translations/Messages_fr_FR.json
> +  "overTheBox_autoconfigure_firewall_target_optional": "Cible (optionel)",
**issue(blocking):** There are some typo (`optionel` must be replaced by `optionnel`).

2022-03-22 14:23 UTC, antleblanc approved these changes

2022-03-25 09:00 UTC, merged