fix(ip.byoip): fix byoip tracking issues
ovh/manager pull request #6472
Opened 2022-02-14 11:24 UTC by varun257

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/byoip`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-8440
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Fix Ip tracking issues

## Related

2022-02-15 07:12 UTC, antleblanc requested changes
@varun257 Could you please resolve existing conflicts?
Thank you!

2022-02-15 07:26 UTC, radireddy approved these changes

2022-02-15 07:27 UTC, ghyenne approved these changes

2022-02-15 08:24 UTC, anooparveti approved these changes

2022-02-22 07:06 UTC, antleblanc commented
@varun257 Might be interesting to rebase branches on `develop` in order to solve the following error (from Checks):

>  Run Jest tests / test (push) Failing after 3m — test 

It has been fixed on develop via the following commit: https://github.com/ovh/manager/commit/31800ccf94af6e035d24b7816f6240a7af383b61

Thank you!

2022-02-22 07:07 UTC, antleblanc requested changes
Could you please rebase on `develop` branch?

2022-02-25 08:27 UTC, merged