feat(sva): add field bankaccount holder
ovh/manager pull request #6481
Opened 2022-02-15 09:08 UTC by ghyenne

ref: MANAGER-8528
Signed-off-by: Guillaume Hyenne <guillaume.hyenne@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-8528 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I add field bankaccount holder in creation kyc form and bank account update.

## Related

2022-02-16 07:47 UTC, anooparveti approved these changes

2022-02-16 07:56 UTC, antleblanc approved these changes

2022-02-16 08:02 UTC, JeremyDec submitted a review, later dismissed

2022-02-16 09:43 UTC, Jisay approved these changes

2022-02-28 08:17 UTC, antleblanc requested changes
We might need to rebase the branch on `develop` in order to solve following error:

> Some checks were not successful

2022-03-08 14:48 UTC, mohammed-zahaf approved these changes

2022-03-08 17:26 UTC, antleblanc approved these changes

2022-03-08 17:26 UTC, antleblanc commented on packages/manager/apps/telecom/src/app/telecom/telephony/svaWallet/kyc/identity/overview-identity/overview-identity.html
> +<div data-ng-if="!$ctrl.editMode">
**nitpick(non-blocking):** We can get rid of `ng-scope` and `ng-binding` classes.

2022-03-08 17:26 UTC, antleblanc commented on packages/manager/apps/telecom/src/app/telecom/telephony/svaWallet/kyc/identity/form/form.html
> +                    <oui-modal
**question(non-blocking):** I'm wondering why we are not using a stateful modal here? Is there any reason?

2022-03-08 17:29 UTC, merged