fix(atinternet): import atInternet if no shell
ovh/manager pull request #6805
Opened 2022-04-01 12:32 UTC by zakariasahmane

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/ovh-shell-batch2
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

## Description

import old atInternet if no shell

2022-04-01 13:22 UTC, frenautvh submitted a review, later dismissed

2022-04-01 13:22 UTC, frenautvh commented on packages/manager/modules/at-internet-configuration/src/index.js
> +      trackingPlugin ? registerAtInternet(trackingPlugin) : 'atInternet',
'ngAtInternet'

2022-04-06 09:09 UTC, frenautvh submitted a review, later dismissed

2022-04-20 05:33 UTC, antleblanc requested changes
@zakariasahmane Could you please resolve existing conflicts? Thank you!

2022-04-28 08:08 UTC, closed without merging