feat(pci): removed region query #8895
ovh/manager pull request #6849
Opened 2022-04-07 13:50 UTC by vks-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/MANAGER-8895
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Manager PCI - Object storage and regionalization: Currenlty we are passing region(SBG) as hardcoded value, now we have a requirement to pass other region(GRA) to get the services and in future many more region will come. To pass the region dynamically we need to update 2API and pass region dynamically to get all the high perf services.

## Related

https://stash.ovh.net/projects/I2APIENDPOINTS/repos/cloud-project-storage/pull-requests/8/overview

2022-04-08 06:14 UTC, anooparveti approved these changes

2022-04-08 06:16 UTC, anooparveti requested changes
Could you please mention the ticket reference in the table?

2022-04-08 06:27 UTC, anooparveti submitted a review, later dismissed

2022-04-08 07:48 UTC, JeremyDec commented
Hello @vks-ovh, you should also sign off your commit

2022-04-08 09:12 UTC, ghyenne approved these changes

2022-04-08 09:22 UTC, radireddy approved these changes

2022-05-02 12:17 UTC, marie-j approved these changes

2022-05-02 12:19 UTC, merged