Fix/ovh shell integration chatbot display
ovh/manager pull request #6856
Opened 2022-04-08 13:01 UTC by chloren

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/ovh-shell-integration`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9055
| License          | BSD 3-Clause

## Description

Fixed chatbot display in container

2022-04-11 06:50 UTC, zakariasahmane approved these changes

2022-04-14 07:16 UTC, frenautvh commented on packages/manager/apps/hub/src/index.scss
> +  right: 320px;
please use rem instead of px

2022-04-15 08:47 UTC, Jisay approved these changes

2022-04-15 09:49 UTC, frenautvh requested changes

2022-04-15 09:49 UTC, frenautvh commented on packages/manager/apps/container/.eslintignore
> +__tests__
i don't think it should be part of this commit

2022-04-19 09:08 UTC, merged