fix(pnr): add top attribute on ui-kit elements
ovh/manager pull request #7108
Opened 2022-05-11 15:20 UTC by Jisay

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/product-nav-reshuffle`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9363
| License          | BSD 3-Clause

2022-05-11 15:34 UTC, cbourgois requested changes

2022-05-11 15:34 UTC, cbourgois commented on packages/manager/apps/dedicated/client/app/account/user/dashboard/user-dashboard.html
> +                                top="true"
Seems to redirect from `dedicated` to `dedicated`. 
Not external and not `buildURL`.

2022-05-11 15:34 UTC, cbourgois commented on packages/manager/apps/web/client/app/domain/general-informations/GENERAL_INFORMATIONS.html
> +                            top="true"
Are theses URLs external or results of `$state.href` ?

2022-05-11 15:34 UTC, cbourgois commented on packages/manager/apps/web/client/app/hosting/freedom/FREEDOM.html
> +                                top="true"
Not required. We need to use `_top` only for external URL or url builded with URLBuilder
We need to check more in details.

2022-05-12 10:00 UTC, Jisay commented
I have checked all the links and added `top` attribute to all of them that leaved the application.

2022-05-13 09:32 UTC, cbourgois approved these changes

2022-05-16 06:47 UTC, merged