fix(pnr): change onboarding popover position
ovh/manager pull request #7339
Opened 2022-06-10 12:42 UTC by Jisay

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/product-nav-reshuffle`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9527
| License          | BSD 3-Clause

## Description

Change the position of onboarding intro popover and remove `react-popper` dep.

2022-06-10 15:11 UTC, zakariasahmane requested changes

2022-06-10 15:11 UTC, zakariasahmane commented on packages/manager/apps/container/src/container/nav-reshuffle/onboarding/introduction.tsx
> +    console.log('coucou !');
```suggestion

```

2022-06-10 15:11 UTC, zakariasahmane commented on packages/manager/apps/container/src/container/nav-reshuffle/onboarding/style.module.scss
> +  right: 1.875rem !important;
Are the `!important` really needed?

2022-06-13 12:14 UTC, zakariasahmane approved these changes

2022-06-16 06:08 UTC, antleblanc approved these changes

2022-06-17 08:45 UTC, cbourgois submitted a review, later dismissed

2022-06-20 14:59 UTC, cbourgois approved these changes

2022-06-21 07:02 UTC, cbourgois commented
Sonar cloud Code smell fixed.

2022-06-21 13:50 UTC, merged