feat: remove enterprise-cloud-db for eol
ovh/manager pull request #7341
Opened 2022-06-10 14:19 UTC by jperchoc

DATATR-49

Signed-off-by: Jonathan Perchoc <jonathan.perchoc@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DATATR-49
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Remove entreprise-cloud-db application and menu entry.

2022-06-16 06:08 UTC, antleblanc approved these changes

2022-06-16 08:33 UTC, anooparveti submitted a review, later dismissed

2022-06-17 06:23 UTC, antleblanc requested changes
Some checks were not successful
> CDS/UXMAN-manager-test-v3 — test-v3: Fail 

Module `enterprise-cloud-database` is not fully removed (remains `onboarding` folder).

Could you please have a look? Thank you!

2022-06-20 04:37 UTC, antleblanc approved these changes

2022-06-22 10:19 UTC, anooparveti approved these changes

2022-08-11 07:29 UTC, anooparveti approved these changes

2022-08-29 06:06 UTC, antleblanc requested changes
@jperchoc Could you please resolve existing conflict?
Thank you!

2022-09-05 15:34 UTC, anooparveti approved these changes

2022-09-06 06:27 UTC, antleblanc approved these changes

2022-09-09 05:32 UTC, antleblanc approved these changes

2022-09-09 05:32 UTC, merged