docs(ovh-shell): add ovh shell docs
ovh/manager pull request #7419
Opened 2022-06-22 12:54 UTC by zakariasahmane

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

## Description

Add documentation for `ovh-shell` library.

2022-06-28 08:20 UTC, Jisay approved these changes

2022-06-29 07:17 UTC, antleblanc requested changes
That's a really good start!
Just left some comments regarding naming/punctuation (mainly).

2022-06-29 07:17 UTC, antleblanc commented on packages/components/ovh-shell/README.md
> +- `isMenuSidebarVisible() => boolean` : Returns if the PNR menu is displayed.
**question:** Shouldn't we found a name for this menu? PNR sounds more like a project name.

2022-06-29 07:25 UTC, zakariasahmane commented on docs/docs/guide/applications.md
> +| [Container](#container)               | EU / CA / US |
That's actually a very good question, i don't know if it should be added to the list of monolithic applications or have a section of its own. 

Maybe @frenautvh @Jisay or @cbourgois can help answer this question?

2022-06-29 07:27 UTC, zakariasahmane commented on docs/docs/guide/architecture.md
> +In order to enable the uFrontEnd architecture, we use what we call a `Container`. The container contains a standalone application and elements that are common to all applications.
@antleblanc I actually agree with you, i just didn't know how to type that character in my Mac and i thought, i'll copy it !

2022-06-29 15:59 UTC, merged