feat(storages.blocks.add): add iops and bandwidth info
ovh/manager pull request #7426
Opened 2022-06-23 13:00 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-8174
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
1. display `bandwidth` info for `HIGHT-SPEED-GEN-2` volume type
2. display `IOPS` info for all volumes types

2022-06-23 13:37 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
Same as [comment](https://github.com/ovh/manager/pull/7426/files#r905032214)

2022-06-23 13:37 UTC, anooparveti requested changes

2022-06-24 08:51 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
:)

2022-06-24 08:51 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
:)

2022-06-24 09:19 UTC, ghyenne approved these changes

2022-06-24 10:03 UTC, sachinrameshn submitted a review, later dismissed

2022-06-24 10:21 UTC, anooparveti approved these changes

2022-06-29 06:34 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
@mohammed-zahaf Any reason to keep `span` here?

2022-07-05 07:57 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
To be aligned with others used span into page.

2022-07-06 05:48 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
By "others" you mean siblings `<span>` elements?

Here all of them are using a `d-block` helper which in a sense is action as  what's @anooparveti  describe.

Why do we have to use a `<span>` element?

2022-07-07 11:46 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
Because most of HTML elements used in the page are `span`.
i kept `span` for this.

2022-07-08 06:23 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                    <span class="d-block"
We can safely replace them by block elements as mentioned by @anooparveti.

2022-07-11 06:13 UTC, antleblanc submitted a review, later dismissed

2022-07-20 11:04 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                       data-ng-if="$ctrl.isHighSpeedGen2Volume()"
I kept same behavior like we have for all `ng-if` directive (without one-time binding).

2022-07-20 12:08 UTC, JeremyDec commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                       data-ng-if="$ctrl.isHighSpeedGen2Volume()"
There is no point to have this behaviour here, calling the method once should be enough

2022-07-20 12:23 UTC, anooparveti submitted a review, later dismissed

2022-07-20 12:24 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/storages/blocks/add/add.html
> +                       data-ng-if="$ctrl.isHighSpeedGen2Volume()"
no, if we do with your suggestion, the Angular degist cycle will consider once the value and never re-compute it.
we have to display the related block according the selected offer => need to let normal digist cycle occure.

2022-07-22 05:46 UTC, anooparveti approved these changes

2022-07-27 10:48 UTC, merged