fix(container): navbar classic view height
ovh/manager pull request #7459
Opened 2022-06-29 13:08 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9516
| License          | BSD 3-Clause

## Description

fix navbar height in classic view

2022-06-30 06:09 UTC, antleblanc approved these changes

2022-06-30 07:17 UTC, JeremyDec approved these changes

2022-06-30 11:58 UTC, anooparveti submitted a review, later dismissed

2022-07-01 05:42 UTC, antleblanc requested changes
Some checks were not successful
> Run Jest tests / test (push) Failing after 3m — test 

Could you please have a look?
Thank you!

2022-08-09 10:06 UTC, antleblanc approved these changes

2022-08-09 14:55 UTC, JeremyDec approved these changes

2022-08-11 11:57 UTC, anooparveti approved these changes

2022-08-16 07:04 UTC, merged