feat(pci.project): gateway integration while creating Floating IP
ovh/manager pull request #7506
Opened 2022-07-07 07:27 UTC by anooparveti

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9233`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-9614
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Handle gateway integration use-cases while creating Floating IP

## Related

2022-07-07 13:37 UTC, ghyenne requested changes

2022-07-07 13:37 UTC, ghyenne commented on packages/manager/modules/pci/src/components/project/gateways/gateways-model-selector/controller.js
> +export default class PciProjectGatewayModelSelctorCtrl {
```suggestion
export default class PciProjectGatewayModelSelectorCtrl {
```

2022-07-07 13:41 UTC, anooparveti commented on packages/manager/modules/pci/src/components/project/gateways/gateways-model-selector/translations/Messages_fr_FR.json
> +  "pci_projects_project_public_gateways_catalog_publiccloud-gateway-l_price": "Prix :"
Because, we need to display label for each available size. It will be useful if we want to display different text for different sizes.

2022-07-11 06:57 UTC, frenautvh approved these changes

2022-07-12 05:17 UTC, sachinrameshn approved these changes

2022-07-12 11:04 UTC, merged