feat(kubernetes.add): remove client pooling after the creation a container
ovh/manager pull request #7545
Opened 2022-07-12 13:49 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9171` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-9171 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

1. task number 1
2. task ...

2022-07-12 14:01 UTC, anooparveti approved these changes

2022-07-15 09:27 UTC, sachinrameshn approved these changes

2022-07-26 11:46 UTC, mohammed-zahaf commented
Hello @brofik, avoid to put a direct link for Jira.
Prefer to fill a handy description

2022-07-26 11:48 UTC, mohammed-zahaf commented
Also, you have to add Jira ref into your commits.
It's mondatory, thanks

2022-07-27 06:42 UTC, anooparveti requested changes
Could you please include ticket ref in the commits?

2022-07-27 08:50 UTC, anooparveti approved these changes

2022-07-27 08:51 UTC, merged