fix(nasha.components): partition regex
ovh/manager pull request #7598
Opened 2022-07-19 07:12 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/nasha-refresh-deletions`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-9482
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2022-07-19 11:04 UTC, anooparveti approved these changes

2022-07-19 11:06 UTC, anooparveti requested changes
Some checks are not successful, Could you please check?

2022-07-22 07:02 UTC, y4nnL commented
Hi @anooparveti 
To fix this issue I need to rewrite a commit message that includes a breaking change on the main feature branch. I can assure you that this is the first thing I'll do once the remaining PRs are merged into the feature branch

2022-07-25 07:05 UTC, anooparveti approved these changes

2022-07-25 11:51 UTC, ghyenne approved these changes

2022-07-25 11:54 UTC, merged