fix(users): update horizon link for trusted zone
ovh/manager pull request #7716
Opened 2022-08-01 15:08 UTC by marie-j

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-86253
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related

2022-08-02 06:59 UTC, anooparveti approved these changes

2022-08-03 07:44 UTC, zakariasahmane approved these changes

2022-08-03 07:48 UTC, JeremyDec approved these changes

2022-08-08 14:05 UTC, antleblanc approved these changes

2022-08-08 14:32 UTC, antleblanc requested changes

2022-08-08 14:32 UTC, antleblanc commented on packages/manager/modules/pci/src/projects/project/users/users.routing.js
> +        (user.isTrusted ? HORIZON_LINK_TRUSTED : HORIZON_LINK)[
```suggestion
        (coreConfig.getUser().isTrusted ? HORIZON_LINK_TRUSTED : HORIZON_LINK)[
```

2022-08-08 14:50 UTC, antleblanc approved these changes

2022-08-08 15:00 UTC, merged