fix(telecom.voip): status update not working in contact section
ovh/manager pull request #7728
Opened 2022-08-04 12:21 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          |  DTRSD-94377 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I fixed the status update not working in contact section

## Related

2022-08-04 14:22 UTC, anooparveti approved these changes

2022-08-04 14:24 UTC, anooparveti commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.controller.js
> +        return this.$translate.instant('telephony_service_contact_sync');
**nitpick:** Fixes SonarCloud issues
```suggestion
      case DIRECTORY_INFO_STATUS.error:
      case DIRECTORY_INFO_STATUS.problem:
        return this.$translate.instant('telephony_service_contact_sync_error');
      case DIRECTORY_INFO_STATUS.done:
        return this.$translate.instant('telephony_service_contact_sync');
```

2022-08-04 14:25 UTC, anooparveti requested changes
Comment: https://github.com/ovh/manager/pull/7728/files#r937854443

2022-08-05 07:30 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.controller.js
> +        return this.$translate.instant('telephony_service_contact_sync');
It's applied

2022-08-05 07:47 UTC, JeremyDec approved these changes

2022-08-05 07:57 UTC, anooparveti approved these changes

2022-08-05 08:28 UTC, sachinrameshn approved these changes

2022-08-08 13:45 UTC, merged