fix(i18n): add missing translations [CDS 1767]
ovh/manager pull request #7749
Opened 2022-08-08 13:49 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9863 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
Add missing translations

## Related

2022-08-09 06:06 UTC, antleblanc approved these changes

2022-08-11 11:47 UTC, anooparveti requested changes
Could you please resolve the conflicts? Thanks!

2022-08-12 08:42 UTC, anooparveti approved these changes

2022-08-16 06:27 UTC, sachinrameshn approved these changes

2022-08-16 06:39 UTC, anooparveti approved these changes

2022-08-16 06:50 UTC, merged