fix(storage-containers): update name of static url
ovh/manager pull request #7819
Opened 2022-08-18 12:32 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9093`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9793
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2022-08-18 12:34 UTC, anooparveti approved these changes

2022-08-18 12:44 UTC, ghyenne approved these changes

2022-08-18 15:39 UTC, antleblanc requested changes
Some checks were not successful

> CDS/UXMAN-manager-test-v3 — test-v3: Fail

2022-08-23 06:36 UTC, antleblanc approved these changes

2022-08-23 06:36 UTC, anooparveti approved these changes

2022-08-23 07:18 UTC, merged