fix(container): pnr assistance auto hide
ovh/manager pull request #7844
Opened 2022-08-22 13:53 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | pnr-ga
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9593, MANAGER-9504
| License          | BSD 3-Clause

## Description

Auto hide assistance menu in sidebar when clicking on other items

2022-08-23 06:38 UTC, anooparveti approved these changes

2022-08-23 06:53 UTC, antleblanc approved these changes

2022-08-23 06:55 UTC, antleblanc requested changes
@frenautvh Could you please resolve existing conflicts?
Thank you!

2022-08-23 07:37 UTC, JeremyDec approved these changes

2022-08-24 05:54 UTC, antleblanc approved these changes

2022-08-24 05:54 UTC, merged