fix(billing.commitment): change content if no discount
ovh/manager pull request #7875
Opened 2022-08-25 11:41 UTC by ghyenne

ref: 

Signed-off-by: Guillaume Hyenne <guillaume.hyenne@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/sprint-2234-2236` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-9819 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I changed content if no discount

## Related

2022-08-26 09:40 UTC, anooparveti approved these changes

2022-08-26 09:41 UTC, anooparveti requested changes
> CDS/UXMAN-manager-installation-v3 — installation-v3: Fail

Could you please take a look on this?

2022-08-26 10:34 UTC, ghyenne commented
> > CDS/UXMAN-manager-installation-v3 — installation-v3: Fail
> 
> Could you please take a look on this?

It was an issue with TLS connection. I have relaunch the workflow it's good now.

2022-08-26 13:05 UTC, anooparveti approved these changes

2022-08-29 07:51 UTC, brofik approved these changes

2022-08-29 07:53 UTC, JeremyDec approved these changes

2022-09-14 08:06 UTC, merged