Refactor/remove testcafe
ovh/manager pull request #7894
Opened 2022-08-29 13:42 UTC by JeremyDec

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` / `release/**` / `develop` 
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2022-08-30 15:24 UTC, marie-j submitted a review, later dismissed

2022-08-30 15:27 UTC, antleblanc requested changes

2022-08-30 15:27 UTC, antleblanc commented on .gitignore
>  /reports
```suggestion
```

2022-08-31 08:38 UTC, antleblanc approved these changes

2022-09-05 08:10 UTC, marie-j approved these changes

2022-09-07 13:02 UTC, merged