Improve container routing / bump react vite / improve vite dev experience
ovh/manager pull request #7937
Opened 2022-09-05 11:55 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | yes
| Tickets          | MANAGER-9806
| License          | BSD 3-Clause

## Description

- Rewrite routing for shell application with better capabilities (application path + application hash)
- Bump React in container to v18
- Bump vite to v3
- Add hot module reload capabilities in dev for both container & contained application

2022-09-05 11:57 UTC, antleblanc commented
:eyes:  #7901

2022-09-08 06:46 UTC, antleblanc requested changes
@frenautvh Could you please resolve existing conflict?
Thank you!

2022-09-09 13:02 UTC, marie-j requested changes

2022-09-09 13:02 UTC, marie-j commented on packages/manager/core/vite-config/package.json
> +  "private": "true",
```suggestion
  "private": true,
```

2022-09-09 13:02 UTC, marie-j commented on packages/manager/core/vite-config/package.json
> +    "@ovh-ux/manager-dev-server-config": "^3.0.0 || ^4.0.0",
```suggestion
    "@ovh-ux/manager-dev-server-config": "^4.0.0",
```

2022-09-09 13:58 UTC, Jisay submitted a review, later dismissed

2022-09-21 09:26 UTC, cbourgois submitted a review, later dismissed

2022-09-23 08:52 UTC, Jisay approved these changes

2022-09-26 08:01 UTC, marie-j commented on packages/manager/modules/config/package.json
> +}
Isn't typescript not needed anymore ? I still see `.ts` files in this module

2022-10-10 07:50 UTC, Jisay approved these changes

2022-10-12 09:01 UTC, merged