fix(storages:s3 tab): fix issue of refresh
ovh/manager pull request #7952
Opened 2022-09-06 12:10 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9093`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10009
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~ [n/a]
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

 Addition of refresh containers capability in Object-storage containers page

2022-09-06 12:12 UTC, anooparveti requested changes

2022-09-06 12:12 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/storages/object-storage/users/users.routing.js
> +      refreshS3Credentials: /* @ngInj ect */ ($state, projectId) => () => {
```suggestion
      refreshS3Credentials: /* @ngInject */ ($state, projectId) => () => {
```

2022-09-06 12:13 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/storages/object-storage/users/users.routing.js
> +      refreshS3Credentials: /* @ngInj ect */ ($state, projectId) => () => {
Done Anoop

2022-09-07 12:31 UTC, mohammed-zahaf approved these changes

2022-09-07 12:37 UTC, merged