fix(pci.project): diable Assigner une IP flottante button
ovh/manager pull request #7967
Opened 2022-09-08 14:18 UTC by vks-ovh

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/l3-services` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-9970
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- ~~[ ] Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

Disable Assigner une IP flottante instead of showing and hiding.

## Related

2022-09-08 14:43 UTC, anooparveti requested changes

2022-09-08 14:43 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/instances/instances.html
> +                data-disabled="$row.hasPublicIpV4() && $row.hasPublicIpV6() && $ctrl.isAdditionalIpsAvailable"
**nitpick:** Should be displayed only if Floating IP is supported in the region.
```suggestion
                data-ng-if=" $ctrl.isAdditionalIpsAvailable"
                data-disabled="$row.hasPublicIpV4() && $row.hasPublicIpV6()"
```

2022-09-09 05:10 UTC, anooparveti approved these changes

2022-09-09 06:32 UTC, sachinrameshn approved these changes

2022-09-09 06:43 UTC, merged