feat(dedicated-ip): separate failover from all ips
ovh/manager pull request #8043
Opened 2022-09-21 07:02 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/ip-strat`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-9611
| License          | BSD 3-Clause

- [ ] ~~Try to keep pull requests small so they can be easily reviewed.~~
- [X] Commits are signed-off
- [X] Only FR translations have been updated
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2022-09-21 09:48 UTC, anooparveti reviewed
**nitpick:** Could you please remove the empty file `packages/manager/apps/dedicated/client/app/ip/ip.component.js`

2022-09-21 09:55 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/list.controller.js
> +    }
**question:** Can we refactor and attach on controller object instead of `$scope`?

2022-09-21 10:03 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/list.html
> +    <table class="table table-hover" id="module-ip-table">
**question:** Now that we have a separate tabs for all the types of IPs, can we use `oui-datagrid` with expandable rows instead?
Ref: https://ovh.github.io/ovh-ui-kit/?path=/docs/design-system-components-datagrid-webcomponent--expandable-rows

2022-09-26 03:46 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/ip/ip.routing.js
> +      const universe = coreConfig.getUniverse() === 'server' ? 'server' : 'hpc';
Can we maintain server and hpc in constant file.

2022-09-27 06:22 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/ip/failover/translations/Messages_fr_FR.json
> +  "ip_failover_text": "Les IP failover sont des adresses IP publiques qui peuvent être transférées dynamiquement d’un service OVHcloud à l’autre. Ces adresses sont disponibles sous forme d’adresses i
i guess better `à un autre` ?

 ```suggestion
  "ip_failover_text": "Les IP failover sont des adresses IP publiques qui peuvent être transférées dynamiquement d’un service OVHcloud à un autre. Ces adresses sont disponibles sous forme d’adresses individuelles ou sous forme de blocs d’adresses."
```

2022-09-27 06:30 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/ip/ip.html
> +                href="{{ dashboardLink }}"
```suggestion
                href="{{:: dashboardLink }}"
```

2022-09-27 06:30 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/ip/ip.html
> +                href="{{ failoverLink }}"
```suggestion
                href="{{:: failoverLink }}"
```

2022-09-27 06:33 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/ip/components/list/list.html
> +                <td></td>
no value ?

2022-09-27 06:49 UTC, mohammed-zahaf commented on packages/manager/apps/dedicated/client/app/ip/components/list/list.html
> +                <td></td>
No values ?

2022-09-27 06:52 UTC, JeremyDec requested changes
Hello @y4nnL, your branch isn't successful on build stage, from your CDS run. Could you please check

2022-09-27 08:58 UTC, y4nnL commented
@JeremyDec rebased on master and... Fixed :)

2022-09-27 09:21 UTC, anooparveti approved these changes

2022-09-27 09:50 UTC, sachinrameshn approved these changes

2022-09-27 10:24 UTC, merged