fix(dedicated.helpcenter): add modal for helpcenter for ca and eu
ovh/manager pull request #8281
Opened 2022-10-24 14:34 UTC by stif59100

| Question         | Answer
| ---------------- | ---
 Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10138
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I created a modal for new helpcenter on the support manager ticket.

## Related

2022-10-25 09:05 UTC, vks-ovh commented on packages/manager/modules/support/src/modal/modal.html
> +            <img data-ng-src="{{ $ctrl.illustration }}" alt="" />
Can we put some good name for `alt` instead of keeping it empty ?

2022-10-25 09:44 UTC, vks-ovh approved these changes

2022-10-25 10:28 UTC, ghyenne requested changes

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/support.component.js
> +  bindings: { goToHelpCenterModal: '<' },
No need "goToHelpCenterModal: '<'"

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/modal.constants.js
> +export const EVENT_NAMES = {
isn't use.

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/modal.constants.js
> +export const EVENT_NAMESPACE = 'modal.events';
Isn't use

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/index.js
> +      url: '/modal',
In module you use url: '/betaHelpCenter', should to be same.

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/modal.html
> +    loading="$ctrl.isLoading"
Isn't defined.

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/modal.routing.js
> +      features: /* @ngInject */ (ovhFeatureFlipping) => {
You can use a more explicit variable.

2022-10-25 10:28 UTC, ghyenne commented on packages/manager/modules/support/src/modal/modal.routing.js
> +      },
```suggestion
      features: /* @ngInject */ (ovhFeatureFlipping) => ovhFeatureFlipping.checkFeatureAvailability(FEATURES),
```

2022-10-25 13:55 UTC, stif59100 commented
I cleaned up my code.

It was not necessary to do a featureFlipping because the dispatch is done directly in the sidebar.

2022-10-25 14:56 UTC, cbourgois commented on packages/manager/modules/support/src/modal/modal.scss
> +h1 {
IMO you shouldn't override global styles.

2022-10-26 10:51 UTC, vks-ovh approved these changes

2022-10-26 11:03 UTC, mohammed-zahaf commented on packages/manager/modules/support/src/modal/translations/Messages_fr_FR.json
> +  "modal_beta_help_center_please_note": "Découvrez la dès maintenant en basculant sur la nouvelle interface et faites-nous part de votre avis.",
i am not stotaly sure but may be it's like this :
```suggestion
  "modal_beta_help_center_please_note": "Découvrez là dès maintenant en basculant sur la nouvelle interface et faites-nous part de votre avis.",
```

2022-10-26 11:15 UTC, mohammed-zahaf commented on packages/manager/modules/support/src/modal/modal.html
> +                alt="Beta image modal"
I think it's a good practice to have put this.
So, we can add a French alternative description.

`alt="{{ 'ma_description' | translate }}"`

2022-10-26 11:17 UTC, mohammed-zahaf commented on packages/manager/modules/support/src/modal/modal.constants.js
> +  DE: `${helpRoot}/de${homeIndex}`,
it's a good practice to have a default entry (en for example).
```suggestion
  DEFAULT: `${helpRoot}/en${homeIndex}`,
  DE: `${helpRoot}/de${homeIndex}`,
```

2022-10-26 11:34 UTC, anooparveti commented on packages/manager/modules/support/src/modal/modal.controller.js
> +    this.window = $window;
```suggestion
    this.$window = $window;
```

2022-10-26 11:39 UTC, anooparveti commented on packages/manager/modules/support/src/modal/modal.scss
> +    color: $p-500;
**nitpick:** Can we directly use `oui-color-p-500` class on the required tag?

2022-10-26 11:40 UTC, anooparveti commented on packages/manager/modules/support/src/modal/modal.scss
> +    float: right;
**nitpick:** Use `float-right` from bootstrap

2022-10-26 13:03 UTC, mohammed-zahaf submitted a review, later dismissed

2022-10-26 14:30 UTC, anooparveti commented on packages/manager/modules/support/src/modal/modal.html
> +                variant-nav="next"
```suggestion
                data-on-click="$ctrl.goBack()"
                data-variant="link"
                data-variant-nav="next"
```

2022-10-26 14:42 UTC, anooparveti approved these changes

2022-10-26 14:52 UTC, ghyenne requested changes

2022-10-26 14:52 UTC, ghyenne commented on packages/manager/modules/support/src/modal/translations/Messages_fr_FR.json
> +  "modal_description_image": " Aperçu du centre d'aide"
```suggestion
  "modal_description_image": "Aperçu du centre d'aide"
```

2022-10-26 15:00 UTC, anooparveti approved these changes

2022-10-26 15:04 UTC, ghyenne submitted a review, later dismissed

2022-10-27 03:46 UTC, vks-ovh approved these changes

2022-10-27 05:10 UTC, mohammed-zahaf commented
Hello @stif59100 , i guess you have to target the `release/sprint-2242-2244` ?

2022-10-28 09:51 UTC, antleblanc commented on packages/manager/modules/support/src/modal/modal.controller.js
> +    this.$translate = $translate;
**nitpick:** Looks like `$translate` is unused.

2022-10-28 12:16 UTC, mohammed-zahaf approved these changes

2022-10-28 12:18 UTC, ghyenne approved these changes

2022-11-17 13:43 UTC, ghyenne approved these changes

2022-11-17 13:50 UTC, anooparveti approved these changes

2022-11-21 09:03 UTC, merged