fix(pcc.athos): remove cta order for end of sales of anthos
ovh/manager pull request #8347
Opened 2022-11-07 10:16 UTC by stif59100

| Question         | Answer
| ---------------- | ---
 Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10309
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I remove the cta order for anthos on pcc.

## Related

2022-11-07 10:27 UTC, cbourgois requested changes
I see multiples files edited, not related to this issue.
You have to rebase/clean.

2022-11-07 10:27 UTC, cbourgois commented on packages/manager/modules/anthos/src/anthos.html
> -        <oui-datagrid-topbar>
Should be feature flipped.

2022-11-07 11:06 UTC, frenautvh submitted a review, later dismissed

2022-11-07 13:24 UTC, anooparveti submitted a review, later dismissed

2022-11-08 13:45 UTC, mohammed-zahaf submitted a review, later dismissed

2022-11-08 15:06 UTC, ghyenne submitted a review, later dismissed

2022-11-09 08:12 UTC, ghyenne approved these changes

2022-11-09 08:12 UTC, mohammed-zahaf approved these changes

2022-11-09 08:37 UTC, cbourgois approved these changes

2022-11-16 05:38 UTC, merged