feat(dedicated.server): display endoflife information
ovh/manager pull request #8413
Opened 2022-11-22 02:58 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | ` release/sprint-2246-2248`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-7544
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

Description: 
When customer is installing an OS on a dedicated server, the OS end of support at OVH should be displayed to customer.

2022-11-22 08:18 UTC, ghyenne approved these changes

2022-11-22 09:42 UTC, mohammed-zahaf approved these changes

2022-11-23 08:56 UTC, JayBeeDe requested changes

2022-11-24 06:57 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/dedicated/server/translations/Messages_fr_FR.json
> +  "dedicated_servers_installation_customer_template_wizard_message": " À partir de {{ eolDate }}, il ne sera plus possible de lancer une réinstallation de {{ osName }} sur votre serveur dédié, et vot
Done

2022-11-24 06:57 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/dedicated/server/translations/Messages_fr_FR.json
> +  "dedicated_servers_installation_ovhcloud_template_wizard_message": "À partir de {{ eolDate }}, il ne sera plus possible de lancer une réinstallation de {{ osDescription }} sur votre serveur dédié.
Done

2022-11-24 07:07 UTC, ghyenne approved these changes

2022-11-24 07:59 UTC, mohammed-zahaf approved these changes

2022-12-16 11:08 UTC, ghyenne approved these changes

2022-12-19 09:27 UTC, stif59100 submitted a review, later dismissed

2023-01-12 12:58 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/dedicated/server/installation/gabarit/dedicated-server-installation-gabarit.html
> +                                            </i>
```suggestion
                                            <i
                                                class="pl-2 fa"
                                                aria-hidden="true"
                                                data-ng-class="{
                                                    'fa-warning' : showEndOfLifeMessage(gabarit.endOfInstall,true),
                                                    'fa-info-circle' : showEndOfLifeMessage(gabarit.endOfInstall,false),
                                                }"
                                                data-oui-tooltip="{{ getEndOfLifeMessage(gabarit) }}"
                                                data-oui-tooltip-placement="bottom"
                                            >
                                            </i>
```

2023-01-30 15:19 UTC, stif59100 approved these changes

2023-01-30 15:20 UTC, merged