feat(storage.cold-archive): label a cold-archive as an"archive" instead of "container"
ovh/manager pull request #8500
Opened 2022-12-05 08:21 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9069` 
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-10495 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2022-12-05 09:41 UTC, stif59100 approved these changes

2022-12-05 09:49 UTC, vks-ovh approved these changes

2022-12-06 08:39 UTC, anooparveti requested changes
Hello @brofik,
Could you please resolve the conflicts?
Thanks!

2022-12-07 05:52 UTC, anooparveti approved these changes

2022-12-07 05:54 UTC, anooparveti reviewed
Could you please make the commit and PR title short?
Suggestion: `feat(storage.cold-archive): rename container to cold-archive`

2022-12-08 14:58 UTC, merged