fix(pci): add unit for bandwidth
ovh/manager pull request #8521
Opened 2022-12-07 05:17 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/sprint-2248-2250` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #... MANAGER-10316
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ (not applicable)

## Description
Bandwidth unit is missing

## Related

:flags: Translations:
- [x] TRANS-48054

2022-12-07 05:28 UTC, anooparveti requested changes

2022-12-07 05:28 UTC, anooparveti commented on packages/manager/modules/pci/src/components/project/gateways/gateways-model-selector/controller.js
> +            'pci_projects_project_gateways_model_selector_bandwidth_unit_size_Gbps',
```suggestion
            'pci_projects_project_gateways_model_selector_bandwidth_unit_size_Mbps',
```

2022-12-07 05:28 UTC, anooparveti commented on packages/manager/modules/pci/src/components/project/gateways/gateways-model-selector/translations/Messages_fr_FR.json
> +  "pci_projects_project_gateways_model_selector_bandwidth_unit_size_Gbps": " Gbps"
```suggestion
  "pci_projects_project_gateways_model_selector_bandwidth_unit_size_mbps": " Mbps",
  "pci_projects_project_gateways_model_selector_bandwidth_unit_size_gbps": " Gbps"
```

2022-12-07 05:37 UTC, sachinrameshn commented on packages/manager/modules/pci/src/components/project/gateways/gateways-model-selector/controller.js
> +          );
Okay Anoop

2022-12-07 05:50 UTC, anooparveti approved these changes

2022-12-07 06:36 UTC, mohammed-zahaf approved these changes

2022-12-27 11:23 UTC, anooparveti approved these changes

2022-12-27 11:24 UTC, merged