feat(dedicated.otrs): paginate support tickets
ovh/manager pull request #8540
Opened 2022-12-09 12:54 UTC by anooparveti

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/sprint-2248-2250`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10469
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

 Display Server side paginated support tickets
 Known inconsistencies: Filtering and Sorting is handled on the current page records

2022-12-12 09:41 UTC, stif59100 approved these changes

2022-12-12 09:42 UTC, brofik requested changes
Could you please remove the translation files other than the ``fr_FR one`` ?

2022-12-13 08:52 UTC, anooparveti commented
> Could you please remove the translation files other than the `fr_FR one` ?

Hello Rafik, this is a copy/paste of existing component from different module. That's why there is no reason to go through the trans cycle as there is no mismatch in the existing data at memsource level and manager.

2022-12-13 09:43 UTC, brofik approved these changes

2022-12-13 09:43 UTC, stif59100 approved these changes

2022-12-14 08:06 UTC, merged