fix(server-sidebar): add CA US links for Kub OCC
ovh/manager pull request #8556
Opened 2022-12-13 08:54 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-96864
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2022-12-13 09:00 UTC, stif59100 approved these changes

2022-12-13 09:00 UTC, ghyenne submitted a review, later dismissed

2022-12-13 09:00 UTC, vks-ovh submitted a review, later dismissed

2022-12-13 09:01 UTC, anooparveti approved these changes

2022-12-13 09:03 UTC, anooparveti requested changes
Can you check if the OVHcloud connect is coming in CA Manager with this change? If not, let me know, I know the fix.

2022-12-13 09:36 UTC, anooparveti submitted a review, later dismissed

2022-12-13 10:09 UTC, mohammed-zahaf approved these changes

2023-01-04 07:33 UTC, sachinrameshn approved these changes

2023-01-04 07:39 UTC, anooparveti approved these changes

2023-01-10 16:19 UTC, merged