fix(dedicated.account): add check on siret form
ovh/manager pull request #8574
Opened 2022-12-15 14:41 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `fix/MANAGER-9844`  
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10517 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added the check on siret form

## Related

2022-12-16 09:40 UTC, anooparveti requested changes

2022-12-16 09:40 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/account/user/components/newAccountForm/new-account-form-controller.js
> +        };
**nitpick:** unnecessary destructuring
```suggestion
        this.siretModuleRules[rule.fieldName] = {
            mandatory: rule.mandatory,
            regularExpression: rule.regularExpression,
        };
```

2022-12-16 11:14 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/account/user/components/newAccountForm/new-account-form-controller.js
> +        };
It's applied.

2022-12-19 04:49 UTC, anooparveti approved these changes

2022-12-19 08:53 UTC, merged