fix(user-account-menu): add missing fr traduction key
ovh/manager pull request #8607
Opened 2022-12-21 09:12 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-99791 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added missing / lost fr traduction key. in other traduction files is it exist.

## Related

2022-12-21 09:41 UTC, stif59100 approved these changes

2022-12-21 09:49 UTC, brofik approved these changes

2022-12-21 10:03 UTC, sachinrameshn approved these changes

2023-01-02 15:35 UTC, anooparveti commented
Pulling translations.

2023-01-03 06:23 UTC, anooparveti requested changes
Translations commit is empty. Checking with Trads team

2023-01-06 08:25 UTC, anooparveti approved these changes

2023-01-10 15:36 UTC, merged