Fix/dtrsd 93019
ovh/manager pull request #8624
Opened 2022-12-23 11:03 UTC by stif59100

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/sprint-2250-2252
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-93019
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I deleted balise <b> on trad english anormaly

## Related

2022-12-23 11:12 UTC, ghyenne approved these changes

2022-12-23 11:21 UTC, mohammed-zahaf approved these changes

2022-12-28 07:40 UTC, anooparveti requested changes
Could you please get this change from trans request?

2023-01-02 12:19 UTC, stif59100 commented
> Could you please get this change from trans request?

TRANS-48470 it's done we haven't this on trad

2023-01-10 15:16 UTC, merged