fix(storage.cold-archive): ajust size field inputs in add Cold-Archive view
ovh/manager pull request #8636
Opened 2022-12-26 23:50 UTC by brofik

ref: MANAGER-10605
Signed-off-by: Rafik Adiche <rafik.adiche.ext@corp.ovh.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-9069` / `release/**` / `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-10605 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2022-12-27 05:54 UTC, anooparveti requested changes
Could you please correct the typo in the commit title?
`ajust` -> `adjust`

2022-12-27 07:39 UTC, anooparveti commented
> Could you please correct the typo in the commit title? `ajust` -> `adjust`

You also need to change in the commit title and push it again. @brofik

2022-12-27 11:31 UTC, brofik commented
> > Could you please correct the typo in the commit title? `ajust` -> `adjust`
> 
> You also need to change in the commit title and push it again. @brofik

Done.

2022-12-28 07:38 UTC, anooparveti approved these changes

2022-12-28 08:36 UTC, merged