sync: master to develop
ovh/manager pull request #8646
Opened 2022-12-28 15:08 UTC by anooparveti

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #... 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

Synchronise master to develop

2022-12-29 11:12 UTC, antleblanc requested changes
Some checks were not successful
> CDS/UXMAN-manager-build-v4 — build-v4: Fail

Could you please have a look? Thank you!

2022-12-29 11:53 UTC, anooparveti commented
> Some checks were not successful
> 
> > CDS/UXMAN-manager-build-v4 — build-v4: Fail
> 
> Could you please have a look? Thank you!

Hello @antleblanc, I re-ran the failed workflow. It is good now.

2022-12-29 13:04 UTC, antleblanc approved these changes

2023-01-02 03:39 UTC, sachinrameshn approved these changes

2023-01-02 12:02 UTC, frenautvh approved these changes

2023-01-02 12:11 UTC, merged