Build/node 18
ovh/manager pull request #8679
Opened 2023-01-04 13:19 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | yes
| Tickets          | DTCORE-78
| License          | BSD 3-Clause

## Description

Bump monorepo to node 18 & webpack 5

2023-01-04 14:00 UTC, anooparveti approved these changes

2023-01-10 19:22 UTC, antleblanc requested changes
Could you please resolve existing conflicts? Thank you!

2023-01-11 07:48 UTC, frenautvh commented
rebased on master de02b1600dafb80ad48395ccc4576049991fb46f

2023-03-08 08:41 UTC, frenautvh commented
rebased on master a84bf63d00bd3ce3f477635129436c45bf4d0c81

2023-06-08 07:04 UTC, cbourgois commented
Rebased on `master`

2023-06-08 07:06 UTC, antleblanc approved these changes

2023-07-13 07:02 UTC, antleblanc submitted a review, later dismissed

2023-08-10 07:38 UTC, qpavy commented on packages/manager/modules/pci/src/projects/creating/index.scss
> +      stroke-dashoffset: calc(-#{$d} / 3);
```suggestion
      stroke-dashoffset: calc(-$d / 3);
```
Why need string encapsulation here as $d is a number ?

2023-08-10 07:45 UTC, qpavy commented on packages/manager/modules/pci/src/projects/project/creating/creating.scss
> +      stroke-dashoffset: calc(-#{$d} / 3);
same as https://github.com/ovh/manager/pull/8679/files#r1289693974

2023-08-10 14:37 UTC, antleblanc submitted a review, later dismissed

2023-08-11 09:23 UTC, sachinrameshn approved these changes

2023-08-14 06:37 UTC, sachinrameshn approved these changes

2023-08-14 06:56 UTC, antleblanc submitted a review, later dismissed

2023-09-06 06:25 UTC, sachinrameshn approved these changes

2023-09-06 06:25 UTC, BrunoMarquesOVH approved these changes

2023-09-06 06:30 UTC, merged