fix(dedicated.ipstrat): add tag for additional ip ip blocks
ovh/manager pull request #8700
Opened 2023-01-06 13:50 UTC by stif59100

ref:MANAGER-10324

Signed-off-by: stif59100 <steeve.vanderstocken@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` /
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10324
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I add a tag for additional ip blocks

## Related

2023-01-06 13:55 UTC, sachinrameshn approved these changes

2023-01-06 13:56 UTC, anooparveti requested changes
**nitpick:** there is no module called `ipstrat` Could you please correct it to `ip`?

2023-01-06 15:32 UTC, ghyenne approved these changes

2023-01-11 07:06 UTC, anooparveti approved these changes

2023-01-19 16:26 UTC, ghyenne approved these changes

2023-01-20 02:44 UTC, sachinrameshn approved these changes

2023-03-07 00:00 UTC, closed without merging

2023-06-28 08:37 UTC, anooparveti commented
Hello @stif59100,
I see that the PR is closed. If the branch is not required anymore, may I request you to delete the branch on origin?
Thanks!