fix(telecom.sms): add guide shortcut at top of page
ovh/manager pull request #8757
Opened 2023-01-16 09:50 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/telecom_sms_smpp_ga` !-- target branch -->
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10718 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added guide shortcut at top of page

## Related

2023-01-16 13:06 UTC, anooparveti commented on packages/manager/modules/sms/src/sms.component.js
> +
```suggestion
```

2023-01-16 13:10 UTC, anooparveti approved these changes

2023-01-16 13:15 UTC, ghyenne commented on packages/manager/modules/sms/src/sms.component.js
> +
It's fixed.

2023-01-18 08:00 UTC, y4nnL requested changes

2023-01-18 09:15 UTC, ghyenne commented on packages/manager/modules/sms/src/sms.html
> +    <oui-guide-menu text="{{ 'sms_header_guide' | translate }}">
It's applied.

2023-01-18 09:18 UTC, ghyenne commented on packages/manager/modules/sms/src/sms/telecom-sms.html
> +    placement="end"
It's applied.

2023-01-18 09:18 UTC, ghyenne commented on packages/manager/modules/sms/src/sms/telecom-sms.html
> +                data-ng-if="!$ctrl.isSmppAccount"
I need the variable.

2023-01-18 09:18 UTC, ghyenne commented on packages/manager/modules/sms/src/sms/telecom-sms.html
> +                data-ng-if="!$ctrl.isSmppAccount"
I need the variable.

2023-01-18 09:19 UTC, ghyenne commented on packages/manager/modules/sms/src/sms/telecom-sms.routing.js
> +        })),
It isn't easy because it isn't parent or child state.

2023-01-18 09:20 UTC, ghyenne commented on packages/manager/modules/sms/src/sms/telecom-sms.html
> +                data-ng-if="!$ctrl.isSmppAccount"
I need the variable.

2023-01-20 09:55 UTC, stif59100 approved these changes

2023-01-20 10:03 UTC, merged