fix(dedicated.ip): optimize the size of the ip dashboard
ovh/manager pull request #8794
Opened 2023-01-24 10:57 UTC by stif59100

ref:MANAGER-10553

Signed-off-by: stif59100 <steeve.vanderstocken@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/sprint-2302-2304
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGE-10553
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I optimize the size of the IP dashboard.

## Related

2023-01-24 11:05 UTC, anooparveti requested changes
**issue(blocking)**: There are multiple `tr` in the html. You need to remove the column from all the `tr`

2023-01-24 15:35 UTC, anooparveti submitted a review, later dismissed

2023-01-26 07:38 UTC, mohammed-zahaf submitted a review, later dismissed

2023-01-30 15:18 UTC, sachinrameshn approved these changes

2023-01-31 09:57 UTC, anooparveti approved these changes

2023-01-31 09:59 UTC, merged