feat(pci.ai): datatr-180 - ai deploy - add label free during beta
ovh/manager pull request #8802
Opened 2023-01-25 14:07 UTC by jperchoc

datatr-180

Signed-off-by: Jonathan Perchoc <jonathan.perchoc@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #datatr-180
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Add a label "free during beta" for ai deploy

2023-01-25 15:21 UTC, ClaveauAlex submitted a review, later dismissed

2023-01-27 06:27 UTC, mohammed-zahaf commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/components/app-review/translations/Messages_fr_FR.json
> +  "pci_app_add_review_price_free_during_beta": "Gratuit pendant la beta",
```suggestion
  "pci_app_add_review_price_free_during_beta": "Gratuit pendant la bêta",
```

2023-01-27 06:27 UTC, mohammed-zahaf submitted a review, later dismissed

2023-01-27 09:06 UTC, jperchoc commented on packages/manager/modules/pci/src/projects/project/ai/apps/add/components/app-review/translations/Messages_fr_FR.json
> +  "pci_app_add_review_price_free_during_beta": "Gratuit pendant la beta",
Changed here: https://github.com/ovh/manager/pull/8802/commits/638f1cf72e1f7d54052fb7fdf18618dd533f91fd
Thanks !

2023-01-27 09:38 UTC, mohammed-zahaf approved these changes

2023-01-27 10:01 UTC, y4nnL reviewed
Hello,
Have you considered adding a `beta` option to the `ovh-manager-catalog-price` component that defaults to `false` to prevent any side effects, and would display a beta badge and `<del></del>` its content when it is set to `true` ?

2023-01-27 13:32 UTC, ClaveauAlex approved these changes

2023-01-27 15:45 UTC, y4nnL requested changes
@jperchoc can you please have a look at my previous comment
Other projects could use this option :+1:

2023-01-30 08:51 UTC, jperchoc commented
Hi @y4nnL , this sound like an awesome feature that could/should be added to the manager project. It would also simplify the tags on the left menu, which are hardcoded too.
However, I'm afraid that this is more a feature request, that should be handled in a separate PR, with further testing and QA, as it could break existing things. 
This PR is expected to reach prod quickly, as it is a very important information for our users.

2023-01-30 09:32 UTC, ClaveauAlex commented on packages/manager/modules/catalog-price/src/catalog-price.html
> +            <strong data-ng-class="{ 'd-block': $ctrl.block}">
```suggestion
            <strong data-ng-class="{ 'd-block': $ctrl.block }">
```

2023-01-30 09:44 UTC, jperchoc commented on packages/manager/modules/catalog-price/src/catalog-price.controller.js
> +    // Set bate to false by default
fixed: https://github.com/ovh/manager/pull/8802/commits/fd17b19a828fc8baec980f1b8951b7f43d8a7a75

2023-01-30 09:44 UTC, jperchoc commented on packages/manager/modules/catalog-price/src/catalog-price.html
> +            <strong data-ng-class="{ 'd-block': $ctrl.block}">
Fixed: https://github.com/ovh/manager/pull/8802/commits/fd17b19a828fc8baec980f1b8951b7f43d8a7a75

2023-01-30 09:45 UTC, ClaveauAlex submitted a review, later dismissed

2023-01-30 09:47 UTC, mohammed-zahaf approved these changes

2023-01-30 12:34 UTC, ClaveauAlex approved these changes

2023-01-30 13:17 UTC, y4nnL approved these changes

2023-02-06 10:35 UTC, anooparveti approved these changes

2023-02-09 10:54 UTC, merged