fix(pcc): nsx batch 1
ovh/manager pull request #8829
Opened 2023-01-30 15:57 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10153 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

## Related
:flags: Translations
- [x] TRANS-51126
- [x] TRANS-51135

2023-01-31 16:20 UTC, anooparveti submitted a review, later dismissed

2023-02-13 13:22 UTC, anooparveti approved these changes

2023-04-07 14:27 UTC, anooparveti requested changes

2023-04-07 14:27 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/dashboard/tiles/options/components/nsxt/nsxt.html
> +    </dt>
```suggestion
    <dt>
        <span data-translate="{{:: 'ovhManagerPccDashboardOptionsNsxt_name' }}"></span>
        <button
            type="button"
            class="oui-popover-button"
            oui-popover="{{ 'ovhManagerPccDashboardOptionsNsxt_tooltip' | translate }}"
        ></button>
    </dt>
```

2023-04-25 14:49 UTC, ghyenne commented on packages/manager/apps/dedicated/client/app/components/dedicated-cloud/dashboard/tiles/options/components/nsxt/nsxt.html
> +    </dt>
I fixed up

2023-05-31 12:24 UTC, darsene approved these changes

2023-05-31 12:27 UTC, merged