fix(dedicated.server): commitment feature not showing cancel options
ovh/manager pull request #8866
Opened 2023-02-06 10:18 UTC by stif59100

ref:DTRSD-83000

Signed-off-by: stif59100 <steeve.vanderstocken@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/components-w7`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-83000
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I corrected commitment feature not showing "Cancel" options

## Related

2023-02-06 12:14 UTC, ghyenne approved these changes

2023-02-06 12:19 UTC, anooparveti requested changes
**question:** I dont see all the changes required for the ticket. If server does not have engagementDetails, we have to call an `serviceInfos` API.

2023-02-06 13:10 UTC, anooparveti requested changes

2023-02-06 13:10 UTC, anooparveti commented on packages/manager/modules/billing-components/src/components/utils/billing.service.js
> +      .put(`${servicePath}/serviceInfos`)
**nitpick:** Pass `deleteAtExpiration:true` with the PUT call

2023-02-06 13:27 UTC, anooparveti requested changes

2023-02-06 13:27 UTC, anooparveti commented on packages/manager/modules/billing-components/src/components/resiliation/resiliation.controller.js
> +        this.service.renew.deleteAtExpiration === true,
```suggestion
        this.service.id,
        { deleteAtExpiration:true }
```

2023-02-06 13:27 UTC, anooparveti commented on packages/manager/modules/billing-components/src/components/utils/billing.service.js
> +      .put(`${servicePath}/serviceInfos`)
```suggestion
  putServiceInfos(servicePath, params) {
    return this.$http
      .put(`${servicePath}/serviceInfos`, params)
```

2023-02-06 14:35 UTC, anooparveti requested changes

2023-02-06 14:35 UTC, anooparveti commented on packages/manager/modules/billing-components/src/components/resiliation/resiliation.controller.js
> +    console.log(this.serviceName);
**nitpick:** Remove the console statement

2023-02-07 08:42 UTC, anooparveti approved these changes

2023-02-14 11:13 UTC, ghyenne approved these changes

2023-02-14 12:40 UTC, merged