fix(hub.account): add a banner to invit the customer to update the siret
ovh/manager pull request #8905
Opened 2023-02-14 14:01 UTC by stif59100

ref:MANAGER-10205

Signed-off-by: stif59100 <steeve.vanderstocken@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `release/components-w12`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-10205
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

I added a banner to invit the customer to update the siret

## Related

2023-02-16 08:03 UTC, mohammed-zahaf approved these changes

2023-02-16 08:03 UTC, ghyenne requested changes

2023-02-16 08:03 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +    this.companyNationalIdentificationNumber = this.coreConfig.getUser().companyNationalIdentificationNumber;
For the logic you need the same that ACCOUNT_DASHBOARD_URL.

2023-02-16 08:03 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/routing.js
> +      },
```suggestion
      isDisplayableHubBanner: /* @ngInject */ (ovhFeatureFlipping) => ovhFeatureFlipping
          .checkFeatureAvailability('hub:banner-hub-invite-customer-siret')
          .then((feature) => feature.isFeatureAvailable(bannerHubSiretId)),
```

2023-02-16 10:34 UTC, mohammed-zahaf submitted a review, later dismissed

2023-02-16 11:38 UTC, ghyenne submitted a review, later dismissed

2023-02-16 12:41 UTC, mohammed-zahaf approved these changes

2023-02-17 10:10 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +    this.country = this.coreConfig.getUser().country;
```suggestion
    this.availableSiretBanner = false;
    this.isDisplayableHubBanner.then((data) => {
      this.availableSiretBanner = data && !this.user.companyNationalIdentificationNumber && this.user.legalform === 'corporation' && this.user.country === 'FR';
      if (this.availableSiretBanner) {
        this.atInternet.trackPage({
          name: TRACKING_PREFIX,
          type: 'navigation',
        });
      }
    });

    this.ACCOUNT_DASHBOARD_URL = this.coreURLBuilder.buildURL(
      'dedicated',
      '#/useraccount/infos?fieldToFocus=siretForm',
    );
```

2023-02-17 10:10 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +  }
```suggestion
  constructor(coreURLBuilder, coreConfig, atInternet) {
    this.coreURLBuilder = coreURLBuilder;
    this.user = this.coreConfig.getUser();
    this.atInternet = atInternet;
    this.TRACKING_PREFIX = TRACKING_PREFIX;
    this.HIT_PREFIX = HIT_PREFIX;
  }
```

2023-02-17 10:10 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +        >
```suggestion
            data-ng-if="$ctrl.availableSiretBanner"
        >
```

2023-02-17 10:29 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +            data-ng="$ctrl.goToSiret()"
no need.

2023-02-17 10:29 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +            data-ng="$ctrl.goToSiret()"
no need

2023-02-17 13:20 UTC, ghyenne approved these changes

2023-02-17 13:21 UTC, mohammed-zahaf approved these changes

2023-02-21 12:36 UTC, ghyenne submitted a review, later dismissed

2023-02-21 12:36 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +            <span data-translate="manager_hub_dashboard_banner_siret"> </span>
```suggestion
            <span data-translate="manager_hub_dashboard_banner_siret"></span>
```

2023-02-21 12:50 UTC, anooparveti requested changes

2023-02-21 12:50 UTC, anooparveti commented on packages/manager/apps/hub/src/dashboard/dashboard.component.js
> +    isDisplayableHubBanner: '<',
**nitpick:** `isDisplayableHubBanner` sounds very generic. 
```suggestion
    displaySiretBanner: '<',
```

2023-02-22 10:32 UTC, ghyenne approved these changes

2023-02-22 11:03 UTC, anooparveti approved these changes

2023-02-24 07:01 UTC, mohammed-zahaf approved these changes

2023-03-21 11:02 UTC, anooparveti approved these changes

2023-03-21 11:02 UTC, merged