build(iam): set up the dev env
ovh/manager pull request #8972
Opened 2023-02-24 17:35 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/iam`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-10394
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Add aliases support to get rid of relative paths

2023-02-24 21:01 UTC, y4nnL commented on packages/manager/apps/iam/package.json
> +    "@ovh-ux/ui-kit": "git+ssh://git@github.com:ovh/ovh-ui-kit.git#feat/datagrid-pagination-mode",
Will be updated one https://github.com/ovh/ovh-ui-kit/pull/807 is published

2023-02-24 21:01 UTC, y4nnL commented on packages/manager/modules/iam/package.json
> +    "@ovh-ux/ui-kit": "git+ssh://git@github.com:ovh/ovh-ui-kit.git#feat/datagrid-pagination-mode",
Will be updated one https://github.com/ovh/ovh-ui-kit/pull/807 is published

2023-03-07 18:30 UTC, antleblanc requested changes

2023-03-07 18:30 UTC, antleblanc commented on packages/manager/tools/webpack-config/src/alias/iam.js
> +  module: '@ovh-ux/manager-iam',
**issue(blocking):** Shared webpack configuration mustn't be coupled to a module nor feature business logic.

2023-03-08 08:22 UTC, closed without merging