ci(github): remove team-manager-core from MAINTAINERS, update CODEOWNERS
ovh/manager pull request #8989
Opened 2023-03-01 08:18 UTC by frenautvh

| Question         | Answer
| ---------------- | ---
| Branch?          | master
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | DTCORE-622
| License          | BSD 3-Clause

## Description

update CODEOWNERS & MAINTAINERS for team manager core

2023-03-07 08:13 UTC, cbourgois submitted a review, later dismissed

2023-03-07 18:33 UTC, antleblanc requested changes

2023-03-07 18:33 UTC, antleblanc commented on .github/CODEOWNERS
> -/docs/ @ovh/team-manager-core
**nitpick(non-blocking):** the whole Documentation block could be removed (see L2).

2023-03-08 09:27 UTC, antleblanc submitted a review, later dismissed

2023-03-15 14:42 UTC, antleblanc approved these changes

2023-03-15 14:44 UTC, merged