feat(iam): lazy load iam module
ovh/manager pull request #9006
Opened 2023-03-06 07:36 UTC by y4nnL

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/iam`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10394
| License          | BSD 3-Clause

- [X] Try to keep pull requests small so they can be easily reviewed.
- [X] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [X] Branch is up-to-date with target branch
- [X] Lint has passed locally
- [X] Standalone app was ran and tested locally
- [X] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

2023-03-06 09:49 UTC, anooparveti requested changes

2023-03-06 09:49 UTC, anooparveti commented on packages/manager/modules/iam/src/iam.module.js
> +import revolves from '@iam/resolves';
```suggestion
import resolves from '@iam/resolves';
```

2023-03-06 09:49 UTC, anooparveti commented on packages/manager/modules/iam/src/iam.module.js
> +  revolves,
```suggestion
  resolves,
```

2023-03-07 09:41 UTC, sachinrameshn approved these changes

2023-03-07 09:47 UTC, anooparveti approved these changes

2023-03-08 08:37 UTC, merged