feat(dedicated): alternate colored lines to partitioning wizzard
ovh/manager pull request #9027
Opened 2023-03-08 14:03 UTC by JayBeeDe

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10700
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
~~Breaking change is mentioned in relevant commits~~

## Description

## Related

MANAGER-10700

2023-03-08 14:06 UTC, JayBeeDe commented
![image](https://user-images.githubusercontent.com/17429937/223733753-e68a81e2-ded5-47ad-9366-1bfe349d94eb.png)
Here is how it will look like

2023-03-09 08:04 UTC, anooparveti requested changes

2023-03-09 08:04 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/css/less/utils/variables.less
> +@defaultlineevenbackground: #f3feff;
**nitpick:** Avoid using custom colors. You can choose the appropriate one from https://ovh.github.io/ovh-ui-kit/?path=/story/design-system-helpers-colors--primary

2023-03-10 09:39 UTC, anooparveti submitted a review, later dismissed

2023-03-10 09:49 UTC, mohammed-zahaf approved these changes

2023-03-13 13:32 UTC, JayBeeDe commented
![image](https://user-images.githubusercontent.com/17429937/224716663-d8b58fbc-af34-4046-b814-006e64bbca2f.png)
I've been thinking, what about also doing it for the step 4/4 ?
Adding it now...

2023-04-11 11:41 UTC, merged