fix(ldp): update en_gb translation related to encryption keys
ovh/manager pull request #9030
Opened 2023-03-09 08:37 UTC by pfrayer

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

A recent english translation is erroneous (`Surname` instead of `Name`). It refers to an object (an encryption key), and not a real person, so `Name` should be the good translation. Other languages translations seems OK.

## Related

PR #8249

2023-03-10 06:23 UTC, anooparveti requested changes
Hello @pfrayer,
We are not supposed to modify the translations files apart from `Message_fr_FR.json`. Could you please handle this change by raising a translation request?

Procedure:

1. Create a branch from `master`
2. Push it to origin
3. Prepare a `yaml` config 
4. Request a translation

Let me know if you have any queries.

2023-03-13 09:49 UTC, pfrayer commented
Hello @anooparveti ,

Should we really go to the entire translation process to just update one word ? If so, the translation process will result in the exact content of this PR.

2023-03-15 09:48 UTC, anooparveti commented
> 

Hello @pfrayer,
Yes it is required to go through the trans process no matter the size of the change. This is required because all the French content is cached and the next time if we request trans for the existing content, trans process will serve it from the cache. So when the change goes through trans process, we can make sure cache is updated.

2023-03-21 10:08 UTC, pfrayer commented
Fixed in [f6a075eecd6492a61bfc8f786a022e9a24203780](https://github.com/ovh/manager/commit/f6a075eecd6492a61bfc8f786a022e9a24203780#diff-13f5687a3bbd8fac6a111c8346b2212338918dbf40b8a7a320950d360a866354)

2023-03-21 10:08 UTC, closed without merging