fix(i18n): add missing translations
ovh/manager pull request #9107
Opened 2023-03-27 12:09 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11058 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-03-28 10:41 UTC, anooparveti approved these changes

2023-03-30 09:04 UTC, antleblanc requested changes
Could you please resolve existing conflicts?

I've left one question regarding the generator.

2023-03-30 09:04 UTC, antleblanc commented on packages/manager/tools/sao-ovh-manager-module/template/src/onboarding/translations/Messages_fr_FR.json
**question**: Why removing default translation files from the actual generator?
same question for `packages/manager/tools/sao-ovh-manager-module/template/src/translations/Messages_fr_FR.json`.

2023-03-31 08:35 UTC, brofik commented on packages/manager/tools/sao-ovh-manager-module/template/src/onboarding/translations/Messages_fr_FR.json
Because these files are empty.

2023-04-03 18:47 UTC, antleblanc commented on packages/manager/tools/sao-ovh-manager-module/template/src/onboarding/translations/Messages_fr_FR.json
Theses files must be kept. Could you please revert changes? Thank you

2023-04-03 18:47 UTC, antleblanc requested changes
Some translation files must be kept (generator).

2023-04-05 03:11 UTC, brofik commented on packages/manager/tools/sao-ovh-manager-module/template/src/onboarding/translations/Messages_fr_FR.json
I've done the revert on the commit that remove fr translation files.

2023-04-11 05:59 UTC, antleblanc submitted a review, later dismissed
Some translation files must be kept (generator).

2023-04-11 06:18 UTC, anooparveti submitted a review, later dismissed

2023-04-11 08:01 UTC, brofik commented
> Some translation files must be kept (generator).

which ones ?

2023-04-11 08:44 UTC, anooparveti requested changes
I think this commit cd6ee06bc3ef729f021829c4d6586146ba5ef5c8 can be removed. We dont know the consequences of removal of keys. Maybe "empty string" is expected for this keys.
Can you confirm this dont have any consequence?

2023-04-11 12:21 UTC, brofik commented
> I think this commit [cd6ee06](https://github.com/ovh/manager/commit/cd6ee06bc3ef729f021829c4d6586146ba5ef5c8) can be removed. We dont know the consequences of removal of keys. Maybe "empty string" is expected for this keys. Can you confirm this dont have any consequence?

I don't see these labels used anywhere. So I don't see the point of keeping them.

2023-04-12 10:04 UTC, anooparveti approved these changes

2023-04-14 08:38 UTC, aboungnaseng-ovhcloud approved these changes
👍

2023-04-19 12:03 UTC, merged