feat(pci.data-processing): adding spark notebooks
ovh/manager pull request #9127
Opened 2023-03-30 09:25 UTC by Dimfacion

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #DATATR-61 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Main branch that regroup all the features developped for Spark Notebooks.
Branches :
DATATR-96
|
\\/
DATATR-98 
|
\\/
DATATR-94 
|
\\/
DATATR-97
|
\\/
DATATR-95 
|
\\/
DATATR-93 | DATATR-184 | DATATR-242
|
\\/
DATATR-61 

List of PR already merged : 
https://github.com/ovh/manager/pull/8486
https://github.com/ovh/manager/pull/8485
https://github.com/ovh/manager/pull/8470 
https://github.com/ovh/manager/pull/8460
https://github.com/ovh/manager/pull/8452
https://github.com/ovh/manager/pull/8449
https://github.com/ovh/manager/pull/8820
https://github.com/ovh/manager/pull/9052

## Related

2023-04-17 12:24 UTC, anooparveti requested changes

2023-04-17 12:24 UTC, anooparveti commented on .lintstagedrc.json
Could you please remove the changes on this file?

2023-04-17 12:26 UTC, Dimfacion commented on .lintstagedrc.json
Yep, doing :)

2023-04-18 10:03 UTC, anooparveti approved these changes

2023-04-18 10:08 UTC, merged