feat(iam): add advanced mode on datagrid policies
ovh/manager pull request #9147
Opened 2023-04-05 09:24 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/MANAGER-11169` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-11170 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I added advanced mode on datagrid policies

## Related

2023-04-11 08:41 UTC, anooparveti approved these changes

2023-04-18 07:24 UTC, y4nnL requested changes

2023-04-18 07:24 UTC, y4nnL commented on packages/manager/modules/iam/src/routes/policies.route.js
> +      }),
Same as https://github.com/ovh/manager/pull/9146#discussion_r1169586737 and https://github.com/ovh/manager/pull/9146#discussion_r1169586522

2023-04-21 06:22 UTC, y4nnL commented on packages/manager/modules/iam/src/routes/policies.route.js
> +        hasPolicies ? { state: ROUTES.POLICIES } : false,
```suggestion
        !hasPolicies ? { state: ROUTES.ONBOARDING } : false,
```
Are you sure it shouldn't redirect to onboarding ?

2023-04-26 07:55 UTC, merged