feat(hub): add kyc banners for india nic
ovh/manager pull request #9228
Opened 2023-04-26 15:54 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/acquisition-storage`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11156
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

Add a banner for KYC updation when its not yet done

2023-04-27 09:50 UTC, ghyenne requested changes

2023-04-27 09:50 UTC, ghyenne commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +            }
I think there is a mistake
We have twice this.showKycBanner = true;

2023-04-27 09:57 UTC, mohammed-zahaf commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +            }
```suggestion
this.showKycBanner = ['open', 'required'].includes(data.status)
```

2023-04-27 09:57 UTC, anooparveti commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +            }
**nitpick:** can be simplified

```suggestion
              this.showKycBanner = !!['open', 'required'].includes(data.status);
```

2023-04-27 09:58 UTC, anooparveti commented on packages/manager/apps/hub/src/dashboard/dashboard.html
> +                    aria-hidden="true"
```suggestion
```

2023-04-27 09:58 UTC, anooparveti commented on packages/manager/apps/hub/src/dashboard/order-dashboard/template.html
> +            aria-hidden="true"
```suggestion
```

2023-04-27 09:58 UTC, mohammed-zahaf commented on packages/manager/apps/hub/src/dashboard/translations/Messages_fr_FR.json
> +  "manager_hub_dashboard_kyc_banner_description": "Vous souhaitez commander un produit OVHcloud: la réglementation en vigueur nécessite une vérification de votre identité. Veuillez ajouter vos docume
```suggestion
  "manager_hub_dashboard_kyc_banner_description": "Vous souhaitez commander un produit OVHcloud : la réglementation en vigueur nécessite une vérification de votre identité. Veuillez ajouter vos documents d'identité.",
```

2023-04-27 12:38 UTC, mohammed-zahaf approved these changes

2023-04-28 07:41 UTC, sachinrameshn commented on packages/manager/apps/hub/src/dashboard/dashboard.controller.js
> +        }
done

2023-04-28 07:45 UTC, y4nnL commented on packages/manager/apps/hub/src/dashboard/order-dashboard/template.html
> +    dismissable
Can you please have a second look ? Thanks

2023-04-28 07:56 UTC, y4nnL approved these changes

2023-04-28 07:59 UTC, merged