fix(dedicated.ip): fix filter issue on ips
ovh/manager pull request #9244
Opened 2023-05-04 04:53 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #DTRSD-112402
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~ [n/a]

## Description

## Related

2023-05-04 05:49 UTC, anooparveti submitted a review, later dismissed

2023-05-04 05:57 UTC, ghyenne submitted a review, later dismissed

2023-05-04 07:14 UTC, ghyenne approved these changes

2023-05-12 08:27 UTC, anooparveti requested changes
**question:** I dont see any changes on `Messages_fr_FR.json`. If there are no changes, maybe you can exclude the commit added by TRANS

2023-05-15 06:37 UTC, sachinrameshn commented
> **question:** I dont see any changes on `Messages_fr_FR.json`. If there are no changes, maybe you can exclude the commit added by TRANS

Hi Anoop, 

Yeah we have all translations and not FR translations because we missed to prod the TRANS commit in the last release and proded only FR translations.

2023-05-15 14:53 UTC, anooparveti approved these changes

2023-05-23 13:22 UTC, merged