fix: set need new modem flag to false when no modem selected
ovh/manager pull request #9284
Opened 2023-05-12 10:13 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #UXCT-477
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Set needNewModem flag to false when no modem is selected in offers page

## Related

2023-05-15 08:40 UTC, anooparveti requested changes
@Steffy29  can you please include ticket reference in the comimt body?

2023-05-15 08:41 UTC, y4nnL approved these changes

2023-05-15 09:09 UTC, Steffy29 commented
@anooparveti  ok I note this comment for next time.

2023-05-23 14:47 UTC, anooparveti approved these changes

2023-05-30 10:22 UTC, merged