fix(modules.emailpro): propagate primary email
ovh/manager pull request #9334
Opened 2023-05-23 14:18 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-113692
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description
propagate primary email address

2023-05-23 14:23 UTC, darsene approved these changes

2023-05-23 14:34 UTC, anooparveti requested changes
Can you please remove `modules` from the scope of the commit scope?

2023-05-24 05:58 UTC, mohammed-zahaf commented
> Can you please remove `modules` from the scope of the commit scope?

Any raisons for this ?

2023-05-24 06:16 UTC, anooparveti commented
> > Can you please remove `modules` from the scope of the commit scope?
> 
> Any raisons for this ?

Scope from the commit title is used to generate changelogs. So it should indicate one of the folders in `apps` or `modules`. In this scenario, there is no app or module called `modules` and the generated log will not be appropriated.

2023-05-24 07:21 UTC, y4nnL approved these changes

2023-05-26 06:50 UTC, anooparveti approved these changes

2023-05-26 11:56 UTC, merged