fix(dedicated): removed duplicated netboot translations
ovh/manager pull request #9344
Opened 2023-05-25 15:58 UTC by JayBeeDe

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
~Breaking change is mentioned in relevant commits~

## Description

Removed duplicated netboot translations

## Related

ref: MANAGER-11478

2023-05-25 17:00 UTC, anooparveti requested changes

2023-05-25 17:00 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/dedicated/server/netboot/translations/Messages_fr_FR.json
@JayBeeDe, if you are deleting the entire `Messages_fr_FR` file, you can delete other language files as well since the cron job only compares the keys and fails to identify the file deletion, the other language files will not be deleted by it.

2023-05-25 17:06 UTC, JayBeeDe commented on packages/manager/apps/dedicated/client/app/dedicated/server/netboot/translations/Messages_fr_FR.json
@anooparveti PR updated accordingly

2023-05-26 08:41 UTC, sachinrameshn approved these changes

2023-05-26 08:41 UTC, anooparveti approved these changes

2023-06-13 07:59 UTC, merged