feat(dedicated): remove header buttons and tab on ip onboarding page
ovh/manager pull request #9395
Opened 2023-06-05 13:45 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAER-10388
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~[n/a]
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~[n/a]

## Description

Remove button links and tab in ip onboarding header.

## Related

2023-06-05 15:34 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/ip.controller.js
> +  $scope.displayHeaderButtons = !$state.is('app.ip.onboarding');
this information is already computed in `hasAnyIp` so you can use it directly I guess

2023-06-06 07:08 UTC, anooparveti requested changes
**nitpick:** Better to have hide these buttons would be to create a new `ui-view` and load the onboarding page in this view.

2023-06-06 13:16 UTC, ghyenne approved these changes

2023-06-06 13:18 UTC, ghyenne commented
Maybe clean your history for to have only one commit.

2023-06-07 08:39 UTC, darsene approved these changes

2023-06-07 08:40 UTC, anooparveti approved these changes

2023-07-18 14:56 UTC, merged