fix(public-cloud): upgrade by using installation instead of renew
ovh/manager pull request #9410
Opened 2023-06-07 09:08 UTC by mohammed-zahaf

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-114571
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description
use `installation` instead of `renew` to upgrade project quota

2023-06-07 09:10 UTC, ghyenne approved these changes

2023-06-07 09:11 UTC, darsene approved these changes

2023-06-07 09:30 UTC, sachinrameshn requested changes

2023-06-07 09:30 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.service.js
>      const renewPrice = serviceOption.prices?.find((price) =>
```suggestion
    const installationPrice = serviceOption.prices?.find((price) =>
```

2023-06-07 09:30 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/quota/increase-request/increase-request.service.js
>      const renewPrice = serviceOption.prices?.find((price) =>
Just a variable name suggestion.

2023-06-09 12:52 UTC, ghyenne approved these changes

2023-06-09 12:53 UTC, darsene approved these changes

2023-06-09 12:54 UTC, merged