docs: fix error on uapp generator scaffolding tools
ovh/manager pull request #9431
Opened 2023-06-09 16:20 UTC by darsene

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-11509
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- ~Only FR translations have been updated~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~Breaking change is mentioned in relevant commits~

## Description

## Related

2023-06-12 08:38 UTC, anooparveti requested changes

2023-06-12 08:38 UTC, anooparveti commented on packages/manager/tools/sao-ovh-manager-app/template/src/app.module.js
> +          }rm
**nitpick:** unwanted change no?
```suggestion
          }
```

2023-06-12 09:19 UTC, darsene commented on packages/manager/tools/sao-ovh-manager-app/template/src/app.module.js
> +          }rm
Totally ! Good catch!

2023-06-12 09:21 UTC, darsene commented on packages/manager/tools/sao-ovh-manager-app/template/src/app.module.js
> +          }rm
It's fixed

2023-06-12 09:41 UTC, anooparveti approved these changes

2023-06-12 11:37 UTC, cbourgois approved these changes

2023-06-13 05:35 UTC, antleblanc commented
**question:** Shouldn't commit type being a `fix` rather than `build`?

2023-06-14 07:32 UTC, antleblanc approved these changes

2023-06-14 09:49 UTC, merged