feat: super-components workspace and msc-tile super-component
ovh/manager pull request #9450
Opened 2023-06-14 08:42 UTC by chipp972

ref: MANAGER-11577

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | MANAGER-11577
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-06-14 17:28 UTC, aboungnaseng-ovhcloud commented on .eslintrc.js
> +        camelcase: 'off',
?

2023-06-16 09:47 UTC, chipp972 commented on .eslintrc.js
> +        camelcase: 'off',
autofix on javascript files

2023-06-26 12:13 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2023-06-28 07:36 UTC, chipp972 commented on packages/manager/modules/veeam-enterprise/package.json
> +    "@ovh-ux/ng-translate-async-loader": "^2.1.6",
it's an eslint error

2023-06-28 07:36 UTC, chipp972 commented on packages/manager/modules/pci/package.json
> +    "@ovh-ux/ng-at-internet-ui-router-plugin": "^3.2.3",
it's an eslint error also

2023-07-14 15:06 UTC, anooparveti commented on packages/super-components/components/msc-tile/react/.gitignore
> +src/
**question:** Why `src` folder is included in `.gitignore`?

2023-07-14 15:23 UTC, anooparveti commented on packages/super-components/components/msc-tile/src/msc-tile/msc-tile.scss
> +      margin-bottom: 16px;
**nitpick:** To maintain uniformity across the Manager, use utility classes from Bootstrap

2023-07-14 15:23 UTC, anooparveti commented on packages/super-components/components/msc-tile/src/msc-tile/msc-tile.scss
> +      margin-left: 10px;
**nitpick:** To maintain uniformity across the Manager, use utility classes from Bootstrap

2023-07-14 15:23 UTC, anooparveti commented on packages/super-components/components/msc-tile/src/msc-tile/msc-tile.scss
> +      margin-bottom: 16px;
**nitpick:** To maintain uniformity across the Manager, use utility classes from Bootstrap

2023-07-14 15:23 UTC, anooparveti commented on packages/super-components/components/msc-tile/src/msc-tile/msc-tile.scss
> +      margin-bottom: 12px;
**nitpick:** To maintain uniformity across the Manager, use utility classes from Bootstrap

2023-07-14 15:23 UTC, anooparveti commented on packages/super-components/components/msc-tile/src/msc-tile/msc-tile.scss
> +      margin-left: 10px;
**nitpick:** To maintain uniformity across the Manager, use utility classes from Bootstrap

2023-07-15 12:39 UTC, anooparveti commented on packages/super-components/components/msc-tile/vue/.gitignore
> +src/
**question:** Why `src` folder is added to `.gitignore`?

2023-07-15 12:45 UTC, anooparveti reviewed
**suggestion:** Maybe we need to add organisation name to the prefix of supercomponent.
`msc` -> `omsc`

2023-07-15 12:49 UTC, anooparveti commented on packages/super-components/generator/component/index.js
> +          !currentComponentList.includes(componentTag),
**question:** Are we restricting all the super-component tag to start with `msc-`. 
If yes, we can add this check to validate function.
If not, we should consider restricting.

2023-07-15 12:49 UTC, anooparveti commented on packages/super-components/generator/component/index.js
> +          !currentComponentList.includes(componentTag),
**question:** Are we restricting all the super-component tag to start with `msc-`. 
If yes, we can add this check to validate function.
If not, we should consider restricting.

2023-07-15 12:51 UTC, anooparveti requested changes

2023-07-15 12:51 UTC, anooparveti commented on packages/super-components/generator/component/index.js
> +        default: ({ componentTag }) => componentTag.split('-')[1],
**nitpick:** In the `componentTag`, I dont see any restrictions that the tag must contain `-`. So this check can fail if the `componentTag` doesn't contain `-`

2023-07-15 13:00 UTC, anooparveti commented on packages/super-components/generator/component/templates/src/index.html.hbs
> +        <title>Dev msc-tile</title>
```suggestion
        <title>Dev msc-{{componentTag}}</title>
```

2023-07-15 13:34 UTC, anooparveti requested changes

2023-07-15 13:34 UTC, anooparveti commented on packages/super-components/storybook/stories/Introduction.mdx
> +- `vue/` the generated react component (you should not touch anything in this folder)
```suggestion
- `vue/` the generated vue component (you should not touch anything in this folder)
```

2023-07-19 13:45 UTC, aboungnaseng-ovhcloud commented on packages/super-components/components/msc-tile/src/index.html
> +                        style="margin-top: 1.5rem"
the index.html file inside mcs-tile is only an exemple how the implement the msc-tile component,  we can use this component like that or sure we can create a css file to add the rule

2023-07-19 13:47 UTC, aboungnaseng-ovhcloud commented on packages/super-components/components/msc-tile/docs/create-tile.ts
> +          <osds-button color="primary" style="margin-top: 1.5rem">Commander</osds-button>
same comment as below its only a css for documentation, of course we can create a file for this, but this way is more ligther to load the documentation  and maintain it

2023-07-20 13:21 UTC, anooparveti requested changes

2023-07-20 13:21 UTC, anooparveti commented on packages/super-components/generator/component/templates/vue/.gitignore
> +src/
**nitpick:** Can you remove this from `.gitignore`?

2023-07-27 15:18 UTC, anooparveti approved these changes

2023-07-28 07:29 UTC, aboungnaseng-ovhcloud submitted a review, later dismissed

2023-07-28 09:40 UTC, Kranysys approved these changes

2023-07-31 07:15 UTC, aboungnaseng-ovhcloud approved these changes

2023-07-31 07:15 UTC, anooparveti approved these changes

2023-07-31 07:17 UTC, merged