feat(pci.ai): removed home and registry tabs for ai training
ovh/manager pull request #9456
Opened 2023-06-14 15:30 UTC by abullet33

| Question         | Answer
| ---------------- | ---
| Branch?          | feat/datatr-296-ai-dashboard-1.1
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #datatr-253 
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description
Remove Home and Registry tabs from ai training to standardize AI tools. Registry will be moved to AI dashboard section in an other PR. 

## Related
DATATR-232 | Main branch : https://github.com/ovh/manager/tree/feat/datatr-296-ai-dashboard-1.1
- [DATATR-251](https://github.com/ovh/manager/pull/9405)
- [DATATR-204](https://github.com/ovh/manager/pull/9446)
- [DATATR-300](https://github.com/ovh/manager/pull/9454)

2023-06-16 08:17 UTC, anooparveti requested changes

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_de_DE.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_en_GB.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_es_ES.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_fr_CA.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_it_IT.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_pl_PL.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 08:17 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_pt_PT.json
**nitpick:** Can you please get these changes from trans team?
As per the contribution guide, developers are allowed to modify only `fr_FR` files. You can find it [here](https://github.com/ovh/manager/blob/master/CONTRIBUTING.md#translations).

2023-06-16 11:52 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_de_DE.json
Hi @anooparveti , as I deleted this folder "modules/pci/src/projects/project/training/registries/translations/", it has an impact on one translations, and the text "pci_projects_project_training_jobs_resubmit": "Relaunch" were display as : pci_projects_project_training_jobs_resubmit. As It have already been trad by traduction team, I figured that I just copy/paste each one in the different language without asking trad team to do something that they already done. I did not change anything else in terms of translation. Would it be ok for you or do you want me to go for translation ?

2023-06-16 11:52 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_en_GB.json
Same as https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-16 11:52 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_es_ES.json
https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-16 11:53 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_fr_CA.json
Same as https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-16 11:53 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_it_IT.json
Same as https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-16 11:53 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_pl_PL.json
Same as https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-16 11:53 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_pt_PT.json
Same as https://github.com/ovh/manager/pull/9456#discussion_r1232149416

2023-06-20 09:01 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_de_DE.json
Hi @abullet33, could you please go through the trans for the change?

2023-06-20 09:27 UTC, abullet33 commented on packages/manager/modules/pci/src/projects/project/training/translations/Messages_de_DE.json
Hi @anooparveti , yes, I will

2023-06-20 12:25 UTC, anooparveti approved these changes

2023-06-21 14:27 UTC, merged