fix(pcc.vmware): update url order
ovh/manager pull request #9519
Opened 2023-06-26 15:09 UTC by ghyenne

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-11229 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
I updated the urls order vmware

## Related

2023-06-26 15:12 UTC, darsene submitted a review, later dismissed

2023-06-27 03:49 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/dedicatedCloud/onboarding/constants.js
> +  ASIA: 'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
Can you add India specific CTA link ?
```suggestion
  ASIA: 'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
```

2023-06-27 03:50 UTC, sachinrameshn commented on packages/manager/apps/container/src/container/legacy/server-sidebar/order/shop-config/order.constants.ts
> +        'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
Can you please add India specific link ?

```suggestion
        'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
```

2023-06-27 03:51 UTC, sachinrameshn requested changes

2023-06-27 03:51 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/dedicatedCloud/onboarding/constants.js
> +  ASIA: 'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
Add India Specific CTA link ?
```suggestion
  ASIA: 'https://www.ovhcloud.com/asia/hosted-private-cloud/vmware/prices/',
```

2023-07-21 08:21 UTC, sachinrameshn approved these changes

2023-07-28 06:40 UTC, sachinrameshn approved these changes

2023-07-28 06:58 UTC, anooparveti approved these changes

2023-08-28 09:07 UTC, merged