feat(projects.registry): change fr label wording
ovh/manager pull request #9538
Opened 2023-06-30 08:19 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-10973 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

- [x] CMT-1113

2023-06-30 08:39 UTC, darsene requested changes
You have to update FR file instead of EN file

2023-07-03 00:41 UTC, brofik commented
> You have to update FR file instead of EN file

This ticket is created specifically to change an english translation.
you can check the ticket description for more informations.

2023-07-03 12:38 UTC, qpavy approved these changes

2023-07-04 06:44 UTC, anooparveti approved these changes

2023-07-28 13:07 UTC, merged