feat(telecom): add inward postcode for uk phone number
ovh/manager pull request #9554
Opened 2023-07-03 14:04 UTC by qpavy

ref: MANAGER-11693

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11693
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2023-07-03 14:24 UTC, darsene requested changes
replace `isServiceInUK` function with property instead

2023-07-03 14:31 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.html
> +                                        data-ng-pattern="/^\d[a-zA-Z]{2}$/"
Can you move the regex in constant file.

2023-07-04 07:25 UTC, qpavy commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.html
> +                                    </oui-select>
I add an input text field as it is possible to have non geographic number in uk

2023-07-04 07:44 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.html
> +                                        items="$ctrl.isServiceInUKautoCompletePostCode"
```suggestion
                                        items="$ctrl.autoCompletePostCode"
```

2023-07-04 07:49 UTC, ghyenne commented on packages/manager/apps/telecom/src/app/telecom/telephony/service/contact/contact.html
> +                                    data-ng-class="$ctrl.isServiceInUK ? 'col-md-4' :  'col-md-12'"
```suggestion
                                    data-ng-if="$ctrl.isServiceInUK"
                                    label="{{:: 'telephony_service_contact_outwardcode' | translate }}*"
                                    error-messages="{ 'required': ('telephony_service_contact_must_fill' | translate) }"
                                    class="col-md-4"
```

you are data-ng-if so this contition on class isn't required

2023-07-04 08:01 UTC, darsene submitted a review, later dismissed

2023-07-04 10:06 UTC, ghyenne approved these changes

2023-07-04 10:12 UTC, darsene submitted a review, later dismissed

2023-07-13 04:16 UTC, anooparveti approved these changes

2023-07-18 15:12 UTC, merged