Dev/vcasse/manager 11329
ovh/manager pull request #9572
Opened 2023-07-05 10:06 UTC by VincentCasse

| Question         | Answer
| ---------------- | ---
| Branch?          | `feat/iam
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | MANAGER-11329
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Add identities experience was really confusing. When we was using the interface, we didn't add user by clicking on submit and was thinking IAM is not working.

## Related

2023-07-11 16:21 UTC, VincentCasse commented
Just rebased to feat/iam

2023-07-13 07:15 UTC, y4nnL requested changes

2023-07-13 08:30 UTC, y4nnL requested changes

2023-07-13 08:34 UTC, VincentCasse commented on packages/manager/modules/iam/src/identities/translations/Messages_fr_FR.json
> +  "iam_identities_submit_identity_success": "Les modifications de vos identités ont bien été réalisées."
done

2023-07-19 06:27 UTC, merged