fix(ai): update guides CLI section name
ovh/manager pull request #9588
Opened 2023-07-07 10:52 UTC by Benzhaomin

| Question         | Answer
| ---------------- | ---
| Branch?          | develop
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

## Description

The guides API returns updated section names since moving docs to ServiceNow. This change fixes the list of tutorials that shows on the CLI tab of the AI dashboard.

It's all read-only and a very safe change.

2023-07-10 08:31 UTC, JacquesLarique approved these changes

2023-07-10 08:36 UTC, qpavy approved these changes

2023-07-11 09:22 UTC, Benzhaomin commented
two other commits were pushed to this branch instead of another by mistake, now they are reverted so there's no change vs what was reviewed yesterday

2023-07-18 08:15 UTC, darsene requested changes
Hello @Benzhaomin ,

You have to follow the contribution guide https://github.com/ovh/manager/blob/master/CONTRIBUTING.md (your commits aren't sign off and ticket reference is missing)

2023-07-21 13:22 UTC, abullet33 approved these changes

2023-07-21 13:35 UTC, jperchoc approved these changes

2023-07-25 08:42 UTC, darsene approved these changes

2023-08-11 12:29 UTC, merged