fix(ldp): edit alert conditions
ovh/manager pull request #9629
Opened 2023-07-12 15:19 UTC by pdepaepe

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix OB-5202
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

This PR will fix the edit panel of alert conditions of Logs Data Platform control panel.

2023-07-13 08:07 UTC, anooparveti submitted a review, later dismissed

2023-07-18 08:36 UTC, qpavy requested changes

2023-07-18 08:36 UTC, qpavy commented on packages/manager/modules/dbaas-logs/src/logs/detail/streams/alerts/add/alerts-add.html
> +    {{ctrl.alert.conditionType}}
```suggestion
    <span data-ng-bind="ctrl.alert.conditionType"></span>
```

2023-07-18 09:13 UTC, pdepaepe commented on packages/manager/modules/dbaas-logs/src/logs/detail/streams/alerts/add/alerts-add.html
> +    {{ctrl.alert.conditionType}}
Updated, thanks.

2023-07-18 14:24 UTC, qpavy approved these changes

2023-07-18 15:22 UTC, merged