feat(format): just format all code
ovh/manager pull request #9653
Opened 2023-07-14 13:44 UTC by maximeVaillant

ref: no ticket

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [x] Breaking change is mentioned in relevant commits

## Description

just yarn format on all code

2023-07-17 08:09 UTC, darsene approved these changes

2023-07-17 08:14 UTC, anooparveti requested changes
Since the PR is only about formatting, can you change the commit type to `refactor`?
`feat(format): just format all code` -> `refactor(*): apply formatting`

2023-07-25 08:43 UTC, darsene approved these changes

2023-07-25 10:54 UTC, anooparveti approved these changes

2023-08-04 07:13 UTC, merged