fix(i18n): typography
ovh/manager pull request #9663
Opened 2023-07-17 17:21 UTC by Linkid

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Typography in translations

## Related

2023-07-25 08:42 UTC, qpavy submitted a review, later dismissed

2023-07-25 08:42 UTC, sachinrameshn requested changes
Can you please remove the changes over CA translation file ? We only do modify in FR file and remaining will go the translation request process.

2023-07-28 08:40 UTC, qpavy submitted a review, later dismissed

2023-07-28 08:42 UTC, sachinrameshn approved these changes

2023-08-18 11:07 UTC, merged