fix(pci): add trans for voucher error key
ovh/manager pull request #9688
Opened 2023-07-20 10:39 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `fix/DTRSD-117489` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | DTRSD-117489
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description
Add missing translation for voucher error. 

## Related

2023-07-20 10:44 UTC, qpavy submitted a review, later dismissed

2023-07-20 10:54 UTC, anooparveti requested changes
This issue has been resolved with #9291

2023-07-20 11:58 UTC, anooparveti submitted a review, later dismissed

2023-12-14 07:36 UTC, ghyenne approved these changes

2023-12-14 07:40 UTC, qpavy approved these changes

2023-12-14 08:01 UTC, merged