fix(telecom.sms): use a new systemID format for SMPP
ovh/manager pull request #9709
Opened 2023-07-24 15:12 UTC by mdouchement

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | yes/no
| Tickets          | DTRSD-117431
| License          | BSD 3-Clause

- [ ] Try to keep pull requests small so they can be easily reviewed.
- [ ] Commits are signed-off
- [ ] Only FR translations have been updated
- [ ] Branch is up-to-date with target branch
- [ ] Lint has passed locally
- [ ] Standalone app was ran and tested locally
- [ ] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-07-26 08:06 UTC, qpavy approved these changes

2023-07-28 08:56 UTC, ghyenne approved these changes

2023-07-28 12:04 UTC, anooparveti approved these changes

2023-07-28 12:05 UTC, anooparveti requested changes
Can you please `sign-off` your commit?

2023-07-28 13:14 UTC, mdouchement commented
done

2023-08-11 12:20 UTC, merged