feat(dedicated.ip): configure game firewall - datagrid
ovh/manager pull request #9782
Opened 2023-08-02 10:09 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-481
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

Configure game firewall:

- use datagrid and pagination
- add banner message
- rework on title
- use switch button for activate/deactivate rules
- add edit button on rule

## Related

2023-08-03 08:51 UTC, darsene requested changes

2023-08-03 08:51 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +import toInteger from 'lodash/toInteger';
to remove

2023-08-03 08:51 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +    $scope.pageNumber = toInteger(page) || 1;
`+` operator is enough to convert into integer
```suggestion
    $scope.pageNumber = +page || 1;
```

2023-08-03 08:51 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +    $scope.pageSize = toInteger(pageSize) || self.constantes.PAGE_SIZE_MIN;
```suggestion
    $scope.pageSize = +pageSize || self.constantes.PAGE_SIZE_MIN;
```

2023-08-03 12:45 UTC, darsene approved these changes

2023-08-09 09:06 UTC, anooparveti approved these changes

2023-09-20 09:16 UTC, merged