feat(dedicated.ip): configure game firewall - add rule
ovh/manager pull request #9799
Opened 2023-08-03 13:04 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-482
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

- add line to create new rule
- add button to create new rule
- add button to cancel creation

## Related

- [ ] #9759

2023-08-04 09:09 UTC, darsene requested changes

2023-08-04 09:09 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +    $scope.offset = 1 + ($scope.pageNumber - 1) * $scope.pageSize;
`self`

2023-08-04 09:09 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +              paginate($scope.pageSize, $scope.offset);
use `self`

2023-08-04 09:09 UTC, darsene commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
There is a mistake in the filename `controler` instead of `controller`. Maybe you can rename it (be sure to keep git history)

2023-08-04 13:49 UTC, Steffy29 commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +  };
Sorry but it doesn't do the same thing

2023-08-04 13:53 UTC, Steffy29 commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.controler.js
> +  };
Sorry, but your suggestion doesn't do the same thing

2023-08-07 12:03 UTC, anooparveti approved these changes

2023-09-20 09:17 UTC, merged