feat(dedicated.pcc): wip add link guide for sap hana
ovh/manager pull request #9807
Opened 2023-08-04 11:08 UTC by qpavy

ref: MANAGER-11962

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11962
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

2023-08-04 11:13 UTC, anooparveti requested changes
You need to add links for all Subs in CA as well
https://github.com/ovh/manager/blob/f19c3a19b17ec8f831aa74c445e681a60e245348/packages/manager/apps/dedicated/client/app/config/constants.config.js#L1270
Also, I see that in the ticket links have been provided for all subs but it is not used.

2023-08-04 11:41 UTC, qpavy commented
> You need to add links for all Subs in CA as well
> 
> https://github.com/ovh/manager/blob/f19c3a19b17ec8f831aa74c445e681a60e245348/packages/manager/apps/dedicated/client/app/config/constants.config.js#L1270
> 
> Also, I see that in the ticket links have been provided for all subs but it is not used.

This already answered in the ticket, we only update the existing languages for now. There was no pcc section in CA I add it

2023-08-04 12:15 UTC, anooparveti submitted a review, later dismissed

2023-08-07 08:26 UTC, sachinrameshn approved these changes

2023-08-18 08:16 UTC, anooparveti approved these changes

2023-08-18 09:42 UTC, JacquesLarique approved these changes

2023-08-18 10:03 UTC, merged