fix(additional-ips.order): in public IP creation display only v4 ip addresses in step 3
ovh/manager pull request #9830
Opened 2023-08-10 10:05 UTC by brofik

ref: MANAGER-11506

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-11506 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-08-11 08:48 UTC, JacquesLarique approved these changes

2023-08-11 09:28 UTC, sachinrameshn approved these changes

2023-09-04 06:54 UTC, jmalnuit commented on packages/manager/modules/pci/src/projects/project/additional-ips/order/order.controller.js
> +    )?.length;
@brofik Miss to take in account this feedback before prod this PR :)

2023-09-04 06:54 UTC, jmalnuit commented on packages/manager/modules/pci/src/projects/project/additional-ips/order/order.controller.js
> +    )?.length;
@brofik Miss to take in account this feedback before prod this PR :)

2023-09-05 08:45 UTC, sachinrameshn requested changes

2023-09-05 08:45 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/additional-ips/order/order.controller.js
> +      (network) => network.type === 'private' && network.version === 4,
Can you please take version from constant ?

2023-09-05 08:45 UTC, anooparveti submitted a review, later dismissed

2023-09-05 08:46 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/project/additional-ips/order/order.controller.js
> +      (network) => network.type === 'private' && network.version === 4,
same here as well.

2023-09-05 08:47 UTC, JacquesLarique submitted a review, later dismissed

2023-09-08 11:34 UTC, anooparveti approved these changes

2023-09-11 08:29 UTC, darsene approved these changes

2023-11-27 00:00 UTC, closed without merging