feat(project.new): Add the legal text and a checkbox in the second step of a project creation
ovh/manager pull request #9847
Opened 2023-08-16 13:10 UTC by brofik

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-83 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

TAPC-83: https://github.com/ovh/manager/pull/9779
TAPC-150 : https://github.com/ovh/manager/pull/9831

2023-08-18 08:53 UTC, qpavy submitted a review, later dismissed

2023-08-18 09:04 UTC, JacquesLarique approved these changes

2023-08-29 08:07 UTC, anooparveti submitted a review, later dismissed

2023-08-29 08:07 UTC, JacquesLarique submitted a review, later dismissed

2023-08-29 08:43 UTC, qpavy submitted a review, later dismissed

2023-09-01 07:39 UTC, sachinrameshn requested changes

2023-09-01 07:39 UTC, sachinrameshn commented on packages/manager/modules/pci/src/projects/new/payment/controller.js
> +    if (this.model.paymentMethod.type.isCreditCard()) {
I guess we dont display this component for the card type credit card.

2023-09-07 06:18 UTC, sachinrameshn approved these changes

2023-09-14 08:02 UTC, anooparveti requested changes

2023-09-14 08:02 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/new/payment/controller.js
> +      (elm) => elm === true,
```suggestion
      (agreement) => agreement === true,
```

2023-12-02 00:00 UTC, closed without merging