feat(dedicated.ip): configure game firewall - edit rule
ovh/manager pull request #9848
Opened 2023-08-16 14:04 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-483
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

- show line into edit rule mode
- add button to apply update rule
- add button to cancel update
- remove updated rule and create new rule with updated values

## Related

- [ ] #9799

2023-08-18 08:58 UTC, JacquesLarique requested changes

2023-08-18 08:58 UTC, JacquesLarique commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-if="rule.isEditable"
this condition could be set on the parent td, this way you wouldn't have to set it on both child input

2023-08-18 08:58 UTC, JacquesLarique commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-if="rule.isEditable"
Same as previous comment

2023-08-18 08:58 UTC, JacquesLarique commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-if="rule.isEditable"
same as previous comment

2023-08-18 13:21 UTC, anooparveti approved these changes

2023-08-22 08:38 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-max="65535"
Can you please maintain min and max in constant and used it here ?

2023-08-22 08:39 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-max="65535"
same as here: https://github.com/ovh/manager/pull/9848/files#r1301262617

2023-08-22 08:41 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-pattern="/^[0-9]*$/"
This regular expression can also be mainatined in constant file.

2023-08-22 08:41 UTC, sachinrameshn commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/game/ip-ip-firewall-game.html
> +                            data-ng-pattern="/^[0-9]*$/"
same as here: https://github.com/ovh/manager/pull/9848/files#r1301266509

2023-08-25 08:50 UTC, sachinrameshn approved these changes

2023-08-25 08:54 UTC, sachinrameshn requested changes
Can you please change the commit message to include ticket #  and remove other things

Ex: 
feat(universe): title

ref: ticket#
description

Signed-off-by: Stephanie Moallic <stephanie.moallic@corp.ovh.com>

2023-08-29 08:42 UTC, sachinrameshn approved these changes

2023-09-20 09:58 UTC, Steffy29 commented
This feature is postponed for the moment

2023-09-20 09:58 UTC, closed without merging