fix(dedicated): remove customer template changelog (description)
ovh/manager pull request #9853
Opened 2023-08-17 10:44 UTC by JayBeeDe

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
~Breaking change is mentioned in relevant commits~

## Description

Remove changeLog OS option

## Related

ref: MANAGER-12101

2023-08-18 08:45 UTC, anooparveti requested changes

2023-08-18 08:45 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/dedicated/server/details/translations/Messages_fr_CA.json
Can you please remove the changes in this files as it will be autocleaned?

2023-08-18 08:50 UTC, qpavy submitted a review, later dismissed

2023-08-18 09:37 UTC, JayBeeDe commented on packages/manager/apps/dedicated/client/app/dedicated/server/details/translations/Messages_fr_CA.json
@anooparveti  done

2023-08-21 08:35 UTC, JacquesLarique approved these changes

2023-08-21 08:40 UTC, qpavy approved these changes

2023-08-21 08:46 UTC, anooparveti approved these changes

2023-08-28 10:11 UTC, merged