feat(ip.firewall): firewall add rule
ovh/manager pull request #9874
Opened 2023-08-22 16:12 UTC by Steffy29

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #UXCT-488
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~Breaking change is mentioned in relevant commits~

## Description

- add new line into table
- rework on reload rules after adding
- add success message
- add deny message if no deny rule defined
- remove rule/add

## Related

- [ ] #9863

2023-08-23 08:45 UTC, qpavy approved these changes

2023-08-23 08:54 UTC, anooparveti submitted a review, later dismissed

2023-09-05 10:43 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.controller.js
> +                result.state === 'removalPending'
**nitpick:** constant can be added for `removalPending` as well similar to `CREATION_PENDING`

2023-09-05 10:48 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.controller.js
> +    const sourceIp = /^(0+\.)+0+$/; // Test only here cbecause it's a firewall specitic case
```suggestion
    const sourceIp = /^(0+\.)+0+$/; // Test only here because it's a firewall specitic case
```

2023-09-05 10:50 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                data-ng-if="!IpFirewallCtrl.rulesLoading && IpFirewallCtrl.rules.count >=0"
```suggestion
                data-ng-if="!IpFirewallCtrl.rulesLoading && IpFirewallCtrl.rules.count >= 0"
```

2023-09-05 10:59 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                            />
**nitpick:** You can use default form validation
```suggestion
                            <input
                                type="text"
                                maxlength="5"
                                id="sourcePort"
                                name="sourcePort"
                                class="form-control"
                                data-ng-model="IpFirewallCtrl.rule.sourcePort"
                                required
                                min="0"
                                max="65535"
                            />
```

2023-09-05 11:00 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                            />
Same as https://github.com/ovh/manager/pull/9874/files#r1315732877

2023-09-20 08:57 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                            </span>
```suggestion
                            <span
                                data-ng-show="IpFirewallCtrl.validator.destinationPort === false"
                                class="fa fa-info-circle"
                                data-oui-tooltip="{{:: 'ip_firewall_destination_port_tooltip' | translate }}"
                                data-oui-tooltip-placement="left"
                                aria-hidden="false"
                            >
                            </span>
```

2023-09-20 08:57 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                                </span>
```suggestion
                                <span
                                    data-ng-show="IpFirewallCtrl.validator.fragment === false"
                                    class="fa fa-info-circle"
                                    data-oui-tooltip="{{:: 'ip_firewall_rule_fragments_tooltip' | translate }}"
                                    data-oui-tooltip-placement="left"
                                    aria-hidden="false"
                                >
                                </span>
```

2023-09-27 07:09 UTC, anooparveti requested changes

2023-09-27 07:09 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                        </select>
**nitpick:** Can you add `oui-select` and `oui-select__input` classes to maintain the uniform UX.
```suggestion
                    <td class="oui-select">
                        <select
                            class="form-control oui-select__input"
                            id="sequenceSelect"
                            name="sequenceSelect"
                            data-ng-model="IpFirewallCtrl.rule.sequence"
                            data-ng-options="value as value.name for value in (IpFirewallCtrl.constants.sequences | orderBy:'name')"
                            data-ng-change="IpFirewallCtrl.isFirewallRuleFormValid()"
                        ></select>
                    </td>
                    <td class="oui-select">
                        <select
                            class="form-control oui-select__input"
                            id="actionSelect"
                            name="actionSelect"
                            data-ng-model="IpFirewallCtrl.rule.action"
                            data-ng-options="action as (('ip_firewall_rule_' + action) | translate) for action in IpFirewallCtrl.constants.actions"
                            data-ng-change="IpFirewallCtrl.isFirewallRuleFormValid()"
                        ></select>
                    </td>
                    <td class="oui-select">
                        <select
                            id="protocolSelect"
                            name="protocolSelect"
                            class="form-control oui-select__input"
                            data-ng-model="IpFirewallCtrl.rule.protocol"
                            data-ng-change="IpFirewallCtrl.resetOptionField()"
                            data-ng-options="value as ('ip_firewall_rule_protocol_' + value | translate) for value in IpFirewallCtrl.constants.protocols"
                            required
                        >
                        </select>
```

2023-09-27 07:09 UTC, anooparveti commented on packages/manager/apps/dedicated/client/app/ip/components/list/firewall/ip-ip-firewall.html
> +                            </select>
```suggestion
                        <div
                            class="form-inline oui-select"
                            data-ng-show="IpFirewallCtrl.rule.protocol === 'tcp'"
                        >
                            <select
                                id="tcpOptionSelect"
                                name="tcpOptionSelect"
                                class="form-control oui-select__input"
                                data-ng-model="IpFirewallCtrl.rule.tcpOptions.option"
                                data-ng-options="value as ('ip_firewall_rule_flags_' + value | translate) for value in IpFirewallCtrl.constants.tcpOptions"
                                required
                            >
                            </select>
```

2023-09-29 08:46 UTC, anooparveti approved these changes

2023-10-02 08:17 UTC, merged