feat(web): remove plan solution information
ovh/manager pull request #9907
Opened 2023-08-29 12:55 UTC by BrunoMarquesOVH

ref: MANAGER-11815

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #MANAGER-11815
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

Remove plan solution information for domains

## Related

2023-08-30 09:02 UTC, BrunoMarquesOVH commented
> 

Done!

2023-08-31 08:27 UTC, darsene approved these changes

2023-08-31 08:41 UTC, sachinrameshn submitted a review, later dismissed

2023-09-01 05:13 UTC, anooparveti requested changes
Can you just remove the trans keys just from `fr_FR` files?

2023-09-04 13:30 UTC, BrunoMarquesOVH commented
> Can you just remove the trans keys just from `fr_FR` files?

Done!

2023-09-05 08:43 UTC, anooparveti approved these changes

2023-09-05 08:44 UTC, darsene approved these changes

2023-09-05 08:46 UTC, sachinrameshn approved these changes

2023-09-08 10:21 UTC, merged