fix(dedicated): pick first date of last month to download
ovh/manager pull request #9911
Opened 2023-08-30 11:22 UTC by sachinrameshn

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #DTRSD-119666
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~Breaking change is mentioned in relevant commits~

## Description

Proposal dates for the API: apiv6/me/carbonCalculator/task
If the user is in august month date should be between July 1st till July 31st

## Related

2023-08-30 11:32 UTC, qpavy submitted a review, later dismissed

2023-08-31 10:34 UTC, anooparveti commented on packages/manager/modules/carbon-calculator/src/dashboard/carbon-footprint/service.js
> +    const date = presentDateWithUTCcorrection.toISOString().substring(0, 10);
**suggestion:** Can be simplified
```suggestion
    const date = new Date();
    date.setUTCDate(0); // sets the date to the last date of the previous month
    const date = date.toISOString().substring(0, 10);
```

2023-08-31 11:40 UTC, ghyenne approved these changes

2023-08-31 11:46 UTC, qpavy approved these changes

2023-08-31 11:51 UTC, anooparveti requested changes
commit title must be changed

2023-08-31 12:27 UTC, merged