feat(project.new): add payement challenge component specific to india
ovh/manager pull request #9946
Opened 2023-09-06 08:06 UTC by brofik

ref: TAPC-149

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | yes
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #TAPC-149 
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

## Related

2023-09-07 08:40 UTC, darsene requested changes

2023-09-07 08:40 UTC, darsene commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/challenge.class.js
> +      default:
use constants instead for `CREDIT_CARD` and `BANK_ACOUNT`

2023-09-07 08:40 UTC, darsene commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.html
> +        data-ng-switch-when="CREDIT_CARD"
use the future constant instead of `CREDIT_CARD`

2023-09-07 08:40 UTC, darsene commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.html
> +    <div data-ng-switch-when="RUPAY" class="oui-box border-0 rounded-0 m-0 row">
use the future constant instead of `RUPAY`

2023-09-07 08:40 UTC, darsene commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.html
> +        data-ng-switch-when="PAYPAL"
use constant instead of `PAYPAL`

2023-09-07 08:40 UTC, darsene commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.html
> +        data-ng-switch-when="BANK_ACCOUNT"
use constant instead of `BANK_ACCOUNT`

2023-09-08 08:40 UTC, darsene submitted a review, later dismissed

2023-09-11 08:39 UTC, qpavy reviewed
For accessibility, it is better to use rem size instead of fixing sizes with pixels

2023-09-11 08:39 UTC, qpavy commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.scss
> +        font-size: 14px;
```suggestion
        font-size: 0.875rem;
```

2023-09-11 08:39 UTC, qpavy commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.scss
> +      height: 129px;
```suggestion
      height: 8.0625rem;
```

2023-09-11 08:39 UTC, qpavy commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.scss
> +        height: 29px;
```suggestion
        height: 1.8125rem;
```

2023-09-11 08:39 UTC, qpavy commented on packages/manager/modules/pci/src/projects/new/payment/components/challenge-india/index.scss
> +        left: 155px;
```suggestion
        left: 9.6875rem;
```

2023-09-13 07:58 UTC, qpavy approved these changes

2023-09-13 08:31 UTC, darsene submitted a review, later dismissed

2023-11-27 00:00 UTC, closed without merging