Feat/kyc documents
ovh/manager pull request #9947
Opened 2023-09-06 09:00 UTC by qpavy

| Question         | Answer
| ---------------- | ---
| Branch?          | `master` 
| Bug fix?         | no
| New feature?     | yes
| Breaking change? | no
| Tickets          | Fix #MANAGER-11940
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- ~~[ ] Breaking change is mentioned in relevant commits~~

## Description

## Related

:flags: Translations

- [x] CMT-3811
- [x] CMT-4329 (FR)
- [x] CMT-4330 (MA/SN/TN)
- [x] CMT-4449 (DE)
- [x] CMT-4451 (ES/WS)
- [x] CMT-4459 (IT)
- [x] CMT-4460 (PL)
- [x] CMT-4461 (PT)
- [x] CMT-4462 (EN -> DEFAULT)
- [x] CMT-4360 (QC)

2023-09-19 13:37 UTC, ghyenne approved these changes

2023-09-19 13:42 UTC, anooparveti approved these changes

2023-09-19 13:43 UTC, anooparveti requested changes
Can you have a look on https://github.com/ovh/manager/actions/runs/6236109287/job/16926648808?pr=9947?

2023-09-19 13:47 UTC, qpavy commented
> Can you have a look on https://github.com/ovh/manager/actions/runs/6236109287/job/16926648808?pr=9947?

This is not about code modified by this PR but OK I can have a look

2023-09-19 14:24 UTC, anooparveti submitted a review, later dismissed

2023-09-20 06:31 UTC, ghyenne submitted a review, later dismissed

2023-10-06 20:24 UTC, BrunoMarquesOVH approved these changes

2023-10-09 06:00 UTC, ghyenne submitted a review, later dismissed

2023-12-23 00:00 UTC, closed without merging