feat(pci.data-processing.jobs): display badges for eol items
ovh/manager pull request #9973
Opened 2023-09-12 09:13 UTC by jperchoc

DATATR-348

| Question         | Answer
| ---------------- | ---
| Branch?          | `master`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #DATATR-348
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [x] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

## Description

Improve job selection by filtering EOL versions and add a badge for deprecated / soon deprecated versions

2023-09-12 13:08 UTC, Dimfacion submitted a review, later dismissed

2023-09-14 07:57 UTC, anooparveti commented on packages/manager/modules/pci/src/projects/project/data-processing/jobs/submit-job/jobtype-selector/jobtype-selector.constants.js
> +  const today = moment();
**suggestion:** Can you use native JS?

2023-09-14 08:00 UTC, anooparveti requested changes

2023-09-14 08:37 UTC, Dimfacion submitted a review, later dismissed

2023-09-14 13:38 UTC, anooparveti submitted a review, later dismissed

2023-10-13 08:11 UTC, anooparveti approved these changes

2023-10-13 08:13 UTC, BrunoMarquesOVH approved these changes

2023-10-13 08:13 UTC, Dimfacion approved these changes

2023-10-13 08:14 UTC, merged